act_code: '104331'
requisite: Закон Республики Казахстан от 21 сентябpя 1994 года N 156
title:
  rus: О транспорте в Республике Казахстан
  kaz: Қазақстан Республикасындағы көлiк туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1994-09-21
approved_by:
- '102000000000'
version_date:
  kaz: 2004-07-08
  rus: 2004-07-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/104331/kaz/08.07.2004
  rus: https://zan.gov.kz/client/#!/doc/104331/rus/08.07.2004
caused_by:
  code: '20572'
  requisite: Закон Республики Казахстан от 9 июля 2004 года № 596
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам железнодорожного транспорта
    kaz: Қазақстан Республикасының кейбiр заң актiлерiне темiр жол көлiгі мәселелерi бойынша өзгерiстер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/20572/rus
