act_code: '106335'
requisite: Указ Президента Республики Казахстан от 17 мая 2011 года № 83
title:
  rus: О юбилейной медали в ознаменование 20-летия Независимости Республики Казахстан
  kaz: Қазақстан Республикасы Тәуелсіздігінің 20 жылдығы құрметіне арналған мерекелік медаль туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2011-05-17
approved_by:
- '101000000000'
version_date:
  kaz: 2011-05-17
  rus: 2011-05-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/106335/kaz/17.05.2011
  rus: https://zan.gov.kz/client/#!/doc/106335/rus/17.05.2011
