act_code: '8821'
requisite: Закон Республики Казахстан от 8 мая 2001 года N 197-II
title:
  rus: О потребительском кооперативе
  kaz: Тұтыну кооперативі туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2001-05-08
approved_by:
- '102000000000'
version_date:
  kaz: 2016-01-01
  rus: 2016-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/8821/kaz/01.01.2016
  rus: https://zan.gov.kz/client/#!/doc/8821/rus/01.01.2016
caused_by:
  code: '94878'
  requisite: Закон Республики Казахстан от 29 октября 2015 года № 373-V ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам сельскохозяйственных кооперативов
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне ауыл шаруашылығы кооперативтері мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/94878/rus
