act_code: '221971'
requisite: Закон Республики Казахстан от 9 февраля 2026 года № 262-VIII ЗРК
title:
  rus: О ратификации Соглашения между Правительством Республики Казахстан и Правительством Французской Республики о реадмиссии лиц
  kaz: Қазақстан Республикасының Үкіметі мен Француз Республикасының Үкіметі арасындағы адамдарды реадмиссиялау туралы келісімді ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2026-02-09
approved_by:
- '102000000000'
version_date:
  kaz: 2026-02-09
  rus: 2026-02-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/221971/kaz/09.02.2026
  rus: https://zan.gov.kz/client/#!/doc/221971/rus/09.02.2026
