act_code: '8408'
requisite: Приказ Министра внутренних дел Республики Казахстан от 28 февраля 2001 года N 186. Зарегистрирован в Министерстве юстиции Республики Казахстан 20 марта 2001 года N 1430. Утратил силу - приказом Министра внутренних дел РК от 8 сентября 2004 года N 517
title:
  rus: Об утверждении Правил морального и материального стимулирования сотрудников органов внутренних дел и военнослужащих внутренних войск МВД Республики Казахстан, овладевших государственным языком в объеме программы обучения и умеющих применять его в делопроизводстве
  kaz: '"Мемлекеттік тілді оқу бағдарламасы көлемінде меңгерген және оны іс жүргізуде қолдана білетін Қазақстан Республикасы ішкі істер органдарының қызметкерлері мен Ішкіісмин ішкі әскерлерінің әскери қызметшілерін моральдық және материалдық ынталандыру тәртібін" бекіту туралы'
type_codes:
- ПРАВ
approved_on: 2001-02-28
approved_by:
- '103003000000'
version_date:
  kaz: 2001-02-28
  rus: 2001-02-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/8408/kaz/28.02.2001
  rus: https://zan.gov.kz/client/#!/doc/8408/rus/28.02.2001
