act_code: '6498'
requisite: Закон Республики Казахстан от 5 июля 2000 года № 70-II
title:
  rus: О ратификации Договора между Правительством Республики Казахстан и Правительством Российской Федерации об аренде объектов и боевых полей 4 Государственного центрального полигона Российской Федерации, расположенных на территории Республики Казахстан
  kaz: Қазақстан Республикасының Үкiметi мен Ресей Федерациясы Үкiметiнiң арасындағы Ресей Федерациясының 4 - Мемлекеттiк орталық полигонының Қазақстан Республикасының аумағында орналасқан объектiлерi мен әскери алаңдарын жалдау туралы шартты бекіту туралы
form: ДОГ
type_codes:
- ДОГ
- ЗАК
approved_on: 2000-07-04
approved_by:
- '102000000000'
version_date:
  kaz: 2000-07-04
  rus: 2000-07-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/6498/kaz/04.07.2000
  rus: https://zan.gov.kz/client/#!/doc/6498/rus/04.07.2000
