act_code: '5499'
requisite: Постановление Правительства Республики Казахстан от 13 марта 2000 года N 382
title:
  rus: Об утверждении Соглашения между Правительством Республики Казахстан и Правительством Республики Армения о создании совместной комиссии по экономическому сотрудничеству
  kaz: Қазақстан Республикасы Үкіметі мен Армения Республикасының Үкіметі арасындағы Экономикалық ынтымақтастық жөніндегі бірлескен комиссия құру туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2000-03-13
approved_by:
- '103000000000'
version_date:
  kaz: 2000-03-13
  rus: 2000-03-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/5499/kaz/13.03.2000
  rus: https://zan.gov.kz/client/#!/doc/5499/rus/13.03.2000
