act_code: '4416'
requisite: Совместный приказ Министра транспорта, коммуникаций и туризма Республики Казахстан от 8 октября 1999 года № 705 А-I, Министра иностранных дел Республики Казахстан от 12 октября 1999 года № 36, Министра обороны Республики Казахстан от 14 октября 1999 года № 170. Зарегистрирован в Министерстве юстиции Республики Казахстан 20.10.99г. за N 944. Утратил силу - совместным приказом Министра транспорта, коммуникаций и туризма Республики Казахстан от 8 октября 1999 года № 705 А-I, Министра иностранных дел Республики Казахстан от 12 октября 1999 года № 36, Министра обороны Республики Казахстан от 14 октября 1999 года № 170
title:
  rus: Об утверждении Правил осуществления нерегулярных авиаперевозок на международных и внутренних воздушных линиях Республики Казахстан
  kaz: Қазақстан Республикасының халықаралық және ішкі әуе желілерінде оқтын-оқтын авиатасымалдарды орындаудың тәртібін бекіту туралы
type_codes:
- ПРАВ
approved_on: 1999-10-07
approved_by:
- '103004000000'
- '103008000000'
- '103013000000'
version_date:
  rus: 1999-10-07
source:
  rus: https://zan.gov.kz/client/#!/doc/4416/rus/07.10.1999
