act_code: '5539'
requisite: Приказ Министерства юстиции Республики Казахстан от 28 февраля 2000 года N 21 Зарегистрирован в Министерстве юстиции Республики Казахстан 9.03.2000 г. за N 1079. Утратил силу - приказ Министерства юстиции РК от 9 июня 2000г. N 52
title:
  rus: Об утверждении Правил организации и проведения аукционов по реализации арестованного имущества должников судебными исполнителями
  kaz: Борышкерлердiң сот орындаушылары тыйым салған мүлiктерін сату жөнiнде аукциондар ұйымдастыру мен өткiзудiң Ережелерiн бекiту туралы
type_codes:
- ПРАВ
approved_on: 2000-02-28
approved_by:
- '103001000000'
version_date:
  rus: 2000-02-28
source:
  rus: https://zan.gov.kz/client/#!/doc/5539/rus/28.02.2000
