act_code: '62908'
requisite: Закон Республики Казахстан от 6 января 2012 года № 528-IV
title:
  rus: О космической деятельности
  kaz: Ғарыш қызметі туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2012-01-06
approved_by:
- '102000000000'
version_date:
  kaz: 2019-04-10
  rus: 2019-04-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/62908/kaz/10.04.2019
  rus: https://zan.gov.kz/client/#!/doc/62908/rus/10.04.2019
caused_by:
  code: '129651'
  requisite: Закон Республики Казахстан от 18 марта 2019 года № 237-VІ ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам оборонной и аэрокосмической промышленности, информационной безопасности в сфере информатизации
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне қорғаныс және аэроғарыш өнеркәсібі, ақпараттандыру саласындағы ақпараттық қауіпсіздік мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/129651/rus
