act_code: '13401'
requisite: Указ Президента Республики Казахстан от 29 марта 2002 года № 828. Утратил силу Указом Президента Республики Казахстан от 31 июля 2023 года № 290
title:
  rus: О некоторых вопросах кадровой политики в системе органов государственной власти
  kaz: Мемлекеттiк билiк органдары жүйесіндегі кадр саясатының кейбiр мәселелерi туралы
form: УКАЗ
type_codes:
- ПОЛ
- ПРЧ
- УКАЗ
approved_on: 2002-03-29
approved_by:
- '101000000000'
version_date:
  kaz: 2019-11-11
  rus: 2019-11-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/13401/kaz/11.11.2019
  rus: https://zan.gov.kz/client/#!/doc/13401/rus/11.11.2019
caused_by:
  code: '135979'
  requisite: Указ Президента Республики Казахстан от 11 ноября 2019 года № 203
  title:
    rus: О дальнейшем совершенствовании системы государственного управления Республики Казахстан
    kaz: Қазақстан Республикасының мемлекеттік басқару жүйесін одан әрі жетілдіру туралы
  link: https://zan.gov.kz/client/#!/doc/135979/rus
