act_code: '193060'
requisite: Закон Республики Казахстан от 2 февраля 2024 года № 58-VIII ЗРК
title:
  rus: О ратификации Соглашения между Правительством Республики Казахстан и Правительством Государства Катар о взаимном поощрении и защите инвестиций
  kaz: Қазақстан Республикасының Үкіметі мен Қатар Мемлекетінің Үкіметі арасындағы инвестицияларды өзара көтермелеу және қорғау туралы келісімді ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2024-02-02
approved_by:
- '102000000000'
version_date:
  kaz: 2024-02-02
  rus: 2024-02-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/193060/kaz/02.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193060/rus/02.02.2024
