act_code: '105287'
requisite: Закон Республики Казахстан от 26 июля 2016 года № 11-VI ЗРК
title:
  rus: О платежах и платежных системах
  kaz: Төлемдер және төлем жүйелері туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2016-07-26
approved_by:
- '102000000000'
version_date:
  kaz: 2023-01-01
  rus: 2023-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/105287/kaz/01.01.2023
  rus: https://zan.gov.kz/client/#!/doc/105287/rus/01.01.2023
caused_by:
  code: '112917'
  requisite: Закон Республики Казахстан от 20 июня 2017 года № 76-VI ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам социального обеспечения
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне әлеуметтік қамсыздандыру мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/112917/rus
