act_code: '9530'
requisite: Закон Республики Казахстан от 10 июля 2001 года № 229-II
title:
  rus: О ратификации Соглашения о займе между Правительством Республики Казахстан и Фондом Развития Абу-Даби для финансирования строительства дороги Караганда-Астана, совершенного 28 апреля 2001 года
  kaz: 2001 жылғы 28 сәуірде жасалған Қазақстан Республикасының Үкіметі мен Абу-Даби Даму Қорының арасындағы Қарағанды-Астана жолының құрылысын қаржыландыруға арналған заем туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2001-07-09
approved_by:
- '102000000000'
version_date:
  kaz: 2001-07-09
  rus: 2001-07-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/9530/kaz/09.07.2001
  rus: https://zan.gov.kz/client/#!/doc/9530/rus/09.07.2001
