act_code: '12520'
requisite: Указ Президента Республики Казахстан от 25 июня 2002 года N 897
title:
  rus: Об утверждении Соглашения о сотрудничестве государств-участников Содружества Независимых Государств в борьбе с преступлениями в сфере компьютерной информации
  kaz: Тәуелсіз Мемлекеттер Достастығына қатысушы мемлекеттердің компьютерлік ақпарат саласындағы қылмысқа қарсы күрестегі ынтымақтастығы туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- СОГЛ
- УКАЗ
approved_on: 2002-06-25
approved_by:
- '101000000000'
version_date:
  kaz: 2019-12-09
  rus: 2019-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/12520/kaz/09.12.2019
  rus: https://zan.gov.kz/client/#!/doc/12520/rus/09.12.2019
caused_by:
  code: '136883'
  requisite: Закон Республики Казахстан от 9 декабря 2019 года № 277-VІ ЗРК
  title:
    rus: О ратификации Соглашения о сотрудничестве государств – участников Содружества Независимых Государств в борьбе с преступлениями в сфере информационных технологий
    kaz: Тәуелсіз Мемлекеттер Достастығына қатысушы мемлекеттердің ақпараттық технологиялар саласындағы қылмыстармен күрестегі ынтымақтастығы туралы келісімді ратификациялау туралы
  link: https://zan.gov.kz/client/#!/doc/136883/rus
