act_code: '3740'
requisite: Утверждена приказом Генеральной прокуратуры Республики Казахстан от 1 октября 1997 г. N 26; согласована с Министерством финансов Республики Казахстан и Министерством юстиции Республики Казахстан Зарегистрирована в Министерстве юстиции Республики Казахстан 1 октября 1997 г. N 378. Утратила силу - Заключение о регистрации Инструкции "О порядке формирования и использования средств внебюджетного счета органов прокуратуры РК" от 12 июня 1998 г. ~V980518 )
title:
  rus: ИНСТРУКЦИЯ "О порядке формирования и использования средств внебюджетного счета органов прокуратуры Республики Казахстан"
  kaz: Қазақстан Республикасы прокуратура органдарының бюджеттен тыс есебiнiң қаражатын қалыптастыру және пайдалану тәртiбi туралы НҰСҚАУ
type_codes:
- ИНСТ
approved_on: 1997-09-30
approved_by:
- '107000000000'
version_date:
  rus: 1997-09-30
source:
  rus: https://zan.gov.kz/client/#!/doc/3740/rus/30.09.1997
