act_code: '117063'
requisite: Закон Республики Казахстан от 25 декабря 2017 года № 121-VІ ЗРК. Утратил силу Кодексом Республики Казахстан от 18 июля 2025 года № 214-VIII (вводится в действие с 1 января 2026 года)
title:
  rus: О введении в действие Кодекса Республики Казахстан «О налогах и других обязательных платежах в бюджет» (Налоговый кодекс)
  kaz: «Салық және бюджетке төленетін басқа да міндетті төлемдер туралы» Қазақстан Республикасының Кодексін (Салық кодексі) қолданысқа енгізу туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2017-12-25
approved_by:
- '102000000000'
version_date:
  kaz: 2024-03-01
  rus: 2024-03-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/117063/kaz/01.03.2024
  rus: https://zan.gov.kz/client/#!/doc/117063/rus/01.03.2024
caused_by:
  code: '189904'
  requisite: Закон Республики Казахстан от 12 декабря 2023 года № 45-VIII ЗРК
  title:
    rus: О внесении изменений и дополнений в Кодекс Республики Казахстан «О налогах и других обязательных платежах в бюджет» (Налоговый кодекс) и Закон Республики Казахстан «О введении в действие Кодекса Республики Казахстан «О налогах и других обязательных платежах в бюджет» (Налоговый кодекс)»
    kaz: «Салық және бюджетке төленетін басқа да міндетті төлемдер туралы» Қазақстан Республикасының Кодексіне (Салық кодексі) және «Салық  және бюджетке төленетін басқа да міндетті төлемдер туралы» Қазақстан Республикасының Кодексін (Салық кодексі) қолданысқа енгізу туралы» Қазақстан Республикасының Заңына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/189904/rus
