act_code: '21306'
requisite: Указ Президента Республики Казахстан от 17 сентября 2004 года N 1443. Утратил силу Указом Президента Республики Казахстан от 16 сентября 2009 года N 871
title:
  rus: Об утверждении Правил составления и представления отчета об исполнении республиканского бюджета
  kaz: Республикалық бюджеттiң атқарылуы туралы есептi жасау және ұсыну ережесiн бекiту туралы
form: УКАЗ
type_codes:
- ПОЛ
- УКАЗ
approved_on: 2004-09-16
approved_by:
- '101000000000'
version_date:
  kaz: 2006-12-08
  rus: 2006-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/21306/kaz/08.12.2006
  rus: https://zan.gov.kz/client/#!/doc/21306/rus/08.12.2006
caused_by:
  code: '30590'
  requisite: Указ Президента Республики Казахстан от 8 декабря 2006 года № 218. Утратил силу Указом Президента Республики Казахстан от 16 сентября 2009 года № 871
  title:
    rus: О внесении изменений в Указ Президента Республики Казахстан от 17 сентября 2004 года № 1443
    kaz: Қазақстан Республикасы Президентінің 2004 жылғы 17 қыркүйектегі № 1443 Жарлығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/30590/rus
