act_code: '49485'
requisite: Постановление Правительства Республики Казахстан от 25 декабря 2009 года № 2188
title:
  rus: Об утверждении Соглашения между Правительством Республики Казахстан и Правительством Азербайджанской Республики о погашении задолженности, образовавшейся в результате торгово-экономических отношений за 1992-1993 годы (до и после перехода на расчеты по корреспондентским счетам)
  kaz: Қазақстан Республикасының Үкіметі мен Әзірбайжан Республикасының Үкіметі арасындағы 1992 - 1993 жылдардағы сауда-экономикалық қатынастардың нәтижесінде пайда болған (корреспонденттік шоттар бойынша есеп айырысуға етуге дейін және одан кейін) берешекті өтеу туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2009-12-25
approved_by:
- '103000000000'
version_date:
  kaz: 2009-12-25
  rus: 2009-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/49485/kaz/25.12.2009
  rus: https://zan.gov.kz/client/#!/doc/49485/rus/25.12.2009
