act_code: '3719'
requisite: Постановление Правления Национального Банка Республики Казахстан от 18 июня 1999 года N 129. Зарегистрировано в Министерстве юстиции Республики Казахстан от 26 июля 1999 года N 855. Утратило силу постановлением Правления Агентства Республики Казахстан по регулированию и надзору финансового рынка и финансовых организаций от 27 октября 2006 года N 229
title:
  rus: Об утверждении Правил о требованиях, предъявляемых к отчету о проведении аудита банков
  kaz: Банктерге аудит жүргізу жөніндегі есеп беруге қойылатын талаптар туралы ережені бекіту туралы
type_codes:
- ПРАВ
approved_on: 1999-06-17
approved_by:
- '117000000000'
version_date:
  kaz: 2003-12-26
  rus: 2003-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/3719/kaz/26.12.2003
  rus: https://zan.gov.kz/client/#!/doc/3719/rus/26.12.2003
caused_by:
  code: '18268'
  requisite: Постановление Правления Национального Банка Республики Казахстан от 26 декабря 2003 года N 454. Зарегистрировано в Министерстве юстиции Республики Казахстан 31 декабря 2003 года N 2668. Утратило силу постановлением Правления Агентства Республики Казахстан по регулированию и надзору финансового рынка и финансовых организаций от 27 октября 2006 года N 229
  title:
    rus: О внесении изменений и дополнений в постановление Правления Национального Банка Республики Казахстан от 18 июня 1999 года N 129 "Об утверждении Правил о требованиях, предъявляемых к отчету о проведении аудита банковской деятельности и заключению аудитора, аудиторской организации, уполномоченных на проведение аудита банковской деятельности", зарегистрированное в Министерстве юстиции Республики Казахстан под N 855
    kaz: Қазақстан Республикасының Әділет министрлігінде N 855 тіркелген Қазақстан Республикасының Ұлттық Банкі Басқармасының "Банктік қызметке аудит жүргізу туралы есеп беруге және банктік қызметке аудит жүргізуге өкілеттік берілген аудитордың, аудиторлық ұйымдардың қорытындысына қойылатын талаптар туралы ережені бекіту жөнінде" 1999 жылғы 18 маусымдағы N 129 қаулысына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/18268/rus
