act_code: '7789'
requisite: Закон Республики Казахстан от 14 декабря 2000 года № 115-II
title:
  rus: О ратификации Конвенции о равном вознаграждении мужчин и женщин за труд равной ценности
  kaz: Құндылығы бірдей еңбек үшін еркектер мен әйелдерге бірдей сыйақы беру туралы конвенцияны бекіту туралы
form: КОНВ
type_codes:
- ДОГ
- ЗАК
- КОНВ
approved_on: 2000-12-14
approved_by:
- '102000000000'
version_date:
  kaz: 2000-12-14
  rus: 2000-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/7789/kaz/14.12.2000
  rus: https://zan.gov.kz/client/#!/doc/7789/rus/14.12.2000
