act_code: '4720'
requisite: Приказ Национального пенсионного агентства Министерства труда и социальной защиты населения Республики Казахстан от 27 августа 1997 г. N 2-П. Зарегистрирован в Министерстве юстиции Республики Казахстан 17.09.1997г. N 374. Утратил силу - постановлением Правления Национального Банка  Республики Казахстан от 21 апреля 2003 года N 127
title:
  rus: Об утверждении Инструкции об основных требованиях по формированию собственного капитала накопительных пенсионных фондов в Республике Казахстан
  kaz: 'Қазақстан Республикасында Жинақтаушы зейнетақы қорларының өз капиталын қалыптастыру жөнiндегi негiзгi талаптар туралы нұсқаулық ЕСКЕРТУ: Нормативтiк-құқықтық актiнiң атауы жаңа редакцияда жазылды - ҚР Еңбек және халықты әлеуметтік қорғау министрлігінің Жинақтаушы зейнетақы қорларының қызметін реттеу жөніндегі комитетінің 1999 жылғы 15 қазандағы N 83-Ө Бұйрығымен.'
type_codes:
- ПОЛ
approved_on: 1997-08-26
approved_by:
- '103016001000'
version_date:
  rus: 1998-12-18
source:
  rus: https://zan.gov.kz/client/#!/doc/4720/rus/18.12.1998
caused_by:
  code: '2155'
  requisite: Приказ Национального пенсионного агентства Министерства труда и социальной защиты населения Республики Казахстан от 18 декабря 1998 года № 176-П. Зарегистрирован в Министерстве юстиции Республики Казахстан 22 января 1999 года № 674. Утратил силу постановлением Правления Национального Банка Республики Казахстан от 21 апреля 2003 года № 127
  title:
    rus: Об утверждении изменения в "Положение о формировании собственного капитала накопительного пенсионного фонда в Республике Казахстан"
    kaz: Қазақстан Республикасының Еңбек және халықты әлеуметтік қорғау министрлігі Ұлттық зейнетақы агенттігінің 1997 жылғы 27 тамыздағы N 2-Ө бұйрығымен бекітілген (1997 жылғы 17 қыркүйектегі мемлекеттік тіркелім N 374), 1998 жылғы 22 мамырдағы N 68-Ө өзгерістермен және толықтырулармен (1998 жылғы 3 шілдедегі мемлекеттік тіркелім N 90) "Қазақстан Республикасында Жинақтаушы зейнетақы қорының өз капиталын қалыптастыру туралы ереже" өзгерісті бекіту туралы
  link: https://zan.gov.kz/client/#!/doc/2155/rus
