act_code: '35752'
requisite: Указ Президента Республики Казахстан от 12 ноября 2007 года № 434. Утратил силу Указом Президента Республики Казахстан от 20 октября 2017 года № 568
title:
  rus: Об Архитектурном совете столицы при Президенте Республики Казахстан
  kaz: Қазақстан Республикасының Президенті жанындағы Астананың сәулет кеңесі туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2007-11-12
approved_by:
- '101000000000'
version_date:
  kaz: 2014-02-12
  rus: 2014-02-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/35752/kaz/12.02.2014
  rus: https://zan.gov.kz/client/#!/doc/35752/rus/12.02.2014
caused_by:
  code: '79299'
  requisite: Указ Президента Республики Казахстан от 12 февраля 2014 года № 750
  title:
    rus: О внесении изменений и дополнений в некоторые акты Президента Республики Казахстан по вопросам организации деятельности консультативно-совещательных и иных органов при Президенте Республики Казахстан
    kaz: Қазақстан Республикасы Президенті жанындағы консультативтік-кеңесші және өзге де органдардың қызметін ұйымдастыру мәселелері жөніндегі Қазақстан Республикасы Президентінің кейбір актілеріне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/79299/rus
