act_code: '1950'
requisite: Закон Республики Казахстан от 24 декабря 1998 года № 335-I
title:
  rus: О ратификации Соглашения между Правительством Республики Казахстан и Правительством Российской Федерации о регулировании процесса переселения и защите прав переселенцев
  kaz: Қазақстан Республикасының Үкіметі мен Ресей Федерациясының Үкіметі арасындағы Көші-қон процесін реттеу және қоныс аударушылардың құқықтарын қорғау туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 1998-12-24
approved_by:
- '102000000000'
version_date:
  kaz: 1998-12-24
  rus: 1998-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/1950/kaz/24.12.1998
  rus: https://zan.gov.kz/client/#!/doc/1950/rus/24.12.1998
