act_code: '71881'
requisite: Указ Президента Республики Казахстан от 3 апреля 2013 года № 537
title:
  rus: О некоторых вопросах кадровой политики в правоохранительных органах Республики Казахстан
  kaz: Қазақстан Республикасының құқық қорғау органдарындағы кадр саясатының кейбір мәселелері туралы
form: УКАЗ
type_codes:
- ПОЛ
- УКАЗ
approved_on: 2013-04-03
approved_by:
- '101000000000'
version_date:
  kaz: 2021-02-20
  rus: 2021-02-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/71881/kaz/20.02.2021
  rus: https://zan.gov.kz/client/#!/doc/71881/rus/20.02.2021
caused_by:
  code: '153121'
  requisite: Указ Президента Республики Казахстан от 20 февраля 2021 года № 515
  title:
    rus: О некоторых вопросах Агентства Республики Казахстан по финансовому мониторингу
    kaz: Қазақстан Республикасының Қаржылық мониторинг агенттігінің кейбір мәселелері туралы
  link: https://zan.gov.kz/client/#!/doc/153121/rus
