act_code: '53716'
requisite: Закон Республики Казахстан от 30 июня 2010 года № 324-IV ЗРК
title:
  rus: О ратификации Соглашения об особенностях использования транспортных средств международной перевозки, осуществляющих перевозку пассажиров, а также прицепов, полуприцепов, контейнеров и железнодорожного подвижного состава, осуществляющих перевозку грузов и (или) багажа для внутренней перевозки по таможенной территории таможенного союза
  kaz: Жолаушыларды тасымалдауды жүзеге асыратын халықаралық тасымалдаудың көлік құралдарын, сондай-ақ жүктерді және (немесе) багажды тасымалдауды жүзеге асыратын тіркемелерді, жартылай тіркемелерді, контейнерлер мен теміржол жылжымалы құрамын кеден одағының кедендік аумағы арқылы ішкі тасымалдау үшін пайдалану ерекшеліктері туралы келісімді ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2010-06-30
approved_by:
- '102000000000'
version_date:
  kaz: 2010-06-30
  rus: 2010-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/53716/kaz/30.06.2010
  rus: https://zan.gov.kz/client/#!/doc/53716/rus/30.06.2010
