act_code: '198262'
requisite: Закон Республики Казахстан от 27 июня 2024 года № 99-VIII ЗРК
title:
  rus: О ратификации Соглашения о международных комбинированных грузовых перевозках между правительствами государств – членов Организации тюркских государств
  kaz: Түркі мемлекеттері ұйымына мүше мемлекеттердің үкіметтері арасындағы халықаралық құрамдастырылған жүк тасымалдары туралы келісімді ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2024-06-27
approved_by:
- '102000000000'
version_date:
  kaz: 2024-06-27
  rus: 2024-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/198262/kaz/27.06.2024
  rus: https://zan.gov.kz/client/#!/doc/198262/rus/27.06.2024
