act_code: '104318'
requisite: Закон Республики Казахстан от 12 декабря 1995 года № 2676
title:
  rus: О государственных наградах Республики Казахстан
  kaz: Қазақстан Республикасының мемлекеттiк наградалары туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1995-12-12
approved_by:
- '101000000000'
version_date:
  kaz: 2024-04-26
  rus: 2024-04-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/104318/kaz/26.04.2024
  rus: https://zan.gov.kz/client/#!/doc/104318/rus/26.04.2024
caused_by:
  code: '196159'
  requisite: Закон Республики Казахстан от 26 апреля 2024 года № 78-VIII ЗРК
  title:
    rus: О внесении изменений и дополнения в Закон Республики Казахстан «О государственных наградах Республики Казахстан»
    kaz: «Қазақстан Республикасының мемлекеттік наградалары туралы» Қазақстан Республикасының Заңына өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/196159/rus
