act_code: '104318'
requisite: Закон Республики Казахстан от 12 декабря 1995 года № 2676
title:
  rus: О государственных наградах Республики Казахстан
  kaz: Қазақстан Республикасының мемлекеттiк наградалары туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1995-12-12
approved_by:
- '101000000000'
version_date:
  kaz: 2008-12-01
  rus: 2008-12-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/104318/kaz/01.12.2008
  rus: https://zan.gov.kz/client/#!/doc/104318/rus/01.12.2008
caused_by:
  code: '42518'
  requisite: Закон Республики Казахстан от 1 декабря 2008 года № 93-IV
  title:
    rus: О внесении изменения и дополнений в Закон Республики Казахстан "О государственных наградах Республики Казахстан"
    kaz: '"Қазақстан Республикасының мемлекеттік наградалары туралы" Қазақстан Республикасының Заңына өзгеріс пен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/42518/rus
