act_code: '4713'
requisite: Приказ Председателя Комитета здравоохранения Министерства здравоохранения, образования и спорта Республики Казахстан от 12 октября 1999 года N 500. Зарегистрирован в Министерстве юстиции Республики Казахстан 30.11.99г. за N 989. Утратил силу - приказом Министра здравоохранения Республики Казахстан  от 10 октября 2003 года N 737 (V032537)
title:
  rus: Об утверждении Положения о враче общей практики/семейном враче и Положения о семейной врачебной амбулатории
  kaz: Жалпы практика дәрігер/отбасылық дәрігер туралы Ереже мен Отбасылық дәрігерлік амбулатория туралы Ережені бекіту туралы
type_codes:
- ПОЛ
approved_on: 1999-10-11
approved_by:
- '103010000000'
version_date:
  kaz: 1999-10-11
  rus: 1999-10-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/4713/kaz/11.10.1999
  rus: https://zan.gov.kz/client/#!/doc/4713/rus/11.10.1999
