act_code: '139114'
requisite: Нормативное постановление Конституционного Совета Республики Казахстан от 21 января 2020 года № 1
title:
  rus: О проверке конституционности подпункта 8) статьи 107 Закона Республики Казахстан «О жилищных отношениях» по представлению Алатауского районного суда города Алматы
  kaz: Алматы қаласы Алатау аудандық сотының ұсынысы бойынша «Тұрғын үй қатынастары туралы» Қазақстан Республикасы Заңының 107-бабы 8) тармақшасының конституциялылығын тексеру туралы
form: НПОС
type_codes:
- НПОС
approved_on: 2020-01-21
approved_by:
- '106000000000'
version_date:
  kaz: 2020-01-21
  rus: 2020-01-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/139114/kaz/21.01.2020
  rus: https://zan.gov.kz/client/#!/doc/139114/rus/21.01.2020
