act_code: '189673'
requisite: Нормативное постановление Конституционного Суда Республики Казахстан от 6 декабря 2023 года № 37-НП
title:
  rus: О рассмотрении на соответствие Конституции Республики Казахстан части третьей статьи 428 Уголовного кодекса Республики Казахстан от 3 июля 2014 года и подпункта 2) части второй статьи 130 Уголовно-исполнительного кодекса Республики Казахстан от 5 июля 2014 года
  kaz: 2014 жылғы 3 шілдедегі Қазақстан Республикасы Қылмыстық кодексінің 428-бабы үшінші бөлігінің және 2014 жылғы 5 шілдедегі Қазақстан Республикасы Қылмыстық-атқару кодексінің 130-бабы екінші бөлігі 2) тармақшасының Қазақстан Республикасының Конституциясына сәйкестігін қарау туралы
form: НПОС
type_codes:
- НПОС
approved_on: 2023-12-06
approved_by:
- '106000000000'
version_date:
  kaz: 2023-12-06
  rus: 2023-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/189673/kaz/06.12.2023
  rus: https://zan.gov.kz/client/#!/doc/189673/rus/06.12.2023
