act_code: '3655'
requisite: Закон Республики Казахстан от 16 июля 1999 года № 432-I
title:
  rus: О ратификации Конвенции о передаче осужденных к лишению свободы для дальнейшего отбывания наказания
  kaz: Бас еркінен айыруға сотталған адамдарды жазасын одан әрі өтеу үшін беру туралы конвенцияны бекіту туралы
form: КОНВ
type_codes:
- КОНВ
approved_on: 1999-07-15
approved_by:
- '102000000000'
version_date:
  kaz: 1999-07-15
  rus: 1999-07-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/3655/kaz/15.07.1999
  rus: https://zan.gov.kz/client/#!/doc/3655/rus/15.07.1999
