act_code: '142836'
requisite: Закон Республики Казахстан от 14 мая 2020 года № 328-VІ ЗРК
title:
  rus: О ратификации Рамочного соглашения о партнерстве (поправки и дополнения к Рамочному соглашению о партнерстве между Правительством Республики Казахстан и Азиатским Банком Развития по усилению сотрудничества в целях экономической диверсификации, устойчивому развитию и всеобъемлющему росту Республики Казахстан от 4 мая 2014 года)
  kaz: Әріптестік туралы негіздемелік келісімді (2014 жылғы 4 мамырдағы Қазақстан Республикасының Үкіметі мен Азия Даму Банкі арасындағы Қазақстан Республикасын экономикалық әртараптандыру және оның орнықты дамуына, жалпы өсуіне жәрдемдесу мақсатында ынтымақтастықты күшейту жөніндегі әріптестік туралы негіздемелік келісімге түзетулер мен толықтырулар) ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2020-05-14
approved_by:
- '102000000000'
version_date:
  kaz: 2020-05-14
  rus: 2020-05-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/142836/kaz/14.05.2020
  rus: https://zan.gov.kz/client/#!/doc/142836/rus/14.05.2020
