act_code: '104469'
requisite: Закон Республики Казахстан от 20 июня 1997 года № 136. Утратил силу Законом Республики Казахстан от 21 июня 2013 года № 105-V
title:
  rus: О пенсионном обеспечении в Республике Казахстан
  kaz: Қазақстан Республикасында зейнетақымен қамсыздандыру туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1997-06-19
approved_by:
- '102000000000'
version_date:
  kaz: 2010-12-15
  rus: 2010-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/104469/kaz/15.12.2010
  rus: https://zan.gov.kz/client/#!/doc/104469/rus/15.12.2010
caused_by:
  code: '56030'
  requisite: Закон Республики Казахстан от 15 декабря 2010 года № 363-IV
  title:
    rus: О внесении изменений в Закон Республики Казахстан "О пенсионном обеспечении в Республике Казахстан"
    kaz: '"Қазақстан Республикасында зейнетақымен қамсыздандыру туралы" Қазақстан Республикасының Заңына өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/56030/rus
