act_code: '58278'
requisite: Постановление Правительства Республики Казахстан от 7 апреля 2011 года № 386
title:
  rus: Об утверждении Соглашения между Правительством Республики Казахстан и Правительством Республики Таджикистан о сотрудничестве в области туризма
  kaz: Қазақстан Республикасының Үкіметі мен Тәжікстан Республикасының Үкіметі арасындағы Туризм саласындағы ынтымақтастық туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2011-04-07
approved_by:
- '103000000000'
version_date:
  kaz: 2011-04-07
  rus: 2011-04-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/58278/kaz/07.04.2011
  rus: https://zan.gov.kz/client/#!/doc/58278/rus/07.04.2011
