act_code: '1021'
requisite: Закон Республики Казахстан от 10 июля 1998 года N 279
title:
  rus: О наркотических средствах, психотропных веществах, их аналогах и прекурсорах и мерах противодействия их незаконному обороту и злоупотреблению ими
  kaz: Есiрткi, психотроптық заттар, сол тектестер мен прекурсорлар және олардың заңсыз айналымы мен терiс пайдаланылуына қарсы iс-қимыл шаралары туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1998-07-10
approved_by:
- '102000000000'
version_date:
  kaz: 2006-03-02
  rus: 2006-03-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/1021/kaz/02.03.2006
  rus: https://zan.gov.kz/client/#!/doc/1021/rus/02.03.2006
caused_by:
  code: '26720'
  requisite: Закон Республики Казахстан от 2 марта 2006 года № 130-III ЗРК
  title:
    rus: О внесении изменений и дополнений в Закон Республики Казахстан "О наркотических средствах, психотропных веществах, прекурсорах и мерах противодействия их незаконному обороту и злоупотреблению ими"
    kaz: '"Есірткі, психотроптық заттар, прекурсорлар және олардың заңсыз айналымы мен теріс пайдаланылуына қарсы іс-қимыл шаралары туралы" Қазақстан Республикасының Заңына өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/26720/rus
