act_code: '4438'
requisite: Распоряжение Акима Карагандинской области от 30 сентября 1999 года № 172р. Зарегистрировано управлением юстиции Карагандинской области 15.10.1999 г. за № 38.Утратило силу решением акима Карагандинской области от 14 мая 2004 года № 44
title:
  rus: О мероприятиях по созданию новых рабочих мест, содействию трудоустройству и предотвращению безработицы
  kaz: Жаңа жұмыс орнын құру, жұмысқа орналасуға көмек көрсету және жұмыссыздықты болдырмау жөніндегі шаралар туралы
form: РАСП
type_codes:
- РАСП
approved_on: 1999-09-29
approved_by:
- '160000000001'
version_date:
  kaz: 1999-09-29
  rus: 1999-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/4438/kaz/29.09.1999
  rus: https://zan.gov.kz/client/#!/doc/4438/rus/29.09.1999
