act_code: '8096'
requisite: Кодекс Республики Казахстан от 30 января 2001 года № 155. Утратил силу Кодексом Республики Казахстан от 5 июля 2014 года № 235 (вводится в действие с 01.01.2015)
title:
  rus: Об административных правонарушениях
  kaz: Әкімшілік құқық бұзушылық туралы
form: КОД
type_codes:
- КОД
approved_on: 2001-01-30
approved_by:
- '102000000000'
version_date:
  kaz: 2008-11-20
  rus: 2008-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/8096/kaz/20.11.2008
  rus: https://zan.gov.kz/client/#!/doc/8096/rus/20.11.2008
caused_by:
  code: '42372'
  requisite: Закон Республики Казахстан от 20 ноября 2008 года № 88-IV
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам коллективного инвестирования и деятельности накопительных пенсионных фондов
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне ұжымдық инвестициялау және жинақтаушы зейнетақы қорлары қызметінің мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/42372/rus
