act_code: '8096'
requisite: Кодекс Республики Казахстан от 30 января 2001 года № 155. Утратил силу Кодексом Республики Казахстан от 5 июля 2014 года № 235 (вводится в действие с 01.01.2015)
title:
  rus: Об административных правонарушениях
  kaz: Әкімшілік құқық бұзушылық туралы
form: КОД
type_codes:
- КОД
approved_on: 2001-01-30
approved_by:
- '102000000000'
version_date:
  kaz: 2008-12-25
  rus: 2008-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/8096/kaz/25.12.2008
  rus: https://zan.gov.kz/client/#!/doc/8096/rus/25.12.2008
caused_by:
  code: '43166'
  requisite: Закон Республики Казахстан от 25 декабря 2008 года № 113-IV
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам конкуренции
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне бәсекелестік мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/43166/rus
