act_code: '857'
requisite: Закон Республики Казахстан от 29 июня 1998 года № 248
title:
  rus: О присоединении Республики Казахстан к Конвенции о ликвидации всех форм дискриминации в отношении женщин
  kaz: Қазақстан Республикасының Әйелдердi кемсiтушiлiктiң барлық нысандарын жою туралы конвенцияға қосылуы туралы
form: КОНВ
type_codes:
- ЗАК
- КОНВ
approved_on: 1998-06-28
approved_by:
- '102000000000'
version_date:
  kaz: 1998-06-28
  rus: 1998-06-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/857/kaz/28.06.1998
  rus: https://zan.gov.kz/client/#!/doc/857/rus/28.06.1998
