act_code: '15348'
requisite: Закон Республики Казахстан от 13 мая 2003 года № 415
title:
  rus: Об акционерных обществах
  kaz: Акционерлік қоғамдар туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2003-05-13
approved_by:
- '102000000000'
version_date:
  kaz: 2011-12-28
  rus: 2011-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/15348/kaz/28.12.2011
  rus: https://zan.gov.kz/client/#!/doc/15348/rus/28.12.2011
caused_by:
  code: '62861'
  requisite: Закон Республики Казахстан от 28 декабря 2011 года № 524-IV ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам регулирования банковской деятельности и финансовых организаций в части минимизации рисков
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне банк қызметін және қаржы ұйымдарын тәуекелдерді азайту тұрғысынан реттеу мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/62861/rus
