act_code: '74333'
requisite: Приказ и.о. Министра образования и науки Республики Казахстан от 7 августа 2013 года № 323. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 августа 2013 года № 8678. Утратил силу приказом Министра образования и науки Республики Казахстан от 27 января 2016 года № 83
title:
  rus: Об утверждении Правил проведения и условий аттестации гражданских служащих в сфере образования и науки, а также Правил проведения и условий аттестации педагогических работников и приравненных к ним лиц, занимающих должности в организациях образования, реализующих образовательные учебные программы дошкольного, начального, основного среднего, общего среднего, технического и профессионального, послесреднего образования
  kaz: Білім және ғылым саласындағы азаматтық қызметшілерді аттестаттаудан өткізу қағидалары мен шартын, сондай-ақ Мектепке дейінгі, бастауыш, негізгі орта, жалпы орта, техникалық және кәсіптік, орта білімнен кейінгі білімнің білім беретін оқу бағдарламаларын іске асыратын білім беру ұйымдарында жұмыс істейтін педагог қызметкерлер мен оларға теңестірілген тұлғаларды аттестаттаудан өткізу қaғидалары мен шартын бекіту туралы
form: ДОГ
type_codes:
- ДОГ
- ПРАВ
- ПРИК
approved_on: 2013-08-07
approved_by:
- '103006000000'
version_date:
  kaz: 2013-08-07
  rus: 2013-08-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/74333/kaz/07.08.2013
  rus: https://zan.gov.kz/client/#!/doc/74333/rus/07.08.2013
