act_code: '1692'
requisite: Приказ Министерства энергетики, индустрии и торговли Республики Казахстан от 19 октября 1998 года N 199 Зарегистрирован в Министерстве юстиции Республики Казахстан 24 октября 1998 года N 627. Утратил силу - приказом Агентства РК по государственным закупкам от 25 января 1999 г. N 2 (~V990692)
title:
  rus: Об утверждении и введении в действие "Правил составления и Порядка представления отчетности и формы отчета о проведенных государственных закупках товаров, работ и услуг для организаций, финансируемых из республиканского и местных бюджетов, а также средств внебюджетных фондов"
  kaz: '"Республикалық және жергілікті бюджеттерден, сондай-ақ бюджеттен тыс қорлардан қаржыланатын ұйымдар үшін өткізілген, тауарларды, жұмыстарды және қызмет көрсетулерді мемлекеттік сатып алу туралы есеп берудің жасау мен табыс етудің Ережесі мен есеп нысандарын" бекіту мен күшіне енгізу туралы'
type_codes:
- ПРАВ
approved_on: 1998-10-18
approved_by:
- '103018000000'
version_date:
  rus: 1998-10-18
source:
  rus: https://zan.gov.kz/client/#!/doc/1692/rus/18.10.1998
