act_code: '7698'
requisite: Приказ Министра внутренних дел Республики Казахстан от 5 декабря 2000 года № 664 Зарегистрирован в Министерстве юстиции Республики Казахстан 20 декабря 2000 года № 1340. Утратил силу приказом Министра внутренних дел Республики Казахстан от 21 декабря 2009 года № 485
title:
  rus: Об утверждении Положения о подразделении патрульной полиции по сопровождению пассажирских поездов УВД на транспорте
  kaz: Көлiктегi IIБ-нiң жолаушылар поездарына iлесiп жүру жөнiндегi патрульдiк полиция бөлiмшелерi туралы нұсқаулықты бекiту туралы
type_codes:
- ПОЛ
approved_on: 2000-12-05
approved_by:
- '103003000000'
version_date:
  kaz: 2000-12-05
  rus: 2000-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/7698/kaz/05.12.2000
  rus: https://zan.gov.kz/client/#!/doc/7698/rus/05.12.2000
