act_code: '153121'
requisite: Указ Президента Республики Казахстан от 20 февраля 2021 года № 515
title:
  rus: О некоторых вопросах Агентства Республики Казахстан по финансовому мониторингу
  kaz: Қазақстан Республикасының Қаржылық мониторинг агенттігінің кейбір мәселелері туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2021-02-20
approved_by:
- '101000000000'
version_date:
  kaz: 2022-08-10
  rus: 2022-08-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/153121/kaz/10.08.2022
  rus: https://zan.gov.kz/client/#!/doc/153121/rus/10.08.2022
caused_by:
  code: '170691'
  requisite: Указ Президента Республики Казахстан от 10 августа 2022 года № 976
  title:
    rus: О реорганизации некоторых территориальных органов Агентства Республики Казахстан по финансовому мониторингу и внесении изменения в Указ Президента Республики Казахстан от 20 февраля 2021 года № 515 «О некоторых вопросах Агентства Республики Казахстан по финансовому мониторингу»
    kaz: Қазақстан Республикасы Қаржылық мониторинг агенттігінің кейбір аумақтық органдарын қайта ұйымдастыру және «Қазақстан Республикасының Қаржылық мониторинг агенттігінің кейбір мәселелері туралы» Қазақстан Республикасы Президентінің 2021 жылғы 20 ақпандағы № 515 Жарлығына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/170691/rus
