act_code: '104088'
requisite: Закон Республики Казахстан от 30 июня 1992 года № 1468-XII
title:
  rus: О социальной защите гpаждан, постpадавших вследствие экологического бедствия в Пpиаpалье
  kaz: Арал өңіріндегі экологиялық қасірет салдарынан зардап шеккен азаматтарды әлеуметтік қорғау туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1992-06-30
approved_by:
- '102000000000'
version_date:
  kaz: 2025-06-30
  rus: 2025-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/104088/kaz/30.06.2025
  rus: https://zan.gov.kz/client/#!/doc/104088/rus/30.06.2025
caused_by:
  code: '211863'
  requisite: Закон Республики Казахстан от 30 июня 2025 года № 200-VIII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам деятельности фондов целевого капитала и эндаумент-фондов (целевых капиталов), а также экологически неблагополучных территорий казахстанской части Приаралья
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне нысаналы капитал қорларының және эндаумент-қорлардың (нысаналы капиталдардың) қызметі, сондай-ақ Арал маңының қазақстандық бөлігінің экологиялық қолайсыз аумағы мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/211863/rus
