act_code: '7782'
requisite: Приказ Министра иностранных дел Республики Казахстан от 21 ноября 2000 г. N 264. Зарегистрирован в Министерстве юстиции Республики Казахстан 04.01.2001 г. за N 1350. Утратил силу приказом и.о. Министра иностранных дел Республики Казахстан от 6 декабря 2017 года № 11-1-2/576 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил консульской легализации
  kaz: Консулдық заңдастыру Ережелерiн бекіту туралы
type_codes:
- ПРАВ
approved_on: 2000-11-21
approved_by:
- '103004000000'
version_date:
  kaz: 2013-12-11
  rus: 2013-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/7782/kaz/11.12.2013
  rus: https://zan.gov.kz/client/#!/doc/7782/rus/11.12.2013
caused_by:
  code: '76914'
  requisite: Приказ и.о. Министра иностранных дел Республики Казахстан от 11 декабря 2013 года № 08-1-1-1/613. Зарегистрирован в Министерстве юстиции Республики Казахстан 14 января 2014 года № 9068. Утратил силу приказом и.о. Министра иностранных дел Республики Казахстан от 6 декабря 2017 года № 11-1-2/576 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в приказ Министра иностранных дел Республики Казахстан от 21 ноября 2000 года № 264 "Об утверждении Правил консульской легализации"
    kaz: '"Консулдық заңдастыру ережелерін бекіту туралы" Қазақстан Республикасы Сыртқы істер министрінің 2000 жылғы 21 қарашадағы № 264 бұйрығына өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/76914/rus
