act_code: '15924'
requisite: Кодекс Республики Казахстан от 20 июня 2003 года № 442
title:
  rus: Земельный кодекс Республики Казахстан
  kaz: Қазақстан Республикасының Жер кодексі
form: КОД
type_codes:
- КОД
approved_on: 2003-06-20
approved_by:
- '102000000000'
version_date:
  kaz: 2009-10-22
  rus: 2009-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/15924/kaz/22.10.2009
  rus: https://zan.gov.kz/client/#!/doc/15924/rus/22.10.2009
caused_by:
  code: '78483'
  requisite: Закон Республики Казахстан от 7 апреля 2014 года № 183-V 3PK
  title:
    rus: О ратификации Конвенции о создании процедуры установления минимальной заработной платы (Конвенция 26)
    kaz: Ең төменгі жалақыны белгілеу рәсімін жасау туралы конвенцияны (26-конвенция) ратификациялау туралы
  link: https://zan.gov.kz/client/#!/doc/78483/rus
