act_code: '186713'
requisite: Нормативное постановление Конституционного Суда Республики Казахстан от 25 сентября 2023 года № 29-НП
title:
  rus: О рассмотрении на соответствие Конституции Республики Казахстан статьи 482 Уголовно-процессуального кодекса Республики Казахстан от 4 июля 2014 года
  kaz: 2014 жылғы 4 шілдедегі Қазақстан Республикасы Қылмыстық-процестік кодексінің 482-бабының Қазақстан Республикасының Конституциясына сәйкестігін қарау туралы
form: НПОС
type_codes:
- НПОС
approved_on: 2023-09-25
approved_by:
- '106000000000'
version_date:
  kaz: 2023-09-25
  rus: 2023-09-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/186713/kaz/25.09.2023
  rus: https://zan.gov.kz/client/#!/doc/186713/rus/25.09.2023
