act_code: '7833'
requisite: Конституционный закон Республики Казахстан от 25 декабря 2000 года № 132
title:
  rus: О судебной системе и статусе судей Республики Казахстан
  kaz: Қазақстан Республикасының сот жүйесі мен судьяларының мәртебесі туралы
form: КЗАК
type_codes:
- КЗАК
approved_on: 2000-12-25
approved_by:
- '102000000000'
version_date:
  kaz: 2016-01-01
  rus: 2016-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/7833/kaz/01.01.2016
  rus: https://zan.gov.kz/client/#!/doc/7833/rus/01.01.2016
caused_by:
  code: '96101'
  requisite: Конституционный закон Республики Казахстан от 4 декабря 2015 года № 437-V ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые конституционные законы Республики Казахстан по вопросам Высшего Судебного Совета, судебной системы и статуса судей
    kaz: Қазақстан Республикасының кейбір конституциялық заңдарына Жоғары Сот Кеңесі, сот жүйесі және судьялардың мәртебесі мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/96101/rus
