act_code: '9555'
requisite: Закон Республики Казахстан от 16 июля 2001 года № 242. Утратил силу Кодексом Республики Казахстан от 9 января 2026 года № 253-VIII (вводится в действие с 1 июля 2026 года), за исключением подпунктов 11-1), 23-19), 23-20), 23-22), 23-25) и 23-26) статьи 20, подпункта 17-6) пункта 1 статьи 24, подпункта 18-6) пункта 1 статьи 25 и абзаца второго пункта 1 статьи 32-1, которые действуют до 1 июля 2028 года
title:
  rus: Об архитектурной, градостроительной и строительной деятельности в Республике Казахстан
  kaz: Қазақстан Республикасындағы сәулет, қала құрылысы және құрылыс қызметі туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2001-07-16
approved_by:
- '102000000000'
version_date:
  kaz: 2025-06-10
  rus: 2025-06-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/9555/kaz/10.06.2025
  rus: https://zan.gov.kz/client/#!/doc/9555/rus/10.06.2025
caused_by:
  code: '209027'
  requisite: Закон Республики Казахстан от 9 апреля 2025 года № 179-VIII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам охраны и использования водного фонда
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне су қорын қорғау және пайдалану мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/209027/rus
