act_code: '9555'
requisite: Закон Республики Казахстан от 16 июля 2001 года № 242. Утратил силу Кодексом Республики Казахстан от 9 января 2026 года № 253-VIII (вводится в действие с 1 июля 2026 года), за исключением подпунктов 11-1), 23-19), 23-20), 23-22), 23-25) и 23-26) статьи 20, подпункта 17-6) пункта 1 статьи 24, подпункта 18-6) пункта 1 статьи 25 и абзаца второго пункта 1 статьи 32-1, которые действуют до 1 июля 2028 года
title:
  rus: Об архитектурной, градостроительной и строительной деятельности в Республике Казахстан
  kaz: Қазақстан Республикасындағы сәулет, қала құрылысы және құрылыс қызметі туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2001-07-16
approved_by:
- '102000000000'
version_date:
  kaz: 2015-04-01
  rus: 2015-04-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/9555/kaz/01.04.2015
  rus: https://zan.gov.kz/client/#!/doc/9555/rus/01.04.2015
caused_by:
  code: '88850'
  requisite: Приказ Министра национальной экономики Республики Казахстан от 1 апреля 2015 года № 299. Зарегистрирован в Министерстве юстиции Республики Казахстан 15 апреля 2015 года № 10722. Утратил силу приказом Министра промышленности и строительства Республики Казахстан от 15 мая 2026 года № 240 (вводится в действие с 1 июля 2026 года и подлежит официальному опубликованию)
  title:
    rus: Об утверждении Правил проведения комплексной вневедомственной экспертизы технико-экономических обоснований и проектно-сметной документации, предназначенных для строительства новых, а также изменения (реконструкции, расширения, технического перевооружения, модернизации и капитального ремонта) существующих зданий и сооружений, их комплексов, инженерных и транспортных коммуникаций независимо от источников финансирования
    kaz: Қаржыландыру көздеріне қарамастан, жаңа үйлер мен ғимараттарды, олардың кешендерін, инженерлік және көлік коммуникацияларын салуға, сондай-ақ бұрыннан барын өзгертуге (реконструкциялауға, кеңейтуге, техникалық қайта жарақтандыруға, жаңғыртуға және күрделі жөндеуге) арналған техникалық-экономикалық негіздемелерге және жобалау-сметалық құжаттамаға ведомстводан тыс кешенді сараптама жүргізу қағидаларын бекіту туралы
  link: https://zan.gov.kz/client/#!/doc/88850/rus
