act_code: '51221'
requisite: Указ Президента Республики Казахстан от 4 марта 2010 года № 931. Утратил силу Указом Президента Республики Казахстан от 5 мая 2018 года № 681
title:
  rus: О некоторых вопросах дальнейшего функционирования Системы государственного планирования в Республике Казахстан
  kaz: Қазақстан Республикасындағы мемлекеттік жоспарлау жүйесінің одан әрі жұмыс істеуінің кейбір мәселелері туралы
form: УКАЗ
type_codes:
- ПРАВ
- УКАЗ
approved_on: 2010-03-04
approved_by:
- '101000000000'
version_date:
  kaz: 2010-03-04
  rus: 2010-03-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/51221/kaz/04.03.2010
  rus: https://zan.gov.kz/client/#!/doc/51221/rus/04.03.2010
