act_code: '9'
requisite: Кодекс Республики Казахстан от 13 декабря 1997 года № 206. Утратил силу Кодексом Республики Казахстан от 4 июля 2014 года № 231
title:
  rus: Уголовно-процессуальный кодекс Республики Казахстан
  kaz: Қазақстан Республикасының Қылмыстық іс жүргізу кодексі
form: КОД
type_codes:
- КОД
approved_on: 1997-12-13
approved_by:
- '102000000000'
version_date:
  rus: 2007-05-22
source:
  rus: https://zan.gov.kz/client/#!/doc/9/rus/22.05.2007
caused_by:
  code: '33392'
  requisite: Закон Республики Казахстан от 22 мая 2007 года № 255
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам воинской службы
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне әскери қызмет мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/33392/rus
