act_code: '9'
requisite: Кодекс Республики Казахстан от 13 декабря 1997 года № 206. Утратил силу Кодексом Республики Казахстан от 4 июля 2014 года № 231
title:
  rus: Уголовно-процессуальный кодекс Республики Казахстан
  kaz: Қазақстан Республикасының Қылмыстық іс жүргізу кодексі
form: КОД
type_codes:
- КОД
approved_on: 1997-12-13
approved_by:
- '102000000000'
version_date:
  kaz: 2009-12-08
  rus: 2009-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/9/kaz/08.12.2009
  rus: https://zan.gov.kz/client/#!/doc/9/rus/08.12.2009
caused_by:
  code: '49325'
  requisite: Закон Республики Казахстан от 8 декабря 2009 года № 225-IV
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам пресечения лжепредпринимательства
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне жалған кәсіпкерліктің жолын кесу мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/49325/rus
