act_code: '4876'
requisite: Закон Республики Казахстан от 10 декабря 1999 года N 494-I. Утратил силу Законом Республики Казахстан от 15 мая 2007 года N 252
title:
  rus: О введении в действие Закона Республики Казахстан "О труде в Республике Казахстан"
  kaz: '"Қазақстан Республикасындағы еңбек туралы" Қазақстан Республикасының Заңын күшіне енгізу туралы'
form: ЗАК
type_codes:
- ЗАК
approved_on: 1999-12-10
approved_by:
- '102000000000'
version_date:
  kaz: 1999-12-10
  rus: 1999-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/4876/kaz/10.12.1999
  rus: https://zan.gov.kz/client/#!/doc/4876/rus/10.12.1999
