act_code: '104143'
requisite: Закон Республики Казахстан от 7 мая 1997 года N 101-1. Утратил силу Конституционным Законом Республики Казахстан от 5 июня 2026 года № 297-VIII (вводится в действие с 1 июля 2026 года)
title:
  rus: О комитетах и комиссиях Парламента Республики Казахстан
  kaz: Қазақстан Республикасы Парламентiнiң комитеттерi мен комиссиялары туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1997-05-07
approved_by:
- '102000000000'
version_date:
  kaz: 2023-04-19
  rus: 2023-04-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/104143/kaz/19.04.2023
  rus: https://zan.gov.kz/client/#!/doc/104143/rus/19.04.2023
caused_by:
  code: '179978'
  requisite: Закон Республики Казахстан от 19 апреля 2023 года № 223-VII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам административной реформы в Республике Казахстан
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне Қазақстан Республикасындағы әкімшілік реформа мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/179978/rus
