act_code: '32865'
requisite: Постановление Правительства Республики Казахстан от 23 апреля 2007 года № 323
title:
  rus: Об утверждении Соглашения об основах гармонизации технических регламентов государств-членов Евразийского экономического сообщества
  kaz: Еуразиялық экономикалық қоғамдастыққа мүше мемлекеттердің техникалық регламенттерін үйлестіру негіздері туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ПОР
- ПОСТ
- СОГЛ
approved_on: 2007-04-23
approved_by:
- '103000000000'
version_date:
  kaz: 2007-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/32865/kaz/23.04.2007
