act_code: '2978'
requisite: Закон Республики Казахстан от 20 мая 1999 года № 387-I
title:
  rus: О ратификации Договора между Республикой Казахстан и Азербайджанской Республикой о правовой помощи и правовых отношениях по гражданским делам
  kaz: Қазақстан Республикасы мен Әзірбайжан Республикасы арасындағы азаматтық істер жөніндегі құқықтық көмек және құқықтық қатынастар туралы шартты бекіту туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 1999-05-19
approved_by:
- '102000000000'
version_date:
  kaz: 1999-05-19
  rus: 1999-05-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/2978/kaz/19.05.1999
  rus: https://zan.gov.kz/client/#!/doc/2978/rus/19.05.1999
