act_code: '123177'
requisite: Закон Республики Казахстан от 2 июля 2018 года № 167-VІ ЗРК
title:
  rus: О валютном регулировании и валютном контроле
  kaz: Валюталық реттеу және валюталық бақылау туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2018-07-02
approved_by:
- '102000000000'
version_date:
  kaz: 2020-01-01
  rus: 2020-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/123177/kaz/01.01.2020
  rus: https://zan.gov.kz/client/#!/doc/123177/rus/01.01.2020
caused_by:
  code: '133004'
  requisite: Закон Республики Казахстан от 3 июля 2019 года № 262-VІ ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам регулирования и развития финансового рынка, микрофинансовой деятельности и налогообложения
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне қаржы нарығын реттеу мен дамыту, микроқаржылық қызмет және салық салу мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/133004/rus
