act_code: '123177'
requisite: Закон Республики Казахстан от 2 июля 2018 года № 167-VІ ЗРК
title:
  rus: О валютном регулировании и валютном контроле
  kaz: Валюталық реттеу және валюталық бақылау туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2018-07-02
approved_by:
- '102000000000'
version_date:
  kaz: 2019-04-03
  rus: 2019-04-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/123177/kaz/03.04.2019
  rus: https://zan.gov.kz/client/#!/doc/123177/rus/03.04.2019
caused_by:
  code: '130099'
  requisite: Закон Республики Казахстан от 3 апреля 2019 года № 243-VІ ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам специальных экономических и индустриальных зон, привлечения инвестиций, развития и продвижения экспорта, а также социального обеспечения
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне арнайы экономикалық және индустриялық аймақтар, инвестицияларды тарту, экспортты дамыту және ілгерілету, сондай-ақ әлеуметтік қамсыздандыру мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130099/rus
