act_code: '33509'
requisite: Конституционный закон Республики Казахстан от 4 июня 2007 года № 258
title:
  rus: О государственных символах Республики Казахстан
  kaz: Қазақстан Республикасының мемлекеттік рәміздері туралы
form: КЗАК
type_codes:
- КЗАК
approved_on: 2007-06-04
approved_by:
- '102000000000'
version_date:
  kaz: 2012-06-28
  rus: 2012-06-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/33509/kaz/28.06.2012
  rus: https://zan.gov.kz/client/#!/doc/33509/rus/28.06.2012
caused_by:
  code: '66376'
  requisite: Конституционный закон Республики Казахстан от 28 июня 2012 года № 23-V
  title:
    rus: О внесении изменений и дополнений в Конституционный закон Республики Казахстан "О государственных символах Республики Казахстан"
    kaz: '"Қазақстан Республикасының мемлекеттiк рәмiздерi туралы" Қазақстан Республикасының Конституциялық заңына өзгерiстер мен толықтырулар енгiзу туралы'
  link: https://zan.gov.kz/client/#!/doc/66376/rus
