act_code: '33509'
requisite: Конституционный закон Республики Казахстан от 4 июня 2007 года № 258
title:
  rus: О государственных символах Республики Казахстан
  kaz: Қазақстан Республикасының мемлекеттік рәміздері туралы
form: КЗАК
type_codes:
- КЗАК
approved_on: 2007-06-04
approved_by:
- '102000000000'
version_date:
  kaz: 2008-07-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/33509/kaz/04.07.2008
caused_by:
  code: '40558'
  requisite: Конституционный закон Республики Казахстан от 4 июля 2008 года N 56-IV
  title:
    rus: О внесении изменений в Конституционный закон Республики Казахстан "О государственных символах Республики Казахстан"
    kaz: '"Қазақстан Республикасының мемлекеттік нышандары туралы" Қазақстан Республикасының Конституциялық заңына өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/40558/rus
