act_code: '20523'
requisite: Постановление Правительства Республики Казахстан от 15 июля 2004 года N 765
title:
  rus: Об утверждении Исполнительного протокола между Министерством обороны Республики Казахстан и Генеральным штабом Турецкой Республики о безвозмездной военной помощи
  kaz: Қазақстан Республикасының Қорғаныс министрлiгi мен Түрiк Республикасының Бас штабы арасындағы Өтеусіз әскери көмек туралы атқару хаттамасын бекiту туралы
form: СОГЛ
type_codes:
- ПОСТ
- ПРОТ
- СОГЛ
approved_on: 2004-07-14
approved_by:
- '103000000000'
version_date:
  kaz: 2004-07-14
  rus: 2004-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/20523/kaz/14.07.2004
  rus: https://zan.gov.kz/client/#!/doc/20523/rus/14.07.2004
