act_code: '204302'
requisite: Закон Республики Казахстан от 18 декабря 2024 года № 144-VIII ЗРК
title:
  rus: О ратификации Соглашения о займе (Заем на финансирование политики развития «Инклюзивный и устойчивый рост экономики») между Республикой Казахстан и Международным Банком Реконструкции и Развития
  kaz: Қазақстан Республикасы мен Халықаралық Қайта Құру және Даму Банкі арасындағы қарыз туралы келісімді («Инклюзивті және тұрақты экономикалық өсу» атты даму саясатын қаржыландыруға арналған қарыз) ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2024-12-18
approved_by:
- '102000000000'
version_date:
  kaz: 2024-12-18
  rus: 2024-12-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/204302/kaz/18.12.2024
  rus: https://zan.gov.kz/client/#!/doc/204302/rus/18.12.2024
