act_code: '2748'
requisite: Приказ Председателя Агентства Республики Казахстан по государственным закупкам от 15 апреля 1999 г. N 36. Зарегистрирован в Министерстве юстиции Республики Казахстан 26.04.1999 г. за N 742. Утратил силу приказом Министра финансов Республики Казахстан от 15 апреля 2008 года N 179.
title:
  rus: Инструкция о порядке организации и проведения проверок государственных учреждений по соблюдению ими положений нормативных правовых актов по государственным закупкам
  kaz: Мемлекеттік мекемелерде олардың мемлекеттік сатып алу жөніндегі нормативтік құқықтық актілердің ережелерін сақтауы жөнінде тексеруді ұйымдастыру мен жүргізудің тәртібі туралы Нұсқаулық
type_codes:
- ИНСТ
approved_on: 1999-04-14
approved_by:
- '103002006000'
version_date:
  kaz: 1999-06-16
  rus: 1999-06-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/2748/kaz/16.06.1999
  rus: https://zan.gov.kz/client/#!/doc/2748/rus/16.06.1999
caused_by:
  code: '3447'
  requisite: Приказ Агентства Республики Казахстан по государственным закупкам от 17 июня 1999 года N 46. Зарегистрирован в Министерстве юстиции Республики Казахстан 13.07.1999 г. за N 834. Утратил силу приказом Министра финансов Республики Казахстан от 15 апреля 2008 года N 179.
  title:
    rus: О внесении изменений в Инструкцию о порядке организации и проведения проверок государственных учреждений по соблюдению им положений нормативных правовых актов по государственным закупкам
    kaz: Мемлекеттік мекемелерде олардың мемлекеттік сатып алу жөніндегі нормативтік құқықтық актілердің ережелерін сақтауы жөнінде тексеруді ұйымдастыру мен жүргізудің тәртібі туралы нұсқаулыққа өзгерту енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/3447/rus
