act_code: '151478'
requisite: Указ Президента Республики Казахстан от 31 декабря 2020 года № 485
title:
  rus: Об утверждении квалификационных требований к отдельным политическим государственным должностям
  kaz: Жекелеген мемлекеттік саяси лауазымдарға қойылатын біліктілік талаптарын бекіту туралы
form: УКАЗ
type_codes:
- ТРЕБ
- УКАЗ
approved_on: 2020-12-31
approved_by:
- '101000000000'
version_date:
  kaz: 2023-06-05
  rus: 2023-06-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/151478/kaz/05.06.2023
  rus: https://zan.gov.kz/client/#!/doc/151478/rus/05.06.2023
caused_by:
  code: '182552'
  requisite: Указ Президента Республики Казахстан от 5 июня 2023 года № 239
  title:
    rus: О внесении изменений и дополнений в некоторые указы Президента Республики Казахстан
    kaz: Қазақстан Республикасы Президентінің кейбір жарлықтарына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/182552/rus
