act_code: '22880'
requisite: Закон Республики Казахстан от 7 февраля 2005 года № 30
title:
  rus: Об обязательном страховании работника от несчастных случаев при исполнении им трудовых (служебных) обязанностей
  kaz: Қызметкер еңбек (қызметтік) міндеттерін атқарған кезде оны жазатайым оқиғалардан міндетті сақтандыру туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2005-02-07
approved_by:
- '102000000000'
version_date:
  kaz: 2018-07-02
  rus: 2018-07-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/22880/kaz/02.07.2018
  rus: https://zan.gov.kz/client/#!/doc/22880/rus/02.07.2018
caused_by:
  code: '123091'
  requisite: Закон Республики Казахстан от 2 июля 2018 года № 166-VІ ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам страхования и страховой деятельности, рынка ценных бумаг
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне сақтандыру және сақтандыру қызметі, бағалы қағаздар нарығы мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123091/rus
