act_code: '179971'
requisite: Нормативное постановление Конституционного Суда Республики Казахстан от 11 апреля 2023 года № 9
title:
  rus: О рассмотрении на соответствие Конституции Республики Казахстан отдельных положений части второй статьи 146 Уголовно-процессуального кодекса Республики Казахстан от 4 июля 2014 года
  kaz: 2014 жылғы 4 шілдедегі Қазақстан Республикасы Қылмыстық-процестік кодексінің 146-бабы екінші бөлігінің жекелеген ережелерінің Қазақстан Республикасының Конституциясына сәйкестігін қарау туралы
form: НПОС
type_codes:
- НПОС
approved_on: 2023-04-11
approved_by:
- '106000000000'
version_date:
  kaz: 2023-04-11
  rus: 2023-04-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/179971/kaz/11.04.2023
  rus: https://zan.gov.kz/client/#!/doc/179971/rus/11.04.2023
