act_code: '20974'
requisite: Постановление Правительства Республики Казахстан от 17 августа 2004 года N 863. Утратило силу постановлением Правительства Республики Казахстан от 28 сентября 2015 года № 802
title:
  rus: Об утверждении типовой формы договора о порядке и условиях частичного возмещения страховых выплат, заключаемого между агентом и страховщиком
  kaz: Агент пен сақтандырушының арасында жасалатын сақтандыру төлемдерiн iшiнара өтеу тәртiбi мен талаптары туралы шарттың үлгi нысанын бекiту туралы
form: ДОГ
type_codes:
- ДОГ
- ПОСТ
approved_on: 2004-08-16
approved_by:
- '103000000000'
version_date:
  kaz: 2010-10-08
  rus: 2010-10-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/20974/kaz/08.10.2010
  rus: https://zan.gov.kz/client/#!/doc/20974/rus/08.10.2010
caused_by:
  code: '54756'
  requisite: Постановление Правительства Республики Казахстан от 8 октября 2010 года № 1042
  title:
    rus: О внесении изменений и дополнений в некоторые решения Правительства Республики Казахстан
    kaz: Қазақстан Республикасы Үкіметінің кейбір шешімдеріне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/54756/rus
