act_code: '184506'
requisite: Указ Президента Республики Казахстан от 31 июля 2023 года № 290
title:
  rus: О некоторых вопросах кадровой политики в системе органов государственной власти
  kaz: Мемлекеттік билік органдары жүйесіндегі кадр саясатының кейбір мәселелері туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2023-07-31
approved_by:
- '101000000000'
version_date:
  kaz: 2025-08-26
  rus: 2025-08-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/184506/kaz/26.08.2025
  rus: https://zan.gov.kz/client/#!/doc/184506/rus/26.08.2025
caused_by:
  code: '213592'
  requisite: Указ Президента Республики Казахстан от 26 августа 2025 года № 975
  title:
    rus: О внесении изменений и дополнений в некоторые акты Президента Республики Казахстан
    kaz: Қазақстан Республикасы Президентінің кейбір актілеріне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/213592/rus
