act_code: '39789'
requisite: Постановление Правительства Республики Казахстан от 22 мая 2008 года N 492
title:
  rus: Об утверждении Торгового соглашения между Правительством Республики Казахстан и Правительством Арабской Республики Египет
  kaz: Қазақстан Республикасының Үкіметі мен Египет Араб Республикасының Үкіметі арасындағы Сауда келісімін бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2008-05-22
approved_by:
- '103000000000'
version_date:
  kaz: 2008-05-22
  rus: 2008-05-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/39789/kaz/22.05.2008
  rus: https://zan.gov.kz/client/#!/doc/39789/rus/22.05.2008
