act_code: '56883'
requisite: Закон Республики Казахстан от 14 января 2011 года № 387-IV ЗРК
title:
  rus: О ратификации Соглашения между Правительством Республики Казахстан и Правительством Королевства Саудовская Аравия о предоставлении земельного участка для строительства объектов Посольства Королевства Саудовская Аравия в городе Астане
  kaz: Қазақстан Республикасының Үкіметі мен Сауд Арабиясы Корольдігінің Үкіметі арасындағы Астана қаласында Сауд Арабиясы Корольдігі Елшілігінің объектілерін салу үшін жер учаскесін беру туралы келісімді ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2011-01-14
approved_by:
- '102000000000'
version_date:
  kaz: 2011-01-14
  rus: 2011-01-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/56883/kaz/14.01.2011
  rus: https://zan.gov.kz/client/#!/doc/56883/rus/14.01.2011
