act_code: '104246'
requisite: Закон Республики Казахстан от 18 декабpя 1992 года N 1787-XII
title:
  rus: О социальной защите гpаждан, постpадавших вследствие ядеpных испытаний на Семипалатинском испытательном ядеpном полигоне
  kaz: Семей ядролық сынақ полигонындағы ядролық сынақтардың салдарынан зардап шеккен азаматтарды әлеуметтік қорғау туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1992-12-18
approved_by:
- '102000000000'
version_date:
  rus: 1998-12-17
source:
  rus: https://zan.gov.kz/client/#!/doc/104246/rus/17.12.1998
caused_by:
  code: '1845'
  requisite: Закон Республики Казахстан от 17 декабря 1998 года № 323-I
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам социального обеспечения
    kaz: Қазақстан Республикасының әлеуметтік қамсыздандыру мәселелері бойынша кейбір заң актілеріне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/1845/rus
