act_code: '171107'
requisite: Постановление Правительства Республики Казахстан от 31 августа 2022 года № 631
title:
  rus: Об утверждении Соглашения между Правительством Республики Казахстан и Правительством Республики Узбекистан о сотрудничестве в области исследования и использования космического пространства в мирных целях
  kaz: Қазақстан Республикасының Үкіметі мен Өзбекстан Республикасының Үкіметі арасындағы ғарыш кеңістігін бейбіт мақсаттарда зерттеу және пайдалану саласындағы ынтымақтастық туралы келісім
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2022-08-31
approved_by:
- '103000000000'
version_date:
  kaz: 2022-08-31
  rus: 2022-08-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/171107/kaz/31.08.2022
  rus: https://zan.gov.kz/client/#!/doc/171107/rus/31.08.2022
