act_code: '206376'
requisite: Закон Республики Казахстан от 9 января 2025 года № 152-VIII ЗРК
title:
  rus: О ратификации Рамочного соглашения о всеобъемлющем экономическом сотрудничестве между Евразийским экономическим союзом и его государствами-членами, с одной стороны, и Республикой Сингапур, с другой стороны, и Соглашения о свободной торговле между Евразийским экономическим союзом и его государствами-членами, с одной стороны, и Республикой Сингапур, с другой стороны
  kaz: Бір тараптан Еуразиялық экономикалық одақ пен оған мүше мемлекеттер және екінші тараптан Сингапур Республикасы арасындағы жан-жақты экономикалық ынтымақтастық туралы негіздемелік келісімді және Бір тараптан Еуразиялық экономикалық одақ пен оған мүше мемлекеттер және екінші тараптан Сингапур Республикасы арасындағы еркін сауда туралы келісімді ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2025-01-09
approved_by:
- '102000000000'
version_date:
  kaz: 2025-01-09
  rus: 2025-01-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/206376/kaz/09.01.2025
  rus: https://zan.gov.kz/client/#!/doc/206376/rus/09.01.2025
