act_code: '9688'
requisite: Закон Республики Казахстан от 17 июля 2001 года № 245
title:
  rus: Об автомобильных дорогах
  kaz: Автомобиль жолдары туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2001-07-17
approved_by:
- '102000000000'
version_date:
  kaz: 2022-01-01
  rus: 2022-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/9688/kaz/01.01.2022
  rus: https://zan.gov.kz/client/#!/doc/9688/rus/01.01.2022
caused_by:
  code: '155528'
  requisite: Закон Республики Казахстан от 30 апреля 2021 года № 34-VII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам туристской деятельности
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне туристік қызмет мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/155528/rus
