act_code: '9688'
requisite: Закон Республики Казахстан от 17 июля 2001 года № 245
title:
  rus: Об автомобильных дорогах
  kaz: Автомобиль жолдары туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2001-07-17
approved_by:
- '102000000000'
version_date:
  kaz: 2019-04-19
  rus: 2019-04-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/9688/kaz/19.04.2019
  rus: https://zan.gov.kz/client/#!/doc/9688/rus/19.04.2019
caused_by:
  code: '130744'
  requisite: Закон Республики Казахстан от 19 апреля 2019 года № 249-VІ ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам транспорта
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне көлік мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130744/rus
