act_code: '48642'
requisite: Закон Республики Казахстан от 11 ноября 2009 года № 199-IV
title:
  rus: О ратификации Соглашения Истисна'а между Правительством Республики Казахстан и Исламским Банком Развития о реконструкции участка дороги "Граница Южно-Казахстанской области - Тараз" в рамках проекта дороги "Западная Европа - Западный Китай" и Агентского соглашения (Истисна'а) между Правительством Республики Казахстан и Исламским Банком Развития о реконструкции участка дороги "Граница Южно-Казахстанской области - Тараз" в рамках проекта дороги "Западная Европа - Западный Китай"
  kaz: Қазақстан Республикасының Үкіметі мен Ислам Даму Банкі арасындағы "Батыс Еуропа - Батыс Қытай" жолының жобасы шеңберінде "Оңтүстік Қазақстан облысының шекарасы - Тараз" жолының учаскесін реконструкциялау туралы Истисна'а келісімін және Қазақстан Республикасының Үкіметі мен Ислам Даму Банкі арасындағы "Батыс Еуропа - Батыс Қытай" жолының жобасы шеңберінде "Оңтүстік Қазақстан облысының шекарасы - Тараз" жолының учаскесін реконструкциялау туралы агенттік келісімді (Истисна'а) ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2009-11-11
approved_by:
- '102000000000'
version_date:
  kaz: 2009-11-11
  rus: 2009-11-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/48642/kaz/11.11.2009
  rus: https://zan.gov.kz/client/#!/doc/48642/rus/11.11.2009
