act_code: '4757'
requisite: Утверждена постановлением Государственного комитета Республики Казахстан по инвестициям от 30 июня 1997 г. N 25. Зарегистрировано в Министерстве юстиции Республики Казахстан 20 октября 1997 г. N 411. Постановление утратило силу - приказом председателя Комитета по инвестициям Министерства индустрии и торговли Республики Казахстан от 20 февраля 2004 года N 7-п
title:
  rus: ИНСТРУКЦИЯ о порядке координации деятельности государственных органов по реализации инвестиционных проектов утвержденным инвестором
  kaz: '"Мемлекеттiк органдардың бекiтiлген инвестордың инвестициялық жобаларды жүзеге асыруы жөнiндегi қызметiн үйлестiруiнiң тәртiбi туралы нұсқаулықты" бекiту туралы"'
type_codes:
- ИНСТ
approved_on: 1997-06-29
approved_by:
- '103004001000'
version_date:
  kaz: 1997-06-29
  rus: 1997-06-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/4757/kaz/29.06.1997
  rus: https://zan.gov.kz/client/#!/doc/4757/rus/29.06.1997
