act_code: '36063'
requisite: Закон Республики Казахстан от 6 декабря 2007 года N 8-IV
title:
  rus: О республиканском бюджете на 2008 год
  kaz: 2008 жылға арналған республикалық бюджет туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2007-12-06
approved_by:
- '102000000000'
version_date:
  kaz: 2008-10-24
  rus: 2008-10-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/36063/kaz/24.10.2008
  rus: https://zan.gov.kz/client/#!/doc/36063/rus/24.10.2008
caused_by:
  code: '42023'
  requisite: Закон Республики Казахстан от 24 октября 2008 года N 76-IV
  title:
    rus: О внесении изменений и дополнения в Закон Республики Казахстан "О республиканском бюджете на 2008 год"
    kaz: '"2008 жылға арналған республикалық бюджет туралы" Қазақстан Республикасының Заңына өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/42023/rus
