act_code: '46038'
requisite: Постановление Правительства Республики Казахстан от 14 мая 2009 года № 709. Утратило силу постановлением Правительства Республики Казахстан от 14 августа 2024 года № 652 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об утверждении типовой формы договора присоединения, определяющего условия оказания услуг присоединения других сетей телекоммуникаций, а также связанные с этим обязательства по взаимодействию сетей и пропуску трафика для доминирующего оператора связи сети телекоммуникаций общего пользования
  kaz: Орталық пайдаланылатын телекоммуникация желілерінің басым байланыс операторлары үшін телекоммуникацияның басқа желілерін қосу қызметтерін көрсетудің, сондай-ақ желілердің әрекеттестігі және трафикті өткізу бойынша осыған байланысты міндеттемелердің талаптарын айқындайтын қосу шартының үлгі нысанын бекіту туралы
form: ДОГ
type_codes:
- ДОГ
- ПОСТ
approved_on: 2009-05-14
approved_by:
- '103000000000'
version_date:
  kaz: 2009-05-14
  rus: 2009-05-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/46038/kaz/14.05.2009
  rus: https://zan.gov.kz/client/#!/doc/46038/rus/14.05.2009
