act_code: '218606'
requisite: Закон Республики Казахстан от 10 декабря 2025 года № 240-VIII ЗРК
title:
  rus: О ратификации Протокола по проблемам воды и здоровья к Конвенции по охране и использованию трансграничных водотоков и международных озер 1992 года
  kaz: 1992 жылғы Шекарааралық су арналары мен халықаралық көлдерді қорғау және пайдалану жөніндегі конвенцияға Су және денсаулық проблемалары туралы хаттаманы ратификациялау туралы
form: ПРОТ
type_codes:
- ЗАК
- ПРОТ
approved_on: 2025-12-10
approved_by:
- '102000000000'
version_date:
  kaz: 2025-12-10
  rus: 2025-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/218606/kaz/10.12.2025
  rus: https://zan.gov.kz/client/#!/doc/218606/rus/10.12.2025
