act_code: '29045'
requisite: Указ Президента Республики Казахстан от 25 июля 2006 года № 155
title:
  rus: Об утверждении Положения о специальном представителе Президента Республики Казахстан на комплексе "Байконур"
  kaz: '"Байқоңыр" кешенiндегi Қазақстан Республикасы Президентiнiң арнаулы өкiлi туралы ереженi бекiту туралы'
form: УКАЗ
type_codes:
- ПОЛ
- УКАЗ
approved_on: 2006-07-25
approved_by:
- '101000000000'
version_date:
  kaz: 2013-09-12
  rus: 2013-09-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/29045/kaz/12.09.2013
  rus: https://zan.gov.kz/client/#!/doc/29045/rus/12.09.2013
caused_by:
  code: '76143'
  requisite: Указ Президента Республики Казахстан от 12 сентября 2013 года № 643
  title:
    rus: О внесении изменений и дополнений в Указ Президента Республики Казахстан от 25 июля 2006 года № 155 "Об утверждении Положения о специальном представителе Президента Республики Казахстан на комплексе "Байконур"
    kaz: '"Байқоңыр" кешеніндегі Қазақстан Республикасы Президентінің арнаулы өкілі туралы ережені бекіту туралы" Қазақстан Республикасы Президентінің 2006 жылғы 25 шілдедегі № 155 Жарлығына өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/76143/rus
