act_code: '490'
requisite: Утверждена приказом Министра финансов Республики Казахстан от 21 июня 1995 г. N 150. Зарегистрирован в Министерстве юстиции РК 30.06.1995 г. за N 71. Утратила силу - приказом Министра государственных доходов РК от 9.04.2002 № 416 (извлечение из приказа см. ниже).
title:
  rus: Инструкция N 38 О порядке исчисления и уплаты налога на имущество
  kaz: Мүлiк салығын есептеу мен төлеу тәртiбi туралы Нұсқаулық
type_codes:
- ИНСТ
approved_on: 1995-06-20
approved_by:
- '103002000000'
version_date:
  rus: 1999-05-02
source:
  rus: https://zan.gov.kz/client/#!/doc/490/rus/02.05.1999
caused_by:
  code: '3182'
  requisite: Утверждено приказом Министра государственных доходов Республики Казахстан 3 мая 1999 года N 310. Зарегистрирован в Министерстве юстиции Республики Казахстан 1.06.1999г.N 785. Утратил силу - приказом Министра государственных доходов РК от 9.04.2002 № 416 (извлечение из приказа см. ниже).
  title:
    rus: О внесении изменений и дополнений в Инструкцию N 38 "О порядке исчисления и уплаты налога на имущество"
    kaz: '"Мүлікке салық есептеу мен төлеудің тәртібі туралы" N 38 Нұсқауға өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/3182/rus
