act_code: '189580'
requisite: Закон Республики Казахстан от 5 декабря 2023 года № 42-VIII ЗРК. Утратил силу Законом Республики Казахстан от 4 декабря 2024 года № 140-VIII (вводится в действие с 1 января 2025 года)
title:
  rus: О гарантированном трансферте из Национального фонда Республики Казахстан на 2024 – 2026 годы
  kaz: Қазақстан Республикасының Ұлттық қорынан 2024 – 2026 жылдарға арналған кепілдендірілген трансферт туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2023-12-05
approved_by:
- '102000000000'
version_date:
  kaz: 2023-12-05
  rus: 2023-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/189580/kaz/05.12.2023
  rus: https://zan.gov.kz/client/#!/doc/189580/rus/05.12.2023
repealed_on: 2025-01-01
repealed_by:
  code: '203648'
  requisite: Закон Республики Казахстан от 4 декабря 2024 года № 140-VIII ЗРК. Утратил силу Законом Республики Казахстан от 8 декабря 2025 года № 239-VIII (вводится в действие с 1 января 2026 года)
  title:
    rus: О гарантированном трансферте из Национального фонда Республики Казахстан на 2025 – 2027 годы
    kaz: Қазақстан Республикасының Ұлттық қорынан 2025 – 2027 жылдарға арналған кепілдендірілген трансферт туралы
  link: https://zan.gov.kz/client/#!/doc/203648/rus
