act_code: '56882'
requisite: Закон Республики Казахстан от 14 января 2011 года № 386-IV
title:
  rus: О ратификации Конвенции между Правительством Республики Казахстан и Правительством Королевства Испания об избежании двойного налогообложения и предотвращении уклонения от налогообложения в отношении налогов на доход и на капитал и Протокола к ней
  kaz: Қазақстан Республикасының Үкіметі мен Испания Корольдігінің Үкіметі арасындағы Табыс пен капиталға салынатын салықтарға қатысты қосарланған салық салуды болдырмау және салық салудан жалтаруға жол бермеу туралы конвенцияны және оған Хаттаманы ратификациялау туралы
form: КОНВ
type_codes:
- ЗАК
- КОНВ
- ПРОТ
approved_on: 2011-01-14
approved_by:
- '102000000000'
version_date:
  kaz: 2011-01-14
  rus: 2011-01-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/56882/kaz/14.01.2011
  rus: https://zan.gov.kz/client/#!/doc/56882/rus/14.01.2011
