act_code: '104325'
requisite: Закон Республики Казахстан от 31 августа 1995 года № 2444. Утратил силу Законом Республики Казахстан от 16 января 2026 года № 258-VIII (вводится в действие по истечении шестидесяти календарных дней после дня его первого официального опубликования), за исключением статей 40-1, 40-2, 40-3, 40-4, пункта 7-2 статьи 50, которые признаются утратившими силу с 1 января 2027 года
title:
  rus: О банках и банковской деятельности в Республике Казахстан
  kaz: Қазақстан Республикасындағы банктер және банк қызметі туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1995-08-31
approved_by:
- '101000000000'
version_date:
  kaz: 2009-02-12
  rus: 2009-02-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/104325/kaz/12.02.2009
  rus: https://zan.gov.kz/client/#!/doc/104325/rus/12.02.2009
caused_by:
  code: '44264'
  requisite: Закон Республики Казахстан от 12 февраля 2009 года № 133-IV
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам организации и деятельности исламских банков и организации исламского финансирования
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне ислам банктерін ұйымдастыру мен олардың қызметі және исламдық қаржыландыруды ұйымдастыру мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/44264/rus
