act_code: '104325'
requisite: Закон Республики Казахстан от 31 августа 1995 года № 2444. Утратил силу Законом Республики Казахстан от 16 января 2026 года № 258-VIII (вводится в действие по истечении шестидесяти календарных дней после дня его первого официального опубликования), за исключением статей 40-1, 40-2, 40-3, 40-4, пункта 7-2 статьи 50, которые признаются утратившими силу с 1 января 2027 года
title:
  rus: О банках и банковской деятельности в Республике Казахстан
  kaz: Қазақстан Республикасындағы банктер және банк қызметі туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1995-08-31
approved_by:
- '101000000000'
version_date:
  kaz: 2024-10-01
  rus: 2024-10-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/104325/kaz/01.10.2024
  rus: https://zan.gov.kz/client/#!/doc/104325/rus/01.10.2024
caused_by:
  code: '197920'
  requisite: Закон Республики Казахстан от 19 июня 2024 года № 97-VIII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам минимизации рисков при кредитовании, защиты прав заемщиков, совершенствования регулирования финансового рынка и исполнительного производства
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне кредит беру кезінде тәуекелдерді барынша азайту, қарыз алушылардың құқықтарын қорғау, қаржы нарығын реттеуді және атқарушылық іс жүргізуді жетілдіру мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/197920/rus
