act_code: '19551'
requisite: Кодекс Республики Казахстан от 24 апреля 2004 года № 548. Утратил силу Кодексом Республики Казахстан от 4 декабря 2008 года № 95-IV
title:
  rus: Бюджетный кодекс Республики Казахстан
  kaz: Қазақстан Республикасының Бюджет кодексі
form: КОД
type_codes:
- КОД
approved_on: 2004-04-23
approved_by:
- '102000000000'
version_date:
  kaz: 2007-01-12
  rus: 2007-01-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/19551/kaz/12.01.2007
  rus: https://zan.gov.kz/client/#!/doc/19551/rus/12.01.2007
caused_by:
  code: '31395'
  requisite: Закон Республики Казахстан от 12 января 2007 года № 220
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам игорного бизнеса
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне ойын бизнесі мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/31395/rus
