act_code: '104000'
requisite: Закон Республики Казахстан от 12 мая 1990 года. Утратил силу Законом Республики Казахстан от 31 марта 1998 года № 215
title:
  rus: О крестьянском хозяйстве
  kaz: О крестьянском хозяйстве
form: ЗАК
type_codes:
- ЗАК
approved_on: 1990-05-11
approved_by:
- '102000000000'
version_date:
  rus: 1995-10-30
source:
  rus: https://zan.gov.kz/client/#!/doc/104000/rus/30.10.1995
