act_code: '17490'
requisite: Закон Республики Казахстан от 18 ноября 2003 года N 497-ІІ
title:
  rus: О ратификации Соглашения между Правительством Республики Казахстан и Швейцарским Федеральным Советом о международных перевозках пассажиров и грузов
  kaz: Қазақстан Республикасының Yкiметi мен Швейцария Федералдық Кеңесiнiң арасындағы Жолаушылар мен жүктердiң халықаралық тасымалдары туралы келiсiмдi бекiту туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2003-11-18
approved_by:
- '102000000000'
version_date:
  kaz: 2003-11-18
  rus: 2003-11-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/17490/kaz/18.11.2003
  rus: https://zan.gov.kz/client/#!/doc/17490/rus/18.11.2003
