act_code: '802'
requisite: Указ Президента Республики Казахстан от 13 ноября 1997 г. N 3755. Утратил силу - Указом Президента РК от 11 июля 2001 г. N 654
title:
  rus: Об утверждении Положения о Национальной комиссии Республики Казахстан по ценным бумагам
  kaz: Қазақстан Республикасының Бағалы қағаздар жөнiндегi ұлттық комиссиясы туралы ереженi бекiту туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 1997-11-13
approved_by:
- '101000000000'
version_date:
  rus: 1997-11-13
source:
  rus: https://zan.gov.kz/client/#!/doc/802/rus/13.11.1997
