act_code: '41722'
requisite: Закон Республики Казахстан от 29 сентября 2008 года № 68-IV
title:
  rus: О ратификации Протокола о порядке вступления в силу международных договоров, направленных на формирование договорно-правовой базы таможенного союза, выхода из них и присоединения к ним
  kaz: Кеден одағының шарттық-құқықтық базасын қалыптастыруға бағытталған халықаралық шарттардың күшіне ену, олардан шығу және оларға қосылу тәртібі туралы хаттаманы ратификациялау туралы
form: ПРОТ
type_codes:
- ЗАК
- ПРОТ
approved_on: 2008-09-29
approved_by:
- '102000000000'
version_date:
  kaz: 2008-09-29
  rus: 2008-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/41722/kaz/29.09.2008
  rus: https://zan.gov.kz/client/#!/doc/41722/rus/29.09.2008
