act_code: '104415'
requisite: Закон Республики Казахстан от 24 декабря 1996 года N 54. Утратил силу - Законом РК от 13 июня 2005 года N 57 (вводится в действие по истечении шести месяцев со дня опубликования)
title:
  rus: О валютном регулировании
  kaz: Валюталық реттеу туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1996-12-24
approved_by:
- '102000000000'
version_date:
  rus: 1999-07-15
source:
  rus: https://zan.gov.kz/client/#!/doc/104415/rus/15.07.1999
caused_by:
  code: '3654'
  requisite: Закон Республики Казахстан от 16 июля 1999 года № 431-I
  title:
    rus: О внесении изменений в Закон Республики Казахстан "О валютном регулировании"
    kaz: '"Валюталық реттеу туралы" Қазақстан Республикасы Заңына өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/3654/rus
