act_code: '208751'
requisite: Закон Республики Казахстан от 1 апреля 2025 года № 177-VIII ЗРК
title:
  rus: О ратификации Соглашения о сотрудничестве государств – участников Содружества Независимых Государств в противодействии коррупции
  kaz: Тәуелсіз Мемлекеттер Достастығына қатысушы мемлекеттердің сыбайлас жемқорлыққа қарсы іс-қимылдағы ынтымақтастығы туралы келісімді ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2025-04-01
approved_by:
- '102000000000'
version_date:
  kaz: 2025-04-01
  rus: 2025-04-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/208751/kaz/01.04.2025
  rus: https://zan.gov.kz/client/#!/doc/208751/rus/01.04.2025
