act_code: '81094'
requisite: Закон Республики Казахстан от 2 июля 2014 года № 224-V ЗРК
title:
  rus: О ратификации Соглашения между Правительством Республики Казахстан и Правительством Российской Федерации о сотрудничестве в области транспортировки российской нефти через территорию Республики Казахстан в Китайскую Народную Республику
  kaz: Қазақстан Республикасының Үкіметі мен Ресей Федерациясының Үкіметі арасындағы Қазақстан Республикасының аумағы арқылы Қытай Халық Республикасына ресейлік мұнайды тасымалдау саласындағы ынтымақтастық туралы келісімді ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2014-07-02
approved_by:
- '102000000000'
version_date:
  kaz: 2024-05-20
  rus: 2024-05-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/81094/kaz/20.05.2024
  rus: https://zan.gov.kz/client/#!/doc/81094/rus/20.05.2024
caused_by:
  code: '196878'
  requisite: Закон Республики Казахстан от 20 мая 2024 года № 84-VIII ЗРК
  title:
    rus: О ратификации Протокола о внесении изменений в Соглашение между Правительством Республики Казахстан и Правительством Российской Федерации о сотрудничестве в области транспортировки российской нефти через территорию Республики Казахстан в Китайскую Народную Республику от 24 декабря 2013 года
    kaz: 2013 жылғы 24 желтоқсандағы Қазақстан Республикасының Үкіметі мен Ресей Федерациясының Үкіметі арасындағы Қазақстан Республикасының аумағы арқылы Қытай Халық Республикасына ресейлік мұнайды тасымалдау саласындағы ынтымақтастық туралы келісімге өзгерістер енгізу туралы хаттаманы ратификациялау туралы
  link: https://zan.gov.kz/client/#!/doc/196878/rus
