act_code: '55694'
requisite: Указ Президента Республики Казахстан от 3 ноября 2010 года № 1093. Утратил силу Указом Президента Республики Казахстан от 19 января 2023 года № 106 (вводится в действие со дня его подписания)
title:
  rus: Об утверждении Положения о Департаменте по обеспечению деятельности судов при Верховном Суде Республики Казахстан (аппарате Верховного Суда Республики Казахстан)
  kaz: Қазақстан Республикасы Жоғарғы Сотының жанындағы Соттардың қызметін қамтамасыз ету департаменті (Қазақстан Республикасы Жоғарғы Сотының аппараты) туралы ережені бекіту туралы
form: УКАЗ
type_codes:
- ПОЛ
- УКАЗ
approved_on: 2010-11-03
approved_by:
- '101000000000'
version_date:
  kaz: 2019-04-05
  rus: 2019-04-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/55694/kaz/05.04.2019
  rus: https://zan.gov.kz/client/#!/doc/55694/rus/05.04.2019
caused_by:
  code: '130258'
  requisite: Указ Президента Республики Казахстан от 5 апреля 2019 года № 16
  title:
    rus: О внесении изменений и дополнений в указы Президента Республики Казахстан от 26 июня 2001 года № 643 «Об утверждении положений, предусмотренных Конституционным законом Республики Казахстан «О судебной системе и статусе судей Республики Казахстан» и от 3 ноября 2010 года № 1093 «Об утверждении Положения о Департаменте по обеспечению деятельности судов при Верховном Суде Республики Казахстан (аппарате Верховного Суда Республики Казахстан)»
    kaz: Қазақстан Республикасы Президентінің «Қазақстан Республикасының сот жүйесi мен судьяларының мәртебесi туралы» Қазақстан Республикасының Конституциялық заңында көзделген ережелердi бекiту туралы» 2001 жылғы 26 маусымдағы № 643 және «Қазақстан Республикасы Жоғарғы Сотының жанындағы Соттардың қызметін қамтамасыз ету департаменті (Қазақстан Республикасы Жоғарғы Сотының аппараты) туралы ережені бекіту туралы» 2010 жылғы 3 қарашадағы № 1093 жарлықтарына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130258/rus
