act_code: '64550'
requisite: Закон Республики Казахстан от 8 апреля 2012 года № 8-V ЗРК
title:
  rus: О ратификации Соглашения о сотрудничестве государств-членов Организации Договора о коллективной безопасности в области разработки, производства, эксплуатации, ремонта, модернизации, продления сроков эксплуатации и утилизации продукции военного назначения
  kaz: Ұжымдық қауіпсіздік туралы шарт ұйымына мүше мемлекеттердің әскери мақсаттағы өнімдерді әзірлеу, жасау, пайдалану, жөндеу, жаңғырту, пайдалану мерзімін ұзарту және кәдеге жарату саласындағы ынтымақтастығы туралы келісімді ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2012-04-08
approved_by:
- '102000000000'
version_date:
  kaz: 2012-04-08
  rus: 2012-04-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/64550/kaz/08.04.2012
  rus: https://zan.gov.kz/client/#!/doc/64550/rus/08.04.2012
