act_code: '110980'
requisite: Приказ Заместителя Премьер-Министра Республики Казахстан - Министра сельского хозяйства Республики Казахстан от 23 февраля 2017 года № 83. Зарегистрирован в Министерстве юстиции Республики Казахстан 27 марта 2017 года № 14933
title:
  rus: Об утверждении формы предписания об устранении нарушения требований законодательства Республики Казахстан о семеноводстве, протокола об административном правонарушении, постановления по делу об административном правонарушении
  kaz: Қазақстан Республикасының тұқым шаруашылығы туралы заңнамасының талаптарын бұзуды жою туралы нұсқаманың, әкімшілік құқық бұзушылық туралы хаттаманың, әкімшілік құқық бұзушылық туралы іс бойынша қаулының нысандарын бекіту туралы
form: ПРОТ
type_codes:
- ПРИК
- ПРОТ
approved_on: 2017-02-23
approved_by:
- '103012000000'
version_date:
  kaz: 2023-12-08
  rus: 2023-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/110980/kaz/08.12.2023
  rus: https://zan.gov.kz/client/#!/doc/110980/rus/08.12.2023
caused_by:
  code: '189817'
  requisite: Приказ Министра сельского хозяйства Республики Казахстан от 8 декабря 2023 года № 423. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 декабря 2023 года № 33761
  title:
    rus: О внесении изменений в приказ Заместителя Премьер-Министра Республики Казахстан – Министра сельского хозяйства Республики Казахстан от 23 февраля 2017 года № 83 «Об утверждении формы предписания об устранении нарушения требований законодательства Республики Казахстан о семеноводстве, протокола об административном правонарушении, постановления по делу об административном правонарушении»
    kaz: «Қазақстан Республикасының тұқым шаруашылығы туралы заңнамасының талаптарын бұзуды жою туралы нұсқаманың, әкімшілік құқық бұзушылық туралы хаттаманың, әкімшілік құқық бұзушылық туралы іс бойынша қаулының нысандарын бекіту туралы» Қазақстан Республикасы Премьер-Министрінің орынбасары – Қазақстан Республикасы Ауыл шаруашылығы министрінің 2017 жылғы 23 ақпандағы № 83 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/189817/rus
