act_code: '134646'
requisite: Указ Президента Республики Казахстан от 27 августа 2019 года № 141
title:
  rus: О некоторых вопросах Президентского молодежного кадрового резерва
  kaz: Президенттік жастар кадр резервінің кейбір мәселелері туралы
form: УКАЗ
type_codes:
- ПОЛ
- ПРАВ
- УКАЗ
approved_on: 2019-08-27
approved_by:
- '101000000000'
version_date:
  kaz: 2024-06-29
  rus: 2024-06-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/134646/kaz/29.06.2024
  rus: https://zan.gov.kz/client/#!/doc/134646/rus/29.06.2024
caused_by:
  code: '198356'
  requisite: Указ Президента Республики Казахстан от 29 июня 2024 года № 591
  title:
    rus: О внесении изменений и дополнений в некоторые акты Президента Республики Казахстан
    kaz: Қазақстан Республикасы Президентінің кейбір актілеріне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/198356/rus
