act_code: '3559'
requisite: Кодекс Республики Казахстан от 1 июля 1999 года № 409
title:
  rus: Гражданский кодекс Республики Казахстан (особенная часть)
  kaz: Қазақстан Республикасының азаматтық кодексі (ерекше бөлім)
form: КОД
type_codes:
- КОД
approved_on: 1999-07-01
approved_by:
- '102000000000'
version_date:
  kaz: 2003-01-08
  rus: 2003-01-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/3559/kaz/08.01.2003
  rus: https://zan.gov.kz/client/#!/doc/3559/rus/08.01.2003
caused_by:
  code: '14073'
  requisite: Закон Республики Казахстан от 8 января 2003 года N 376
  title:
    rus: О внесении изменения в Гражданский кодекс Республики Казахстан (Особенная часть)
    kaz: Қазақстан Республикасының Азаматтық кодексіне (Ерекше бөлім) өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/14073/rus
