act_code: '3559'
requisite: Кодекс Республики Казахстан от 1 июля 1999 года № 409
title:
  rus: Гражданский кодекс Республики Казахстан (особенная часть)
  kaz: Қазақстан Республикасының азаматтық кодексі (ерекше бөлім)
form: КОД
type_codes:
- КОД
approved_on: 1999-07-01
approved_by:
- '102000000000'
version_date:
  kaz: 2015-11-27
  rus: 2015-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/3559/kaz/27.11.2015
  rus: https://zan.gov.kz/client/#!/doc/3559/rus/27.11.2015
caused_by:
  code: '95779'
  requisite: Закон Республики Казахстан от 27 ноября 2015 года № 424-V ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам производства органической продукции и развития агропромышленного комплекса
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне органикалық өнім өндіру және агроөнеркәсіптік кешенді дамыту мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/95779/rus
