act_code: '3559'
requisite: Кодекс Республики Казахстан от 1 июля 1999 года № 409
title:
  rus: Гражданский кодекс Республики Казахстан (особенная часть)
  kaz: Қазақстан Республикасының азаматтық кодексі (ерекше бөлім)
form: КОД
type_codes:
- КОД
approved_on: 1999-07-01
approved_by:
- '102000000000'
version_date:
  rus: 1999-11-29
source:
  rus: https://zan.gov.kz/client/#!/doc/3559/rus/29.11.1999
caused_by:
  code: '4736'
  requisite: Закон Республики Казахстан от 29 ноября 1999 года N 486-I
  title:
    rus: О внесении изменений в Гражданский кодекс Республики Казахстан (особенная часть)
    kaz: Қазақстан Республикасының Азаматтық кодексіне (ерекше бөлім) өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/4736/rus
