act_code: '24593'
requisite: Закон Республики Казахстан от 28 июня 2005 года N 63. Утратил силу Кодексом Республики Казахстан от 20 апреля 2023 года № 224-VII (вводится в действие с 1 июля 2023 года)
title:
  rus: О государственных пособиях семьям, имеющим детей
  kaz: Балалы отбасыларға берілетін мемлекеттік жәрдемақылар туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2005-06-28
approved_by:
- '102000000000'
version_date:
  kaz: 2020-06-25
  rus: 2020-06-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/24593/kaz/25.06.2020
  rus: https://zan.gov.kz/client/#!/doc/24593/rus/25.06.2020
caused_by:
  code: '144175'
  requisite: Закон Республики Казахстан от 25 июня 2020 года № 347-VI ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам регулирования цифровых технологий
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне цифрлық технологияларды реттеу мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/144175/rus
