act_code: '104442'
requisite: Закон Республики Казахстан от 5 марта 1997 года N 77. Утратил силу - Законом РК от 2 июля 2003 года N 461
title:
  rus: О рынке ценных бумаг
  kaz: Бағалы қағаздар рыногы туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1997-03-05
approved_by:
- '102000000000'
version_date:
  kaz: 2001-07-10
  rus: 2001-07-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/104442/kaz/10.07.2001
  rus: https://zan.gov.kz/client/#!/doc/104442/rus/10.07.2001
caused_by:
  code: '9520'
  requisite: Закон Республики Казахстан от 11 июля 2001 года № 237-II
  title:
    rus: О внесении изменений и дополнения в некоторые законодательные акты Республики Казахстан по вопросам рынка ценных бумаг
    kaz: Қазақстан Республикасының кейбір заң актілеріне бағалы қағаздар рыногы мәселелері бойынша өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/9520/rus
