act_code: '9704'
requisite: Постановление Правления Национального Банка Республики Казахстан от 25 июня 2001 года N 255. Зарегистрировано в Министерстве юстиции Республики Казахстан 6 августа 2001 года N 1611. Утратило силу - постановлением Правления Агентства Республики Казахстан по регулированию и надзору финансового рынка и финансовых организаций от 9 января 2006 года N 3 (V064042)
title:
  rus: Об утверждении Правил о порядке дачи согласия на приобретение статуса крупного участника банка второго уровня или банковского холдинга
  kaz: Екінші деңгейдегі банктің немесе банктік холдингтің ірі қатысушысы мәртебесіне ие болуға келісім беру тәртібі туралы ережені бекіту жөнінде
type_codes:
- ПРАВ
approved_on: 2001-06-24
approved_by:
- '117000000000'
version_date:
  kaz: 2003-10-27
  rus: 2003-10-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/9704/kaz/27.10.2003
  rus: https://zan.gov.kz/client/#!/doc/9704/rus/27.10.2003
caused_by:
  code: '17710'
  requisite: Постановление Правления Национального Банка Республики Казахстан от 27 октября 2003 года N 376. Зарегистрировано в Министерстве юстиции Республики Казахстан 1 декабря 2003 года N 2587. Утратило силу - постановлением Правления Агентства Республики Казахстан по регулированию и надзору финансового рынка и финансовых организаций от 9 января 2006 года N 3 (V064042)
  title:
    rus: О внесении изменений и дополнения в постановление Правления Национального Банка Республики Казахстан от 25 июня 2001 года N 255 "Об утверждении Правил о порядке дачи согласия Национального Банка Республики Казахстан на приобретение статуса крупного участника банка второго уровня или банковского холдинга", зарегистрированное в Министерстве юстиции Республики Казахстан под N 1611
    kaz: Қазақстан Республикасының Әділет министрлігінде N 1611 тіркелген Қазақстан Республикасының Ұлттық Банкі Басқармасының "Екінші деңгейдегі банктің немесе банктік холдингтің ірі қатысушысы мәртебесіне ие болуға Қазақстан Республикасы Ұлттық Банкінің келісім беру тәртібі туралы ережені бекіту жөнінде" 2001 жылғы 25 маусымдағы N 255 қаулысына өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/17710/rus
