act_code: '1091'
requisite: ПРИКАЗ Таможенного комитета при Кабинете Министров Республики Казахстан от 24 июля 1995 г. N 55. Утратил силу - приказом ТК РК от 27 октября 1995  г. N 158-П ~V950135
title:
  rus: О мерах по введению маркировки отдельных подакцизных товаров, ввозимых на территорию Республики Казахстан
  kaz: Қазақстан Республикасы кеден аумағына әкелiнетiн кейбiр акцизделетiн тауарларды таңбалауды енгiзу шаралары туралы
type_codes:
- ИНСТ
approved_on: 1995-07-23
approved_by:
- '103002004000'
version_date:
  rus: 1995-07-23
source:
  rus: https://zan.gov.kz/client/#!/doc/1091/rus/23.07.1995
