act_code: '53775'
requisite: Закон Республики Казахстан от 30 июня 2010 года № 312-IV
title:
  rus: О ратификации Соглашения по вопросам свободных (специальных, особых) экономических зон на таможенной территории таможенного союза и таможенной процедуры свободной таможенной зоны
  kaz: Кеден одағының кедендік аумағындағы еркін (арнайы, ерекше) экономикалық аймақтар және еркін кедендік аймақтың кедендік рәсімі мәселелері жөніндегі келісімді ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2010-06-30
approved_by:
- '102000000000'
version_date:
  kaz: 2014-12-24
  rus: 2014-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/53775/kaz/24.12.2014
  rus: https://zan.gov.kz/client/#!/doc/53775/rus/24.12.2014
caused_by:
  code: '85244'
  requisite: Закон Республики Казахстан от 24 декабря 2014 года № 265-V ЗРК
  title:
    rus: О ратификации Договора о присоединении Республики Армения к Договору о Евразийском экономическом союзе от 29 мая 2014 года
    kaz: 2014 жылғы 29 мамырдағы Еуразиялық экономикалық одақ туралы шартқа Армения Республикасының қосылуы туралы шартты ратификациялау туралы
  link: https://zan.gov.kz/client/#!/doc/85244/rus
