act_code: '30572'
requisite: Закон Республики Казахстан от 8 декабря 2006 года № 196
title:
  rus: О ратификации Соглашения между Правительством Республики Казахстан и Региональной группой управления проектом по борьбе со СПИДом в Центральной Азии об условиях пребывания Региональной группы управления проектом по борьбе со СПИДом в Центральной Азии в Республике Казахстан
  kaz: Қазақстан Республикасының Үкіметі мен Орталық Азиядағы ЖҚТБ-мен күрес жөніндегі жобаны басқару өңірлік тобы арасындағы Орталық Азиядағы ЖҚТБ-мен күрес жөніндегі жобаны басқару өңірлік тобының Қазақстан Республикасында болу шарттары туралы келісімді ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2006-12-08
approved_by:
- '102000000000'
version_date:
  kaz: 2006-12-08
  rus: 2006-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/30572/kaz/08.12.2006
  rus: https://zan.gov.kz/client/#!/doc/30572/rus/08.12.2006
