act_code: '6568'
requisite: Постановление Правительства Республики Казахстан от 26 июля 2000 года N 1123
title:
  rus: Об утверждении Соглашения между Правительством Республики Казахстан и Правительством Азербайджанской Республики о трудовой деятельности и социальной защите граждан Азербайджанской Республики, временно работающих на территории Республики Казахстан, и граждан Республики Казахстан, временно работающих на территории Азербайджанской Республики
  kaz: Қазақстан Республикасының Үкіметі мен Әзірбайжан Республикасы Үкіметі арасындағы Қазақстан Республикасының аумағында уақытша жұмыс істейтін Әзірбайжан Республикасы азаматтарының және Әзірбайжан Республикасының аумағында уақытша жұмыс істейтін Қазақстан Республикасы азаматтарының еңбек қызметі және оларды әлеуметтік қорғау туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2000-07-25
approved_by:
- '103000000000'
version_date:
  kaz: 2000-07-25
  rus: 2000-07-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/6568/kaz/25.07.2000
  rus: https://zan.gov.kz/client/#!/doc/6568/rus/25.07.2000
