act_code: '5064'
requisite: Закон Республики Казахстан от 30 декабря 1999 года № 17
title:
  rus: О ратификации Соглашения между Республикой Беларусь, Республикой Казахстан, Кыргызской Республикой и Российской Федерацией об упрощенном порядке приобретения гражданства
  kaz: Беларусь Республикасының, Қазақстан Республикасының, Қырғыз Республикасының және Ресей Федерациясының арасындағы Азаматтық алудың оңайлатылған тәртiбi туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 1999-12-30
approved_by:
- '102000000000'
version_date:
  kaz: 1999-12-30
  rus: 1999-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/5064/kaz/30.12.1999
  rus: https://zan.gov.kz/client/#!/doc/5064/rus/30.12.1999
