act_code: '129992'
requisite: Закон Республики Казахстан от 1 апреля 2019 года № 239-VІ ЗРК
title:
  rus: О ратификации Рамочного соглашения между Правительством Республики Казахстан и Правительством Республики Узбекистан о некоторых вопросах сотрудничества в сфере энергетики
  kaz: Қазақстан Республикасының Үкіметі мен Өзбекстан Республикасының Үкіметі арасындағы Энергетика саласындағы ынтымақтастықтың кейбір мәселелері туралы негіздемелік келісімді ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2019-04-01
approved_by:
- '102000000000'
version_date:
  kaz: 2019-04-01
  rus: 2019-04-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/129992/kaz/01.04.2019
  rus: https://zan.gov.kz/client/#!/doc/129992/rus/01.04.2019
