act_code: '182233'
requisite: Закон Республики Казахстан от 29 мая 2023 года № 5-VIII ЗРК
title:
  rus: О ратификации Соглашения о сотрудничестве государств – участников СНГ по охране и защите прав на объекты авторского права и смежных прав в информационно-телекоммуникационных сетях
  kaz: ТМД-ға қатысушы мемлекеттердің ақпараттық-телекоммуникациялық желілерде авторлық құқық пен сабақтас құқықтар объектілеріне құқықтарды сақтау және қорғау бойынша ынтымақтастығы туралы келісімді ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2023-05-29
approved_by:
- '102000000000'
version_date:
  kaz: 2023-05-29
  rus: 2023-05-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/182233/kaz/29.05.2023
  rus: https://zan.gov.kz/client/#!/doc/182233/rus/29.05.2023
