act_code: '34453'
requisite: Закон Республики Казахстан от 21 июля 2007 года № 305
title:
  rus: О безопасности машин и оборудования
  kaz: Машиналар мен жабдықтардың қауіпсіздігі туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2007-07-21
approved_by:
- '102000000000'
version_date:
  kaz: 2011-07-05
  rus: 2011-07-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/34453/kaz/05.07.2011
  rus: https://zan.gov.kz/client/#!/doc/34453/rus/05.07.2011
caused_by:
  code: '59629'
  requisite: Закон Республики Казахстан от 5 июля 2011 года № 452-IV
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам пересмотра компетенции уполномоченных государственных органов и Правительства Республики Казахстан на принятие нормативных правовых актов, устанавливающих требования к проверяемым субъектам
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне уәкілетті мемлекеттік органдар мен Қазақстан Республикасы Үкіметінің тексерілетін субъектілерге қойылатын талаптарды белгілейтін нормативтік құқықтық актілерді қабылдау құзыреттерін қайта қарау мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/59629/rus
