act_code: '4782'
requisite: Утверждена Приказом Министерства финансов Республики Казахстан от 7 октября 1997 г. N 334. Зарегистрирована в Министерстве юстиции Республики Казахстан 17 декабря 1997 года N 421. Утратила силу - Приказом Министерства финансов РК от 25 мая 1999 г. N 241
title:
  rus: Инструкция О порядке открытия, ведения и закрытия банковских счетов организаций, содержащихся за счет средств республиканского и местных бюджетов Республики Казахстан
  kaz: Қазақстан Республикасының республикалық және жергiлiктi бюджетiнiң есебiнен ұсталатын ұйымдардың банктегi шоттарын ашу, жүргiзу және жабу тәртiбi туралы Нұсқаулық
type_codes:
- ИНСТ
approved_on: 1997-10-06
approved_by:
- '103002000000'
version_date:
  rus: 1997-10-06
source:
  rus: https://zan.gov.kz/client/#!/doc/4782/rus/06.10.1997
