act_code: '5503'
requisite: Указ Президента Республики Казахстан от 10 марта 2000 года N 357. Утратил силу Указом Президента Республики Казахстан от 29 декабря 2015 года № 152
title:
  rus: Об утверждении Положения о порядке прохождения государственной службы
  kaz: Мемлекеттік қызмет өткеру тәртібі туралы ережені бекіту туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2000-03-10
approved_by:
- '101000000000'
version_date:
  rus: 2000-03-10
source:
  rus: https://zan.gov.kz/client/#!/doc/5503/rus/10.03.2000
