act_code: '118154'
requisite: Нормативное постановление Верховного Суда Республики Казахстан от 8 декабря 2017 года № 12
title:
  rus: О применении судами норм Гражданского процессуального кодекса Республики Казахстан при пересмотре судебных актов по вновь открывшимся или новым обстоятельствам
  kaz: Сот актілерін жаңадан ашылған немесе жаңа мән-жайлар бойынша қайта қарау кезінде соттардың Қазақстан Республикасы Азаматтық процестік кодексінің нормаларын қолдануы туралы
form: НПОС
type_codes:
- НПОС
approved_on: 2017-12-08
approved_by:
- '105000000000'
version_date:
  kaz: 2024-11-28
  rus: 2024-11-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/118154/kaz/28.11.2024
  rus: https://zan.gov.kz/client/#!/doc/118154/rus/28.11.2024
caused_by:
  code: '204002'
  requisite: Нормативное постановление Верховного Суда Республики Казахстан от 28 ноября 2024 года № 2
  title:
    rus: О внесении изменений и дополнений в некоторые нормативные постановления Верховного Суда Республики Казахстан по гражданскому и гражданскому процессуальному законодательству
    kaz: Қазақстан Республикасы Жоғарғы Сотының кейбір нормативтік қаулыларына азаматтық және азаматтық процестік заңнама бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/204002/rus
