act_code: '11583'
requisite: Закон Республики Казахстан от 18 марта 2002 года № 304
title:
  rus: Об органах юстиции
  kaz: Әділет органдары туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2002-03-18
approved_by:
- '102000000000'
version_date:
  kaz: 2008-06-24
  rus: 2008-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/11583/kaz/24.06.2008
  rus: https://zan.gov.kz/client/#!/doc/11583/rus/24.06.2008
caused_by:
  code: '40215'
  requisite: Закон Республики Казахстан от 24 июня 2008 года N 46-IV
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам охраны исправительных учреждений
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне түзеу мекемелерін күзету мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/40215/rus
