act_code: '16048'
requisite: Закон Республики Казахстан от 2 июля 2003 года N 456-ІІ
title:
  rus: О ратификации Соглашения между Правительством Республики Казахстан и Правительством Королевства Испания о международных автомобильных перевозках пассажиров и грузов
  kaz: Қазақстан Республикасының Үкіметі мен Испания Корольдігі Үкіметінің арасындағы Жолаушылар мен жүктердің халықаралық автомобиль тасымалы туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2003-07-01
approved_by:
- '102000000000'
version_date:
  kaz: 2003-07-01
  rus: 2003-07-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/16048/kaz/01.07.2003
  rus: https://zan.gov.kz/client/#!/doc/16048/rus/01.07.2003
