act_code: '58171'
requisite: Указ Президента Республики Казахстан от 6 декабря 2010 года № 1116
title:
  rus: О Совете по управлению Фондом национального благосостояния "Самрук-Казына"
  kaz: '"Самұрық-Қазына" ұлттық әл-ауқат қорын басқару жөніндегі кеңес туралы'
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2010-12-06
approved_by:
- '101000000000'
version_date:
  kaz: 2010-12-06
  rus: 2010-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/58171/kaz/06.12.2010
  rus: https://zan.gov.kz/client/#!/doc/58171/rus/06.12.2010
