act_code: '96914'
requisite: Указ Президента Республики Казахстан от 29 декабря 2015 года № 152
title:
  rus: О некоторых вопросах прохождения государственной службы
  kaz: Мемлекеттік қызмет өткерудің кейбір мәселелері туралы
form: УКАЗ
type_codes:
- ПРАВ
- УКАЗ
approved_on: 2015-12-29
approved_by:
- '101000000000'
version_date:
  kaz: 2024-11-21
  rus: 2024-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/96914/kaz/21.11.2024
  rus: https://zan.gov.kz/client/#!/doc/96914/rus/21.11.2024
caused_by:
  code: '203023'
  requisite: Указ Президента Республики Казахстан от 21 ноября 2024 года № 709
  title:
    rus: О внесении изменения и дополнений в некоторые указы Президента Республики Казахстан
    kaz: Қазақстан Республикасы Президентінің кейбір жарлықтарына өзгеріс пен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/203023/rus
