act_code: '216'
requisite: Приказ Министерства юстиции Республики Казахстан от 11 февраля 1998 года № 131. Зарегистрирован в Министерстве юстиции Республики Казахстан 25 февраля 1998 года № 470. Утратил силу приказом Министерства юстиции Республики Казахстан от 30 апреля 1998 года № 339
title:
  rus: Положение "О Центральной аттестационной комиссии"
  kaz: Орталық аттестациялық комиссия туралы Ереже
type_codes:
- ПОЛ
approved_on: 1998-02-11
approved_by:
- '103001000000'
version_date:
  rus: 1998-02-11
source:
  rus: https://zan.gov.kz/client/#!/doc/216/rus/11.02.1998
