act_code: '96634'
requisite: Указ Президента Республики Казахстан от 23 декабря 2015 года № 137
title:
  rus: О мерах по совершенствованию деятельности Высшего Судебного Совета Республики Казахстан
  kaz: Қазақстан Республикасы Жоғары Сот Кеңесінің қызметін жетілдіру шаралары туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2015-12-23
approved_by:
- '101000000000'
version_date:
  kaz: 2025-01-01
  rus: 2025-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/96634/kaz/01.01.2025
  rus: https://zan.gov.kz/client/#!/doc/96634/rus/01.01.2025
caused_by:
  code: '204254'
  requisite: Указ Президента Республики Казахстан от 18 декабря 2024 года № 736
  title:
    rus: О внесении изменений и дополнений в указы Президента Республики Казахстан от 26 июня 2001 года № 643 «Об утверждении положений, предусмотренных Конституционным законом Республики Казахстан «О судебной системе и статусе судей Республики Казахстан» и от 23 декабря 2015 года № 137 «О мерах по совершенствованию деятельности Высшего Судебного Совета Республики Казахстан»
    kaz: Қазақстан Республикасы Президентінің «Қазақстан Республикасының сот жүйесi мен судьяларының мәртебесi туралы» Қазақстан Республикасының Конституциялық заңында көзделген ережелердi бекiту туралы» 2001 жылғы 26 маусымдағы № 643 және «Қазақстан Республикасы Жоғары Сот Кеңесінің қызметін жетілдіру шаралары туралы» 2015 жылғы 23 желтоқсандағы № 137 жарлықтарына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/204254/rus
