act_code: '4712'
requisite: Указ Президента Республики Казахстан от 3 декабря 1999 года № 280. Утратил силу Указом Президента Республики Казахстан от 29 августа 2014 года № 900
title:
  rus: Вопросы Агентства Республики Казахстан по делам государственной службы
  kaz: Қазақстан Республикасы Мемлекеттік қызмет істері агенттігінің мәселелері
form: УКАЗ
type_codes:
- ПОЛ
- УКАЗ
approved_on: 1999-12-03
approved_by:
- '101000000000'
version_date:
  kaz: 2013-08-09
  rus: 2013-08-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/4712/kaz/09.08.2013
  rus: https://zan.gov.kz/client/#!/doc/4712/rus/09.08.2013
caused_by:
  code: '73929'
  requisite: Указ Президента Республики Казахстан от 9 августа 2013 года № 608. Утратил силу Указом Президента Республики Казахстан от 29 августа 2014 года № 900
  title:
    rus: О внесении изменений и дополнений в Указ Президента Республики Казахстан от 3 декабря 1999 года № 280 "Вопросы Агентства Республики Казахстан по делам государственной службы"
    kaz: '"Қазақстан Республикасы Мемлекеттік қызмет істері агенттігінің мәселелері" Қазақстан Республикасы Президентінің 1999 жылғы 3 желтоқсандағы № 280 Жарлығына өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/73929/rus
