act_code: '111946'
requisite: Закон Республики Казахстан от 6 мая 2017 года № 62-VI ЗРК
title:
  rus: О коллекторской деятельности
  kaz: Коллекторлық қызмет туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2017-05-06
approved_by:
- '102000000000'
version_date:
  kaz: 2024-06-19
  rus: 2024-06-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/111946/kaz/19.06.2024
  rus: https://zan.gov.kz/client/#!/doc/111946/rus/19.06.2024
caused_by:
  code: '197920'
  requisite: Закон Республики Казахстан от 19 июня 2024 года № 97-VIII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам минимизации рисков при кредитовании, защиты прав заемщиков, совершенствования регулирования финансового рынка и исполнительного производства
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне кредит беру кезінде тәуекелдерді барынша азайту, қарыз алушылардың құқықтарын қорғау, қаржы нарығын реттеуді және атқарушылық іс жүргізуді жетілдіру мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/197920/rus
