act_code: '111946'
requisite: Закон Республики Казахстан от 6 мая 2017 года № 62-VI ЗРК
title:
  rus: О коллекторской деятельности
  kaz: Коллекторлық қызмет туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2017-05-06
approved_by:
- '102000000000'
version_date:
  kaz: 2022-09-05
  rus: 2022-09-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/111946/kaz/05.09.2022
  rus: https://zan.gov.kz/client/#!/doc/111946/rus/05.09.2022
caused_by:
  code: '169539'
  requisite: Закон Республики Казахстан от 4 июля 2022 года № 133-VII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам развития рынка стрессовых активов
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне стрестік активтер нарығын дамыту мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/169539/rus
