act_code: '104090'
requisite: Закон Республики Казахстан от 14 января 1992 года. Утратил силу Законом Республики Казахстан от 20 декабря 2004 года № 12 (вводится в действие с 1 января 2005 года)
title:
  rus: Об особенностях приватизации имущества государственных сельскохозяйственных предприятий
  kaz: Об особенностях приватизации имущества государственных сельскохозяйственных предприятий
form: ЗАК
type_codes:
- ЗАК
approved_on: 1992-01-14
approved_by:
- '102000000000'
version_date:
  rus: 1995-10-30
source:
  rus: https://zan.gov.kz/client/#!/doc/104090/rus/30.10.1995
