act_code: '33116'
requisite: Закон Республики Казахстан от 7 мая 2007 года N 246
title:
  rus: О ратификации Соглашения о транзите при международных воздушных сообщениях
  kaz: Халықаралық әуе қатынастары кезіндегі транзит туралы келісімді ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2007-05-07
approved_by:
- '102000000000'
version_date:
  kaz: 2007-05-07
  rus: 2007-05-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/33116/kaz/07.05.2007
  rus: https://zan.gov.kz/client/#!/doc/33116/rus/07.05.2007
