act_code: '11968'
requisite: Закон Республики Казахстан от 18 апреля 2002 года № 315
title:
  rus: О ратификации Соглашения между Правительством Республики Казахстан и Правительством Кыргызской Республики о передаче ответственности за организацию и управление воздушным движением
  kaz: Қазақстан Республикасының Үкіметі мен Қырғыз Республикасы Үкіметінің арасындағы әуе қозғалысын ұйымдастыру мен басқару үшін жауапкершілікті беру туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2002-04-17
approved_by:
- '102000000000'
version_date:
  kaz: 2002-04-17
  rus: 2002-04-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/11968/kaz/17.04.2002
  rus: https://zan.gov.kz/client/#!/doc/11968/rus/17.04.2002
