act_code: '3863'
requisite: Указ Президента Республики Казахстан от 25 августа 1999 г. N 191
title:
  rus: Об утверждении Конвенции о создании и статусе международных научно-исследовательских центров и научных организаций
  kaz: Халықаралық ғылыми-зерттеу орталықтары мен ғылыми ұйымдарды құру және олардың мәртебесі туралы конвенцияны бекіту туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 1999-08-24
approved_by:
- '101000000000'
version_date:
  kaz: 1999-08-24
  rus: 1999-08-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/3863/kaz/24.08.1999
  rus: https://zan.gov.kz/client/#!/doc/3863/rus/24.08.1999
