act_code: '104335'
requisite: Закон Веpховного Совета Республики Казахстан от 8 июля 1994 года N 110-ХIII. Утратил силу - Законом РК от 4 декабря 2002 года N 361
title:
  rus: О санитарно-эпидемиологическом благополучии населения
  kaz: Халықтың санитарлық-эпидемиологиялық салауаттылығы туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1994-07-07
approved_by:
- '102000000000'
version_date:
  rus: 1994-07-07
source:
  rus: https://zan.gov.kz/client/#!/doc/104335/rus/07.07.1994
