act_code: '62774'
requisite: Закон Республики Казахстан от 9 января 2012 года № 532-IV
title:
  rus: О газе и газоснабжении
  kaz: Газ және газбен жабдықтау туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2012-01-09
approved_by:
- '102000000000'
version_date:
  kaz: 2020-12-30
  rus: 2020-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/62774/kaz/30.12.2020
  rus: https://zan.gov.kz/client/#!/doc/62774/rus/30.12.2020
caused_by:
  code: '151219'
  requisite: Закон Республики Казахстан от 30 декабря 2020 года № 393-VI ЗРК
  title:
    rus: 'О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросу реализации отдельных положений Послания Главы государства народу Казахстана от 1 сентября 2020 года «Казахстан в новой реальности: время действий»'
    kaz: 'Қазақстан Республикасының кейбір заңнамалық актілеріне Мемлекет басшысының 2020 жылғы 1 қыркүйектегі «Жаңа жағдайдағы Қазақстан: іс-қимыл кезеңі» атты Қазақстан халқына Жолдауының жекелеген ережелерін іске асыру мәселесі бойынша өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/151219/rus
