act_code: '10674'
requisite: Закон Республики Казахстан от 15 декабря 2001 года № 271. Утратил силу Законом Республики Казахстан от 15 июля 2010 года № 339-IV
title:
  rus: О государственном регулировании гражданской авиации
  kaz: Азаматтық авиацияны мемлекеттiк реттеу туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2001-12-15
approved_by:
- '102000000000'
version_date:
  kaz: 2005-04-15
  rus: 2005-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/10674/kaz/15.04.2005
  rus: https://zan.gov.kz/client/#!/doc/10674/rus/15.04.2005
caused_by:
  code: '23713'
  requisite: Закон Республики Казахстан от 15 апреля 2005 года № 45
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам лицензирования
    kaz: Қазақстан Республикасының кейбiр заңнамалық актiлерiне лицензиялау мәселелерi бойынша өзгерiстер мен толықтырулар енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/23713/rus
