act_code: '6333'
requisite: Указ Президента Республики Казахстан от 6 июля 2000 года N 417. Утратил силу Указом Президента Республики Казахстан от 9 января 2006 года N 1696
title:
  rus: О структуре Вооруженных Сил Республики Казахстан
  kaz: Қазақстан Республикасы Қарулы Күштерінің құрылымы туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2000-07-05
approved_by:
- '101000000000'
version_date:
  kaz: 2003-05-06
  rus: 2003-05-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/6333/kaz/06.05.2003
  rus: https://zan.gov.kz/client/#!/doc/6333/rus/06.05.2003
caused_by:
  code: U030001085_
