act_code: '20569'
requisite: Закон Республики Казахстан от 9 июля 2004 года № 588
title:
  rus: Об электроэнергетике
  kaz: Электр энергетикасы туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2004-07-09
approved_by:
- '102000000000'
version_date:
  kaz: 2023-04-01
  rus: 2023-04-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/20569/kaz/01.04.2023
  rus: https://zan.gov.kz/client/#!/doc/20569/rus/01.04.2023
caused_by:
  code: '178541'
  requisite: Закон Республики Казахстан от 6 февраля 2023 года № 194-VII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам цифровых активов и информатизации
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне цифрлық активтер және ақпараттандыру мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/178541/rus
