act_code: '18187'
requisite: Закон Республики Казахстан от 13 января 2004 года № 522. Утратил силу Кодексом Республики Казахстан от 18 сентября 2009 года № 193-IV
title:
  rus: О лекарственных средствах
  kaz: Дәрiлiк заттар туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2004-01-13
approved_by:
- '102000000000'
version_date:
  kaz: 2006-07-07
  rus: 2006-07-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/18187/kaz/07.07.2006
  rus: https://zan.gov.kz/client/#!/doc/18187/rus/07.07.2006
caused_by:
  code: '28850'
  requisite: Закон Республики Казахстан от 7 июля 2006 года № 171
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам здравоохранения
    kaz: Қазақстан Республикасының кейбiр заңнамалық актiлерiне денсаулық сақтау мәселелерi бойынша өзгерiстер мен толықтырулар енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/28850/rus
