act_code: '7966'
requisite: Закон Республики Казахстан от 23 января 2001 года № 148
title:
  rus: О местном государственном управлении и самоуправлении в Республике Казахстан
  kaz: Қазақстан Республикасындағы жергілікті мемлекеттік басқару және өзін-өзі басқару туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2001-01-23
approved_by:
- '102000000000'
version_date:
  rus: 2001-01-23
source:
  rus: https://zan.gov.kz/client/#!/doc/7966/rus/23.01.2001
