act_code: '7966'
requisite: Закон Республики Казахстан от 23 января 2001 года № 148
title:
  rus: О местном государственном управлении и самоуправлении в Республике Казахстан
  kaz: Қазақстан Республикасындағы жергілікті мемлекеттік басқару және өзін-өзі басқару туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2001-01-23
approved_by:
- '102000000000'
version_date:
  kaz: 2011-03-24
  rus: 2011-03-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/7966/kaz/24.03.2011
  rus: https://zan.gov.kz/client/#!/doc/7966/rus/24.03.2011
caused_by:
  code: '57869'
  requisite: Закон Республики Казахстан от 24 марта 2011 года № 420-IV
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам деятельности крестьянских или фермерских хозяйств
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне шаруа немесе фермер қожалықтарының қызметі мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/57869/rus
