act_code: '148866'
requisite: Постановление Правительства Республики Казахстан от 19 ноября 2020 года № 774
title:
  rus: Об утверждении Соглашения между Правительством Республики Казахстан и Правительством Турецкой Республики о взаимной защите секретной информации в военной области
  kaz: Қазақстан Республикасының Үкіметі мен Түркия Республикасының Үкіметі арасындағы әскери саладағы құпия ақпаратты өзара қорғау туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2020-11-19
approved_by:
- '103000000000'
version_date:
  kaz: 2020-11-19
  rus: 2020-11-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/148866/kaz/19.11.2020
  rus: https://zan.gov.kz/client/#!/doc/148866/rus/19.11.2020
