act_code: '76855'
requisite: Указ Президента Республики Казахстан от 13 января 2014 года № 722
title:
  rus: Об утверждении Правил оформления, выдачи, замены, сдачи, изъятия, учета, хранения и уничтожения дипломатических и служебных паспортов Республики Казахстан и перечня должностных лиц Республики Казахстан, которым выдаются дипломатические и служебные паспорта Республики Казахстан
  kaz: Қазақстан Республикасының дипломатиялық және қызметтік паспорттарын ресімдеу, беру, ауыстыру, тапсыру, алып қою, есепке алу, сақтау және жою қағидаларын және Қазақстан Республикасының дипломатиялық және қызметтік паспорттары берілетін Қазақстан Республикасының лауазымды адамдарының тізбесін бекіту туралы
form: УКАЗ
type_codes:
- ПРАВ
- ПРЧ
- УКАЗ
approved_on: 2014-01-13
approved_by:
- '101000000000'
version_date:
  kaz: 2022-05-18
  rus: 2022-05-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/76855/kaz/18.05.2022
  rus: https://zan.gov.kz/client/#!/doc/76855/rus/18.05.2022
caused_by:
  code: '168721'
  requisite: Указ Президента Республики Казахстан от 18 мая 2022 года № 895
  title:
    rus: О внесении дополнения в Указ Президента Республики Казахстан от 13 января 2014 года № 722 «Об утверждении Правил оформления, выдачи, замены, сдачи, изъятия, учета, хранения и уничтожения дипломатических и служебных паспортов Республики Казахстан и перечня должностных лиц Республики Казахстан, которым выдаются дипломатические и служебные паспорта Республики Казахстан»
    kaz: «Қазақстан Республикасының дипломатиялық және қызметтік паспорттарын ресімдеу, беру, ауыстыру, тапсыру, алып қою, есепке алу, сақтау және жою қағидаларын және Қазақстан Республикасының дипломатиялық және қызметтік паспорттары берілетін Қазақстан Республикасының лауазымды адамдарының тізбесін бекіту туралы» Қазақстан Республикасы Президентінің 2014 жылғы 13 қаңтардағы № 722 Жарлығына толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/168721/rus
