act_code: '104443'
requisite: Закон Республики Казахстан от 5 марта 1997 года N 78. Утратил силу - Законом РК от 2 июля 2003 года N 461
title:
  rus: О регистрации сделок с ценными бумагами в Республике Казахстан
  kaz: Қазақстан Республикасында Бағалы қағаздармен жасалған мәмiлелердi тiркеу туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1997-03-05
approved_by:
- '102000000000'
version_date:
  rus: 2001-03-02
source:
  rus: https://zan.gov.kz/client/#!/doc/104443/rus/02.03.2001
caused_by:
  code: '8282'
  requisite: Закон Республики Казахстан от 2 марта 2001 года № 162-II
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам банковской деятельности
    kaz: Қазақстан Республикасының кейбір заң актілеріне банк қызметі мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/8282/rus
