act_code: '1658'
requisite: Распоряжение акима Западно-Казахстанской области от 9 июля 1998 года № 1-46р. Зарегистрировано Управлением юстиции Западно-Казахстанской области 21 июля 1998 года № 20. Утратило силу решением акима Западно-Казахстанской области от 30 декабря 1999 года № 254
title:
  rus: Об утверждении лимитов вылова рыбы природопользователями области на 1998 год
  kaz: Облыс табиғат пайдаланушыларының 1998 жылға балық аулауының лимитін белгілеу туралы
form: РАСП
type_codes:
- РАСП
approved_on: 1998-07-08
approved_by:
- '159000000001'
version_date:
  kaz: 1998-07-08
  rus: 1998-07-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/1658/kaz/08.07.1998
  rus: https://zan.gov.kz/client/#!/doc/1658/rus/08.07.1998
