act_code: '96918'
requisite: Указ Президента Республики Казахстан от 29 декабря 2015 года № 154
title:
  rus: Об утверждении Правил подготовки, внесения Национального доклада о противодействии коррупции Президенту Республики Казахстан и его опубликования
  kaz: Сыбайлас жемқорлыққа қарсы іс-қимыл туралы ұлттық баяндаманы дайындау, Қазақстан Республикасының Президентіне енгізу және оны жариялау қағидаларын бекіту туралы
form: УКАЗ
type_codes:
- ПРАВ
- УКАЗ
approved_on: 2015-12-29
approved_by:
- '101000000000'
version_date:
  kaz: 2022-02-02
  rus: 2022-02-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/96918/kaz/02.02.2022
  rus: https://zan.gov.kz/client/#!/doc/96918/rus/02.02.2022
caused_by:
  code: '164308'
  requisite: Указ Президента Республики Казахстан от 2 февраля 2022 года № 802
  title:
    rus: Об утверждении Концепции антикоррупционной политики Республики Казахстан на 2022 – 2026 годы и внесении изменений в некоторые указы Президента Республики Казахстан
    kaz: Қазақстан Республикасының сыбайлас жемқорлыққа қарсы саясатының 2022 – 2026 жылдарға арналған тұжырымдамасын бекіту және Қазақстан Республикасы Президентінің кейбір жарлықтарына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/164308/rus
