act_code: '104323'
requisite: Закон Республики Казахстан от 5 октября 1995 года N 2486
title:
  rus: О производственном кооперативе
  kaz: Өндiрiстiк кооператив туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1995-10-05
approved_by:
- '101000000000'
version_date:
  kaz: 2001-07-11
  rus: 2001-07-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/104323/kaz/11.07.2001
  rus: https://zan.gov.kz/client/#!/doc/104323/rus/11.07.2001
caused_by:
  code: '9498'
  requisite: Закон Республики Казахстан от 12 июля 2001 года № 241-II
  title:
    rus: О внесении изменений и дополнений в Указ Президента Республики Казахстан, имеющий силу Закона, "О производственном кооперативе"
    kaz: Қазақстан Республикасы Президентiнiң "Өндiрiстiк кооператив туралы" заң күшi бар Жарлығына өзгерiстер мен толықтырулар енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/9498/rus
