act_code: '17606'
requisite: Постановление Правительства Республики Казахстан от 28 ноября 2003 года N 1194. Утратило силу постановлением Правительства Республики Казахстан от 18 марта 2016 года № 148
title:
  rus: Об утверждении типовых договоров на предоставляемые услуги (товары, работы), относящиеся к сфере естественной монополии
  kaz: Табиғи монополия саласына жататын, ұсынылатын қызметтерге (тауарларға, жұмыстарға) арналған үлгi шарттарды бекiту туралы
form: ДОГ
type_codes:
- ДОГ
- ПОСТ
approved_on: 2003-11-28
approved_by:
- '103000000000'
version_date:
  kaz: 2013-07-23
  rus: 2013-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/17606/kaz/23.07.2013
  rus: https://zan.gov.kz/client/#!/doc/17606/rus/23.07.2013
caused_by:
  code: '73579'
  requisite: Постановление Правительства Республики Казахстан от 23 июля 2013 года № 735
  title:
    rus: О внесении изменений в некоторые решения Правительства Республики Казахстан
    kaz: Қазақстан Республикасы Үкiметiнiң кейбiр шешiмдерiне өзгерiстер енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/73579/rus
