act_code: '123163'
requisite: Закон Республики Казахстан от 2 июля 2018 года № 169-VІ ЗРК
title:
  rus: О защите детей от информации, причиняющей вред их здоровью и развитию
  kaz: Балаларды денсаулығы мен дамуына зардабын тигізетін ақпараттан қорғау туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2018-07-02
approved_by:
- '102000000000'
version_date:
  kaz: 2026-07-12
  rus: 2026-07-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/123163/kaz/12.07.2026
  rus: https://zan.gov.kz/client/#!/doc/123163/rus/12.07.2026
caused_by:
  code: '226889'
  requisite: Закон Республики Казахстан от 24 июня 2026 года № 326-VIII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам цифровизации, защиты персональных данных, дорожного движения и регулирования передовых технологий на транспорте
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне цифрландыру, дербес деректерді қорғау, жол жүрісі және көліктегі озық технологияларды реттеу мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/226889/rus
