act_code: '312'
requisite: Приказ Таможенного комитета Республики Казахстан от 6 января 1997 г. N 2-П. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 февраля 1997 г. N 264. Утратил силу - приказом Таможенного комитета МГД РК от 9 февраля 2001 г. N 46
title:
  rus: О порядке таможенного контроля в свободной таможенной зоне
  kaz: Еркiн кеден аймағындағы кедендiк бақылаудың тәртiбi туралы
type_codes:
- ПОР
approved_on: 1997-01-06
approved_by:
- '103002004000'
version_date:
  rus: 1997-01-06
source:
  rus: https://zan.gov.kz/client/#!/doc/312/rus/06.01.1997
