act_code: '7949'
requisite: Совместный приказ Председателя Агентства Республики Казахстан по делам здравоохранения от 13 декабря 2000 года № 799 и Министра внутренних дел Республики Казахстан от 6 декабря 2000 года № 668. Зарегистрирован в Министерстве юстиции Республики Казахстан 12.01.2001 г. за № 1360. Утратил силу совместным приказом и.о. Министра здравоохранения Республики Казахстан от 10 ноября 2009 года № 686 и и.о. Министра внутренних дел Республики Казахстан от 25 ноября 2009 года № 441
title:
  rus: Об организации принудительного лечения граждан, больных заразной формой туберкулеза
  kaz: Туберкулездің жұқпалы түрімен ауыратын азаматтарды мәжбүрлеп емдеуді ұйымдастыру туралы
type_codes:
- ПРАВ
approved_on: 2000-12-13
approved_by:
- '103003000000'
- '103010000000'
version_date:
  rus: 2009-11-10
source:
  rus: https://zan.gov.kz/client/#!/doc/7949/rus/10.11.2009
caused_by:
  code: A09R0001800
