act_code: '47702'
requisite: Закон Республики Казахстан от 28 августа 2009 года № 191-IV
title:
  rus: О противодействии легализации (отмыванию) доходов, полученных преступным путем, и финансированию терроризма
  kaz: Қылмыстық жолмен алынған кірістерді заңдастыруға (жылыстатуға) және терроризмді қаржыландыруға қарсы іс-қимыл туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2009-08-28
approved_by:
- '102000000000'
version_date:
  kaz: 2023-09-12
  rus: 2023-09-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/47702/kaz/12.09.2023
  rus: https://zan.gov.kz/client/#!/doc/47702/rus/12.09.2023
caused_by:
  code: '183935'
  requisite: Закон Республики Казахстан от 12 июля 2023 года № 23-VIII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам возврата государству незаконно приобретенных активов
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне заңсыз иемденілген активтерді мемлекетке қайтару мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/183935/rus
