act_code: '12072'
requisite: Указ Президента Республики Казахстан от 7 мая 2002 года № 865. Утратил силу Указом Президента Республики Казахстан от 30 сентября 2011 года № 155
title:
  rus: О медалях Вооруженных Сил Республики Казахстан
  kaz: Қазақстан Республикасы Қарулы Күштерінің медальдары туралы
form: УКАЗ
type_codes:
- ОПИС
- ПРЧ
- УКАЗ
approved_on: 2002-05-06
approved_by:
- '101000000000'
version_date:
  kaz: 2004-06-15
  rus: 2004-06-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/12072/kaz/15.06.2004
  rus: https://zan.gov.kz/client/#!/doc/12072/rus/15.06.2004
caused_by:
  code: '20385'
  requisite: Указ Президента Республики Казахстан от 16 июня 2004 года № 1393. Утратил силу Указом Президента Республики Казахстан от 30 сентября 2011 года № 155
  title:
    rus: О внесении дополнений в Указ Президента Республики Казахстан от 7 мая 2002 года N 865
    kaz: Қазақстан Республикасы Президентiнiң 2002 жылғы 7 мамырдағы N 865 Жарлығына толықтырулар енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/20385/rus
