act_code: '31398'
requisite: Закон Республики Казахстан от 12 января 2007 года N 223
title:
  rus: О национальных реестрах идентификационных номеров
  kaz: Сәйкестендiру нөмiрлерiнiң ұлттық тiзiлiмдерi туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2007-01-12
approved_by:
- '102000000000'
version_date:
  kaz: 2013-01-29
  rus: 2013-01-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/31398/kaz/29.01.2013
  rus: https://zan.gov.kz/client/#!/doc/31398/rus/29.01.2013
caused_by:
  code: '70574'
  requisite: Закон Республики Казахстан от 29 января 2013 года № 74-V
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам документов, удостоверяющих личность
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне жеке басты куәландыратын құжаттар мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/70574/rus
