act_code: '59665'
requisite: Закон Республики Казахстан от 8 июля 2011 года № 456-IV
title:
  rus: О ратификации Соглашения о единых принципах и правилах конкуренции
  kaz: Бәсекелестіктің бірыңғай қағидаттары мен қағидалары туралы келісімді ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2011-07-08
approved_by:
- '102000000000'
version_date:
  kaz: 2011-07-08
  rus: 2011-07-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/59665/kaz/08.07.2011
  rus: https://zan.gov.kz/client/#!/doc/59665/rus/08.07.2011
