act_code: '60054'
requisite: Постановление Правительства Республики Казахстан от 27 июня 2011 года № 716. Утратило силу постановлением Правительства Республики Казахстан от 10 августа 2015 года № 622
title:
  rus: Об утверждении Типового договора организации регулярных автомобильных перевозок пассажиров и багажа
  kaz: Жолаушылар мен багажды автомобильмен тұрақты тасымалдауды ұйымдастырудың үлгі шартын бекіту туралы
form: ДОГ
type_codes:
- ДОГ
- ПОСТ
approved_on: 2011-06-27
approved_by:
- '103000000000'
version_date:
  kaz: 2011-06-27
  rus: 2011-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/60054/kaz/27.06.2011
  rus: https://zan.gov.kz/client/#!/doc/60054/rus/27.06.2011
