act_code: '1722'
requisite: Утверждено приказом Министра транспорта и коммуникаций Республики Казахстан от 10 августа 1998 года № 172. Зарегистрирован Министерством юстиции Республики Казахстан 13 октября 1998 года № 617. Утратил силу приказом и.о. Министра транспорта и коммуникаций Республики Казахстан от 12 октября 2012 года № 691
title:
  rus: Инструкция по оценке технического состояния маломерных судов, их баз-стоянок, переправ, поднадзорных Комитету транспортного контроля Министерства транспорта и коммуникаций Республики Казахстан
  kaz: Қазақстан Республикасы Көлік және коммуникация министрлігі Көліктік бақылау комитетінің қадағалауындағы шағын өлшемді кемелердің, олардың тұрақ-базаларының, өткелдердің техникалық күйін бағалау бойынша нұсқаулық
type_codes:
- ИНСТ
approved_on: 1998-08-09
approved_by:
- '103013000000'
version_date:
  kaz: 2005-06-24
  rus: 2005-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/1722/kaz/24.06.2005
  rus: https://zan.gov.kz/client/#!/doc/1722/rus/24.06.2005
caused_by:
  code: '24610'
  requisite: Приказ и.о. Министра транспорта и коммуникаций Республики Казахстан от 24 июня 2005 года № 220-I. Зарегистрирован Министерством юстиции Республики Казахстан 4 июля 2005 года № 3713. Утратил силу приказом и.о. Министра транспорта и коммуникаций Республики Казахстан от 6 августа 2011 года № 496
  title:
    rus: О внесении изменений и дополнений в приказ и.о. Министра транспорта и коммуникаций Республики Казахстан от 10 августа 1998 года № 172 "Об утверждении документов, регламентирующих безопасность плавания маломерных судов на водоемах Республики Казахстан"
    kaz: '"Қазақстан Республикасы су қоймаларында шағын өлшемді кемелердің жүзу қауіпсіздігін белгілейтін құжаттарды бекіту туралы" Қазақстан Республикасының Көлік және коммуникациялар министрі м.а. 1998 жылғы 10 тамыздағы N 172 бұйрығына өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/24610/rus
