act_code: '879'
requisite: Кодекс Республики Казахстан от 27 декабря 1994 года № 268-XIII
title:
  rus: ГРАЖДАНСКИЙ КОДЕКС РЕСПУБЛИКИ КАЗАХСТАН (ОБЩАЯ ЧАСТЬ)
  kaz: ҚАЗАҚСТАН РЕСПУБЛИКАСЫНЫҢ АЗАМАТТЫҚ КОДЕКСI (ЖАЛПЫ БӨЛІМ)
form: КОД
type_codes:
- КОД
approved_on: 1994-12-27
approved_by:
- '102000000000'
version_date:
  rus: 1998-03-22
source:
  rus: https://zan.gov.kz/client/#!/doc/879/rus/22.03.1998
caused_by:
  code: '227'
  requisite: Закон Республики Казахстан от 2 марта 1998 года № 211
  title:
    rus: О внесении изменений и дополнений в Гражданский кодекс Республики Казахстан (общая часть) и в Постановление Верховного Совета Республики Казахстан "О введении в действие Гражданского кодекса Республики Казахстан (общая часть)"
    kaz: Қазақстан Республикасының Азаматтық кодексiне (жалпы бөлiм) және "Қазақстан Республикасының Азаматтық кодексiн (жалпы бөлiм) күшiне енгiзу туралы" Қазақстан Республикасы Жоғарғы Кеңесiнiң қаулысына өзгерiстер мен толықтырулар енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/227/rus
