act_code: '879'
requisite: Кодекс Республики Казахстан от 27 декабря 1994 года № 268-XIII
title:
  rus: ГРАЖДАНСКИЙ КОДЕКС РЕСПУБЛИКИ КАЗАХСТАН (ОБЩАЯ ЧАСТЬ)
  kaz: ҚАЗАҚСТАН РЕСПУБЛИКАСЫНЫҢ АЗАМАТТЫҚ КОДЕКСI (ЖАЛПЫ БӨЛІМ)
form: КОД
type_codes:
- КОД
approved_on: 1994-12-27
approved_by:
- '102000000000'
version_date:
  rus: 1997-01-21
source:
  rus: https://zan.gov.kz/client/#!/doc/879/rus/21.01.1997
caused_by:
  code: '104433'
  requisite: Закон Республики Казахстан от 21 января 1997 года N 68-1
  title:
    rus: О признании утратившим силу Указа Президента Республики Казахстан, имеющего силу Закона, "О банкротстве" и внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан
    kaz: Қазақстан Республикасы Президентiнiң "Банкроттық туралы" Заң күшi бар Жарлығының күшi жойылды деп тану және Қазақстан Республикасының кейбiр заң актiлерiне өзгерiстер мен толықтырулар енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/104433/rus
