act_code: '151312'
requisite: Кодекс Республики Казахстан от 2 января 2021 года № 400-VI ЗРК
title:
  rus: ЭКОЛОГИЧЕСКИЙ КОДЕКС РЕСПУБЛИКИ КАЗАХСТАН
  kaz: ҚАЗАҚСТАН РЕСПУБЛИКАСЫНЫҢ ЭКОЛОГИЯ КОДЕКСІ
form: КОД
type_codes:
- КОД
approved_on: 2021-01-02
approved_by:
- '102000000000'
version_date:
  kaz: 2025-07-17
  rus: 2025-07-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/151312/kaz/17.07.2025
  rus: https://zan.gov.kz/client/#!/doc/151312/rus/17.07.2025
caused_by:
  code: '212519'
  requisite: Закон Республики Казахстан от 17 июля 2025 года № 213-VIII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам развития столицы и городов республиканского значения, национальных проектов, предпринимательства и оптимизации функций государственных органов
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне астананы және республикалық маңызы бар қалаларды, ұлттық жобаларды дамыту, кәсіпкерлік және мемлекеттік органдардың функцияларын оңтайландыру мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/212519/rus
