act_code: '151312'
requisite: Кодекс Республики Казахстан от 2 января 2021 года № 400-VI ЗРК
title:
  rus: ЭКОЛОГИЧЕСКИЙ КОДЕКС РЕСПУБЛИКИ КАЗАХСТАН
  kaz: ҚАЗАҚСТАН РЕСПУБЛИКАСЫНЫҢ ЭКОЛОГИЯ КОДЕКСІ
form: КОД
type_codes:
- КОД
approved_on: 2021-01-02
approved_by:
- '102000000000'
version_date:
  kaz: 2023-09-05
  rus: 2023-09-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/151312/kaz/05.09.2023
  rus: https://zan.gov.kz/client/#!/doc/151312/rus/05.09.2023
caused_by:
  code: '183767'
  requisite: Закон Республики Казахстан от 5 июля 2023 года № 17-VIII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам Семипалатинской зоны ядерной безопасности, экологии и электроэнергетики
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне Семей ядролық қауіпсіздік аймағы, экология және электр энергетикасы мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/183767/rus
