act_code: '128977'
requisite: Закон Республики Казахстан от 8 февраля 2019 года № 222-VІ ЗРК
title:
  rus: О ратификации Конвенции о правовом статусе Каспийского моря
  kaz: Каспий теңізінің құқықтық мәртебесі туралы конвенцияны ратификациялау туралы
form: КОНВ
type_codes:
- ЗАК
- КОНВ
approved_on: 2019-02-08
approved_by:
- '102000000000'
version_date:
  kaz: 2019-02-08
  rus: 2019-02-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/128977/kaz/08.02.2019
  rus: https://zan.gov.kz/client/#!/doc/128977/rus/08.02.2019
