act_code: '4082'
requisite: Постановление Правления Национального Банка Республики Казахстан от 16 августа 1999 года № 256. Зарегистрирован в Министерстве юстиции Республики Казахстан 15.09.99г. за N 894. Утратил силу - постановлением Правления Национального Банка Республики Казахстан от 4 июля 2003 г. N 223
title:
  rus: Об утверждении Правил о пруденциальных нормативах и иных обязательных к соблюдению нормах и лимитах для кредитных товариществ Республики Казахстан
  kaz: Қазақстан Республикасының кредиттік серіктестіктерге арналған пруденциалдық нормативтер және сақтауға міндетті басқа да нормалар мен лимиттер туралы ережені бекіту жөнінде
type_codes:
- ПРАВ
approved_on: 1999-08-15
approved_by:
- '117000000000'
version_date:
  rus: 1999-08-15
source:
  rus: https://zan.gov.kz/client/#!/doc/4082/rus/15.08.1999
