act_code: '28210'
requisite: Закон Республики Казахстан от 5 июня 2006 года № 145. Утратил силу Конституционным законом Республики Казахстан от 7 декабря 2015 года № 438-V
title:
  rus: О региональном финансовом центре города Алматы
  kaz: Алматы қаласының өңірлік қаржы орталығы туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2006-06-05
approved_by:
- '102000000000'
version_date:
  kaz: 2011-07-05
  rus: 2011-07-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/28210/kaz/05.07.2011
  rus: https://zan.gov.kz/client/#!/doc/28210/rus/05.07.2011
caused_by:
  code: '59629'
  requisite: Закон Республики Казахстан от 5 июля 2011 года № 452-IV
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам пересмотра компетенции уполномоченных государственных органов и Правительства Республики Казахстан на принятие нормативных правовых актов, устанавливающих требования к проверяемым субъектам
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне уәкілетті мемлекеттік органдар мен Қазақстан Республикасы Үкіметінің тексерілетін субъектілерге қойылатын талаптарды белгілейтін нормативтік құқықтық актілерді қабылдау құзыреттерін қайта қарау мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/59629/rus
