act_code: '15149'
requisite: Постановление Правительства Республики Казахстан от 24 апреля 2003 года № 401
title:
  rus: Об утверждении Исполнительного Протокола к Соглашению между Правительством Республики Казахстан и Правительством Республики Польша о международных автомобильных перевозках
  kaz: Қазақстан Республикасы Үкіметі мен Польша Республикасы Үкіметі арасындағы Халықаралық автомобиль тасымалдары туралы келісімнің Атқару Хаттамасын бекіту туралы
form: ПРОТ
type_codes:
- ПОСТ
- ПРОТ
approved_on: 2003-04-23
approved_by:
- '103000000000'
version_date:
  kaz: 2003-04-23
  rus: 2003-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/15149/kaz/23.04.2003
  rus: https://zan.gov.kz/client/#!/doc/15149/rus/23.04.2003
