act_code: '30296'
requisite: Закон Республики Казахстан от 9 ноября 2006 года N 187
title:
  rus: О ратификации Договора о союзнических отношениях между Республикой Казахстан и Кыргызской Республикой
  kaz: Қазақстан Республикасы мен Қырғыз Республикасы арасындағы Одақтастық қатынастар туралы шартты ратификациялау туралы
form: ДОГ
type_codes:
- ДОГ
- ЗАК
approved_on: 2006-11-09
approved_by:
- '102000000000'
version_date:
  kaz: 2006-11-09
  rus: 2006-11-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/30296/kaz/09.11.2006
  rus: https://zan.gov.kz/client/#!/doc/30296/rus/09.11.2006
