act_code: '104119'
requisite: Закон Республики Казахстан от 17 апреля 1995 года № 2200. Утратил силу Законом Республики Казахстан от 11 января 2007 года № 214 (вводится в действие по истечении шести месяцев со дня его официального опубликования)
title:
  rus: О лицензировании
  kaz: Лицензиялау туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1995-04-16
approved_by:
- '101000000000'
version_date:
  rus: 1998-12-30
source:
  rus: https://zan.gov.kz/client/#!/doc/104119/rus/30.12.1998
caused_by:
  code: '1890'
  requisite: Закон Республики Казахстан от 30 декабря 1998 года № 339
  title:
    rus: О государственном контроле за оборотом отдельных видов оружия
    kaz: Жекелеген қару түрлерінің айналымына мемлекеттік бақылау жасау туралы
  link: https://zan.gov.kz/client/#!/doc/1890/rus
