act_code: '2169'
requisite: Утверждена Министерством по делам молодежи, туризма и спорта Республики Казахстан 28 декабря 1995 года. Зарегистрировано в Министерстве юстиции Республики Казахстан 6 марта 1997 г. № 268. Утратил силу приказом и.о. Министра туризма и спорта Республики Казахстан от 29 ноября 2011 года № 02-02-18/220
title:
  rus: Инструкция о едином порядке выдачи спортивного имущества физкультурно-спортивными организациями Республики Казахстан
  kaz: Қазақстан Республикасының дене тәрбиесi-спорттық, ұйымдарының спорт мүлкiн берудiң бiрыңғай тәртiбi туралы НҰСҚАУ
type_codes:
- ИНСТ
approved_on: 1995-12-28
approved_by:
- '103014000000'
version_date:
  kaz: 1995-12-28
  rus: 1995-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/2169/kaz/28.12.1995
  rus: https://zan.gov.kz/client/#!/doc/2169/rus/28.12.1995
