act_code: '9441'
requisite: Закон Республики Казахстан от 5 июля 2001 года N 222-II
title:
  rus: О Государственной премии мира и прогресса Первого Президента Республики Казахстан – Елбасы
  kaz: Қазақстан Республикасы Тұңғыш Президентінің - Елбасының Мемлекеттік бейбітшілік және прогресс сыйлығы туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2001-07-04
approved_by:
- '102000000000'
version_date:
  kaz: 2001-07-04
  rus: 2001-07-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/9441/kaz/04.07.2001
  rus: https://zan.gov.kz/client/#!/doc/9441/rus/04.07.2001
