act_code: '16645'
requisite: Нормативное постановление Верховного Суда Республики Казахстан от 11 июля 2003 года № 5
title:
  rus: О судебном решении по гражданским делам
  kaz: Азаматтық істер бойынша сот шешімі туралы
form: НПОС
type_codes:
- НПОС
approved_on: 2003-07-11
approved_by:
- '105000000000'
version_date:
  kaz: 2018-09-10
  rus: 2018-09-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/16645/kaz/10.09.2018
  rus: https://zan.gov.kz/client/#!/doc/16645/rus/10.09.2018
caused_by:
  code: '124749'
  requisite: Нормативное постановление Верховного Суда Республики Казахстан от 10 сентября 2018 года № 14
  title:
    rus: О внесении изменений и дополнений в нормативное постановление Верховного Суда Республики Казахстан от 11 июля 2003 года № 5 «О судебном решении»
    kaz: «Сот шешiмi туралы» Қазақстан Республикасы Жоғарғы Сотының 2003 жылғы 11 шілдедегі № 5 нормативтік қаулысына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/124749/rus
