act_code: '53306'
requisite: Закон Республики Казахстан от 24 июня 2010 года № 291-IV. Утратил силу Кодексом Республики Казахстан от 27 декабря 2017 года № 125-VI (вводится в действие по истечении шести месяцев после дня его первого официального опубликования), за исключением положений, установленных пунктом 14 статьи 277 Кодекса
title:
  rus: О недрах и недропользовании
  kaz: Жер қойнауы және жер қойнауын пайдалану туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2010-06-24
approved_by:
- '102000000000'
version_date:
  kaz: 2011-07-05
  rus: 2011-07-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/53306/kaz/05.07.2011
  rus: https://zan.gov.kz/client/#!/doc/53306/rus/05.07.2011
caused_by:
  code: '59629'
  requisite: Закон Республики Казахстан от 5 июля 2011 года № 452-IV
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам пересмотра компетенции уполномоченных государственных органов и Правительства Республики Казахстан на принятие нормативных правовых актов, устанавливающих требования к проверяемым субъектам
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне уәкілетті мемлекеттік органдар мен Қазақстан Республикасы Үкіметінің тексерілетін субъектілерге қойылатын талаптарды белгілейтін нормативтік құқықтық актілерді қабылдау құзыреттерін қайта қарау мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/59629/rus
