act_code: '8812'
requisite: Закон Республики Казахстан от 4 мая 2001 года № 187
title:
  rus: О ратификации Протокола, касающегося изменения Конвенции о международной гражданской авиации (Статья 3 bis)
  kaz: Халықаралық азаматтық авиация туралы конвенцияны өзгертуге қатысты хаттаманы (3-bis бап) бекіту туралы
form: ПРОТ
type_codes:
- ЗАК
- ПРОТ
approved_on: 2001-05-03
approved_by:
- '102000000000'
version_date:
  kaz: 2001-05-03
  rus: 2001-05-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/8812/kaz/03.05.2001
  rus: https://zan.gov.kz/client/#!/doc/8812/rus/03.05.2001
