act_code: '227403'
requisite: Нормативное постановление Конституционного Суда Республики Казахстан от 7 июля 2026 года № 89-НП
title:
  rus: Об официальном толковании пункта 1 статьи 43, пунктов 2 и 3 статьи 72, пункта 1 статьи 83 и пункта 3 статьи 84 Конституции Республики Казахстан
  kaz: Қазақстан Республикасы Конституциясының 43-бабының 1-тармағын, 72-бабының 2 және 3-тармақтарын, 83-бабының 1-тармағын және 84-бабының 3-тармағын ресми түсіндіру туралы
form: НПОС
type_codes:
- НПОС
approved_on: 2026-07-07
approved_by:
- '106000000000'
version_date:
  kaz: 2026-07-07
  rus: 2026-07-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/227403/kaz/07.07.2026
  rus: https://zan.gov.kz/client/#!/doc/227403/rus/07.07.2026
