act_code: '3819'
requisite: Закон Республики Казахстан от 2 мая 1995 года N 2255
title:
  rus: О хозяйственных товариществах
  kaz: Шаруашылық серіктестіктері туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1995-05-02
approved_by:
- '101000000000'
version_date:
  rus: 1997-07-13
source:
  rus: https://zan.gov.kz/client/#!/doc/3819/rus/13.07.1997
caused_by:
  code: '104453'
  requisite: Закон Республики Казахстан от 14 июля 1997 года N 159-I
  title:
    rus: О внесении дополнений в Указ Президента Республики Казахстан, имеющий силу Закона, "О хозяйственных товариществах" по вопросу подготовки и проведения общего собрания акционеров инвестиционных приватизационных фондов
    kaz: Қазақстан Республикасы Президентiнiң "Шаруашылық серiктестiктерi туралы" заң күшi бар Жарлығына инвестициялық жекешелендiру қорлары акционерлерiнiң жалпы жиналысын әзiрлеу мен өткiзу мәселесi бойынша толықтырулар енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/104453/rus
