act_code: '20140'
requisite: Закон Республики Казахстан от 9 июня 2004 года № 557
title:
  rus: О ратификации Договора о сотрудничестве в охране внешних границ государств-членов Евразийского экономического сообщества
  kaz: Еуразиялық экономикалық қоғамдастыққа мүше мемлекеттердiң сыртқы шекараларын күзетудегi ынтымақтастық туралы шартты бекiту туралы
form: ДОГ
type_codes:
- ДОГ
- ЗАК
- СОГЛ
approved_on: 2004-06-08
approved_by:
- '102000000000'
version_date:
  kaz: 2004-06-08
  rus: 2004-06-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/20140/kaz/08.06.2004
  rus: https://zan.gov.kz/client/#!/doc/20140/rus/08.06.2004
