act_code: '4'
requisite: Конституционный закон Республики Казахстан от 28 сентября 1995 года N 2464
title:
  rus: О выборах в Республике Казахстан
  kaz: Қазақстан Республикасындағы сайлау туралы
form: КЗАК
type_codes:
- КЗАК
approved_on: 1995-09-28
approved_by:
- '102000000000'
version_date:
  kaz: 2024-01-01
  rus: 2024-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/4/kaz/01.01.2024
  rus: https://zan.gov.kz/client/#!/doc/4/rus/01.01.2024
caused_by:
  code: '173442'
  requisite: Конституционный закон Республики Казахстан от 5 ноября 2022 года № 156-VII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые конституционные законы Республики Казахстан по вопросам реализации Послания Главы государства от 16 марта 2022 года
    kaz: Қазақстан Республикасының кейбір конституциялық заңдарына Мемлекет басшысының 2022 жылғы 16 наурыздағы Жолдауын іске асыру мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/173442/rus
