act_code: '4'
requisite: Конституционный закон Республики Казахстан от 28 сентября 1995 года N 2464
title:
  rus: О выборах в Республике Казахстан
  kaz: Қазақстан Республикасындағы сайлау туралы
form: КЗАК
type_codes:
- КЗАК
approved_on: 1995-09-28
approved_by:
- '102000000000'
version_date:
  kaz: 2013-10-03
  rus: 2013-10-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/4/kaz/03.10.2013
  rus: https://zan.gov.kz/client/#!/doc/4/rus/03.10.2013
caused_by:
  code: '74591'
  requisite: Конституционный Закон Республики Казахстан от 3 октября 2013 года № 133-V
  title:
    rus: О внесении изменений и дополнений в некоторые конституционные законы Республики Казахстан по вопросам исчисления конституционных сроков
    kaz: Қазақстан Республикасының кейбір конституциялық заңдарына конституциялық мерзімдерді есептеу мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/74591/rus
