act_code: '4909'
requisite: Указ Президента Республики Казахстан от 29 декабря 1999 года N 317. Утратил силу Указом Президента Республики Казахстан от 29 декабря 2015 года № 152
title:
  rus: Об утверждении Правил наложения дисциплинарных взысканий на политических государственных служащих
  kaz: Мемлекеттік саяси қызметшілерге тәртіптік жаза қолдану қағидаларын бекіту туралы
form: УКАЗ
type_codes:
- ПОЛ
- УКАЗ
approved_on: 1999-12-29
approved_by:
- '101000000000'
version_date:
  kaz: 2012-10-05
  rus: 2012-10-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/4909/kaz/05.10.2012
  rus: https://zan.gov.kz/client/#!/doc/4909/rus/05.10.2012
caused_by:
  code: '67993'
  requisite: Указ Президента Республики Казахстан от 5 октября 2012 года № 403. Утратил силу Указом Президента Республики Казахстан от 1 июня 2016 года № 272, за исключением пункта 1
  title:
    rus: О создании республиканского государственного учреждения "Служба центральных коммуникаций" при Президенте Республики Казахстан и внесении дополнений в некоторые указы Президента Республики Казахстан
    kaz: Қазақстан Республикасының Президенті жанындағы "Орталық коммуникациялар қызметі" республикалық мемлекеттік мекемесін құру және Қазақстан Республикасы Президентінің кейбір жарлықтарына толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/67993/rus
