act_code: '24715'
requisite: Указ Президента Республики Казахстан от 8 июля 2005 года N 1611
title:
  rus: Вопросы Академии государственного управления при Президенте Республики Казахстан
  kaz: Қазақстан Республикасы Президентінің жанындағы Мемлекеттік басқару академиясының мәселелері
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2005-07-08
approved_by:
- '101000000000'
version_date:
  kaz: 2006-07-08
  rus: 2006-07-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/24715/kaz/08.07.2006
  rus: https://zan.gov.kz/client/#!/doc/24715/rus/08.07.2006
caused_by:
  code: U060000145_
