act_code: '150158'
requisite: Закон Республики Казахстан от 21 декабря 2020 года № 388-VI ЗРК
title:
  rus: О ратификации Соглашения о займе (Активные меры по борьбе с СOVID-19 и программа поддержки расходов) между Республикой Казахстан и Азиатским Банком Инфраструктурных Инвестиций
  kaz: Қазақстан Республикасы мен Азия Инфрақұрылымдық Инвестициялар Банкі арасындағы Қарыз туралы келісімді (COVID-19-ға қарсы күрес жөніндегі белсенді шаралар мен шығыстарды қолдау бағдарламасы) ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2020-12-21
approved_by:
- '102000000000'
version_date:
  kaz: 2020-12-21
  rus: 2020-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/150158/kaz/21.12.2020
  rus: https://zan.gov.kz/client/#!/doc/150158/rus/21.12.2020
