act_code: '104233'
requisite: Закон Республики Казахстан от 9 апpеля 1993 года. Утратил силу - Законом Республики Казахстан от 7 января 2005 года N 29
title:
  rus: Об обороне и Вооруженных Силах Республики Казахстан
  kaz: Қазақстан Республикасының қорғанысы және Қарулы Күштерi туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1993-04-08
approved_by:
- '102000000000'
version_date:
  kaz: 1999-04-04
  rus: 1999-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/104233/kaz/04.04.1999
  rus: https://zan.gov.kz/client/#!/doc/104233/rus/04.04.1999
caused_by:
  code: '2600'
  requisite: Закон Республики Казахстан от 5 апреля 1999 года № 360-1
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам штатной численности и заимствования
    kaz: Қазақстан Республикасының штат саны және қарыз алу мәселелері бойынша кейбір заң актілеріне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/2600/rus
