act_code: '99394'
requisite: Закон Республики Казахстан от 19 февраля 2016 года № 456-V ЗРК
title:
  rus: О ратификации Соглашения между Правительством Республики Казахстан и Правительством Чешской Республики о реадмиссии лиц с незаконным пребыванием
  kaz: Қазақстан Республикасының Үкіметі мен Чех Республикасының Үкіметі арасындағы Заңсыз келген адамдардың реадмиссиясы туралы келісімді ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2016-02-19
approved_by:
- '102000000000'
version_date:
  kaz: 2016-02-19
  rus: 2016-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/99394/kaz/19.02.2016
  rus: https://zan.gov.kz/client/#!/doc/99394/rus/19.02.2016
