act_code: '21247'
requisite: Постановление Правительства Республики Казахстан от 16 сентября 2004 года N 968
title:
  rus: Об утверждении Конвенции о статусе корреспондента, представляющего средство массовой информации государства-участника Содружества Независимых Государств в других государствах Содружества
  kaz: Тәуелсіз Мемлекеттер Достастығының басқа мемлекеттерiнде Достастыққа қатысушы мемлекеттің бұқаралық ақпарат құралының өкілі болып табылатын тiлшiнiң мәртебесі туралы конвенцияны бекiту туралы
form: КОНВ
type_codes:
- КОНВ
- ПОСТ
approved_on: 2004-09-15
approved_by:
- '103000000000'
version_date:
  kaz: 2004-09-15
  rus: 2004-09-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/21247/kaz/15.09.2004
  rus: https://zan.gov.kz/client/#!/doc/21247/rus/15.09.2004
