act_code: '78488'
requisite: Постановление Правительства Республики Казахстан от 21 июля 2014 года № 809
title:
  rus: Об утверждении Соглашения между Правительством Республики Казахстан и Правительством Латвийской Республики по сотрудничеству в области охраны окружающей среды
  kaz: Қазақстан Республикасының Үкіметі мен Латвия Республикасының Үкіметі арасындағы қоршаған ортаны қорғау саласындағы ынтымақтастық жөніндегі келісімді бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2014-07-21
approved_by:
- '103000000000'
version_date:
  kaz: 2014-07-21
  rus: 2014-07-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/78488/kaz/21.07.2014
  rus: https://zan.gov.kz/client/#!/doc/78488/rus/21.07.2014
