act_code: '1063'
requisite: Распоряжение Акима Восточно-Казахстанской области от 10 марта 1998 года N 7-58р. Зарегистрировано управлением юстиции Восточно-Казахстанской области 22 мая 1998 года за N 24. Утратило силу решением акима ВКО от 24 сентября 2004 года N 100
title:
  rus: О разграничении функций, выполняемых субъектами транспортного процесса по перевозке пассажиров
  kaz: Көлік процесі субъектілерінің жолаушыларды тасымалдау жөнінде орындайтын қызметтерінің ара жігін ажырату туралы
form: РАСП
type_codes:
- РАСП
approved_on: 1998-03-10
approved_by:
- '157000000001'
version_date:
  kaz: 1998-03-10
  rus: 1998-03-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/1063/kaz/10.03.1998
  rus: https://zan.gov.kz/client/#!/doc/1063/rus/10.03.1998
