act_code: '142718'
requisite: Постановление Правительства Республики Казахстан от 12 мая 2020 года № 285
title:
  rus: Об утверждении Соглашения между Правительством Республики Казахстан и Правительством Кыргызской Республики о совместных действиях по строительству нового моста и реконструкции существующего моста между пунктами пропуска «Карасу – автодорожный» Республики Казахстан и «Ак-Тилек – автодорожный» Кыргызской Республики
  kaz: Қазақстан Республикасының Үкіметі мен Қырғыз Республикасының Үкіметі арасындағы Қазақстан Республикасының «Қарасу – автожол» және Қырғыз Республикасының «Ақ-Тілек – автожол» өткізу пункттері арасында жаңа көпір салу және қолданыстағы көпірді реконструкциялау бойынша бірлескен іс-қимылдар туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2020-05-12
approved_by:
- '103000000000'
version_date:
  kaz: 2020-05-12
  rus: 2020-05-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/142718/kaz/12.05.2020
  rus: https://zan.gov.kz/client/#!/doc/142718/rus/12.05.2020
