act_code: '128916'
requisite: Закон Республики Казахстан от 25 января 2019 года № 220-VІ ЗРК
title:
  rus: О ратификации Соглашения между Правительством Республики Казахстан и Правительством Республики Таджикистан о сотрудничестве в области миграции
  kaz: Қазақстан Республикасының Үкіметі мен Тәжікстан Республикасының Үкіметі арасындағы көші-қон саласындағы ынтымақтастық туралы келісімді ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2019-01-25
approved_by:
- '102000000000'
version_date:
  kaz: 2019-01-25
  rus: 2019-01-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/128916/kaz/25.01.2019
  rus: https://zan.gov.kz/client/#!/doc/128916/rus/25.01.2019
