act_code: '28641'
requisite: Указ Президента Республики Казахстан от 5 июля 2006 года № 140
title:
  rus: О Комиссии по вопросам помилования при Президенте Республики Казахстан
  kaz: Қазақстан Республикасы Президентiнiң жанындағы Кешiрiм жасау мәселелерi жөнiндегi комиссия туралы
form: УКАЗ
type_codes:
- ПОЛ
- УКАЗ
approved_on: 2006-07-05
approved_by:
- '101000000000'
version_date:
  kaz: 2018-02-21
  rus: 2018-02-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/28641/kaz/21.02.2018
  rus: https://zan.gov.kz/client/#!/doc/28641/rus/21.02.2018
caused_by:
  code: '118918'
  requisite: Указ Президента Республики Казахстан от 21 февраля 2018 года № 642
  title:
    rus: О внесении изменений и дополнений в некоторые акты Президента Республики Казахстан
    kaz: Қазақстан Республикасы Президентінің кейбір актілеріне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/118918/rus
