act_code: '28641'
requisite: Указ Президента Республики Казахстан от 5 июля 2006 года № 140
title:
  rus: О Комиссии по вопросам помилования при Президенте Республики Казахстан
  kaz: Қазақстан Республикасы Президентiнiң жанындағы Кешiрiм жасау мәселелерi жөнiндегi комиссия туралы
form: УКАЗ
type_codes:
- ПОЛ
- УКАЗ
approved_on: 2006-07-05
approved_by:
- '101000000000'
version_date:
  kaz: 2019-10-28
  rus: 2019-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/28641/kaz/28.10.2019
  rus: https://zan.gov.kz/client/#!/doc/28641/rus/28.10.2019
caused_by:
  code: '135803'
  requisite: Указ Президента Республики Казахстан от 28 октября 2019 года № 195
  title:
    rus: О внесении изменений и дополнений в некоторые акты Президента Республики Казахстан
    kaz: Қазақстан Республикасы Президентінің кейбір актілеріне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/135803/rus
