act_code: '16192'
requisite: Закон Республики Казахстан от 4 июля 2003 года № 474-II
title:
  rus: О государственном регулировании, контроле и надзоре финансового рынка и финансовых организаций
  kaz: Қаржы нарығы мен қаржы ұйымдарын мемлекеттiк реттеу, бақылау және қадағалау туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2003-07-04
approved_by:
- '102000000000'
version_date:
  kaz: 2014-12-15
  rus: 2014-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/16192/kaz/15.12.2014
  rus: https://zan.gov.kz/client/#!/doc/16192/rus/15.12.2014
caused_by:
  code: '80649'
  requisite: Закон Республики Казахстан от 10 июня 2014 года № 206-V ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам противодействия легализации (отмыванию) доходов, полученных преступным путем, и финансированию терроризма
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне қылмыстық жолмен алынған кірістерді заңдастыруға (жылыстатуға) және терроризмді қаржыландыруға қарсы іс-қимыл мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/80649/rus
