act_code: '16192'
requisite: Закон Республики Казахстан от 4 июля 2003 года № 474-II
title:
  rus: О государственном регулировании, контроле и надзоре финансового рынка и финансовых организаций
  kaz: Қаржы нарығы мен қаржы ұйымдарын мемлекеттiк реттеу, бақылау және қадағалау туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2003-07-04
approved_by:
- '102000000000'
version_date:
  kaz: 2021-01-01
  rus: 2021-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/16192/kaz/01.01.2021
  rus: https://zan.gov.kz/client/#!/doc/16192/rus/01.01.2021
caused_by:
  code: '133004'
  requisite: Закон Республики Казахстан от 3 июля 2019 года № 262-VІ ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам регулирования и развития финансового рынка, микрофинансовой деятельности и налогообложения
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне қаржы нарығын реттеу мен дамыту, микроқаржылық қызмет және салық салу мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/133004/rus
