act_code: '61850'
requisite: Указ Президента Республики Казахстан от 29 ноября 2011 года № 187
title:
  rus: О создании специальной экономической зоны "Хоргос - Восточные ворота"
  kaz: '"Қорғас - Шығыс қақпасы" арнайы экономикалық аймағын құру туралы'
form: УКАЗ
type_codes:
- ПОЛ
- УКАЗ
approved_on: 2011-11-29
approved_by:
- '101000000000'
version_date:
  kaz: 2016-11-25
  rus: 2016-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/61850/kaz/25.11.2016
  rus: https://zan.gov.kz/client/#!/doc/61850/rus/25.11.2016
caused_by:
  code: '107770'
  requisite: Указ Президента Республики Казахстан от 25 ноября 2016 года № 377
  title:
    rus: О внесении изменений в некоторые указы Президента Республики Казахстан
    kaz: Қазақстан Республикасы Президентінің кейбір жарлықтарына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/107770/rus
