act_code: '104432'
requisite: Закон Республики Казахстан от 21 января 1997 года N 67. Утратил силу Законом Республики Казахстан от 7 марта 2014 года № 176-V
title:
  rus: О банкротстве
  kaz: Банкроттық туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1997-01-21
approved_by:
- '102000000000'
version_date:
  kaz: 2011-01-11
  rus: 2011-01-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/104432/kaz/11.01.2011
  rus: https://zan.gov.kz/client/#!/doc/104432/rus/11.01.2011
caused_by:
  code: '56754'
  requisite: Закон Республики Казахстан от 11 января 2011 года № 385-IV
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам противодействия неправомерному захвату бизнеса и собственности (рейдерству)
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне бизнес пен жеке меншікті заңсыз тартып алуға (рейдерлікке) қарсы іс-қимыл мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/56754/rus
