act_code: '4449'
requisite: Распоряжение Акима Восточно-Казахстанской области от 20 октября 1999 года № 1-733р. Зарегистрировано управлением юстиции Восточно-Казахстанской области 29 октября 1999 года за № 243. Утратило силу решением акима ВКО от 19 августа 2004 года № 94
title:
  rus: О взимании сбора за право реализации товаров на рынках с применением контрольно-кассовых аппаратов
  kaz: Бақылау-касса аппаратын қолдана отырып базарларда тауарларды сату құқығы үшін алым жинау туралы
form: РАСП
type_codes:
- РАСП
approved_on: 1999-10-19
approved_by:
- '157000000003'
version_date:
  kaz: 1999-10-19
  rus: 1999-10-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/4449/kaz/19.10.1999
  rus: https://zan.gov.kz/client/#!/doc/4449/rus/19.10.1999
