act_code: '3197'
requisite: Закон Республики Казахстан от 7 июня 1999 года № 389. Утратил силу Законом Республики Казахстан от 27 июля 2007 года № 319
title:
  rus: Об образовании
  kaz: Білім туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1999-06-06
approved_by:
- '102000000000'
version_date:
  kaz: 2006-07-07
  rus: 2006-07-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/3197/kaz/07.07.2006
  rus: https://zan.gov.kz/client/#!/doc/3197/rus/07.07.2006
caused_by:
  code: '28850'
  requisite: Закон Республики Казахстан от 7 июля 2006 года № 171
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам здравоохранения
    kaz: Қазақстан Республикасының кейбiр заңнамалық актiлерiне денсаулық сақтау мәселелерi бойынша өзгерiстер мен толықтырулар енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/28850/rus
