act_code: '227553'
requisite: Закон Республики Казахстан от 8 июля 2026 года № 341-VIII ЗРК
title:
  rus: Об охране почв
  kaz: Топырақты қорғау туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2026-07-08
approved_by:
- '102000000000'
version_date:
  kaz: 2026-07-08
  rus: 2026-07-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/227553/kaz/08.07.2026
  rus: https://zan.gov.kz/client/#!/doc/227553/rus/08.07.2026
