act_code: '16516'
requisite: Указ Президента Республики Казахстан от 31 июля 2003 года № 1157. Утратил силу Указом Президента Республики Казахстан от 30 сентября 2011 года № 155
title:
  rus: О медалях органов внутренних дел Республики Казахстан
  kaz: Қазақстан Республикасы iшкi iстер органдарының медальдары туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2003-07-30
approved_by:
- '101000000000'
version_date:
  kaz: 2003-07-30
  rus: 2003-07-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/16516/kaz/30.07.2003
  rus: https://zan.gov.kz/client/#!/doc/16516/rus/30.07.2003
