act_code: '6784'
requisite: Распоряжение Акима Карагандинской области от 29 июня 2000 года № 137р. Зарегистрировано управлением юстиции Карагандинской области 5 июля 2000 года за № 109. Утратило силу распоряжением Акима Карагандинской области от 14 марта 2003 года № 23р
title:
  rus: О мерах по усилению контроля за качеством реализуемого зерна и продуктов его переработки
  kaz: Өткізілетін астықтың және оның ұқсатылған өнімдерінің сапасына бақылауды күшейту жөніндегі шаралар туралы
form: РАСП
type_codes:
- РАСП
approved_on: 2000-06-28
approved_by:
- '160000000001'
version_date:
  kaz: 2000-06-28
  rus: 2000-06-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/6784/kaz/28.06.2000
  rus: https://zan.gov.kz/client/#!/doc/6784/rus/28.06.2000
