act_code: '131329'
requisite: Постановление Правительства Республики Казахстан от 13 мая 2019 года № 275
title:
  rus: Об утверждении Соглашения о сотрудничестве в области обмена геопространственной информацией в интересах вооруженных сил государств-участников Содружества Независимых Государств
  kaz: Тәуелсіз Мемлекеттер Достастығына қатысушы мемлекеттер қарулы күштерінің мүдделерінде геокеңістіктік ақпарат алмасу саласындағы ынтымақтастық туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2019-05-13
approved_by:
- '103000000000'
version_date:
  kaz: 2019-05-13
  rus: 2019-05-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/131329/kaz/13.05.2019
  rus: https://zan.gov.kz/client/#!/doc/131329/rus/13.05.2019
