act_code: '82224'
requisite: Указ Президента Республики Казахстан от 10 апреля 1997 г. № 3446. Утратил силу - Указом Президента РК от 9 января 2006 года N 1696
title:
  rus: О первоочередных мерах по обеспечению своевременных выплат пенсий и заработной платы
  kaz: Зейнетақылар мен еңбекақыны уақтылы төлеудi қамтамасыз ету жөнiндегi бiрiншi кезектегi шаралар туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 1997-04-09
approved_by:
- '101000000000'
version_date:
  kaz: 1997-04-09
  rus: 1997-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/82224/kaz/09.04.1997
  rus: https://zan.gov.kz/client/#!/doc/82224/rus/09.04.1997
