act_code: '4054'
requisite: Закон Республики Казахстан от 23 июля 1999 года № 453. Утратил силу Законом Республики Казахстан от 23 ноября 2015 года № 416-V
title:
  rus: О государственной службе
  kaz: Мемлекеттік қызмет туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1999-07-22
approved_by:
- '102000000000'
version_date:
  kaz: 2003-03-11
  rus: 2003-03-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/4054/kaz/11.03.2003
  rus: https://zan.gov.kz/client/#!/doc/4054/rus/11.03.2003
caused_by:
  code: '14659'
  requisite: Закон Республики Казахстан от 11 марта 2003 года N 393
  title:
    rus: О внесении изменений и дополнений в Закон Республики Казахстан "О государственной службе"
    kaz: '"Мемлекеттік қызмет туралы" Қазақстан Республикасының Заңына өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/14659/rus
