act_code: '1999'
requisite: Распоряжение Акима Восточно-Казахстанской области от 6 ноября 1998 г. № 1-496 p. зарегистрировано управлением юстиции Восточно-Казахстанской обл. 09.11.1998 г. за № 111. Утратило силу решением акима ВКО от 29 июня 2007 года № 09
title:
  rus: Об организации экологических постов и взимания платы за проезд транзитного автотранспорта
  kaz: Об организации экологических постов и взимания платы за проезд транзитного автотранспорта
form: РАСП
type_codes:
- РАСП
approved_on: 1998-11-06
approved_by:
- '157000000001'
version_date:
  rus: 1998-11-06
source:
  rus: https://zan.gov.kz/client/#!/doc/1999/rus/06.11.1998
