act_code: '117004'
requisite: Кодекс Республики Казахстан от 25 декабря 2017 года № 120-VI. Утратил силу Кодексом Республики Казахстан от 18 июля 2025 года № 214-VIII (вводится в действие с 1 января 2026 года), за исключением пункта 1-1 статьи 68, который признается утратившим силу с 1 января 2027 года, и пункта 23 статьи 26, который признается утратившим силу с 1 января 2029 года
title:
  rus: О НАЛОГАХ И ДРУГИХ ОБЯЗАТЕЛЬНЫХ ПЛАТЕЖАХ В БЮДЖЕТ (НАЛОГОВЫЙ КОДЕКС)
  kaz: САЛЫҚ ЖӘНЕ БЮДЖЕТКЕ ТӨЛЕНЕТІН БАСҚА ДА МІНДЕТТІ ТӨЛЕМДЕР ТУРАЛЫ (САЛЫҚ КОДЕКСІ)
form: КОД
type_codes:
- КОД
approved_on: 2017-12-25
approved_by:
- '102000000000'
version_date:
  kaz: 2023-01-01
  rus: 2023-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/117004/kaz/01.01.2023
  rus: https://zan.gov.kz/client/#!/doc/117004/rus/01.01.2023
caused_by:
  code: '169749'
  requisite: Закон Республики Казахстан от 11 июля 2022 года № 135-VII ЗРК
  title:
    rus: О внесении изменений и дополнений в Кодекс Республики Казахстан «О налогах и других обязательных платежах в бюджет» (Налоговый кодекс) и Закон Республики Казахстан «О введении в действие Кодекса Республики Казахстан «О налогах и других обязательных платежах в бюджет» (Налоговый кодекс)»
    kaz: «Салық және бюджетке төленетін басқа да міндетті төлемдер туралы» Қазақстан Республикасының Кодексіне (Салық кодексі) және «Салық және бюджетке төленетін басқа да міндетті төлемдер туралы» Қазақстан Республикасының Кодексін (Салық кодексі) қолданысқа енгізу туралы» Қазақстан Республикасының Заңына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/169749/rus
