act_code: '6965'
requisite: Распоряжение акима Атырауской области от 27 января 2000 года № 377р. Зарегистрированo Управлением юстиции Атырауской области 4 августа 2000 года за № 234
title:
  rus: О проведении государственного технического осмотра транспортных средств
  kaz: Көлік құралдарын мемлекеттік техникалық байқаудан өткізу туралы
form: РАСП
type_codes:
- РАСП
approved_on: 2000-01-27
approved_by:
- '156000000003'
version_date:
  kaz: 2000-01-27
  rus: 2000-01-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/6965/kaz/27.01.2000
  rus: https://zan.gov.kz/client/#!/doc/6965/rus/27.01.2000
