act_code: '4802'
requisite: Указ Президента Республики Казахстан от 13 декабря 1999 года N 284
title:
  rus: О единовременных выплатах родителям, усыновителям, опекунам погибших, умерших военнослужащих
  kaz: Қаза тапқан, қайтыс болған әскери қызметшілердің ата-аналарына, асырап алушыларына, қамқоршыларына біржолғы төлем туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 1999-12-13
approved_by:
- '101000000000'
version_date:
  kaz: 2005-05-16
  rus: 2005-05-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/4802/kaz/16.05.2005
  rus: https://zan.gov.kz/client/#!/doc/4802/rus/16.05.2005
caused_by:
  code: '24033'
  requisite: Указ Президента Республики Казахстан от 16 мая 2005 года № 1572
  title:
    rus: О признании утратившим силу Указа Президента Республики Казахстан от 16 сентября 1997 года N 3636 и внесении изменения в Указ Президента Республики Казахстан от 13 декабря 1999 года N 284
    kaz: Қазақстан Республикасы Президентiнiң 1997 жылғы 16 қыркүйектегi N 3636 Жарлығының күшi жойылды деп тану және Қазақстан Республикасы Президентiнiң 1999 жылғы 13 желтоқсандағы N 284 Жарлығына өзгерiс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/24033/rus
