act_code: '104315'
requisite: Закон Республики Казахстан от 21 декабря 1995 г. N 2709. Утратил силу Законом Республики Казахстан от 30 июня 2017 года № 81-VI
title:
  rus: О Прокуратуре
  kaz: Прокуратура туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1995-12-21
approved_by:
- '101000000000'
version_date:
  kaz: 2012-07-10
  rus: 2012-07-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/104315/kaz/10.07.2012
  rus: https://zan.gov.kz/client/#!/doc/104315/rus/10.07.2012
caused_by:
  code: '66681'
  requisite: Закон Республики Казахстан от 10 июля 2012 года № 36-V
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам сокращения разрешительных документов и оптимизации контрольных и надзорных функций государственных органов
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне рұқсат беру құжаттарын қысқарту және мемлекеттік органдардың бақылау мен қадағалау функцияларын оңтайландыру мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/66681/rus
