act_code: '104315'
requisite: Закон Республики Казахстан от 21 декабря 1995 г. N 2709. Утратил силу Законом Республики Казахстан от 30 июня 2017 года № 81-VI
title:
  rus: О Прокуратуре
  kaz: Прокуратура туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1995-12-21
approved_by:
- '101000000000'
version_date:
  kaz: 2010-03-19
  rus: 2010-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/104315/kaz/19.03.2010
  rus: https://zan.gov.kz/client/#!/doc/104315/rus/19.03.2010
caused_by:
  code: '51542'
  requisite: Закон Республики Казахстан от 19 марта 2010 года № 258-IV
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам государственной статистики и налогообложения
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне мемлекеттік статистика және салық салу мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/51542/rus
