act_code: '56792'
requisite: Закон Республики Казахстан от 6 января 2011 года № 380-IV
title:
  rus: О правоохранительной службе
  kaz: Құқық қорғау қызметі туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2011-01-06
approved_by:
- '102000000000'
version_date:
  kaz: 2021-01-01
  rus: 2021-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/56792/kaz/01.01.2021
  rus: https://zan.gov.kz/client/#!/doc/56792/rus/01.01.2021
caused_by:
  code: '95658'
  requisite: Закон Республики Казахстан от 18 ноября 2015 года № 412-V ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам декларирования доходов и имущества физических лиц
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне жеке тұлғалардың кірістері мен мүлкін декларациялау мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/95658/rus
