act_code: '152621'
requisite: Закон Республики Казахстан от 1 февраля 2021 года № 3-VII ЗРК
title:
  rus: О ратификации Соглашения между Республикой Казахстан и Международной финансовой корпорацией об учреждении и деятельности офисов в Республике Казахстан
  kaz: Қазақстан Республикасы мен Халықаралық қаржы корпорациясы арасындағы Қазақстан Республикасында офистер құру және олардың қызметі туралы келісімді ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2021-02-01
approved_by:
- '102000000000'
version_date:
  kaz: 2021-02-01
  rus: 2021-02-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/152621/kaz/01.02.2021
  rus: https://zan.gov.kz/client/#!/doc/152621/rus/01.02.2021
