act_code: '108376'
requisite: Постановление Правительства Республики Казахстан от 15 декабря 2016 года № 811
title:
  rus: Об утверждении Соглашения между Правительством Республики Казахстан и Правительством Республики Польша о сотрудничестве в области сельского хозяйства
  kaz: Қазақстан Республикасының Үкіметі мен Польша Республикасының Үкіметі арасындағы ауыл шаруашылығы саласындағы ынтымақтастық туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2016-12-15
approved_by:
- '103000000000'
version_date:
  kaz: 2016-12-15
  rus: 2016-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/108376/kaz/15.12.2016
  rus: https://zan.gov.kz/client/#!/doc/108376/rus/15.12.2016
