act_code: '19434'
requisite: Закон Республики Казахстан от 1 апреля 2004 года N 540
title:
  rus: О ратификации Соглашения между Правительством Республики Казахстан и Правительством Королевства Бельгия о воздушном сообщении
  kaz: Қазақстан Республикасының Үкіметі мен Бельгия Корольдігі Үкіметінің арасындағы Әуе қатынасы туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2004-03-31
approved_by:
- '102000000000'
version_date:
  kaz: 2004-03-31
  rus: 2004-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/19434/kaz/31.03.2004
  rus: https://zan.gov.kz/client/#!/doc/19434/rus/31.03.2004
