act_code: '12639'
requisite: Нормативное Постановление Верховного Суда Республики Казахстан от 28 июня 2002 года N 13
title:
  rus: О судебной практике по делам об установлении фактов, имеющих юридическое значение
  kaz: Заңдық маңызы бар фактілерді анықтау туралы істер бойынша сот практикасы туралы
form: НПОС
type_codes:
- НПОС
approved_on: 2002-06-28
approved_by:
- '105000000000'
version_date:
  kaz: 2002-06-27
  rus: 2002-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/12639/kaz/27.06.2002
  rus: https://zan.gov.kz/client/#!/doc/12639/rus/27.06.2002
