act_code: '52190'
requisite: Указ Президента Республики Казахстан от 27 апреля 2010 года № 976
title:
  rus: Об утверждении Правил подготовки и реализации послания, работы с актами и поручениями Президента Республики Казахстан и осуществления контроля за их исполнением, проведения мониторинга нормативных правовых указов
  kaz: Қазақстан Республикасы Президентінің жолдауын дайындау және іске асыру, актілерімен және тапсырмаларымен жұмыс істеу және олардың орындалуын бақылауды жүзеге асыру, нормативтік құқықтық жарлықтарға мониторинг жүргізу қағидаларын бекіту туралы
form: УКАЗ
type_codes:
- ПРАВ
- УКАЗ
approved_on: 2010-04-27
approved_by:
- '101000000000'
version_date:
  kaz: 2021-10-23
  rus: 2021-10-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/52190/kaz/23.10.2021
  rus: https://zan.gov.kz/client/#!/doc/52190/rus/23.10.2021
caused_by:
  code: '159754'
  requisite: Указ Президента Республики Казахстан от 23 октября 2021 года № 680
  title:
    rus: О внесении изменений в Указ Президента Республики Казахстан от 27 апреля 2010 года № 976 «Об утверждении Правил подготовки, согласования и представления на рассмотрение Президенту Республики Казахстан проекта послания Президента Республики Казахстан народу Казахстана, подготовки, согласования, представления на подпись проектов актов и поручений Президента Республики Казахстан, реализации послания Президента Республики Казахстан народу Казахстана, осуществления контроля за исполнением актов и поручений Президента Республики Казахстан, а также поручений, содержащихся в решениях Совета Безопасности Республики Казахстан и Ассамблеи народа Казахстана, проведения мониторинга нормативных правовых указов Президента Республики Казахстан»
    kaz: «Қазақстан Республикасы Президентінің Қазақстан халқына жолдауының жобасын дайындау, келісу және Қазақстан Республикасы Президентінің қарауына ұсыну, Қазақстан Республикасы Президентінің актілері мен тапсырмаларының жобаларын дайындау, келісу, қол қоюға ұсыну, Қазақстан Республикасы Президентінің Қазақстан халқына жолдауын іске асыру, Қазақстан Республикасы Президентінің актілері мен тапсырмаларының, сондай-ақ Қазақстан Республикасы Қауіпсіздік Кеңесінің және Қазақстан халқы Ассамблеясының шешімдерінде қамтылған тапсырмалардың орындалуын бақылауды жүзеге асыру, Қазақстан Республикасы Президентінің нормативтік құқықтық жарлықтарына мониторинг жүргізу қағидаларын бекіту туралы» Қазақстан Республикасы Президентінің 2010 жылғы 27 сәуірдегі № 976 Жарлығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/159754/rus
