act_code: '104184'
requisite: Закон Республики Казахстан от 10 декабpя 1993 года № 4100. Утратил силу Законом Республики Казахстан от 8 мая 2001 года № 198
title:
  rus: О местных пpедставительных и исполнительных оpганах Республики Казахстан
  kaz: Қазақстан Республикасының жергiлiктi өкiлдi және атқарушы органдары туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1993-12-10
approved_by:
- '102000000000'
version_date:
  rus: 1999-07-19
source:
  rus: https://zan.gov.kz/client/#!/doc/104184/rus/19.07.1999
caused_by:
  code: '3905'
  requisite: Закон Республики Казахстан от 20 июля 1999 г. № 442-1
  title:
    rus: О внесении изменений в некоторые законодательные акты Республики Казахстан по вопросам численности депутатов маслихатов
    kaz: Қазақстан Республикасының мәслихаттар депутаттарының саны мәселелері бойынша кейбір заң актілеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/3905/rus
