act_code: '177794'
requisite: Постановление Правительства Республики Казахстан от 29 декабря 2022 года № 1097
title:
  rus: Об утверждении Соглашения между Правительством Республики Казахстан и Правительством Республики Никарагуа о взаимной отмене визовых требований
  kaz: Қазақстан Республикасының Үкіметі мен Никарагуа Республикасының Үкіметі арасындағы өзара визалық талаптардан босату туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2022-12-29
approved_by:
- '103000000000'
version_date:
  kaz: 2022-12-29
  rus: 2022-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/177794/kaz/29.12.2022
  rus: https://zan.gov.kz/client/#!/doc/177794/rus/29.12.2022
