act_code: '26160'
requisite: Закон Республики Казахстан от 15 декабря 2005 года № 103
title:
  rus: О ратификации Соглашения об обеспечении защиты секретной информации в рамках Региональной антитеррористической структуры Шанхайской организации сотрудничества
  kaz: Шанхай ынтымақтастық ұйымының Өңiрлiк терроризмге қарсы құрылымы шеңберiндегi құпия ақпаратты қорғауды қамтамасыз ету туралы келiсiмдi ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2005-12-15
approved_by:
- '102000000000'
version_date:
  kaz: 2005-12-15
  rus: 2005-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/26160/kaz/15.12.2005
  rus: https://zan.gov.kz/client/#!/doc/26160/rus/15.12.2005
