act_code: '20'
requisite: Постановление Сената Парламента Республики Казахстан от 8 февраля 1996 года
title:
  rus: Регламент Сената Парламента Республики Казахстан
  kaz: Қазақстан Республикасы Парламенті Сенатының Регламенті
type_codes:
- РЕГЛ
approved_on: 1996-02-08
approved_by:
- '102000000000'
version_date:
  kaz: 2019-12-26
  rus: 2019-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/20/kaz/26.12.2019
  rus: https://zan.gov.kz/client/#!/doc/20/rus/26.12.2019
caused_by:
  code: '139835'
  requisite: Постановление Сената Парламента Республики Казахстан от 26 декабря 2019 года № 641-VI СП
  title:
    rus: О внесении изменений и дополнений в Регламент Сената Парламента Республики Казахстан
    kaz: Қазақстан Республикасы Парламенті Сенатының Регламентіне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/139835/rus
