act_code: '86005'
requisite: Указ Президента Республики Казахстан от 21 января 2015 года № 993
title:
  rus: О государственных премиях Республики Казахстан в области науки и техники имени аль-Фараби, гуманитарных наук имени А. Байтурсынулы и литературы и искусства имени Абая
  kaz: Қазақстан Республикасының әл-Фараби атындағы ғылым мен техника, А. Байтұрсынұлы атындағы гуманитарлық ғылымдар және Абай атындағы әдебиет пен өнер саласындағы мемлекеттік сыйлықтары туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2015-01-21
approved_by:
- '101000000000'
version_date:
  kaz: 2022-08-11
  rus: 2022-08-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/86005/kaz/11.08.2022
  rus: https://zan.gov.kz/client/#!/doc/86005/rus/11.08.2022
caused_by:
  code: '170690'
  requisite: Указ Президента Республики Казахстан от 11 августа 2022 года № 977
  title:
    rus: О внесении изменений и дополнений в Указ Президента Республики Казахстан от 21 января 2015 года № 993 «О государственных премиях Республики Казахстан в области науки и техники имени аль-Фараби, литературы и искусства имени Абая»
    kaz: «Қазақстан Республикасының әл-Фараби атындағы ғылым мен техника саласындағы және Абай атындағы әдебиет пен өнер саласындағы мемлекеттік сыйлықтары туралы» Қазақстан Республикасы Президентінің 2015 жылғы 21 қаңтардағы № 993 Жарлығына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/170690/rus
