act_code: '174149'
requisite: Закон Республики Казахстан от 24 ноября 2022 года № 160-VII ЗРК
title:
  rus: О ратификации Соглашения о принципах и подходах осуществления государственного контроля (надзора) за соблюдением требований технических регламентов Евразийского экономического союза в целях гармонизации законодательства государств – членов Евразийского экономического союза в указанной сфере
  kaz: Еуразиялық экономикалық одақтың техникалық регламенттері талаптарының сақталуына мемлекеттік бақылауды (қадағалауды) Еуразиялық экономикалық одаққа мүше мемлекеттердің көрсетілген саладағы заңнамасын үйлестіру мақсатында жүзеге асыру қағидаттары мен тәсілдері туралы келісімді ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2022-11-24
approved_by:
- '102000000000'
version_date:
  kaz: 2022-11-24
  rus: 2022-11-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/174149/kaz/24.11.2022
  rus: https://zan.gov.kz/client/#!/doc/174149/rus/24.11.2022
