act_code: '73340'
requisite: Закон Республики Казахстан от 4 июля 2013 года № 129-V
title:
  rus: О Национальной палате предпринимателей Республики Казахстан
  kaz: Қазақстан Республикасының Ұлттық кәсіпкерлер палатасы туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2013-07-04
approved_by:
- '102000000000'
version_date:
  kaz: 2018-10-05
  rus: 2018-10-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/73340/kaz/05.10.2018
  rus: https://zan.gov.kz/client/#!/doc/73340/rus/05.10.2018
caused_by:
  code: '125030'
  requisite: Закон Республики Казахстан от 5 октября 2018 года № 184-VІ ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам обеспечения единства измерений и стандартизации
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне өлшем бірлігін қамтамасыз ету және стандарттау мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/125030/rus
