act_code: '73340'
requisite: Закон Республики Казахстан от 4 июля 2013 года № 129-V
title:
  rus: О Национальной палате предпринимателей Республики Казахстан
  kaz: Қазақстан Республикасының Ұлттық кәсіпкерлер палатасы туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2013-07-04
approved_by:
- '102000000000'
version_date:
  kaz: 2015-11-23
  rus: 2015-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/73340/kaz/23.11.2015
  rus: https://zan.gov.kz/client/#!/doc/73340/rus/23.11.2015
caused_by:
  code: '95686'
  requisite: Закон Республики Казахстан от 23 ноября 2015 года № 415-V ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам регулирования труда
    kaz: Қазақстан Республикасының кейбiр заңнамалық актiлерiне еңбекті реттеу мәселелерi бойынша өзгерiстер мен толықтырулар енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/95686/rus
