act_code: '8'
requisite: Кодекс Республики Казахстан от 16 июля 1997 года № 167. Утратил силу Кодексом РК от 3 июля 2014 года № 226-V
title:
  rus: Уголовный Кодекс Республики Казахстан
  kaz: Қазақстан Республикасының Қылмыстық кодексi
form: КОД
type_codes:
- КОД
approved_on: 1997-07-15
approved_by:
- '102000000000'
version_date:
  kaz: 2002-02-19
  rus: 2002-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/8/kaz/19.02.2002
  rus: https://zan.gov.kz/client/#!/doc/8/rus/19.02.2002
caused_by:
  code: '11366'
  requisite: Закон Республики Казахстан от 19 февраля 2002 года № 295.
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам борьбы с терроризмом
    kaz: Қазақстан Республикасының кейбір заң актілеріне терроризмге қарсы күрес мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/11366/rus
