act_code: '8'
requisite: Кодекс Республики Казахстан от 16 июля 1997 года № 167. Утратил силу Кодексом РК от 3 июля 2014 года № 226-V
title:
  rus: Уголовный Кодекс Республики Казахстан
  kaz: Қазақстан Республикасының Қылмыстық кодексi
form: КОД
type_codes:
- КОД
approved_on: 1997-07-15
approved_by:
- '102000000000'
version_date:
  rus: 1997-07-15
source:
  rus: https://zan.gov.kz/client/#!/doc/8/rus/15.07.1997
