act_code: '8'
requisite: Кодекс Республики Казахстан от 16 июля 1997 года № 167. Утратил силу Кодексом РК от 3 июля 2014 года № 226-V
title:
  rus: Уголовный Кодекс Республики Казахстан
  kaz: Қазақстан Республикасының Қылмыстық кодексi
form: КОД
type_codes:
- КОД
approved_on: 1997-07-15
approved_by:
- '102000000000'
version_date:
  rus: 2000-05-04
source:
  rus: https://zan.gov.kz/client/#!/doc/8/rus/04.05.2000
caused_by:
  code: '5999'
  requisite: Закон Республики Казахстан от 5 мая 2000 года № 47-ІІ
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам борьбы с преступностью
    kaz: Қазақстан Республикасының кейбір заң актілеріне қылмысқа қарсы күрес мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/5999/rus
