act_code: '78725'
requisite: Закон Республики Казахстан от 11 апреля 2014 года № 188-V 3PK
title:
  rus: О гражданской защите
  kaz: Азаматтық қорғау туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2014-04-11
approved_by:
- '102000000000'
version_date:
  kaz: 2024-06-08
  rus: 2024-06-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/78725/kaz/08.06.2024
  rus: https://zan.gov.kz/client/#!/doc/78725/rus/08.06.2024
caused_by:
  code: '195399'
  requisite: Закон Республики Казахстан от 6 апреля 2024 года № 71-VIII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам ведения бизнеса
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне бизнес жүргізу мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/195399/rus
