act_code: '10612'
requisite: Закон Республики Казахстан от 13 декабря 2001 года № 267-ІІ
title:
  rus: О праздниках в Республике Казахстан
  kaz: Қазақстан Республикасындағы мерекелер туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2001-12-13
approved_by:
- '102000000000'
version_date:
  kaz: 2009-04-22
  rus: 2009-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/10612/kaz/22.04.2009
  rus: https://zan.gov.kz/client/#!/doc/10612/rus/22.04.2009
caused_by:
  code: '45379'
  requisite: Закон Республики Казахстан от 22 апреля 2009 года № 152-IV
  title:
    rus: О внесении изменений в Закон Республики Казахстан "О праздниках в Республике Казахстан"
    kaz: '"Қазақстан Республикасындағы мерекелер туралы" Қазақстан Республикасының Заңына өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/45379/rus
