act_code: '5785'
requisite: Приказ Преседателя Агентства Республики Казахстан по миграции и демографии от 14 апреля 2000г. N 18. Зарегистрирован в Министерстве юстиции Республики Казахстан от 17 апреля 2000г. за N 1113. Утратил силу приказом Министра труда и социальной защиты населения Республики Казахстан от 13 октября 2005 года N 272-п
title:
  rus: Об утверждении Правил пребывания переселенцев в центрах адаптации и фильтрации
  kaz: Қоныс аударушылардың бейімделу және іріктелу орталықтарында болу Ережесін бекіту туралы
type_codes:
- ПРАВ
approved_on: 2000-04-13
approved_by:
- '103016002000'
version_date:
  kaz: 2000-04-13
  rus: 2000-04-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/5785/kaz/13.04.2000
  rus: https://zan.gov.kz/client/#!/doc/5785/rus/13.04.2000
