act_code: '12676'
requisite: Закон Республики Казахстан от 10 июля 2002 года N 339
title:
  rus: О ветеринарии
  kaz: Ветеринария туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2002-07-10
approved_by:
- '102000000000'
version_date:
  kaz: 2010-06-30
  rus: 2010-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/12676/kaz/30.06.2010
  rus: https://zan.gov.kz/client/#!/doc/12676/rus/30.06.2010
caused_by:
  code: '53574'
  requisite: Закон Республики Казахстан от 30 июня 2010 года № 305-IV
  title:
    rus: О ратификации Соглашения таможенного союза по ветеринарно-санитарным мерам
    kaz: Кеден одағының ветеринариялық-санитариялық шаралар жөніндегі келісімін ратификациялау туралы
  link: https://zan.gov.kz/client/#!/doc/53574/rus
