act_code: '3749'
requisite: Закон Республики Казахстан от 23 июля 1999 года № 451-I. Утратил силу Законом Республики Казахстан от 19 июня 2024 года № 93-VIII (вводится в действие по истечении шестидесяти календарных дней после дня его первого официального опубликования)
title:
  rus: О средствах массовой информации
  kaz: Бұқаралық ақпарат құралдары туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1999-07-23
approved_by:
- '102000000000'
version_date:
  kaz: 2021-07-01
  rus: 2021-07-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/3749/kaz/01.07.2021
  rus: https://zan.gov.kz/client/#!/doc/3749/rus/01.07.2021
caused_by:
  code: '144271'
  requisite: Закон Республики Казахстан от 29 июня 2020 года № 351-VI ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам административного процедурно-процессуального законодательства Республики Казахстан
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне Қазақстан Республикасының әкімшілік рәсімдік-процестік заңнамасы мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/144271/rus
