act_code: '59924'
requisite: Постановление Правительства Республики Казахстан от 21 июля 2011 года № 837
title:
  rus: Об утверждении Соглашения между Правительством Республики Казахстан и Правительством Королевства Норвегия об освобождении владельцев дипломатических паспортов от визовых требований
  kaz: Қазақстан Республикасының Үкіметі мен Норвегия Корольдігінің Үкіметі арасындағы Дипломаттық паспорттардың иелерін визалық талаптардан босату туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2011-07-21
approved_by:
- '103000000000'
version_date:
  kaz: 2011-07-21
  rus: 2011-07-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/59924/kaz/21.07.2011
  rus: https://zan.gov.kz/client/#!/doc/59924/rus/21.07.2011
