act_code: '104204'
requisite: Закон Республики Казахстан от 19 июня 1997 г. N 130-I
title:
  rus: О системе местных представительных органов в условиях изменений в административно-территориальном устройстве Республики Казахстан
  kaz: Қазақстан Республикасының әкiмшiлiк-аумақтық құрылысындағы өзгерiстер жағдайындағы жергiлiктi өкiлдi органдар жүйесi туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1997-06-18
approved_by:
- '102000000000'
version_date:
  kaz: 1999-07-19
  rus: 1999-07-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/104204/kaz/19.07.1999
  rus: https://zan.gov.kz/client/#!/doc/104204/rus/19.07.1999
caused_by:
  code: '3905'
  requisite: Закон Республики Казахстан от 20 июля 1999 г. № 442-1
  title:
    rus: О внесении изменений в некоторые законодательные акты Республики Казахстан по вопросам численности депутатов маслихатов
    kaz: Қазақстан Республикасының мәслихаттар депутаттарының саны мәселелері бойынша кейбір заң актілеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/3905/rus
