act_code: '4951'
requisite: Приказ Председателя Таможенного комитета Министерства государственных доходов Республики Казахстан от 10.12.99г. N 612-П Зарегистрирован в Министерстве юстиции Республики Казахстан 15.12.99г. за N 1002. Утратил силу - приказом Председателя Таможенного комитета Министерства государственных доходов Республики Казахстан от 22 января 2001 года N 21 ~V011446
title:
  rus: Об утверждении Инструкции о порядке определения страны происхождения товаров
  kaz: Тауарлардың шыққан елін анықтау тәртібін бекіту туралы
type_codes:
- ИНСТ
approved_on: 1999-12-10
approved_by:
- '103002004000'
version_date:
  rus: 1999-12-10
source:
  rus: https://zan.gov.kz/client/#!/doc/4951/rus/10.12.1999
