act_code: '24725'
requisite: Закон Республики Казахстан от 8 июля 2005 года № 66
title:
  rus: О государственном регулировании развития агропромышленного комплекса и сельских территорий
  kaz: Агроөнеркәсіптік кешенді және ауылдық аумақтарды дамытуды мемлекеттік реттеу туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2005-07-08
approved_by:
- '102000000000'
version_date:
  kaz: 2008-12-24
  rus: 2008-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/24725/kaz/24.12.2008
  rus: https://zan.gov.kz/client/#!/doc/24725/rus/24.12.2008
caused_by:
  code: '43067'
  requisite: Закон Республики Казахстан от 24 декабря 2008 года № 111-IV
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам социальной поддержки и стимулирования работников социальной сферы сельских населенных пунктов
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне ауылдық елді мекендердің әлеуметтік сала қызметкерлерін әлеуметтік қолдау және ынталандыру мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/43067/rus
