act_code: '2977'
requisite: Закон Республики Казахстан от 19 мая 1999 года № 385-I
title:
  rus: О ратификации Договора между Республикой Казахстан и Республикой Беларусь о правовом статусе граждан Республики Казахстан, постоянно проживающих на территории Республики Беларусь, и граждан Республики Беларусь, постоянно проживающих на территории Республики Казахстан
  kaz: Қазақстан Республикасы мен Беларусь Республикасы арасындағы Қазақстан Республикасының аумағында тұрақты тұратын Беларусь Республикасы азаматтарының құқықтық статусы және Беларусь Республикасының аумағында тұрақты тұратын Қазақстан Республикасы азаматтарының құқықтық статусы туралы шартты бекіту туралы
form: ДОГ
type_codes:
- ДОГ
- ЗАК
approved_on: 1999-05-18
approved_by:
- '102000000000'
version_date:
  kaz: 1999-05-18
  rus: 1999-05-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/2977/kaz/18.05.1999
  rus: https://zan.gov.kz/client/#!/doc/2977/rus/18.05.1999
