act_code: '44325'
requisite: Указ Президента Республики Казахстан от 13 января 2009 года № 724
title:
  rus: Об учреждении образовательного гранта Первого Президента Республики Казахстан – Лидера Нации «Өркен»
  kaz: Қазақстан Республикасының Тұңғыш Президенті – Елбасының «Өркен» білім беру грантын тағайындау туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2009-01-13
approved_by:
- '101000000000'
version_date:
  kaz: 2009-01-13
  rus: 2009-01-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/44325/kaz/13.01.2009
  rus: https://zan.gov.kz/client/#!/doc/44325/rus/13.01.2009
