act_code: '24'
requisite: Указ Президента Республики Казахстан от 11 ноября 1996 года № 3205
title:
  rus: Об утверждении Положения о Центральной избирательной комиссии Республики Казахстан
  kaz: Қазақстан Республикасының Орталық сайлау комиссиясы туралы ережені бекіту туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 1996-11-11
approved_by:
- '101000000000'
version_date:
  kaz: 2015-01-29
  rus: 2015-01-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/24/kaz/29.01.2015
  rus: https://zan.gov.kz/client/#!/doc/24/rus/29.01.2015
caused_by:
  code: '86935'
  requisite: Указ Президента Республики Казахстан от 29 января 2015 года № 995
  title:
    rus: О внесении дополнений в Указ Президента Республики Казахстан от 11 ноября 1996 года № 3205 "Об утверждении Положения о Центральной избирательной комиссии Республики Казахстан"
    kaz: '"Қазақстан Республикасының Орталық сайлау комиссиясы туралы Ережені бекіту туралы" Қазақстан Республикасы Президентінің 1996 жылғы 11 қарашадағы № 3205 Жарлығына толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/86935/rus
