act_code: '15026'
requisite: Закон Республики Казахстан от 7 апреля 2003 года № 402. Утратил силу Законом Республики Казахстан от 20 июля 2011 года № 463-IV
title:
  rus: О государственном регулировании производства и оборота отдельных видов нефтепродуктов
  kaz: Мұнай өнiмдерiнiң жекелеген түрлерiн өндiрудi және олардың айналымын мемлекеттiк реттеу туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2003-04-06
approved_by:
- '102000000000'
version_date:
  kaz: 2010-10-06
  rus: 2010-10-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/15026/kaz/06.10.2010
  rus: https://zan.gov.kz/client/#!/doc/15026/rus/06.10.2010
caused_by:
  code: '54871'
  requisite: Закон Республики Казахстан от 6 октября 2010 года № 343-IV
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам усиления ответственности в сфере оборота нефти и отдельных видов нефтепродуктов
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне мұнай және мұнай өнімдерінің жекелеген түрлерінің айналымы саласында жауапкершілікті күшейту мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/54871/rus
