act_code: '332'
requisite: Закон Республики Казахстан от 5 декабря 1997 года № 195. Утратил силу Законом Республики Казахстан от 5 июля 2018 года № 176-VІ (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об адвокатской деятельности
  kaz: Адвокаттық қызмет туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1997-12-05
approved_by:
- '102000000000'
version_date:
  kaz: 2007-01-12
  rus: 2007-01-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/332/kaz/12.01.2007
  rus: https://zan.gov.kz/client/#!/doc/332/rus/12.01.2007
caused_by:
  code: '31397'
  requisite: Закон Республики Казахстан от 12 января 2007 года № 222
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам лицензирования
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне лицензиялау мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/31397/rus
