act_code: '2335'
requisite: Указ Президента Республики Казахстан от 20 марта 1999 г. № 88
title:
  rus: О Совете Безопасности Республики Казахстан
  kaz: Қазақстан Республикасының Қауіпсіздік Кеңесі туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 1999-03-20
approved_by:
- '101000000000'
version_date:
  kaz: 2011-07-22
  rus: 2011-07-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/2335/kaz/22.07.2011
  rus: https://zan.gov.kz/client/#!/doc/2335/rus/22.07.2011
caused_by:
  code: '59803'
  requisite: Указ Президента Республики Казахстан от 22 июля 2011 года № 124
  title:
    rus: О внесении изменений и дополнений в некоторые акты Президента Республики Казахстан
    kaz: Қазақстан Республикасы Президентінің кейбір актілеріне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/59803/rus
