act_code: '112558'
requisite: Указ Президента Республики Казахстан от 2 июня 2017 года № 489
title:
  rus: Об Астанинской международной премии за вклад в межрелигиозный диалог и почетной медали Съезда лидеров мировых и традиционных религий
  kaz: Дінаралық диалогқа қосқан үлесі үшін Астана халықаралық сыйлығы мен Әлемдік және дәстүрлі діндер лидерлері съезінің құрмет медалі туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2017-06-02
approved_by:
- '101000000000'
version_date:
  kaz: 2022-08-12
  rus: 2022-08-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/112558/kaz/12.08.2022
  rus: https://zan.gov.kz/client/#!/doc/112558/rus/12.08.2022
caused_by:
  code: '170687'
  requisite: Указ Президента Республики Казахстан от 12 августа 2022 года № 978
  title:
    rus: О внесении изменений в Указ Президента Республики Казахстан от 2 июня 2017 года № 489 «Об Астанинской международной премии за вклад в межрелигиозный диалог и почетной медали Съезда лидеров мировых и традиционных религий»
    kaz: «Дінаралық диалогқа қосқан үлесі үшін Астана халықаралық сыйлығы мен Әлемдік және дәстүрлі діндер лидерлері съезінің құрмет медалі туралы» Қазақстан Республикасы Президентінің 2017 жылғы 2 маусымдағы № 489 Жарлығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/170687/rus
