act_code: '61657'
requisite: Закон Республики Казахстан от 21 ноября 2011 года № 494-IV ЗРК
title:
  rus: О ратификации Договора о функционировании Таможенного союза в рамках многосторонней торговой системы
  kaz: Көпжақты сауда жүйесі шеңберінде Кеден одағының жұмыс істеуі туралы шартты ратификациялау туралы
form: ДОГ
type_codes:
- ДОГ
- ЗАК
approved_on: 2011-11-21
approved_by:
- '102000000000'
version_date:
  kaz: 2011-11-21
  rus: 2011-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/61657/kaz/21.11.2011
  rus: https://zan.gov.kz/client/#!/doc/61657/rus/21.11.2011
