act_code: '104326'
requisite: Закон Республики Казахстан от 19 июня 1995 года N 2335. Утратил силу Законом Республики Казахстан от 1 марта 2011 года № 413-IV
title:
  rus: О государственном предприятии
  kaz: Мемлекеттiк кәсiпорын туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1995-06-18
approved_by:
- '101000000000'
version_date:
  kaz: 2009-12-02
  rus: 2009-12-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/104326/kaz/02.12.2009
  rus: https://zan.gov.kz/client/#!/doc/104326/rus/02.12.2009
caused_by:
  code: '49051'
  requisite: Закон Республики Казахстан от 2 декабря 2009 года № 212-IV
  title:
    rus: О внесении изменения и дополнений в некоторые законодательные акты Республики Казахстан по вопросам предоставления гарантированного объема бесплатной медицинской помощи
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне тегін медициналық көмектің кепілдік берілген көлемін ұсыну мәселелері бойынша өзгеріс пен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/49051/rus
