act_code: '158472'
requisite: Приказ Министра экологии, геологии и природных ресурсов Республики Казахстан от 8 сентября 2021 года № 362. Зарегистрирован в Министерстве юстиции Республики Казахстан 10 сентября 2021 года № 24303
title:
  rus: Об утверждении типового договора залога банковского вклада в качестве финансового обеспечения исполнения обязательств по ликвидации последствий эксплуатации объекта I категории
  kaz: I санаттағы объектіні пайдалану салдарларын жою жөніндегі міндеттемелердің орындалуын қаржылық қамтамасыз ету ретінде банктік салым кепілінің үлгілік шартын бекіту туралы
form: ДОГ
type_codes:
- ДОГ
- ПРИК
approved_on: 2021-09-08
approved_by:
- '103047000000'
version_date:
  kaz: 2021-09-08
  rus: 2021-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/158472/kaz/08.09.2021
  rus: https://zan.gov.kz/client/#!/doc/158472/rus/08.09.2021
