act_code: '3773'
requisite: Постановление Правительства Республики Казахстан от 16 февраля 1999 года № 129
title:
  rus: Об утверждении Соглашения между Правительством Республики Казахстан и Правительством Республики Беларусь о военно-техническом сотрудничестве
  kaz: Қазақстан Республикасының Үкіметі мен Беларусь Республикасының Үкіметі арасындағы Әскери-техникалық ынтымақтастық туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 1999-02-16
approved_by:
- '103000000000'
version_date:
  kaz: 1999-02-16
  rus: 1999-02-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/3773/kaz/16.02.1999
  rus: https://zan.gov.kz/client/#!/doc/3773/rus/16.02.1999
