act_code: '8816'
requisite: Закон Республики Казахстан от 7 мая 2001 года № 191-ІІ
title:
  rus: О присоединении Республики Казахстан к Поправке к Монреальскому протоколу по веществам, разрушающим озоновый слой, Лондон, 27-29 июня 1990 года
  kaz: Лондонда 1990 жылғы 27-29 маусымда жасалған Озон қабатын бүлдіретін заттар жөніндегі Монреаль хаттамасына Түзетуге Қазақстан Республикасының қосылуы туралы
form: ПРОТ
type_codes:
- ЗАК
- ПРОТ
approved_on: 2001-05-06
approved_by:
- '102000000000'
version_date:
  kaz: 2001-05-06
  rus: 2001-05-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/8816/kaz/06.05.2001
  rus: https://zan.gov.kz/client/#!/doc/8816/rus/06.05.2001
