act_code: '31372'
requisite: Указ Президента Республики Казахстан от 9 января 2007 года № 243
title:
  rus: Об изменениях в административно-территориальном устройстве Акмолинской области
  kaz: Ақмола облысының әкімшілік-аумақтық құрылысындағы өзгерістер туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2007-01-09
approved_by:
- '101000000000'
version_date:
  kaz: 2007-01-09
  rus: 2007-01-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/31372/kaz/09.01.2007
  rus: https://zan.gov.kz/client/#!/doc/31372/rus/09.01.2007
