act_code: '49979'
requisite: Постановление Правительства Республики Казахстан от 25 декабря 2009 года № 2199
title:
  rus: Об утверждении Соглашения между Правительством Республики Казахстан и Правительством Эстонской Республики об экономическом и научно-техническом сотрудничестве
  kaz: Қазақстан Республикасының Үкіметі мен Эстония Республикасының Үкіметі арасындағы Экономикалық және ғылыми-техникалық ынтымақтастық туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2009-12-25
approved_by:
- '103000000000'
version_date:
  kaz: 2009-12-25
  rus: 2009-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/49979/kaz/25.12.2009
  rus: https://zan.gov.kz/client/#!/doc/49979/rus/25.12.2009
