act_code: '7239'
requisite: Закон Республики Казахстан от 19 октября 2000 года № 84-II
title:
  rus: О ратификации Соглашения между Правительством Республики Казахстан и Правительством Республики Куба о порядке взаимных поездок граждан обоих государств
  kaz: Қазақстан Республикасының Үкіметі мен Куба Республикасының Үкіметі арасындағы екі мемлекет азаматтарының өзара сапарларының тәртібі жөніндегі келісімді бекіту туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2000-10-18
approved_by:
- '102000000000'
version_date:
  kaz: 2000-10-18
  rus: 2000-10-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/7239/kaz/18.10.2000
  rus: https://zan.gov.kz/client/#!/doc/7239/rus/18.10.2000
