act_code: '8373'
requisite: Постановление Правительства Республики Казахстан от 11 марта 2001 года N 339
title:
  rus: Об утверждении Соглашения между Правительством Республики Казахстан и Правительством Кыргызской Республики о сотрудничестве и обмене информацией в области борьбы с нарушениями налогового законодательства
  kaz: Қазақстан Республикасының Үкіметі мен Қырғыз Республикасының Үкіметі арасындағы Салық заңдарын бұзушылықтарға қарсы күрес саласындағы ынтымақтастық және ақпарат алмасу туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2001-03-11
approved_by:
- '103000000000'
version_date:
  kaz: 2001-03-11
  rus: 2001-03-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/8373/kaz/11.03.2001
  rus: https://zan.gov.kz/client/#!/doc/8373/rus/11.03.2001
