act_code: '33609'
requisite: Закон Республики Казахстан от 7 июня 2007 года N 259
title:
  rus: О ратификации Стокгольмской конвенции о стойких органических загрязнителях
  kaz: Орнықты органикалық ластағыштар туралы Стокгольм конвенциясын ратификациялау туралы
form: КОНВ
type_codes:
- ЗАК
- КОНВ
approved_on: 2007-06-07
approved_by:
- '102000000000'
version_date:
  kaz: 2007-06-07
  rus: 2007-06-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/33609/kaz/07.06.2007
  rus: https://zan.gov.kz/client/#!/doc/33609/rus/07.06.2007
