act_code: '104463'
requisite: Закон Республики Казахстан от 7 июля 1997 года N 150
title:
  rus: О судебных приставах
  kaz: Сот приставтары туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1997-07-07
approved_by:
- '102000000000'
version_date:
  kaz: 2023-03-27
  rus: 2023-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/104463/kaz/27.03.2023
  rus: https://zan.gov.kz/client/#!/doc/104463/rus/27.03.2023
caused_by:
  code: '179249'
  requisite: Закон Республики Казахстан от 27 марта 2023 года № 216-VII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам совершенствования процессуального законодательства и реформирования судебной системы
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне процестік заңнаманы жетілдіру және сот жүйесін реформалау мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/179249/rus
