act_code: '15779'
requisite: Постановление Правительства Республики Казахстан от 11 июня 2003 года N 549
title:
  rus: Об утверждении Соглашения между Правительством Республики Казахстан и Правительством Латвийской Республики о сотрудничестве в области связи
  kaz: Қазақстан Республикасының Үкiметi мен Латвия Республикасының Yкiметi арасындағы Байланыс саласындағы ынтымақтастық туралы келiсiмді бекiту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2003-06-10
approved_by:
- '103000000000'
version_date:
  kaz: 2003-06-10
  rus: 2003-06-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/15779/kaz/10.06.2003
  rus: https://zan.gov.kz/client/#!/doc/15779/rus/10.06.2003
