act_code: '17706'
requisite: Закон Республики Казахстан от 4 декабря 2003 года № 502
title:
  rus: О ратификации Меморандума о взаимопонимании между Правительством Республики Казахстан и Правительством Королевства Саудовская Аравия
  kaz: Қазақстан Республикасының Yкiметi мен Сауд Арабиясы Корольдiгi Үкiметi арасындағы Өзара түсiнiстiк туралы меморандумды бекiту туралы
form: МЕМР
type_codes:
- ЗАК
- МЕМР
approved_on: 2003-12-04
approved_by:
- '102000000000'
version_date:
  kaz: 2003-12-04
  rus: 2003-12-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/17706/kaz/04.12.2003
  rus: https://zan.gov.kz/client/#!/doc/17706/rus/04.12.2003
