act_code: '751'
requisite: Инструкция N 37 Главной налоговой инспекции Министерства Финансов Республики Казахстан от 26 июня 1995 г. Зарегистрирован в Министерстве юстиции Республики Казахстан 5.07.95 г. за N 77. Утратила силу - приказом Министра государственных доходов Республики Казахстан от 2.02.2001 N 117 ~V011434
title:
  rus: О порядке исчисления и уплаты налога на добавленную стоимость
  kaz: Қосылған құнға салынатын салықты есептеу мен төлеу тәртiбi туралы Нұсқаулық
type_codes:
- ИНСТ
approved_on: 1995-06-05
approved_by:
- '103002000000'
version_date:
  rus: 1998-05-21
source:
  rus: https://zan.gov.kz/client/#!/doc/751/rus/21.05.1998
caused_by:
  code: '948'
  requisite: Утверждено Приказом Председателя Налогового комитета Министерства финансов Республики Казахстан от 22 мая 1998 года N 39. Зарегистрировано в Министерстве юстиции РК 13.06.1998г. за N 83. Утратил силу - приказом Министра государственных доходов РК от 9.04.2002 № 416.
  title:
    rus: О внесении изменений и дополнений в Инструкцию Главной налоговой инспекции Министерства финансов Республики Казахстан "О порядке исчисления и уплаты налога на добавленную стоимость" от 26.06.95 года N 37
    kaz: Қазақстан Республикасы Қаржы министрлігінің Бас салық инспекциясының 1995 жылғы 26 маусымдағы N 37 "Қосылған құн салығын есептеудің және төлеудің тәртібі туралы" нұсқаулығына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/948/rus
