act_code: '104437'
requisite: ЗАКОН РЕСПУБЛИКИ КАЗАХСТАН от 24 февраля 1997 года № 72-I ЗРК
title:
  rus: О ратификации Конвенции между Правительством Республики Казахстан и Правительством Украины об избежании двойного налогообложения и предотвращении налоговых уклонений относительно налогов на доходы
  kaz: Қазақстан Республикасының Үкiметi мен Украина Үкiметi арасындағы табысқа қосарланған салық салуды болдырмау және салық төлеуден жалтаруға жол бермеу туралы конвенцияны бекiту туралы
form: КОНВ
type_codes:
- ЗАК
- КОНВ
approved_on: 1997-02-24
approved_by:
- '102000000000'
version_date:
  kaz: 1997-02-24
  rus: 1997-02-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/104437/kaz/24.02.1997
  rus: https://zan.gov.kz/client/#!/doc/104437/rus/24.02.1997
