act_code: '925'
requisite: Закон Республики Казахстан от 30 июня 1998 года № 253. Утратил силу Законом Республики Казахстан от 2 апреля 2010 года № 261-IV
title:
  rus: Об исполнительном производстве и статусе судебных исполнителей
  kaz: Атқарушылық iс жүргiзу және сот орындаушыларының мәртебесi туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1998-06-29
approved_by:
- '102000000000'
version_date:
  rus: 1999-11-16
source:
  rus: https://zan.gov.kz/client/#!/doc/925/rus/16.11.1999
caused_by:
  code: '4571'
  requisite: Закон Республики Казахстан от 16 ноября 1999 года № 479-1
  title:
    rus: О внесении изменений в Закон Республики Казахстан "Об исполнительном производстве и статусе судебных исполнителей"
    kaz: '"Атқарушылық іс жүргізу және сот орындаушыларының мәртебесі туралы" Қазақстан Республикасының Заңына өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/4571/rus
