act_code: '104089'
requisite: Закон Республики Казахстан от 4 июля 1992 года № 1543-XII. Утратил силу Законом Республики Казахстан от 31 января 2006 года № 124 (вводится в действие со дня его официального опубликования)
title:
  rus: О защите и поддержке частного предпринимательства
  kaz: Жеке кәсіпкерлікті қорғау және қолдау туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1992-07-03
approved_by:
- '102000000000'
version_date:
  kaz: 2003-05-07
  rus: 2003-05-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/104089/kaz/07.05.2003
  rus: https://zan.gov.kz/client/#!/doc/104089/rus/07.05.2003
caused_by:
  code: '15326'
  requisite: Закон Республики Казахстан от 8 мая 2003 года № 411
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам банковской деятельности, валютного регулирования и валютного контроля
    kaz: Қазақстан Республикасының кейбір заң актілеріне банк қызметі, валюталық реттеу және валюталық бақылау мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/15326/rus
