act_code: '63315'
requisite: Закон Республики Казахстан от 13 февраля 2012 года № 552-IV
title:
  rus: О специальных государственных органах Республики Казахстан
  kaz: Қазақстан Республикасының арнаулы мемлекеттік органдары туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2012-02-13
approved_by:
- '102000000000'
version_date:
  kaz: 2024-09-09
  rus: 2024-09-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/63315/kaz/09.09.2024
  rus: https://zan.gov.kz/client/#!/doc/63315/rus/09.09.2024
caused_by:
  code: '198640'
  requisite: Закон Республики Казахстан от 8 июля 2024 года № 116-VIII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам игорного бизнеса, лотерейной деятельности, охраны здоровья, государственной инспекции труда, государственного контроля и исключения излишней законодательной регламентации
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне ойын бизнесі, лотерея қызметі, денсаулық сақтау, мемлекеттік еңбек инспекциясы, мемлекеттік бақылау және артық заңнамалық регламенттеуді болғызбау мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/198640/rus
