act_code: '4355'
requisite: Постановление Правления Национального банка Республики Казахстан от 23 мая 1997 года N 229. Зарегистрировано в Министерстве юстиции Республики Казахстан 11 июня 1997 г. N 315. Утратило силу - постановление Правления Национального Банка РК от 25 января 1999 г. N 8 (извлечение из текста постановления см. ниже)
title:
  rus: О Положении "Об организации экспортно-импортного валютного контроля в Республике Казахстан"
  kaz: '"Қазақстан Республикасында экспорттық-импорттық валюта бақылауын ұйымдастыру туралы" Ереже жөнiнде'
type_codes:
- ПОЛ
approved_on: 1997-05-22
approved_by:
- '117000000000'
version_date:
  rus: 1997-05-22
source:
  rus: https://zan.gov.kz/client/#!/doc/4355/rus/22.05.1997
