act_code: '104327'
requisite: Закон Республики Казахстан от 17 апреля 1995 года № 2198
title:
  rus: О государственной регистрации юридических лиц и учетной регистрации филиалов и представительств
  kaz: Заңды тұлғаларды мемлекеттік тіркеу және филиалдар мен өкілдіктерді есептік тіркеу туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1995-04-17
approved_by:
- '101000000000'
version_date:
  rus: 2001-01-05
source:
  rus: https://zan.gov.kz/client/#!/doc/104327/rus/05.01.2001
caused_by:
  code: '7835'
  requisite: Закон Республики Казахстан от 5 января 2001 года № 135-II
  title:
    rus: О внесении изменений и дополнений в Указ Президента Республики Казахстан, имеющий силу Закона, "О государственной регистрации юридических лиц"
    kaz: Қазақстан Республикасы Президентінің "Заңды тұлғаларды мемлекеттік тіркеу туралы" заң күші бар Жарлығына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/7835/rus
