act_code: '172755'
requisite: Закон Республики Казахстан от 12 октября 2022 года № 146-VII ЗРК
title:
  rus: О ратификации Протокола к Временному соглашению, ведущему к образованию зоны свободной торговли между Евразийским экономическим союзом и его государствами-членами, с одной стороны, и Исламской Республикой Иран, с другой стороны, от 17 мая 2018 года
  kaz: 2018 жылғы 17 мамырдағы Бір тараптан Еуразиялық экономикалық одақ пен оған мүше мемлекеттер және екінші тараптан Иран Ислам Республикасы арасындағы еркін сауда аймағын құруға алып келетін уақытша келісімге хаттаманы ратификациялау туралы
form: ПРОТ
type_codes:
- ЗАК
- ПРОТ
approved_on: 2022-10-12
approved_by:
- '102000000000'
version_date:
  kaz: 2022-10-12
  rus: 2022-10-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/172755/kaz/12.10.2022
  rus: https://zan.gov.kz/client/#!/doc/172755/rus/12.10.2022
