act_code: '104239'
requisite: Закон Республики Казахстан от 19 янваpя 1993 года № 1000. Утратил силу - Законом РК от 15 марта 1999 г. N 350
title:
  rus: О защите госудаpственных секpетов Республики Казахстан
  kaz: Қазақстан Республикасының мемлекеттiк құпияларын сақтау туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1993-01-19
approved_by:
- '102000000000'
version_date:
  rus: 1993-01-19
source:
  rus: https://zan.gov.kz/client/#!/doc/104239/rus/19.01.1993
