act_code: '205147'
requisite: Нормативное постановление Конституционного Суда Республики Казахстан от 24 декабря 2024 года № 58-НП
title:
  rus: О рассмотрении на соответствие Конституции Республики Казахстан абзацев второго, третьего и четвертого пункта 29 нормативного постановления Верховного Суда Республики Казахстан от 29 ноября 2019 года № 6 «О применении судами законодательства при рассмотрении дел, связанных с взысканием алиментов»
  kaz: Қазақстан Республикасы Жоғарғы Сотының «Соттардың алименттерді өндіріп алу жөніндегі істерді қараған кезде заңнаманы қолдануы туралы» 2019 жылғы 29 қарашадағы № 6 нормативтік қаулысының 29-тармағы екінші, үшінші және төртінші абзацтарының Қазақстан Республикасының Конституциясына сәйкестігін қарау туралы
form: НПОС
type_codes:
- НПОС
approved_on: 2024-12-24
approved_by:
- '106000000000'
version_date:
  kaz: 2024-12-24
  rus: 2024-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/205147/kaz/24.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205147/rus/24.12.2024
