act_code: '26155'
requisite: Закон Республики Казахстан от 13 декабря 2005 года № 93-III
title:
  rus: Об обязательном экологическом страховании
  kaz: Мiндетті экологиялық сақтандыру туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2005-12-13
approved_by:
- '102000000000'
version_date:
  kaz: 2008-05-26
  rus: 2008-05-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/26155/kaz/26.05.2008
  rus: https://zan.gov.kz/client/#!/doc/26155/rus/26.05.2008
caused_by:
  code: '39777'
  requisite: Закон Республики Казахстан от 26 мая 2008 года № 34-IV
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам предупреждения и ликвидации чрезвычайных ситуаций
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне төтенше жағдайлардың алдын алу және оларды жою мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/39777/rus
