act_code: '1552'
requisite: Закон Республики Казахстан от 9 ноября 1998 года № 295-I
title:
  rus: О ратификации Соглашения между Республикой Казахстан и Федеративной Республикой Германия об избежании двойного налогообложения в отношении налогов на доходы и имущество
  kaz: Қазақстан Республикасы мен Германия Федеративтік Республикасы арасындағы Табыс пен мүлікке салынатын салыққа қатысты қосарланған салықты болдырмау туралы келісімді бекіту жөнінде
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 1998-11-09
approved_by:
- '102000000000'
version_date:
  kaz: 1998-11-09
  rus: 1998-11-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/1552/kaz/09.11.1998
  rus: https://zan.gov.kz/client/#!/doc/1552/rus/09.11.1998
