act_code: '25'
requisite: Указ Президента Республики Казахстан от 22 ноября 1996 г. № 3237. Утратил силу Указом Президента Республики Казахстан от 20 марта 1999 года № 88
title:
  rus: О Совете Безопасности Республики Казахстан
  kaz: Қазақстан Республикасының Қауiпсiздiк Кеңесi туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 1996-11-22
approved_by:
- '101000000000'
version_date:
  rus: 1997-11-14
source:
  rus: https://zan.gov.kz/client/#!/doc/25/rus/14.11.1997
caused_by:
  code: U970003758_
