act_code: '5827'
requisite: Указ Президента Республики Казахстан от 21 апреля 2000 года № 378
title:
  rus: О некоторых вопросах Управления Делами Президента Республики Казахстан
  kaz: Қазақстан Республикасы Президентінің Іс Басқармасының кейбір мәселелері туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2000-04-21
approved_by:
- '101000000000'
version_date:
  kaz: 2004-08-23
  rus: 2004-08-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/5827/kaz/23.08.2004
  rus: https://zan.gov.kz/client/#!/doc/5827/rus/23.08.2004
caused_by:
  code: '21025'
  requisite: Указ Президента Республики Казахстан от 24 августа 2004 года N 1425
  title:
    rus: О внесении дополнений и изменений в Указ Президента Республики Казахстан от 21 апреля 2000 года N 378
    kaz: Қазақстан Республикасы Президентінің 2000 жылғы 21 сәуірдегі N 378 Жарлығына толықтырулар мен өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/21025/rus
