act_code: '2383'
requisite: Постановление Правления Национального банка Республики Казахстан от 27 октября 1998 года № 204. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 ақпандағы 1999 года № 695. Утратило силу постановлением Правления Национального Банка Республики Казахстан от 31 марта 2001 года № 88
title:
  rus: Об утверждении Правил регистрации валютных операций, связанных с движением капитала
  kaz: Капитал қозғалысымен байланысты валюта операцияларын тiркеу ережесiн бекiту туралы
type_codes:
- ПРАВ
approved_on: 1998-10-27
approved_by:
- '117000000000'
version_date:
  rus: 1998-10-27
source:
  rus: https://zan.gov.kz/client/#!/doc/2383/rus/27.10.1998
