act_code: '49212'
requisite: Закон Республики Казахстан от 4 декабря 2009 года № 214-IV. Утратил силу Законом Республики Казахстан от 30 декабря 2025 года № 245-VIII (вводится в действие по истечении шестидесяти календарных дней после дня его первого официального опубликования)
title:
  rus: О профилактике бытового насилия
  kaz: Тұрмыстық зорлық-зомбылық профилактикасы туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2009-12-04
approved_by:
- '102000000000'
version_date:
  kaz: 2009-12-04
  rus: 2009-12-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/49212/kaz/04.12.2009
  rus: https://zan.gov.kz/client/#!/doc/49212/rus/04.12.2009
