act_code: '49212'
requisite: Закон Республики Казахстан от 4 декабря 2009 года № 214-IV. Утратил силу Законом Республики Казахстан от 30 декабря 2025 года № 245-VIII (вводится в действие по истечении шестидесяти календарных дней после дня его первого официального опубликования)
title:
  rus: О профилактике бытового насилия
  kaz: Тұрмыстық зорлық-зомбылық профилактикасы туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2009-12-04
approved_by:
- '102000000000'
version_date:
  kaz: 2023-07-01
  rus: 2023-07-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/49212/kaz/01.07.2023
  rus: https://zan.gov.kz/client/#!/doc/49212/rus/01.07.2023
caused_by:
  code: '180054'
  requisite: Закон Республики Казахстан от 20 апреля 2023 года № 226-VII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам социального обеспечения
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне әлеуметтік қамсыздандыру мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/180054/rus
