act_code: '48991'
requisite: Постановление Правительства Республики Казахстан от 3 декабря 2009 года № 1994
title:
  rus: Об утверждении Соглашения между Правительством Республики Казахстан и Правительством Эстонской Республики об освобождении владельцев дипломатических паспортов от визовых требований
  kaz: Қазақстан Республикасының Үкіметі мен Эстония Республикасының Үкіметі арасындағы Дипломаттық паспорттардың иелерін визалық талаптардан босату туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2009-12-03
approved_by:
- '103000000000'
version_date:
  kaz: 2009-12-03
  rus: 2009-12-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/48991/kaz/03.12.2009
  rus: https://zan.gov.kz/client/#!/doc/48991/rus/03.12.2009
