act_code: '3066'
requisite: Указ Президента Республики Казахстан от 4 мая 1999 года N 132. Утратил силу - Указом Президента Республики Казахстан от 29 марта 2002 года N 828 (U020828)
title:
  rus: О перечне должностей руководящих работников государственных органов, назначаемых и утверждаемых Президентом Республики Казахстан или по согласованию с ним, избираемых по его представлению
  kaz: Мемлекеттік органдардың Қазақстан Республикасының Президенті тағайындайтын және бекітетін немесе оның келісуімен тағайындалатын және бекітілетін, оның ұсынуы бойынша сайланатын басшы қызметкерлерінің лауазымдар тізбесі туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 1999-05-03
approved_by:
- '101000000000'
version_date:
  kaz: 1999-05-03
  rus: 1999-05-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/3066/kaz/03.05.1999
  rus: https://zan.gov.kz/client/#!/doc/3066/rus/03.05.1999
