act_code: '16614'
requisite: Указ Президента Республики Казахстан от 18 августа 2003 года № 1167
title:
  rus: О структуре Управления делами Президента Республики Казахстан
  kaz: Қазақстан Республикасы Президентi Iс басқармасының құрылымы туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2003-08-18
approved_by:
- '101000000000'
version_date:
  kaz: 2010-11-26
  rus: 2010-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/16614/kaz/26.11.2010
  rus: https://zan.gov.kz/client/#!/doc/16614/rus/26.11.2010
caused_by:
  code: U1000001110
