act_code: '53448'
requisite: Кодекс Республики Казахстан от 30 июня 2010 года № 296-IV. Утратил силу Кодексом Республики Казахстан от 26 декабря 2017 года № 123-VI (вводится в действие с 01.01.2018, за исключением случаев, предусмотренных пунктом 9 статьи 553, частью второй пункта 3 статьи 560, пунктом 1 и частью третьей пункта 2 статьи 570 настоящего Кодекса)
title:
  rus: О таможенном деле в Республике Казахстан
  kaz: Қазақстан Республикасындағы кеден ісі туралы
form: КОД
type_codes:
- КОД
approved_on: 2010-06-30
approved_by:
- '102000000000'
version_date:
  kaz: 2010-06-30
  rus: 2010-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/53448/kaz/30.06.2010
  rus: https://zan.gov.kz/client/#!/doc/53448/rus/30.06.2010
