act_code: '53448'
requisite: Кодекс Республики Казахстан от 30 июня 2010 года № 296-IV. Утратил силу Кодексом Республики Казахстан от 26 декабря 2017 года № 123-VI (вводится в действие с 01.01.2018, за исключением случаев, предусмотренных пунктом 9 статьи 553, частью второй пункта 3 статьи 560, пунктом 1 и частью третьей пункта 2 статьи 570 настоящего Кодекса)
title:
  rus: О таможенном деле в Республике Казахстан
  kaz: Қазақстан Республикасындағы кеден ісі туралы
form: КОД
type_codes:
- КОД
approved_on: 2010-06-30
approved_by:
- '102000000000'
version_date:
  kaz: 2014-11-10
  rus: 2014-11-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/53448/kaz/10.11.2014
  rus: https://zan.gov.kz/client/#!/doc/53448/rus/10.11.2014
caused_by:
  code: '84262'
  requisite: Закон Республики Казахстан от 10 ноября 2014 года № 249-V ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам передачи органам государственных доходов функций ветеринарно-санитарного контроля и контроля по карантину растений в автомобильных пунктах пропуска через таможенную границу Таможенного союза
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне Кеден одағының кедендік шекарасы арқылы автомобиль өткізу пункттерінде ветеринариялық-санитариялық бақылау және өсімдіктер карантині бойынша бақылау функцияларын мемлекеттік кіріс органдарына беру мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/84262/rus
