act_code: '167955'
requisite: Закон Республики Казахстан от 21 мая 2022 года № 122-VII ЗРК
title:
  rus: О биологической безопасности Республики Казахстан
  kaz: Қазақстан Республикасының биологиялық қауіпсіздігі туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2022-05-21
approved_by:
- '102000000000'
version_date:
  kaz: 2022-05-21
  rus: 2022-05-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/167955/kaz/21.05.2022
  rus: https://zan.gov.kz/client/#!/doc/167955/rus/21.05.2022
