act_code: '167955'
requisite: Закон Республики Казахстан от 21 мая 2022 года № 122-VII ЗРК
title:
  rus: О биологической безопасности Республики Казахстан
  kaz: Қазақстан Республикасының биологиялық қауіпсіздігі туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2022-05-21
approved_by:
- '102000000000'
version_date:
  kaz: 2024-02-24
  rus: 2024-02-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/167955/kaz/24.02.2024
  rus: https://zan.gov.kz/client/#!/doc/167955/rus/24.02.2024
caused_by:
  code: '190600'
  requisite: Закон Республики Казахстан от 23 декабря 2023 года № 51-VIII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам обеспечения национальной безопасности и службы в специальных государственных органах Республики Казахстан
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне ұлттық қауіпсіздікті қамтамасыз ету және Қазақстан Республикасының арнаулы мемлекеттік органдарындағы қызмет мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/190600/rus
