act_code: '602'
requisite: Утверждены постановлением Комитета Республики Казахстан по чрезвычайным ситуациям от 17 декабря 1997 г. N 48. Зарегистрированы в Министерстве юстиции Республики Казахстан 18.04.1998 г. N 498. Утратили силу - приказом Министра по чрезвычайным ситуациям РК от 20.05.2005г. N 469
title:
  rus: Типовые правила безопасности граждан на водоемах Республики Казахстан
  kaz: Қазақстан Республикасының Cу қоймаларында азаматтардың қауіпсіздігін сақтау типтік ережелері
type_codes:
- ПРАВ
approved_on: 1997-12-17
approved_by:
- '103007000000'
version_date:
  kaz: 1997-12-17
  rus: 1997-12-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/602/kaz/17.12.1997
  rus: https://zan.gov.kz/client/#!/doc/602/rus/17.12.1997
