act_code: '3723'
requisite: Приказ Министра внутренних дел Республики Казахстан от 18 июня 1999 года N 316 Зарегистрирован в Министерстве юстиции Республики Казахстан 28 июля 1999г. за N 860. Утратил силу - приказом Министра внутренних дел Республики Казахстан от 9 июля 2001 года N 548 ~V011577
title:
  rus: Об утверждении правил приема в высшие учебные заведения МВД Республики Казахстан
  kaz: Қазақстан Республикасы Ішкі істер министрлігінің жоғарғы оқу орындарына қабылдау ережелерін бекіту туралы
type_codes:
- ПРАВ
approved_on: 1999-06-17
approved_by:
- '103003000000'
version_date:
  rus: 1999-06-17
source:
  rus: https://zan.gov.kz/client/#!/doc/3723/rus/17.06.1999
