act_code: '63089'
requisite: Постановление Правительства Республики Казахстан от 19 января 2012 года № 117
title:
  rus: Об утверждении Соглашения между Правительством Республики Казахстан и Правительством Республики Индия о сотрудничестве в области мирного использования атомной энергии
  kaz: Қазақстан Республикасының Үкіметі мен Үндістан Республикасының Үкіметі арасындағы Атом энергиясын бейбіт мақсатта пайдалану саласындағы ынтымақтастық туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2012-01-19
approved_by:
- '103000000000'
version_date:
  kaz: 2012-01-19
  rus: 2012-01-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/63089/kaz/19.01.2012
  rus: https://zan.gov.kz/client/#!/doc/63089/rus/19.01.2012
