act_code: '42833'
requisite: Кодекс Республики Казахстан от 10 декабря 2008 года № 99-IV. Утратил силу Законом Республики Казахстан от 25 декабря 2017 года № 121-VІ (порядок введения в действие см. статью 58)
title:
  rus: О налогах и других обязательных платежах в бюджет (Налоговый кодекс)
  kaz: Салық және бюджетке төленетін басқа да міндетті төлемдер туралы (Салық кодексі)
form: КОД
type_codes:
- КОД
approved_on: 2008-12-10
approved_by:
- '102000000000'
version_date:
  kaz: 2010-07-15
  rus: 2010-07-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/42833/kaz/15.07.2010
  rus: https://zan.gov.kz/client/#!/doc/42833/rus/15.07.2010
caused_by:
  code: '53678'
  requisite: Закон Республики Казахстан от 15 июля 2010 года № 338-IV
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам страхования
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне сақтандыру мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/53678/rus
