act_code: '8837'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 30 марта 2001 года № 78  Зарегистрирован в Министерстве юстиции Республики Казахстан 02.05.2001 г. за № 1491. Утратил силу приказом Министра сельского хозяйства Республики Казахстан от 13 февраля 2012 года № 10-1/52
title:
  rus: Об утверждении Правил государственного субсидирования элитного семеноводства сельскохозяйственных культур
  kaz: Ауыл шаруашылығы дақылдарының элиталық тұқым шаруашылығын мемлекеттiк қаражаттандырудың ережесiн бекiту туралы
type_codes:
- ПРАВ
approved_on: 2001-03-29
approved_by:
- '103012000000'
version_date:
  kaz: 2001-03-29
  rus: 2001-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/8837/kaz/29.03.2001
  rus: https://zan.gov.kz/client/#!/doc/8837/rus/29.03.2001
