act_code: '8208'
requisite: Приказ Министра внутренних дел Республики Казахстан от 1 января 2001 года № 1. Зарегистрирован в Министерстве юстиции Республики Казахстан 12.02.2001 г. за № 1398. Утратил силу приказом Министра внутренних дел Республики Казахстан от 27 мая 2011 года № 246
title:
  rus: Об утверждении Инструкции о порядке применения Положения о прохождении службы лицами рядового и начальствующего состава органов внутренних дел Республики Казахстан
  kaz: '"Қазақстан Республикасы ішкі істер органдарының қатардағы және басшы құрамдағы адамдарының қызмет өткеруі туралы ережені қолданудың тәртібі туралы нұсқаулықты бекіту туралы"'
type_codes:
- ИНСТ
approved_on: 2001-01-01
approved_by:
- '103003000000'
version_date:
  kaz: 2004-07-22
  rus: 2004-07-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/8208/kaz/22.07.2004
  rus: https://zan.gov.kz/client/#!/doc/8208/rus/22.07.2004
caused_by:
  code: '20941'
  requisite: Приказ Министра внутренних дел Республики Казахстан от 23 июля 2004 года № 428. Зарегистрирован в Министерстве юстиции Республики Казахстан 17 августа 2004 года № 3018. Утратил силу приказом Министра внутренних дел Республики Казахстан от 27 мая 2011 года № 246
  title:
    rus: О внесении изменений в приказ Министра внутренних дел Республики Казахстан от 1 января 2001 года № 1 "Об утверждении Инструкции о порядке применения Положения о прохождении службы лицами рядового и начальствующего состава органов внутренних дел Республики Казахстан", зарегистрированный в Министерстве юстиции Республики Казахстан за № 1398
    kaz: Қазақстан Республикасының Әділет министрлігінде N 1398 болып тіркелген "Қазақстан Республикасы ішкі істер органдарының қатардағы және басшы құрамдағы адамдарының қызмет өткеруі туралы ережені қолданудың тәртібі туралы нұсқаулықты бекіту туралы" Қазақстан Республикасы Ішкі істер министрінің 2001 жылғы 1 қаңтардағы N 1 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/20941/rus
