act_code: '216362'
requisite: Указ Президента Республики Казахстан от 31 октября 2025 года № 1070
title:
  rus: Об утверждении перечня руководящих должностей правоохранительных органов и органов гражданской защиты Республики Казахстан, подлежащих ротации, и Правил их перемещения
  kaz: Қазақстан Республикасы құқық қорғау органдары мен азаматтық қорғау органдарының ротацияға жататын басшылық лауазымдарының тізбесін және оларды ауыстыру қағидаларын бекіту туралы
form: УКАЗ
type_codes:
- ПРАВ
- ПРЧ
- УКАЗ
approved_on: 2025-10-31
approved_by:
- '101000000000'
version_date:
  kaz: 2025-10-31
  rus: 2025-10-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/216362/kaz/31.10.2025
  rus: https://zan.gov.kz/client/#!/doc/216362/rus/31.10.2025
