act_code: '3921'
requisite: Указ Президента Республики Казахстан от 10 августа 1999 года № 187
title:
  rus: Об утверждении Соглашения о сотрудничестве по формированию единого (общего) образовательного пространства Содружества Независимых Государств
  kaz: Тәуелсіз Мемлекеттер Достастығының бірыңғай (ортақ) білім кеңістігін қалыптастыру жөніндегі ынтымақтастық туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- СОГЛ
- УКАЗ
approved_on: 1999-08-09
approved_by:
- '101000000000'
version_date:
  kaz: 1999-08-09
  rus: 1999-08-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/3921/kaz/09.08.1999
  rus: https://zan.gov.kz/client/#!/doc/3921/rus/09.08.1999
