act_code: '4087'
requisite: Нормативное постановление Верховного Суда Республики Казахстан от 9 июля 1999 года № 7
title:
  rus: О практике применения законодательства по возмещению вреда, причиненного незаконными действиями органов, ведущих уголовный процесс
  kaz: Қылмыстық процесті жүргізетін органдардың заңсыз әрекеттерімен келтірілген зиянды өтеу жөніндегі заңнаманы қолдану практикасы туралы
form: НПОС
type_codes:
- НПОС
approved_on: 1999-07-09
approved_by:
- '105000000000'
version_date:
  kaz: 1999-07-08
  rus: 1999-07-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/4087/kaz/08.07.1999
  rus: https://zan.gov.kz/client/#!/doc/4087/rus/08.07.1999
