act_code: '10366'
requisite: Постановление Правительства Республики Казахстан от 19 октября 2001 года N 1342
title:
  rus: О привлечении займа Международного Банка Реконструкции и Развития для финансирования проекта "Регулирование русла реки Сырдарьи и сохранение северной части Аральского моря (Фаза 1)"
  kaz: '"Сырдария өзенiнiң арнасын реттеу және Арал теңiзiнiң солтүстiк бөлiгін сақтау (1-қезең)" жобасын қаржыландыру үшiн Халықаралық Қайта Құру және Даму Банкiнiң заемын тарту туралы'
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2001-10-18
approved_by:
- '103000000000'
version_date:
  kaz: 2001-10-18
  rus: 2001-10-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/10366/kaz/18.10.2001
  rus: https://zan.gov.kz/client/#!/doc/10366/rus/18.10.2001
