act_code: '203648'
requisite: Закон Республики Казахстан от 4 декабря 2024 года № 140-VIII ЗРК. Утратил силу Законом Республики Казахстан от 8 декабря 2025 года № 239-VIII (вводится в действие с 1 января 2026 года)
title:
  rus: О гарантированном трансферте из Национального фонда Республики Казахстан на 2025 – 2027 годы
  kaz: Қазақстан Республикасының Ұлттық қорынан 2025 – 2027 жылдарға арналған кепілдендірілген трансферт туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2024-12-04
approved_by:
- '102000000000'
version_date:
  kaz: 2024-12-04
  rus: 2024-12-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/203648/kaz/04.12.2024
  rus: https://zan.gov.kz/client/#!/doc/203648/rus/04.12.2024
