act_code: '104094'
requisite: Закон Республики Казахстан от 18 янваpя 1992 года. Утратил силу Законом Республики Казахстан от 7 июня 1999 года № 390
title:
  rus: ОБ ОБРАЗОВАНИИ
  kaz: ОБ ОБРАЗОВАНИИ
form: ЗАК
type_codes:
- ЗАК
approved_on: 1992-01-18
approved_by:
- '102000000000'
version_date:
  rus: 1998-06-30
source:
  rus: https://zan.gov.kz/client/#!/doc/104094/rus/30.06.1998
caused_by:
  code: '929'
  requisite: Закон Республики Казахстан от 1 июля 1998 года № 259
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан ( по вопросам о статусе города Алматы)
    kaz: Қазақстан Республикасының кейбiр заң актiлерiне өзгерiстер мен толықтырулар енгiзу туралы (Алматы қаласының мәртебесi туралы мәселелер жөнiнде)
  link: https://zan.gov.kz/client/#!/doc/929/rus
