act_code: '104308'
requisite: Закон Республики Казахстан от 31 мая 1996 года № 3
title:
  rus: Об общественных объединениях
  kaz: Қоғамдық бiрлестiктер туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1996-05-31
approved_by:
- '102000000000'
version_date:
  rus: 2001-12-24
source:
  rus: https://zan.gov.kz/client/#!/doc/104308/rus/24.12.2001
caused_by:
  code: '10768'
  requisite: Закон Республики Казахстан от 24 декабря 2001 года  № 276-ІІ
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан в связи с принятием Кодекса Республики Казахстан "О налогах и других обязательных платежах в бюджет" (Налоговый кодекс)
    kaz: '"Салық және бюджетке төленетін басқа да міндетті төлемдер туралы" Қазақстан Республикасы кодексінің (Салық кодексінің) қабылдануына байланысты Қазақстан Республикасының кейбір заң актілеріне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/10768/rus
