act_code: '71815'
requisite: Приказ Министра образования и науки Республики Казахстан от 22 февраля 2013 года № 56. Зарегистрирован в Министерстве юстиции Республики Казахстан 20 марта 2013 года № 8386. Утратил силу совместным приказом Министра науки и высшего образования Республики Казахстан от 8 января 2024 года № 7 и Министра просвещения Республики Казахстан от 9 января 2024 года № 4 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении формы типового соглашения о сотрудничестве в сфере Государственной образовательной накопительной системы с организацией образования
  kaz: Білім беру ұйымымен мемлекеттік білім беру жинақтау жүйесі саласындағы ынтымақтастық туралы үлгілік келісімнің нысанын бекіту туралы
form: СОГЛ
type_codes:
- ПРИК
- СОГЛ
approved_on: 2013-02-22
approved_by:
- '103006000000'
version_date:
  kaz: 2022-12-23
  rus: 2022-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/71815/kaz/23.12.2022
  rus: https://zan.gov.kz/client/#!/doc/71815/rus/23.12.2022
caused_by:
  code: '176114'
  requisite: Приказ Министра науки и высшего образования Республики Казахстан от 23 декабря 2022 года № 198. Зарегистрирован в Министерстве юстиции Республики Казахстан 26 декабря 2022 года № 31272. Утратил силу совместным приказом Министра науки и высшего образования Республики Казахстан от 8 января 2024 года № 7 и Министра просвещения Республики Казахстан от 9 января 2024 года № 4 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в приказ Министра образования и науки Республики Казахстан от 22 февраля 2013 года № 56 «Об утверждении формы типового соглашения о сотрудничестве с организацией образования»
    kaz: «Білім беру ұйымымен ынтымақтастық туралы үлгілік келісімнің нысанын бекіту туралы» Қазақстан Республикасы Білім және ғылым министрінің 2013 жылғы 22 ақпандағы № 56 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/176114/rus
