act_code: '154292'
requisite: Указ Президента Республики Казахстан от 5 апреля 2021 года № 545. Утратил силу Указом Президента Республики Казахстан от 3 января 2024 года № 429 (вводится в действие после дня его первого официального опубликования)
title:
  rus: О Специальном представителе Президента Республики Казахстан по международному сотрудничеству
  kaz: Қазақстан Республикасы Президентінің халықаралық ынтымақтастық жөніндегі арнаулы өкілі туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2021-04-05
approved_by:
- '101000000000'
version_date:
  kaz: 2021-04-05
  rus: 2021-04-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/154292/kaz/05.04.2021
  rus: https://zan.gov.kz/client/#!/doc/154292/rus/05.04.2021
