act_code: '4724'
requisite: Постановление Национальной комиссии Республики Казахстан по ценным бумагам от 26 июня 1997 г. N 90. Зарегистрировано в Министерстве юстиции 03 октября 1997 г N 380. Утратило силу - постановлением Правления Агентства РК по регулированию и надзору финансового рынка и финансовых организаций от 21 августа 2004 года N 256
title:
  rus: Об утверждении требований, предъявляемых к инвестиционным декларациям инвестиционных фондов
  kaz: Инвестициялық қорлардың инвестициялық декларацияларына қойылатын талаптарды бекiту туралы
type_codes:
- ТРЕБ
approved_on: 1997-06-25
approved_by:
- '111000000000'
version_date:
  kaz: 1997-06-25
  rus: 1997-06-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/4724/kaz/25.06.1997
  rus: https://zan.gov.kz/client/#!/doc/4724/rus/25.06.1997
