act_code: '38212'
requisite: Постановление Правительства Республики Казахстан от 4 июля 2014 года № 766
title:
  rus: О присоединении к Соглашению о Совете по туризму государств-участников Содружества Независимых Государств
  kaz: Тәуелсіз Мемлекеттер Достастығына қатысушы мемлекеттердің Туризм жөніндегі кеңесі туралы келісімге қосылу туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2014-07-04
approved_by:
- '103000000000'
version_date:
  kaz: 2014-07-04
  rus: 2014-07-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/38212/kaz/04.07.2014
  rus: https://zan.gov.kz/client/#!/doc/38212/rus/04.07.2014
