act_code: '48930'
requisite: Закон Республики Казахстан от 30 ноября 2009 года № 208-IV
title:
  rus: О ратификации Конвенции между Республикой Казахстан и Японией об избежании двойного налогообложения и предотвращении уклонения от налогообложения в отношении налогов на доход и Протокола к ней
  kaz: Қазақстан Республикасы мен Жапония арасындағы Табысқа салынатын салықтарға қатысты қосарланған салық салуды болдырмау және салық салудан жалтаруға жол бермеу туралы конвенцияны және оған Хаттаманы ратификациялау туралы
form: КОНВ
type_codes:
- ЗАК
- КОНВ
approved_on: 2009-11-30
approved_by:
- '102000000000'
version_date:
  kaz: 2009-11-30
  rus: 2009-11-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/48930/kaz/30.11.2009
  rus: https://zan.gov.kz/client/#!/doc/48930/rus/30.11.2009
