act_code: '2524'
requisite: Постановление Национальной комиссии Республики Казахстан по ценным бумагам от 23 декабря 1998 года № 19 Зарегистрирован в Министерстве юстиции Республики Казахстан 17.03.1999 г. за N 703. Утратило силу постановлением Правления Агентства Республики Казахстан по регулированию и надзору финансового рынка и финансовых организаций от 25 июня 2007 года N 175
title:
  rus: Об утверждении Правил осуществления деятельности организаторов торгов с ценными бумагами
  kaz: Бағалы қағаздармен сауда-саттық ұйымдастырушылардың қызметін жүзеге асыру қағидаларын бекіту туралы
type_codes:
- ПРАВ
approved_on: 1998-12-23
approved_by:
- '111000000000'
version_date:
  rus: 2000-03-15
source:
  rus: https://zan.gov.kz/client/#!/doc/2524/rus/15.03.2000
caused_by:
  code: '5781'
  requisite: Постановление Национальной комиссии Республики Казахстан по ценным бумагам от 15 марта 2000г. N 68 Зарегистрирован в Министерстве юстиции Республики Казахстан 5 апреля 2000г. за N 1102. Утратило силу постановлением Правления Агентства Республики Казахстан по регулированию и надзору финансового рынка и финансовых организаций от 25 июня 2007 года N 175
  title:
    rus: О внесении изменения в постановление Национальной комиссии Республики Казахстан по ценным бумагам "Об утверждении Правил осуществления деятельности организаторов торгов с ценными бумагами" от 23 декабря 1998 года N 19
    kaz: '"Бағалы қағаздармен сауда-саттық ұйымдастырушылардың қызметiн жүзеге асыру қағидаларын бекiту туралы" Қазақстан Республикасы Бағалы қағаздар жөнiндегi ұлттық комиссиясының 1998 жылғы 23 желтоқсандағы N 19 қаулысына өзгерiс енгiзу туралы'
  link: https://zan.gov.kz/client/#!/doc/5781/rus
