act_code: '9467'
requisite: Указ Президента Республики Казахстан от 11 июля 2001 года № 654
title:
  rus: О мерах по организации единой системы государственного регулирования финансового рынка
  kaz: Қаржы нарығын мемлекеттік реттеудің бірыңғай жүйесін ұйымдастыру жөніндегі шаралар туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2001-07-10
approved_by:
- '101000000000'
version_date:
  kaz: 2001-07-10
  rus: 2001-07-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/9467/kaz/10.07.2001
  rus: https://zan.gov.kz/client/#!/doc/9467/rus/10.07.2001
