act_code: '7255'
requisite: Закон Республики Казахстан от 23 октября 2000 года № 91-II
title:
  rus: О присоединении Республики Казахстан к Конвенции о трансграничном воздействии промышленных аварий
  kaz: Қазақстан Республикасының Өнеркәсіптiк авариялардың шекарааралық әсері туралы конвенцияға қосылуы туралы
form: КОНВ
type_codes:
- ЗАК
- КОНВ
approved_on: 2000-10-22
approved_by:
- '102000000000'
version_date:
  kaz: 2000-10-22
  rus: 2000-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/7255/kaz/22.10.2000
  rus: https://zan.gov.kz/client/#!/doc/7255/rus/22.10.2000
