act_code: '50301'
requisite: Закон Республики Казахстан от 20 января 2010 года № 240-IV. Утратил силу Законом Республики Казахстан от 10 февраля 2017 года № 44-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования).
title:
  rus: О судебно-экспертной деятельности в Республике Казахстан
  kaz: Қазақстан Республикасындағы сот-сараптама қызметi туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2010-01-20
approved_by:
- '102000000000'
version_date:
  kaz: 2013-07-02
  rus: 2013-07-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/50301/kaz/02.07.2013
  rus: https://zan.gov.kz/client/#!/doc/50301/rus/02.07.2013
caused_by:
  code: '73217'
  requisite: Закон Республики Казахстан от 2 июля 2013 года № 113-V
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам судебно-экспертной деятельности
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне сот-сараптама қызметі мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/73217/rus
