act_code: '55595'
requisite: Закон Республики Казахстан от 9 ноября 2010 года № 350-IV ЗРК
title:
  rus: О ратификации Найробского Договора об охране олимпийского символа, принятого в Найроби 26 сентября 1981 года
  kaz: 1981 жылғы 26 қыркүйекте Найробиде қабылданған Олимпиада рәмізін қорғау туралы Найроби шартын ратификациялау туралы
form: ДОГ
type_codes:
- ДОГ
- ЗАК
approved_on: 2010-11-09
approved_by:
- '102000000000'
version_date:
  kaz: 2010-11-09
  rus: 2010-11-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/55595/kaz/09.11.2010
  rus: https://zan.gov.kz/client/#!/doc/55595/rus/09.11.2010
