act_code: '104112'
requisite: Закон Республики Казахстан от 31 октября 1997 года № 184-I
title:
  rus: О ратификации Соглашения между Правительством Республики Казахстан и Правительством Республики Беларусь об избежании двойного налогообложения и предотвращении уклонения от уплаты налогов в отношении налогов на доходы и имущество
  kaz: Табыс пен мүлiкке қосарланған салық салуды болдырмау және салық төлеуден жалтаруға жол бермеу туралы Қазақстан Республикасының Үкiметi мен Беларусь Республикасының Үкiметi арасындағы келiсiмдi бекiту туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 1997-10-31
approved_by:
- '102000000000'
version_date:
  kaz: 2018-04-09
  rus: 2018-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/104112/kaz/09.04.2018
  rus: https://zan.gov.kz/client/#!/doc/104112/rus/09.04.2018
caused_by:
  code: '120465'
  requisite: Закон Республики Казахстан от 9 апреля 2018 года № 146-VІ ЗРК
  title:
    rus: О ратификации Протокола между Правительством Республики Казахстан и Правительством Республики Беларусь о внесении изменений и дополнений в Соглашение между Правительством Республики Казахстан и Правительством Республики Беларусь об избежании двойного налогообложения и предотвращении уклонения от уплаты налогов в отношении налогов на доходы и имущество от 11 апреля 1997 года
    kaz: Қазақстан Республикасының Үкіметі мен Беларусь Республикасының Үкіметі арасындағы 1997 жылғы 11 сәуірдегі Табыс пен мүлiкке қосарланған салық салуды болдырмау және салық төлеуден жалтаруға жол бермеу туралы Қазақстан Республикасының Үкiметi мен Беларусь Республикасының Үкiметi арасындағы келісімге өзгерістер мен толықтырулар енгізу туралы хаттаманы ратификациялау туралы
  link: https://zan.gov.kz/client/#!/doc/120465/rus
