act_code: '3459'
requisite: Приказ Министра финансов Республики Казахстан от 2 декабря 1996 г. N 264. Зарегистрирован в Министерстве юстиции Республики Казахстан 11 декабря 1996 г. N 231. Утратил силу - приказом Министра финансов РК от 30 декабря 2004 года N 469 (V043337)(вводится в действие с 1 января 2005 года)
title:
  rus: Об утверждении Инструкции по финансированию государственных учреждений, содержащихся за счет местных бюджетов, путем установления лимитов на расходование средств
  kaz: Қаржы шығынына лимит белгiлеу арқылы жергiлiктi бюджеттерiнiң есебiнен ұсталатын, мемлекеттік мекемелерді қаржыландыру нұсқауын бекiту туралы
type_codes:
- ИНСТ
approved_on: 1996-12-02
approved_by:
- '103002000000'
version_date:
  rus: 1997-02-26
source:
  rus: https://zan.gov.kz/client/#!/doc/3459/rus/26.02.1997
caused_by:
  code: '3584'
  requisite: Приказ Министра финансов Республики Казахстан от 26 февраля 1997 г. N 49. Зарегистрирован Министерством юстиции Республики Казахстан 14.03.1997 г. N 39. Утратил силу - приказом Министра финансов РК от 30 декабря 2004 года N 469
  title:
    rus: О внесении дополнений в Инструкцию по финансированию бюджетных организаций, состоящих на местных бюджетах, путем установления лимитов на расходование средств
    kaz: Жергiлiктi бюджетте тұратын бюджет мекемелерiнiң қаржыны жұмсау лимитiн бекiту арқылы қаржыландыру туралы Нұсқаулығына толықтырулар енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/3584/rus
