act_code: '104427'
requisite: Закон Республики Казахстан от 31 декабря 1996 года N 65-1. Утратил силу с 1 января 2002 года - Законом РК от 12 июня 2001 года N 210
title:
  rus: О Государственной пошлине
  kaz: Мемлекеттiк баж туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1996-12-31
approved_by:
- '102000000000'
version_date:
  kaz: 2001-04-24
  rus: 2001-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/104427/kaz/24.04.2001
  rus: https://zan.gov.kz/client/#!/doc/104427/rus/24.04.2001
caused_by:
  code: '8746'
  requisite: Закон Республики Казахстан от 25 апреля 2001 года № 179-ІІ
  title:
    rus: О внесении дополнений в некоторые законодательные акты Республики Казахстан по вопросам деятельности Банка Развития Казахстана
    kaz: Қазақстан Республикасының кейбір заң актілеріне Қазақстанның Даму Банкі қызметінің мәселелері бойынша толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/8746/rus
