act_code: '104225'
requisite: Закон Республики Казахстан от 14 апреля 1993 года
title:
  rus: О реабилитации жертв массовых политических репрессий
  kaz: Жаппай саяси қуғын-сүргiндер құрбандарын ақтау туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1993-04-14
approved_by:
- '102000000000'
version_date:
  kaz: 2018-07-02
  rus: 2018-07-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/104225/kaz/02.07.2018
  rus: https://zan.gov.kz/client/#!/doc/104225/rus/02.07.2018
caused_by:
  code: '123089'
  requisite: Закон Республики Казахстан от 2 июля 2018 года № 165-VІ ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам социального обеспечения
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне әлеуметтік қамсыздандыру мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123089/rus
