act_code: '9812'
requisite: Приказ Председателя Агентства Республики Казахстан по делам здравоохранения от 16 августа 2001 года N 756. Зарегистрирован в Министерстве юстиции Республики Казахстан 24 августа 2001 года N 1631. Утратил силу приказом и.о. Министра здравоохранения Республики Казахстан от 8 июня 2009 года N 297
title:
  rus: О мерах по совершенствованию скорой и неотложной медицинской помощи населению Республики Казахстан
  kaz: Қазақстан Республикасы халқына көрсетілетін жедел және кезек күттірмейтін жәрдемді жетілдіру жөніндегі шаралар туралы
type_codes:
- ПРАВ
approved_on: 2001-08-15
approved_by:
- '103010000000'
version_date:
  kaz: 2001-08-15
  rus: 2001-08-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/9812/kaz/15.08.2001
  rus: https://zan.gov.kz/client/#!/doc/9812/rus/15.08.2001
