act_code: '104255'
requisite: Указ Президента Республики Казахстан от 25 апреля 2016 года № 240
title:
  rus: Об утверждении Консульского устава Республики Казахстан
  kaz: Қазақстан Республикасының Консулдық жарғысын бекіту туралы
form: УКАЗ
type_codes:
- УКАЗ
- УСТ
approved_on: 2016-04-25
approved_by:
- '101000000000'
version_date:
  kaz: 2021-09-18
  rus: 2021-09-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/104255/kaz/18.09.2021
  rus: https://zan.gov.kz/client/#!/doc/104255/rus/18.09.2021
caused_by:
  code: '158839'
  requisite: Указ Президента Республики Казахстан от 18 сентября 2021 года № 661
  title:
    rus: О внесении изменений и дополнений в некоторые указы Президента Республики Казахстан
    kaz: Қазақстан Республикасы Президентінің кейбір жарлықтарына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/158839/rus
