act_code: '7217'
requisite: Закон Республики Казахстан от 19 октября 2000 года № 85
title:
  rus: Об охранной деятельности
  kaz: Күзет қызметі туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2000-10-19
approved_by:
- '102000000000'
version_date:
  kaz: 2018-07-12
  rus: 2018-07-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/7217/kaz/12.07.2018
  rus: https://zan.gov.kz/client/#!/doc/7217/rus/12.07.2018
caused_by:
  code: '123552'
  requisite: Закон Республики Казахстан от 12 июля 2018 года № 180-VІ ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам совершенствования уголовного, уголовно-процессуального законодательства и деятельности правоохранительных и специальных государственных органов
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне қылмыстық, қылмыстық-процестік заңнама мен құқық қорғау және арнаулы мемлекеттік органдар қызметін жетілдіру мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123552/rus
