act_code: '1542'
requisite: Приказ Департамента Казначейства Министерства финансов Республики Казахстан от 14 августа 1998 года N 385 Зарегистрирован Министерством юстиции РК 21.09.1998г. N 609. Утратил силу - приказом Министерства финансов Республики Казахстан от 21 июня 2000 года N 298 ~V001261
title:
  rus: Инструкция по ведению операций в иностранной валюте Департаментом Казначейства и его территориальными органами
  kaz: Қазынашылық департаментінің және оның аумақтық органдарының шетел валютасымен операциялар жүргізу жөніндегі Нұсқаулықты бекіту туралы
type_codes:
- ИНСТ
approved_on: 1998-08-13
approved_by:
- '103002005000'
version_date:
  rus: 1998-08-13
source:
  rus: https://zan.gov.kz/client/#!/doc/1542/rus/13.08.1998
