act_code: '57472'
requisite: Постановление Правительства Республики Казахстан от 25 февраля 2011 года № 185
title:
  rus: Об утверждении Соглашения между правительствами государств-членов Шанхайской организации сотрудничества о сотрудничестве в области сельского хозяйства
  kaz: Шанхай ынтымақтастық ұйымына мүше мемлекеттердің үкіметтері арасындағы Ауыл шаруашылығы саласындағы ынтымақтастық туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2011-02-25
approved_by:
- '103000000000'
version_date:
  kaz: 2011-02-25
  rus: 2011-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/57472/kaz/25.02.2011
  rus: https://zan.gov.kz/client/#!/doc/57472/rus/25.02.2011
