act_code: '154025'
requisite: Закон Республики Казахстан от 31 марта 2021 года № 25-VII ЗРК
title:
  rus: О ратификации Найробийской международной конвенции об удалении затонувших судов 2007 года
  kaz: Суға батып кеткен кемелерді жою туралы 2007 жылғы Найроби халықаралық конвенциясын ратификациялау туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2021-03-31
approved_by:
- '102000000000'
version_date:
  kaz: 2021-03-31
  rus: 2021-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/154025/kaz/31.03.2021
  rus: https://zan.gov.kz/client/#!/doc/154025/rus/31.03.2021
