act_code: '4252'
requisite: Указ Президента Республики Казахстан от 27 сентября 1999 года № 217. Утратил силу Указом Президента Республики Казахстан от 25 апреля 2016 года № 240
title:
  rus: Об утверждении Консульского устава Республики Казахстан
  kaz: Қазақстан Республикасының Консулдық жарғысын бекіту туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 1999-09-26
approved_by:
- '101000000000'
version_date:
  kaz: 2008-06-26
  rus: 2008-06-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/4252/kaz/26.06.2008
  rus: https://zan.gov.kz/client/#!/doc/4252/rus/26.06.2008
caused_by:
  code: '40197'
  requisite: Указ Президента Республики Казахстан от 26 июня 2008 года № 623. Утратил силу Указом Президента Республики Казахстан от 25 апреля 2016 года № 240
  title:
    rus: О внесении изменений и дополнения в Указ Президента Республики Казахстан от 27 сентября 1999 года N 217
    kaz: Қазақстан Республикасы Президентінің 1999 жылғы 27 қыркүйектегі N 217 Жарлығына өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/40197/rus
