act_code: '9643'
requisite: Приказ Министра образования и науки Республики Казахстан от 23 июля 2001 года N 602. Зарегистрирован в Министерстве юстиции Республики Казахстан 30 июля 2001 года N 1599. Утратил силу приказом и.о. Министра образования и науки Республики Казахстан от 5 марта 2008 года N 109.
title:
  rus: Об утверждении Перечня и критериев оценки показателей для аккредитации организаций образования по типу и виду и Инструкции о порядке проведения государственной аккредитации организаций образования
  kaz: Бiлiм беру ұйымдарының үлгiлерi мен түрлерi бойынша мемлекеттiк аккредитациялауға арналған көрсеткiштердi бағалау тiзбесi мен өлшемдерiн және Бiлiм беру ұйымдарын мемлекеттiк аккредитациялаудан өткiзу тәртiбi туралы нұсқаулықты бекiту туралы
type_codes:
- ИНСТ
approved_on: 2001-07-22
approved_by:
- '103006000000'
version_date:
  kaz: 2001-07-22
  rus: 2001-07-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/9643/kaz/22.07.2001
  rus: https://zan.gov.kz/client/#!/doc/9643/rus/22.07.2001
