act_code: '1'
requisite: Конституция принята на республиканском референдуме 30 августа 1995 года. Прекратила действие с 1 июля 2026 года в соответствии с Конституцией Республики Казахстан, принятой на республиканском референдуме 15 марта 2026 года
title:
  rus: Конституция Республики Казахстан
  kaz: Қазақстан Республикасының Конституциясы
form: КОНС
type_codes:
- КОНС
approved_on: 1995-08-30
approved_by:
- '102000000000'
version_date:
  kaz: 2007-05-21
  rus: 2007-05-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/1/kaz/21.05.2007
  rus: https://zan.gov.kz/client/#!/doc/1/rus/21.05.2007
caused_by:
  code: '33304'
  requisite: Закон Республики Казахстан от 21 мая 2007 года № 254
  title:
    rus: О внесении изменений и дополнений в Конституцию Республики Казахстан
    kaz: Қазақстан Республикасының Конституциясына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/33304/rus
