act_code: '30774'
requisite: Закон Республики Казахстан от 15 декабря 2006 года № 207
title:
  rus: О культуре
  kaz: Мәдениет туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2006-12-15
approved_by:
- '102000000000'
version_date:
  kaz: 2024-06-08
  rus: 2024-06-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/30774/kaz/08.06.2024
  rus: https://zan.gov.kz/client/#!/doc/30774/rus/08.06.2024
caused_by:
  code: '195399'
  requisite: Закон Республики Казахстан от 6 апреля 2024 года № 71-VIII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам ведения бизнеса
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне бизнес жүргізу мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/195399/rus
