act_code: '1816'
requisite: Закон Республики Казахстан от 17 декабря 1998 года № 321-I. Утратил силу Кодексом Республики Казахстан от 26 декабря 2011 года № 518-IV
title:
  rus: О браке и семье
  kaz: Неке және отбасы туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1998-12-17
approved_by:
- '102000000000'
version_date:
  rus: 2004-12-20
source:
  rus: https://zan.gov.kz/client/#!/doc/1816/rus/20.12.2004
caused_by:
  code: '22306'
  requisite: Закон Республики Казахстан от 20 декабря 2004 года № 13
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам разграничения полномочий между уровнями государственного управления и бюджетных отношений
    kaz: Қазақстан Республикасының кейбiр заңнамалық актiлерiне мемлекеттік басқару деңгейлерi арасында өкiлеттiктердiң аражiгін ажырату және бюджеттiк қатынастар мәселелерi бойынша өзгерiстер мен толықтырулар енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/22306/rus
