act_code: '38441'
requisite: Постановление Правительства Республики Казахстан от 8 июля 2014 года № 784
title:
  rus: Об утверждении Соглашения между Правительством Республики Казахстан и Правительством Китайской Народной Республики о временной трудовой деятельности граждан Республики Казахстан в Китайской Народной Республике и граждан Китайской Народной Республики в Республике Казахстан
  kaz: Қазақстан Республикасының Үкіметі мен Қытай Халық Республикасының Үкіметі арасындағы Қазақстан Республикасы азаматтарының Қытай Халық Республикасындағы және Қытай Халық Республикасы азаматтарының Қазақстан Республикасындағы уақытша еңбек қызметі туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2014-07-08
approved_by:
- '103000000000'
version_date:
  kaz: 2014-07-08
  rus: 2014-07-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/38441/kaz/08.07.2014
  rus: https://zan.gov.kz/client/#!/doc/38441/rus/08.07.2014
