act_code: '4751'
requisite: Постановление Государственного комитета Республики Казахстан по инвестициям от 28 марта 1997 г. N 5. Зарегистрировано в Министерстве юстиции Республики Казахстан 15 октября 1997 г. N 400. Утратило силу - Приказом Председателя Комитета по инвестициям Министерства иностранных дел Республики Казахстан от 30 марта 2001 года N 23-п
title:
  rus: Об утверждении Инструкции "О порядке регистрации контракта, заключенного Государственным комитетом Республики Казахстан по инвестициям и инвестором" и формы свидетельства о регистрации контракта
  kaz: '"Қазақстан Республикасының инвестициялар жөнiндегi мемлекеттiк комитетi мен инвестордың арасында жасалған келiсiм-шартты тiркеудiң тәртiбi туралы нұсқаулықты" және "Келiсiм-шартты тiркеу туралы куәлiктiң" нысанын бекiту туралы'
type_codes:
- ИНСТ
approved_on: 1997-03-28
approved_by:
- '103004001000'
version_date:
  rus: 1997-03-28
source:
  rus: https://zan.gov.kz/client/#!/doc/4751/rus/28.03.1997
