act_code: '127160'
requisite: Приказ Министра энергетики Республики Казахстан от 14 декабря 2018 года № 512. Зарегистрирован в Министерстве юстиции Республики Казахстан 20 декабря 2018 года № 17976
title:
  rus: Об утверждении Типового договора о покупке услуги по поддержанию готовности электрической мощности с субъектами оптового рынка, включенными в Реестр групп лиц
  kaz: Тұлғалар тобының тізіліміне енгізілген көтерме сауда нарығының субъектілерімен электр қуатының әзірлігін ұстап тұру бойынша көрсетілетін қызметтерді сатып алу туралы үлгілік шартты бекіту туралы
form: ДОГ
type_codes:
- ДОГ
- ПРИК
approved_on: 2018-12-14
approved_by:
- '103036000000'
version_date:
  kaz: 2018-12-14
  rus: 2018-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/127160/kaz/14.12.2018
  rus: https://zan.gov.kz/client/#!/doc/127160/rus/14.12.2018
