act_code: '104113'
requisite: Закон Республики Казахстан от 31 октября 1997 г. № 185-I
title:
  rus: О ратификации Конвенции между Республикой Казахстан и Литовской Республикой об избежании двойного налогообложения и предотвращении уклонения от налогообложения в отношении налогов на доходы и на капитал
  kaz: Қазақстан Республикасы мен Литва Республикасы арасындағы табыстар пен капиталға салынатын салықтарға қатысты қосарланған салық салуды болдырмау және салық төлеуден жалтаруға жол бермеу туралы конвенцияны бекiту туралы
form: КОНВ
type_codes:
- ЗАК
- КОНВ
approved_on: 1997-10-31
approved_by:
- '102000000000'
version_date:
  kaz: 1997-10-31
  rus: 1997-10-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/104113/kaz/31.10.1997
  rus: https://zan.gov.kz/client/#!/doc/104113/rus/31.10.1997
