act_code: '182861'
requisite: Постановление Правительства Республики Казахстан от 13 июня 2023 года № 461
title:
  rus: Об утверждении Меморандума о взаимопонимании между Правительством Республики Казахстан и Правительством Государства Катар по вопросам взаимного сотрудничества в области здравоохранения
  kaz: Қазақстан Республикасының Үкіметі мен Қатар Мемлекетінің Үкіметі арасындағы денсаулық сақтау саласындағы өзара ынтымақтастық мәселелері жөніндегі өзара түсіністік туралы меморандумды бекіту туралы
form: МЕМР
type_codes:
- МЕМР
- ПОСТ
approved_on: 2023-06-13
approved_by:
- '103000000000'
version_date:
  kaz: 2023-06-13
  rus: 2023-06-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/182861/kaz/13.06.2023
  rus: https://zan.gov.kz/client/#!/doc/182861/rus/13.06.2023
