act_code: '53780'
requisite: Закон Республики Казахстан от 15 июля 2010 года № 333-IV ЗРК
title:
  rus: О ратификации Протокола к Соглашению о партнерстве и сотрудничестве (СПС) между Республикой Казахстан, с одной стороны, и Европейскими сообществами и их государствами-членами, с другой стороны, о присоединении Республики Болгария и Румынии к СПС
  kaz: Бір тараптан Қазақстан Республикасы және екінші тараптан Еуропалық қоғамдастықтар мен оларға мүше мемлекеттер арасындағы Әріптестік пен ынтымақтастық туралы келісімге (ӘЫК), Болгария Республикасы мен Румынияның ӘЫК-ге қосылуы туралы хаттаманы ратификациялау туралы
form: ПРОТ
type_codes:
- ЗАК
- ПРОТ
approved_on: 2010-07-15
approved_by:
- '102000000000'
version_date:
  kaz: 2010-07-15
  rus: 2010-07-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/53780/kaz/15.07.2010
  rus: https://zan.gov.kz/client/#!/doc/53780/rus/15.07.2010
