act_code: '115523'
requisite: Указ Президента Республики Казахстан от 26 октября 2017 года № 569
title:
  rus: О переводе алфавита казахского языка с кириллицы на латинскую графику
  kaz: Қазақ тілі әліпбиін кириллицадан латын графикасына көшіру туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2017-10-26
approved_by:
- '101000000000'
version_date:
  kaz: 2018-02-19
  rus: 2018-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/115523/kaz/19.02.2018
  rus: https://zan.gov.kz/client/#!/doc/115523/rus/19.02.2018
caused_by:
  code: '118804'
  requisite: Указ Президента Республики Казахстан от 19 февраля 2018 года № 637
  title:
    rus: О внесении изменения в Указ Президента Республики Казахстан от 26 октября 2017 года № 569 «О переводе алфавита казахского языка с кириллицы на латинскую графику»
    kaz: «Қазақ тілі әліпбиін кириллицадан латын графикасына көшіру туралы» Қазақстан Республикасы Президентінің 2017 жылғы 26 қазандағы №569 Жарлығына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/118804/rus
