act_code: '17723'
requisite: Указ Президента Республики Казахстан от 4 декабря 2003 года N 1243. Утратил силу Указом Президента Республики Казахстан от 29 декабря 2015 года № 151
title:
  rus: О кадровом резерве государственной службы
  kaz: Мемлекеттiк қызметтiң кадр резервi туралы
form: УКАЗ
type_codes:
- ПОЛ
- УКАЗ
approved_on: 2003-12-04
approved_by:
- '101000000000'
version_date:
  kaz: 2008-11-12
  rus: 2008-11-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/17723/kaz/12.11.2008
  rus: https://zan.gov.kz/client/#!/doc/17723/rus/12.11.2008
caused_by:
  code: '42542'
  requisite: Указ Президента Республики Казахстан от 12 ноября 2008 года № 689
  title:
    rus: О внесении изменений в некоторые акты Президента Республики Казахстан
    kaz: Қазақстан Республикасы Президентінің кейбір актілеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/42542/rus
