act_code: '97537'
requisite: Закон Республики Казахстан от 14 января 2016 года № 444-V ЗРК
title:
  rus: О драгоценных металлах и драгоценных камнях
  kaz: Бағалы металдар мен асыл тастар туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2016-01-14
approved_by:
- '102000000000'
version_date:
  kaz: 2016-01-14
  rus: 2016-01-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/97537/kaz/14.01.2016
  rus: https://zan.gov.kz/client/#!/doc/97537/rus/14.01.2016
