act_code: '1755'
requisite: Распоряжение Акима Павлодарской области от 4 июня 1998 года № 1-43-р. Зарегистрировано Управлением юстиции Павлодарской области 7 июля 1998 года за № 50
title:
  rus: Об утверждении тарифов на медицинские услуги в системе обязательного медицинского страхования
  kaz: Міндетті медициналық сақтандыру жүйесіндегі дәрігерлік қызметтерге тарифтерді бекіту туралы
form: РАСП
type_codes:
- РАСП
approved_on: 1998-06-03
approved_by:
- '164000000003'
version_date:
  kaz: 1998-06-03
  rus: 1998-06-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/1755/kaz/03.06.1998
  rus: https://zan.gov.kz/client/#!/doc/1755/rus/03.06.1998
