act_code: '53717'
requisite: Закон Республики Казахстан от 30 июня 2010 года № 325-IV
title:
  rus: О ратификации Соглашения о некоторых вопросах предоставления обеспечения уплаты таможенных пошлин, налогов в отношении товаров, перевозимых в соответствии с таможенной процедурой таможенного транзита, особенностях взыскания таможенных пошлин, налогов и порядке перечисления взысканных сумм в отношении таких товаров
  kaz: Кедендік транзиттің кедендік рәсіміне сәйкес тасымалданатын тауарларға қатысты кедендік баждарды, салықтарды төлеуді қамтамасыз етуді ұсынудың кейбір мәселелері, кедендік баждарды, салықтарды өндіріп алудың ерекшеліктері және осындай тауарларға қатысты өндіріп алынған сомаларды аудару тәртібі туралы келісімді ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2010-06-30
approved_by:
- '102000000000'
version_date:
  kaz: 2010-06-30
  rus: 2010-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/53717/kaz/30.06.2010
  rus: https://zan.gov.kz/client/#!/doc/53717/rus/30.06.2010
