act_code: '156345'
requisite: Закон Республики Казахстан от 8 июня 2021 года № 47-VII ЗРК
title:
  rus: О закупках отдельных субъектов квазигосударственного сектора
  kaz: Квазимемлекеттік сектордың жекелеген субъектілерінің сатып алуы туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2021-06-08
approved_by:
- '102000000000'
version_date:
  kaz: 2024-07-01
  rus: 2024-07-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/156345/kaz/01.07.2024
  rus: https://zan.gov.kz/client/#!/doc/156345/rus/01.07.2024
caused_by:
  code: '198416'
  requisite: Закон Республики Казахстан от 1 июля 2024 года № 107-VIII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам закупок и исключения излишней законодательной регламентации
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне сатып алу және артық заңнамалық регламенттеуді болғызбау мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/198416/rus
