act_code: '6302'
requisite: Закон Республики Казахстан от 23 июня 2000 года № 62-II
title:
  rus: О ратификации Соглашения между Республикой Казахстан и Республикой Таджикистан о принципах взимания косвенных налогов при экспорте и импорте товаров (работ, услуг)
  kaz: Қазақстан Республикасы мен Тәжікстан Республикасының арасындағы тауарлардың (жұмыстардың, қызмет көрсетулердің) экспорты мен импорты кезінде жанама салықтар алудың принциптері туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2000-06-22
approved_by:
- '102000000000'
version_date:
  kaz: 2000-06-22
  rus: 2000-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/6302/kaz/22.06.2000
  rus: https://zan.gov.kz/client/#!/doc/6302/rus/22.06.2000
