act_code: '3320'
requisite: Указ Президента Республики Казахстан от 26 июня 1999 г. № 165
title:
  rus: О некоторых мерах по совершенствованию деятельности сил обеспечения национальной безопасности Республики Казахстан
  kaz: Қазақстан Республикасының ұлттық қауіпсіздігін қамтамасыз ету күштерінің қызметін жетілдіру жөніндегі кейбір шаралар туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 1999-06-25
approved_by:
- '101000000000'
version_date:
  kaz: 1999-06-25
  rus: 1999-06-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/3320/kaz/25.06.1999
  rus: https://zan.gov.kz/client/#!/doc/3320/rus/25.06.1999
