act_code: '170170'
requisite: Указ Президента Республики Казахстан от 28 июля 2022 года № 970
title:
  rus: О некоторых вопросах Агентства Республики Казахстан по противодействию коррупции (Антикоррупционной службы)
  kaz: Қазақстан Республикасы Сыбайлас жемқорлыққа қарсы іс-қимыл агенттігінің (Сыбайлас жемқорлыққа қарсы қызметтің) кейбір мәселелері туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2022-07-28
approved_by:
- '101000000000'
version_date:
  kaz: 2022-07-28
  rus: 2022-07-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/170170/kaz/28.07.2022
  rus: https://zan.gov.kz/client/#!/doc/170170/rus/28.07.2022
