act_code: '28852'
requisite: Закон Республики Казахстан от 7 июля 2006 года № 175
title:
  rus: Об особо охраняемых природных территориях
  kaz: Ерекше қорғалатын табиғи аумақтар туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2006-07-07
approved_by:
- '102000000000'
version_date:
  kaz: 2024-07-08
  rus: 2024-07-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/28852/kaz/08.07.2024
  rus: https://zan.gov.kz/client/#!/doc/28852/rus/08.07.2024
caused_by:
  code: '198638'
  requisite: Закон Республики Казахстан от 8 июля 2024 года № 118-VIII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам особо охраняемых природных территорий и электроэнергетики
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне ерекше қорғалатын табиғи аумақтар және электр энергетикасы мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/198638/rus
