act_code: '28852'
requisite: Закон Республики Казахстан от 7 июля 2006 года № 175
title:
  rus: Об особо охраняемых природных территориях
  kaz: Ерекше қорғалатын табиғи аумақтар туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2006-07-07
approved_by:
- '102000000000'
version_date:
  kaz: 2015-12-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/28852/kaz/04.12.2015
caused_by:
  code: '96095'
  requisite: Закон Республики Казахстан от 4 декабря 2015 года № 435-V ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам государственных закупок
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне мемлекеттік сатып алу мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/96095/rus
