act_code: '22310'
requisite: Закон Республики Казахстан от 22 декабря 2004 года № 17
title:
  rus: О присоединении Республики Казахстан к Конвенции о физической защите ядерного материала
  kaz: Қазақстан Республикасының Ядролық материалды физикалық қорғау туралы конвенцияға қосылуы туралы
form: КОНВ
type_codes:
- ЗАК
- КОНВ
approved_on: 2004-12-22
approved_by:
- '102000000000'
version_date:
  kaz: 2004-12-22
  rus: 2004-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/22310/kaz/22.12.2004
  rus: https://zan.gov.kz/client/#!/doc/22310/rus/22.12.2004
