act_code: '104314'
requisite: Закон Республики Казахстан от 21 декабря 1995 года N 2710
title:
  rus: Об органах национальной безопасности Республики Казахстан
  kaz: Қазақстан Республикасының ұлттық қауiпсiздiк органдары туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1995-12-21
approved_by:
- '101000000000'
version_date:
  kaz: 2015-11-23
  rus: 2015-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/104314/kaz/23.11.2015
  rus: https://zan.gov.kz/client/#!/doc/104314/rus/23.11.2015
caused_by:
  code: '95697'
  requisite: Закон Республики Казахстан от 23 ноября 2015 года № 417-V ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам государственной службы
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне мемлекеттік қызмет мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/95697/rus
