act_code: '104314'
requisite: Закон Республики Казахстан от 21 декабря 1995 года N 2710
title:
  rus: Об органах национальной безопасности Республики Казахстан
  kaz: Қазақстан Республикасының ұлттық қауiпсiздiк органдары туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1995-12-21
approved_by:
- '101000000000'
version_date:
  kaz: 2016-12-28
  rus: 2016-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/104314/kaz/28.12.2016
  rus: https://zan.gov.kz/client/#!/doc/104314/rus/28.12.2016
caused_by:
  code: '108537'
  requisite: Закон Республики Казахстан от 28 декабря 2016 года № 36-VІ ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам контрразведывательной деятельности
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне қарсы барлау қызметі мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/108537/rus
