act_code: '1481'
requisite: Закон Республики Казахстан от 9 ноября 1998 года № 290-I
title:
  rus: О ратификации Соглашения между Правительством Республики Казахстан и Правительством Республики Молдова о принципах взимания косвенных налогов при экспорте и импорте товаров (работ, услуг)
  kaz: Қазақстан Республикасының Үкіметі мен Молдова Республикасының Үкіметі арасындағы Тауарлардың (жұмыстардың, қызметтердің) экспорты мен импорты кезінде жанама салықтарды алудың принциптері туралы келісімді бекіту жөнінде
form: ДОГ
type_codes:
- ДОГ
- ЗАК
approved_on: 1998-11-09
approved_by:
- '102000000000'
version_date:
  kaz: 1998-11-09
  rus: 1998-11-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/1481/kaz/09.11.1998
  rus: https://zan.gov.kz/client/#!/doc/1481/rus/09.11.1998
