act_code: '20856'
requisite: Постановление Правительства Республики Казахстан от 10 августа 2004 года N 832
title:
  rus: Об утверждении Соглашения между Правительством Республики Казахстан и Правительством Китайской Народной Республики о сотрудничестве в области здоровья и карантина животных
  kaz: Қазақстан Республикасының Үкiметi мен Қытай Халық Республикасы Yкiметiнiң арасында Жануарлардың саулығы мен карантинi саласындағы ынтымақтастық туралы келiсiмдi бекiту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2004-08-09
approved_by:
- '103000000000'
version_date:
  kaz: 2004-08-09
  rus: 2004-08-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/20856/kaz/09.08.2004
  rus: https://zan.gov.kz/client/#!/doc/20856/rus/09.08.2004
