act_code: '12052'
requisite: Постановление Правительства Республики Казахстан от 8 мая 2002 года N 509
title:
  rus: Об утверждении Соглашения об информационном взаимодействии государств-членов Евразийского экономического сообщества по пограничным вопросам
  kaz: Еуразиялық экономикалық қауымдастыққа мүше мемлекеттердің Шекара мәселелері бойынша өзара ақпараттық іс-қимылы туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2002-05-07
approved_by:
- '103000000000'
version_date:
  kaz: 2002-05-07
  rus: 2002-05-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/12052/kaz/07.05.2002
  rus: https://zan.gov.kz/client/#!/doc/12052/rus/07.05.2002
