act_code: '6620'
requisite: Распоряжение акима Акмолинской области от 4 мая 2000 года № 1-250р. Зарегистрировано Управлением юстиции Акмолинской области 18 июля 2000 года за № 231. Утратило силу распоряжением акима Акмолинской области от 3 августа 2004 года № 40
title:
  rus: О порядке предоставления права недропользования на проведение разведки, добычи и совмещенной разведки и добычи по Акмолинской области на общераспространенные полезные ископаемые
  kaz: Кен қолданылатын қазба байлықтары алу жұмыстарын барлау, шығару және біріккен барлау мен шығаруды Ақмола облысы бойынша жүргізу құқығын беру тәртібі туралы
form: РАСП
type_codes:
- РАСП
approved_on: 2000-05-03
approved_by:
- '152000000003'
version_date:
  kaz: 2000-05-03
  rus: 2000-05-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/6620/kaz/03.05.2000
  rus: https://zan.gov.kz/client/#!/doc/6620/rus/03.05.2000
