act_code: '26131'
requisite: Закон Республики Казахстан от 13 декабря 2005 года № 95
title:
  rus: О ратификации Договора об основах взаимоотношений и сотрудничества между Республикой Казахстан и Переходным Исламским Государством Афганистан
  kaz: Қазақстан Республикасы мен Ауғанстан Өтпелі Ислам Мемлекеті арасындағы өзара қатынастар мен ынтымақтастықтың негіздері туралы шартты ратификациялау туралы
form: ДОГ
type_codes:
- ДОГ
- ЗАК
approved_on: 2005-12-13
approved_by:
- '102000000000'
version_date:
  kaz: 2005-12-13
  rus: 2005-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/26131/kaz/13.12.2005
  rus: https://zan.gov.kz/client/#!/doc/26131/rus/13.12.2005
