act_code: '2569'
requisite: Указ Президента Республики Казахстан от 23 мая 1997 года № 3528
title:
  rus: Об изменениях в административно-территориальном устройстве Алматинской, Восточно-Казахстанской, Карагандинской и Северо-Казахстанской областей
  kaz: Алматы, Шығыс Қазақстан, Қарағанды және Солтүстiк Қазақстан облыстарының әкiмшiлiк-аумақтық құрылысындағы өзгерiстер туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 1997-05-22
approved_by:
- '101000000000'
version_date:
  kaz: 1997-05-22
  rus: 1997-05-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/2569/kaz/22.05.1997
  rus: https://zan.gov.kz/client/#!/doc/2569/rus/22.05.1997
