act_code: '15028'
requisite: Закон Республики Казахстан от 8 апреля 2003 года № 404. Утратил силу Законом Республики Казахстан от 29 октября 2015 года № 372-V ЗРК
title:
  rus: О сельском потребительском кооперативе водопользователей
  kaz: Су пайдаланушылардың селолық тұтыну кооперативi туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2003-04-07
approved_by:
- '102000000000'
version_date:
  kaz: 2006-01-10
  rus: 2006-01-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/15028/kaz/10.01.2006
  rus: https://zan.gov.kz/client/#!/doc/15028/rus/10.01.2006
caused_by:
  code: '26395'
  requisite: Закон Республики Казахстан от 10 января 2006 года № 116
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам разграничения полномочий между уровнями государственного управления
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне мемлекеттік басқару деңгейлері арасындағы өкілеттіктердің аражігін ажырату мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/26395/rus
