act_code: '4507'
requisite: Приказ Генерального Прокурора Республики Казахстан от 29 сентября 1999 года N 83. Зарегистрирован в Министерстве юстиции Республики Казахстан 29.10.99г. за N 958. Утратил силу - приказом Генерального прокурора РК от 29.12.2000г. N 66
title:
  rus: Об утверждении Правил "О порядке представления и регистрации документов первичного учета проверок деятельности субъектов малого предпринимательства"
  kaz: '"Шағын кәсiпкерлiк субъектiлерiнiң қызметiн тексерудегi алғашқы есеп құжаттарын ұсыну және тiркеу тәртiбi туралы" Ережесiн бекiту туралы'
type_codes:
- ПРАВ
approved_on: 1999-09-28
approved_by:
- '107000000000'
version_date:
  rus: 1999-09-28
source:
  rus: https://zan.gov.kz/client/#!/doc/4507/rus/28.09.1999
