act_code: '45116'
requisite: Закон Республики Казахстан от 27 марта 2009 года № 145-IV
title:
  rus: О ратификации Дополнительного протокола к Женевским конвенциям от 12 августа 1949 года, касающегося принятия дополнительной отличительной эмблемы (Протокол III)
  kaz: Қосымша айырым эмблемасын қабылдауға қатысты 1949 жылғы 12 тамыздағы Женева конвенцияларына қосымша хаттаманы (ІII Хаттама) ратификациялау туралы
form: ПРОТ
type_codes:
- ЗАК
- ПРОТ
approved_on: 2009-03-27
approved_by:
- '102000000000'
version_date:
  kaz: 2009-03-27
  rus: 2009-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/45116/kaz/27.03.2009
  rus: https://zan.gov.kz/client/#!/doc/45116/rus/27.03.2009
