act_code: '15824'
requisite: Закон Республики Казахстан от 11 июня 2003 года N 435
title:
  rus: Об обязательном страховании гражданско-правовой ответственности частных нотариусов
  kaz: Жекеше нотариустардың азаматтық-құқықтық жауапкершiлiгiн мiндеттi сақтандыру туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2003-06-11
approved_by:
- '102000000000'
version_date:
  kaz: 2019-01-01
  rus: 2019-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/15824/kaz/01.01.2019
  rus: https://zan.gov.kz/client/#!/doc/15824/rus/01.01.2019
caused_by:
  code: '123091'
  requisite: Закон Республики Казахстан от 2 июля 2018 года № 166-VІ ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам страхования и страховой деятельности, рынка ценных бумаг
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне сақтандыру және сақтандыру қызметі, бағалы қағаздар нарығы мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123091/rus
