act_code: '3'
requisite: Закон Республики Казахстан от 20 июля 1995 г. N 2368. Утратил силу с 1 мая 2003 г. - Таможенным кодексом РК от 5 апреля 2003 г. N 401
title:
  rus: О таможенном деле в Республике Казахстан
  kaz: Қазақстан Республикасындағы кеден iсi туралы Қазақстан Республикасының Заңы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1995-07-19
approved_by:
- '101000000000'
version_date:
  kaz: 2001-07-04
  rus: 2001-07-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/3/kaz/04.07.2001
  rus: https://zan.gov.kz/client/#!/doc/3/rus/04.07.2001
caused_by:
  code: '9393'
  requisite: Закон Республики Казахстан от 5 июля 2001 года № 223-II
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам специальной экономической зоны "Астана — новый город"
    kaz: Қазақстан Республикасының кейбір заң актілеріне "Астана - жаңа қала" арнайы экономикалық аймағы мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/9393/rus
