act_code: '3'
requisite: Закон Республики Казахстан от 20 июля 1995 г. N 2368. Утратил силу с 1 мая 2003 г. - Таможенным кодексом РК от 5 апреля 2003 г. N 401
title:
  rus: О таможенном деле в Республике Казахстан
  kaz: Қазақстан Республикасындағы кеден iсi туралы Қазақстан Республикасының Заңы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1995-07-19
approved_by:
- '101000000000'
version_date:
  kaz: 2002-03-21
  rus: 2002-03-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/3/kaz/21.03.2002
  rus: https://zan.gov.kz/client/#!/doc/3/rus/21.03.2002
caused_by:
  code: '11624'
  requisite: Закон Республики Казахстан от 21 марта 2002 года № 311.
  title:
    rus: О внесении изменений в Закон Республики Казахстан "О таможенном деле в Республике Казахстан"
    kaz: '"Қазақстан Республикасындағы кеден ісі туралы" Қазақстан Республикасының Заңына өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/11624/rus
