act_code: '117131'
requisite: Кодекс Республики Казахстан от 27 декабря 2017 года № 125-VI
title:
  rus: О недрах и недропользовании
  kaz: Жер қойнауы және жер қойнауын пайдалану туралы
form: КОД
type_codes:
- КОД
approved_on: 2017-12-27
approved_by:
- '102000000000'
version_date:
  kaz: 2026-03-02
  rus: 2026-03-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/117131/kaz/02.03.2026
  rus: https://zan.gov.kz/client/#!/doc/117131/rus/02.03.2026
caused_by:
  code: '220254'
  requisite: Закон Республики Казахстан от 30 декабря 2025 года № 249-VIII ЗРК
  title:
    rus: О внесении изменений и дополнений в Кодекс Республики Казахстан «О недрах и недропользовании» по реализации поручений Главы государства
    kaz: «Жер қойнауы және жер қойнауын пайдалану туралы» Қазақстан Республикасының Кодексіне Мемлекет басшысының тапсырмаларын іске асыру бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/220254/rus
