act_code: '33970'
requisite: Указ Президента Республики Казахстан от 5 июля 2007 года № 364
title:
  rus: Об утверждении общевоинских уставов Вооруженных Сил, других войск и воинских формирований Республики Казахстан
  kaz: Қазақстан Республикасы Қарулы Күштерінің, басқа да әскерлері мен әскери құралымдарының жалпыәскери жарғыларын бекіту туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2007-07-05
approved_by:
- '101000000000'
version_date:
  kaz: 2019-06-13
  rus: 2019-06-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/33970/kaz/13.06.2019
  rus: https://zan.gov.kz/client/#!/doc/33970/rus/13.06.2019
caused_by:
  code: '132541'
  requisite: Указ Президента Республики Казахстан от 13 июня 2019 года № 13
  title:
    rus: О внесении изменений и дополнений в некоторые акты Президента Республики Казахстан
    kaz: Қазақстан Республикасы Президентінің кейбір актілеріне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132541/rus
