act_code: '33970'
requisite: Указ Президента Республики Казахстан от 5 июля 2007 года № 364
title:
  rus: Об утверждении общевоинских уставов Вооруженных Сил, других войск и воинских формирований Республики Казахстан
  kaz: Қазақстан Республикасы Қарулы Күштерінің, басқа да әскерлері мен әскери құралымдарының жалпыәскери жарғыларын бекіту туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2007-07-05
approved_by:
- '101000000000'
version_date:
  kaz: 2022-11-12
  rus: 2022-11-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/33970/kaz/12.11.2022
  rus: https://zan.gov.kz/client/#!/doc/33970/rus/12.11.2022
caused_by:
  code: '173711'
  requisite: Указ Президента Республики Казахстан от 12 ноября 2022 года № 1071
  title:
    rus: О внесении изменений и дополнений в Указ Президента Республики Казахстан от 5 июля 2007 года № 364 «Об утверждении общевоинских уставов Вооруженных Сил, других войск и воинских формирований Республики Казахстан»
    kaz: «Қазақстан Республикасы Қарулы Күштерінің, басқа да әскерлері мен әскери құралымдарының жалпыәскери жарғыларын бекіту туралы» Қазақстан Республикасы Президентінің 2007 жылғы 5 шілдедегі № 364 Жарлығына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/173711/rus
