act_code: '182381'
requisite: Постановление Правительства Республики Казахстан от 31 мая 2023 года № 433
title:
  rus: Об утверждении Соглашения между Правительством Республики Казахстан и Правительством Белиза об освобождении от визовых требований для владельцев дипломатических, служебных и официальных паспортов
  kaz: Қазақстан Республикасының Үкіметі мен Белиз Үкіметі арасындағы дипломатиялық, қызметтік және ресми паспорттардың иелерін визалық талаптардан босату туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2023-05-31
approved_by:
- '103000000000'
version_date:
  kaz: 2023-05-31
  rus: 2023-05-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/182381/kaz/31.05.2023
  rus: https://zan.gov.kz/client/#!/doc/182381/rus/31.05.2023
