act_code: '3978'
requisite: Закон Республики Казахстан от 16 июля 1999 года № 441-1. Утратил силу Законом Республики Казахстан 8 июня 2015 года № 316-V
title:
  rus: О субсидиях и компенсационных мерах
  kaz: Субсидиялар және өтем шаралары туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1999-07-15
approved_by:
- '102000000000'
version_date:
  kaz: 1999-07-15
  rus: 1999-07-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/3978/kaz/15.07.1999
  rus: https://zan.gov.kz/client/#!/doc/3978/rus/15.07.1999
