act_code: '4388'
requisite: Постановление Правления Национального Банка Республики Казахстан от 25 июля 1997 г. N 289. Зарегистрировано в Министерстве юстиции 12 сентября 1997 г. N 368. Утратило силу - постановлением Правления Национального Банка РК от 20 апреля 2001г. N 114
title:
  rus: О Положении "Об основных требованиях к проведению инспектирования (проверки) банков второго уровня и оформлению его результатов"
  kaz: Екiншi деңгейдегi банктерге инспекция (тексеру) жүргiзуге және оның нәтижелерiн ресiмдеуге қойылатын негiзгi талаптар туралы ЕРЕЖЕ
type_codes:
- ПОЛ
approved_on: 1997-07-24
approved_by:
- '117000000000'
version_date:
  rus: 1997-07-24
source:
  rus: https://zan.gov.kz/client/#!/doc/4388/rus/24.07.1997
