act_code: '104124'
requisite: Закон Республики Казахстан от 6 марта 1997 года № 82. Утратил силу Законом Республики Казахстан от 7 июля 2004 года № 576
title:
  rus: ОБ ИНВЕСТИЦИОННЫХ ФОНДАХ В РЕСПУБЛИКЕ КАЗАХСТАН
  kaz: Қазақстан Республикасындағы инвестициялық қорлар туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1997-03-06
approved_by:
- '102000000000'
version_date:
  rus: 1997-07-10
source:
  rus: https://zan.gov.kz/client/#!/doc/104124/rus/10.07.1997
caused_by:
  code: '104459'
  requisite: Закон Республики Казахстан от 11 июля 1997 года N 154
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам банковской деятельности
    kaz: Қазақстан Республикасының банк қызметi мәселелерi жөнiндегi кейбiр заң актiлерiне өзгерiстер мен толықтырулар енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/104459/rus
