act_code: '2027'
requisite: Указ Президента Республики Казахстан от 22 января 1999 года № 30. Утратил силу Указом Президента Республики Казахстан от 30 июля 2012 года № 360
title:
  rus: Об определении организационной структуры и общей штатной численности военнослужащих, рабочих и служащих Республиканской гвардии
  kaz: Республикалық ұланның ұйымдық құрылымын және әскери қызметшілерінің, жұмысшылары мен қызметшілерінің жалпы штат санын айқындау туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 1999-01-22
approved_by:
- '101000000000'
version_date:
  rus: 2004-08-27
source:
  rus: https://zan.gov.kz/client/#!/doc/2027/rus/27.08.2004
caused_by:
  code: '21090'
  requisite: Указ Президента Республики Казахстан от 28 августа 2004 года N 1428. Утратил силу Указом Президента Республики Казахстан от 4 мая 2014 года № 814
  title:
    rus: Об утверждении Положения о Республиканской гвардии Республики Казахстан
    kaz: Қазақстан Республикасының Республикалық ұланы туралы Ереженi бекiту туралы
  link: https://zan.gov.kz/client/#!/doc/21090/rus
