act_code: '844'
requisite: Закон Республики Казахстан от 26 июня 1998 года № 233. Утратил силу Законом Республики Казахстан от 6 января 2012 года № 527-IV
title:
  rus: О национальной безопасности Республики Казахстан
  kaz: Қазақстан Республикасының Ұлттық қауiпсiздiгi туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1998-06-25
approved_by:
- '102000000000'
version_date:
  kaz: 2000-04-27
  rus: 2000-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/844/kaz/27.04.2000
  rus: https://zan.gov.kz/client/#!/doc/844/rus/27.04.2000
caused_by:
  code: '5873'
  requisite: Закон Республики Казахстан от 28 апреля 2000 года N 45
  title:
    rus: О внесении изменений в Закон Республики Казахстан "О национальной безопасности Республики Казахстан"
    kaz: '"Қазақстан Республикасының ұлттық қауіпсіздігі туралы" Қазақстан Республикасының Заңына өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/5873/rus
