act_code: '55498'
requisite: Закон Республики Казахстан от 8 ноября 2010 года № 347-IV
title:
  rus: О ратификации Международной конвенции по борьбе с подделкой денежных знаков и Протокола к ней
  kaz: Ақша белгілерін қолдан жасауға қарсы күрес жөніндегі халықаралық конвенцияны және оған Хаттаманы ратификациялау туралы
form: КОНВ
type_codes:
- ЗАК
- КОНВ
- ПРОТ
approved_on: 2010-11-08
approved_by:
- '102000000000'
version_date:
  kaz: 2010-11-08
  rus: 2010-11-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/55498/kaz/08.11.2010
  rus: https://zan.gov.kz/client/#!/doc/55498/rus/08.11.2010
