act_code: '176676'
requisite: Закон Республики Казахстан от 30 декабря 2022 года № 178-VII ЗРК
title:
  rus: О восстановлении платежеспособности и банкротстве граждан Республики Казахстан
  kaz: Қазақстан Республикасы азаматтарының төлем қабілеттілігін қалпына келтіру және банкроттығы туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2022-12-30
approved_by:
- '102000000000'
version_date:
  kaz: 2022-12-30
  rus: 2022-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/176676/kaz/30.12.2022
  rus: https://zan.gov.kz/client/#!/doc/176676/rus/30.12.2022
