act_code: '62568'
requisite: Кодекс Республики Казахстан от 26 декабря 2011 года № 518-IV
title:
  rus: О браке (супружестве) и семье
  kaz: Неке (ерлі-зайыптылық) және отбасы туралы
form: КОД
type_codes:
- КОД
approved_on: 2011-12-26
approved_by:
- '102000000000'
version_date:
  kaz: 2023-03-27
  rus: 2023-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/62568/kaz/27.03.2023
  rus: https://zan.gov.kz/client/#!/doc/62568/rus/27.03.2023
caused_by:
  code: '179249'
  requisite: Закон Республики Казахстан от 27 марта 2023 года № 216-VII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам совершенствования процессуального законодательства и реформирования судебной системы
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне процестік заңнаманы жетілдіру және сот жүйесін реформалау мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/179249/rus
