act_code: '148898'
requisite: Закон Республики Казахстан от 23 ноября 2020 года № 377-VІ ЗРК
title:
  rus: О ратификации Протокола об охране промышленных образцов к Евразийской патентной конвенции от 9 сентября 1994 года
  kaz: 1994 жылғы 9 қыркүйектегі Еуразиялық патент конвенциясына Өнеркәсіптік үлгілерді қорғау туралы хаттаманы ратификациялау туралы
form: ПРОТ
type_codes:
- ЗАК
- ПРОТ
approved_on: 2020-11-23
approved_by:
- '102000000000'
version_date:
  kaz: 2020-11-23
  rus: 2020-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/148898/kaz/23.11.2020
  rus: https://zan.gov.kz/client/#!/doc/148898/rus/23.11.2020
