act_code: '85731'
requisite: Закон Республики Казахстан от 10 января 2015 года № 274-V ЗРК
title:
  rus: О Национальной гвардии Республики Казахстан
  kaz: Қазақстан Республикасының Ұлттық ұланы туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2015-01-10
approved_by:
- '102000000000'
version_date:
  kaz: 2023-05-20
  rus: 2023-05-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/85731/kaz/20.05.2023
  rus: https://zan.gov.kz/client/#!/doc/85731/rus/20.05.2023
caused_by:
  code: '179174'
  requisite: Закон Республики Казахстан от 17 марта 2023 года № 212-VII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам прав человека в сфере уголовного судопроизводства, исполнения наказания, а также предупреждения пыток и других жестоких, бесчеловечных или унижающих достоинство видов обращения
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне қылмыстық сот ісін жүргізу саласындағы адам құқықтары, жазаны орындау, сондай-ақ азаптау мен басқа да қатыгез, адамгершілікке жатпайтын немесе қадір-қасиетті қорлайтын қарым-қатынас түрлерінің алдын алу мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/179174/rus
