act_code: '60862'
requisite: Указ Президента Республики Казахстан от 30 сентября 2011 года № 155
title:
  rus: О вопросах государственных символов и геральдики ведомственных и иных, приравненных к ним, наград некоторых государственных органов, непосредственно подчиненных и подотчетных Президенту Республики Казахстан, Конституционного Суда Республики Казахстан, правоохранительных органов, судов, Вооруженных Сил, других войск и воинских формирований
  kaz: Мемлекеттік рәміздер және Қазақстан Республикасының Президентіне тікелей бағынатын және есеп беретін кейбір мемлекеттік органдардың, Қазақстан Республикасы Конституциялық Сотының, құқық қорғау органдарының, соттардың, Қарулы Күштердің, басқа да әскерлер мен әскери құралымдардың ведомстволық және оларға теңестірілген өзге де наградаларының геральдикасы мәселелері туралы
form: УКАЗ
type_codes:
- ПОЛ
- ПРАВ
- ПРЧ
- УКАЗ
approved_on: 2011-09-30
approved_by:
- '101000000000'
version_date:
  kaz: 2021-05-31
  rus: 2021-05-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/60862/kaz/31.05.2021
  rus: https://zan.gov.kz/client/#!/doc/60862/rus/31.05.2021
caused_by:
  code: '156341'
  requisite: Указ Президента Республики Казахстан от 31 мая 2021 года № 583
  title:
    rus: О внесении изменений и дополнений в Указ Президента Республики Казахстан от 30 сентября 2011 года № 155 «О вопросах государственных символов и геральдики ведомственных и иных, приравненных к ним, наград некоторых государственных органов, непосредственно подчиненных и подотчетных Президенту Республики Казахстан, Конституционного Совета Республики Казахстан, правоохранительных органов, судов, Вооруженных Сил, других войск и воинских формирований»
    kaz: «Мемлекеттік рәміздер және Қазақстан Республикасының Президентіне тікелей бағынатын және есеп беретін кейбір мемлекеттік органдардың, Қазақстан Республикасы Конституциялық Кеңесінің, құқық қорғау органдарының, соттардың, Қарулы Күштердің, басқа да әскерлер мен әскери құралымдардың ведомстволық және оларға теңестірілген өзге де наградаларының геральдикасы мәселелері туралы» Қазақстан Республикасы Президентінің 2011 жылғы 30 қыркүйектегі № 155 Жарлығына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/156341/rus
