act_code: '60862'
requisite: Указ Президента Республики Казахстан от 30 сентября 2011 года № 155
title:
  rus: О вопросах государственных символов и геральдики ведомственных и иных, приравненных к ним, наград некоторых государственных органов, непосредственно подчиненных и подотчетных Президенту Республики Казахстан, Конституционного Суда Республики Казахстан, правоохранительных органов, судов, Вооруженных Сил, других войск и воинских формирований
  kaz: Мемлекеттік рәміздер және Қазақстан Республикасының Президентіне тікелей бағынатын және есеп беретін кейбір мемлекеттік органдардың, Қазақстан Республикасы Конституциялық Сотының, құқық қорғау органдарының, соттардың, Қарулы Күштердің, басқа да әскерлер мен әскери құралымдардың ведомстволық және оларға теңестірілген өзге де наградаларының геральдикасы мәселелері туралы
form: УКАЗ
type_codes:
- ПОЛ
- ПРАВ
- ПРЧ
- УКАЗ
approved_on: 2011-09-30
approved_by:
- '101000000000'
version_date:
  kaz: 2023-01-19
  rus: 2023-01-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/60862/kaz/19.01.2023
  rus: https://zan.gov.kz/client/#!/doc/60862/rus/19.01.2023
caused_by:
  code: '178118'
  requisite: Указ Президента Республики Казахстан от 19 января 2023 года № 106
  title:
    rus: О некоторых вопросах Судебной администрации Республики Казахстан
    kaz: Қазақстан Республикасы Сот әкімшілігінің кейбір мәселелері туралы
  link: https://zan.gov.kz/client/#!/doc/178118/rus
