act_code: '52383'
requisite: Закон Республики Казахстан от 29 апреля 2010 года № 271-IV. Утратил силу Законом Республики Казахстан от 30 декабря 2025 года № 245-VIII (вводится в действие по истечении шестидесяти календарных дней после дня его первого официального опубликования)
title:
  rus: О профилактике правонарушений
  kaz: Құқық бұзушылық профилактикасы туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2010-04-29
approved_by:
- '102000000000'
version_date:
  kaz: 2010-04-29
  rus: 2010-04-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/52383/kaz/29.04.2010
  rus: https://zan.gov.kz/client/#!/doc/52383/rus/29.04.2010
