act_code: '5996'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 4 апреля 2000 г. N 97. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 апреля 2000 г. N 1124. Утратил силу приказом Министра сельского хозяйства Республики Казахстан от 20 июня 2008 года N 385
title:
  rus: Об утверждении Правил лицензирования деятельности по хранению зерна на хлебоприемных предприятиях
  kaz: Астық қабылдау кәсiпорындарында астықты сақтау жөнiндегi қызметтi лицензиялаудың Ережелерiн бекiту туралы
type_codes:
- ПРАВ
approved_on: 2000-04-03
approved_by:
- '103012000000'
version_date:
  rus: 2000-06-20
source:
  rus: https://zan.gov.kz/client/#!/doc/5996/rus/20.06.2000
caused_by:
  code: '6514'
  requisite: Приказ Министра сельского хозяйства Республики Казахстан от 21 июня 2000 года N 167. Зарегистрирован в Министерстве юстиции Республики Казахстан 21.07.2000 г. за N 1200. Утратил силу приказом Министра сельского хозяйства Республики Казахстан от 20 июня 2008 года N 385
  title:
    rus: О внесении изменения в приказ Министра сельского хозяйства Республики Казахстан от 4.04.2000 г. N 97
    kaz: Қазақстан Республикасы Ауыл шаруашылығы Министрінің 4.04.2000 ж. N 97 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/6514/rus
