act_code: '30465'
requisite: Закон Республики Казахстан от 25 ноября 2006 года № 189
title:
  rus: О гарантированном трансферте из Национального фонда Республики Казахстан на 2007-2009 годы
  kaz: Қазақстан Республикасының Ұлттық қорынан 2007-2009 жылдарға арналған кепілдендірілген трансферт туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2006-11-25
approved_by:
- '102000000000'
version_date:
  kaz: 2008-12-04
  rus: 2008-12-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/30465/kaz/04.12.2008
  rus: https://zan.gov.kz/client/#!/doc/30465/rus/04.12.2008
caused_by:
  code: '42654'
  requisite: Закон Республики Казахстан от 4 декабря 2008 года № 98-IV
  title:
    rus: О внесении изменения в Закон Республики Казахстан "О гарантированном трансферте из Национального фонда Республики Казахстан на 2007-2009 годы"
    kaz: '"Қазақстан Республикасының Ұлттық қорынан 2007-2009 жылдарға арналған кепілдендірілген трансферт туралы" Қазақстан Республикасының Заңына өзгеріс енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/42654/rus
