act_code: '34301'
requisite: Закон Республики Казахстан от 21 июля 2007 года N 291
title:
  rus: О ратификации Соглашения между Правительством Республики Казахстан и Правительством Соединенного Королевства Великобритании и Северной Ирландии по международным автомобильным перевозкам
  kaz: Қазақстан Республикасының Үкіметі мен Ұлыбритания және Солтүстік Ирландия Құрама Корольдігінің Үкіметі арасындағы Халықаралық автомобиль тасымалдары туралы келісімді ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2007-07-21
approved_by:
- '102000000000'
version_date:
  kaz: 2007-07-21
  rus: 2007-07-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/34301/kaz/21.07.2007
  rus: https://zan.gov.kz/client/#!/doc/34301/rus/21.07.2007
