act_code: '2089'
requisite: Приказ Министерства финансов Республики Казахстан от 30 декабря 1994 г. N 329. Утратил силу - приказом Минфина РК от 15.05.98г. N 217 ~V980517
title:
  rus: Об утверждении инструкции об объеме и формах годовой, квартальной и месячной бухгалтерской отчетности учреждений и организаций, состоящих на бюджете
  kaz: Бюджетте тұрған мекемелер мен ұйымдардың жылдық, тоқсандық және айлық бухгалтерлiк есептемесiнiң көлемi мен нысандары туралы НҰСҚАУЛЫҚ
type_codes:
- ИНСТ
approved_on: 1994-12-30
approved_by:
- '103002000000'
version_date:
  rus: 1994-12-30
source:
  rus: https://zan.gov.kz/client/#!/doc/2089/rus/30.12.1994
