act_code: '156531'
requisite: Закон Республики Казахстан от 18 июня 2021 года № 51-VII ЗРК
title:
  rus: О ратификации Соглашения между Правительством Республики Казахстан и Правительством Азербайджанской Республики о сотрудничестве в области миграции
  kaz: Қазақстан Республикасының Үкіметі мен Әзербайжан Республикасының Үкіметі арасындағы көші-қон саласындағы ынтымақтастық туралы келісімді ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2021-06-18
approved_by:
- '102000000000'
version_date:
  kaz: 2021-06-18
  rus: 2021-06-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/156531/kaz/18.06.2021
  rus: https://zan.gov.kz/client/#!/doc/156531/rus/18.06.2021
