act_code: '81097'
requisite: Кодекс Республики Казахстан от 3 июля 2014 года № 226-V ЗРК
title:
  rus: Уголовный кодекс Республики Казахстан
  kaz: Қазақстан Республикасының Қылмыстық кодексi
form: КОД
type_codes:
- КОД
approved_on: 2014-07-03
approved_by:
- '102000000000'
version_date:
  kaz: 2022-01-01
  rus: 2022-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/81097/kaz/01.01.2022
  rus: https://zan.gov.kz/client/#!/doc/81097/rus/01.01.2022
caused_by:
  code: '162429'
  requisite: Закон Республики Казахстан от 27 декабря 2021 года № 88-VII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам внедрения трехзвенной модели с разграничением полномочий и зон ответственности между правоохранительными органами, прокуратурой и судом
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне құқық қорғау органдары, прокуратура және сот арасында өкілеттіктердің және жауапкершілік аясының аражігін ажырата отырып, үш буынды модельді ендіру мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/162429/rus
