act_code: '81097'
requisite: Кодекс Республики Казахстан от 3 июля 2014 года № 226-V ЗРК
title:
  rus: Уголовный кодекс Республики Казахстан
  kaz: Қазақстан Республикасының Қылмыстық кодексi
form: КОД
type_codes:
- КОД
approved_on: 2014-07-03
approved_by:
- '102000000000'
version_date:
  kaz: 2026-07-01
  rus: 2026-07-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/81097/kaz/01.07.2026
  rus: https://zan.gov.kz/client/#!/doc/81097/rus/01.07.2026
caused_by:
  code: '227197'
  requisite: Закон Республики Казахстан от 1 июля 2026 года № 331-VIII ЗРК
  title:
    rus: О внесении изменений и дополнений в Уголовный кодекс Республики Казахстан, Уголовно-процессуальный кодекс Республики Казахстан и Кодекс Республики Казахстан об административных правонарушениях
    kaz: Қазақстан Республикасының Қылмыстық кодексіне, Қазақстан Республикасының Қылмыстық-процестік кодексіне және Қазақстан Республикасының Әкімшілік құқық бұзушылық туралы кодексіне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/227197/rus
