act_code: '180092'
requisite: Нормативное постановление Конституционного Суда Республики Казахстан от 21 апреля 2023 года № 10
title:
  rus: О рассмотрении на соответствие Конституции Республики Казахстан пункта 4 статьи 44, пункта 3 статьи 44-1 Конституционного закона Республики Казахстан от 25 декабря 2000 года «О судебной системе и статусе судей Республики Казахстан» и пункта 1 статьи 24 Закона Республики Казахстан от 4 декабря 2015 года «О Высшем Судебном Совете Республики Казахстан»
  kaz: «Қазақстан Республикасының сот жүйесі мен судьяларының мәртебесі туралы» 2000 жылғы 25 желтоқсандағы Қазақстан Республикасы Конституциялық заңының 44-бабы 4-тармағының, 44-1-бабы 3-тармағының және «Қазақстан Республикасының Жоғары Сот Кеңесі туралы» 2015 жылғы 4 желтоқсандағы Қазақстан Республикасы Заңының 24-бабы 1-тармағының Қазақстан Республикасының Конституциясына сәйкестігін қарау туралы
form: НПОС
type_codes:
- НПОС
approved_on: 2023-04-21
approved_by:
- '106000000000'
version_date:
  kaz: 2023-04-21
  rus: 2023-04-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/180092/kaz/21.04.2023
  rus: https://zan.gov.kz/client/#!/doc/180092/rus/21.04.2023
