act_code: '16111'
requisite: Закон Республики Казахстан от 1 июля 2003 года № 446
title:
  rus: Об обязательном страховании гражданско-правовой ответственности владельцев транспортных средств
  kaz: Көлік құралдары иелерінің азаматтық-құқықтық жауапкершілігін міндетті сақтандыру туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2003-07-01
approved_by:
- '102000000000'
version_date:
  kaz: 2019-04-02
  rus: 2019-04-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/16111/kaz/02.04.2019
  rus: https://zan.gov.kz/client/#!/doc/16111/rus/02.04.2019
caused_by:
  code: '129990'
  requisite: Закон Республики Казахстан от 2 апреля 2019 года № 241-VІ ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам развития бизнес-среды и регулирования торговой деятельности
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне бизнес-ортаны дамыту және сауда қызметін реттеу мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/129990/rus
