act_code: '16111'
requisite: Закон Республики Казахстан от 1 июля 2003 года № 446
title:
  rus: Об обязательном страховании гражданско-правовой ответственности владельцев транспортных средств
  kaz: Көлік құралдары иелерінің азаматтық-құқықтық жауапкершілігін міндетті сақтандыру туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2003-07-01
approved_by:
- '102000000000'
version_date:
  kaz: 2018-07-02
  rus: 2018-07-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/16111/kaz/02.07.2018
  rus: https://zan.gov.kz/client/#!/doc/16111/rus/02.07.2018
caused_by:
  code: '123091'
  requisite: Закон Республики Казахстан от 2 июля 2018 года № 166-VІ ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам страхования и страховой деятельности, рынка ценных бумаг
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне сақтандыру және сақтандыру қызметі, бағалы қағаздар нарығы мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123091/rus
