act_code: '51122'
requisite: Постановление Правительства Республики Казахстан от 10 марта 2010 года № 188
title:
  rus: Об утверждении Соглашения между Правительством Республики Казахстан и Правительством Азербайджанской Республики о взаимных безвизовых поездках граждан
  kaz: Қазақстан Республикасының Үкіметі мен Әзірбайжан Республикасының Үкіметі арасындағы Азаматтардың өзара визасыз жол жүрулері туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2010-03-10
approved_by:
- '103000000000'
version_date:
  kaz: 2021-07-01
  rus: 2021-07-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/51122/kaz/01.07.2021
  rus: https://zan.gov.kz/client/#!/doc/51122/rus/01.07.2021
caused_by:
  code: '156686'
  requisite: Постановление Правительства Республики Казахстан от 1 июля 2021 года № 456
  title:
    rus: Об утверждении Протокола о внесении изменений в Соглашение между Правительством Республики Казахстан и Правительством Азербайджанской Республики о взаимных безвизовых поездках граждан от 2 октября 2009 года
    kaz: 2009 жылғы 2 қазандағы Қазақстан Республикасының Үкіметі мен Әзербайжан Республикасының Үкіметі арасындағы Азаматтардың өзара визасыз жол жүрулері туралы келісімге өзгерістер енгізу туралы хаттаманы бекіту туралы
  link: https://zan.gov.kz/client/#!/doc/156686/rus
