act_code: '14085'
requisite: Закон Республики Казахстан от 8 января 2003 года № 373. Утратил силу Кодексом Республики Казахстан от 29 октября 2015 года № 375-V
title:
  rus: Об инвестициях
  kaz: Инвестициялар туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2003-01-08
approved_by:
- '102000000000'
version_date:
  kaz: 2005-05-04
  rus: 2005-05-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/14085/kaz/04.05.2005
  rus: https://zan.gov.kz/client/#!/doc/14085/rus/04.05.2005
caused_by:
  code: '23897'
  requisite: Закон Республики Казахстан от 4 мая 2005 года № 48
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам инвестиций
    kaz: Қазақстан Республикасының кейбiр заңнамалық актiлерiне инвестициялар мәселелерi бойынша өзгерiстер мен толықтырулар енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/23897/rus
