act_code: '11131'
requisite: Закон Республики Казахстан от 15 января 2002 года № 282
title:
  rus: О ратификации Соглашения между Правительством Республики Казахстан и Правительством Республики Узбекистан об условиях взаимных поездок граждан
  kaz: Қазақстан Республикасының Үкіметі мен Өзбекстан Республикасының Үкіметі арасындағы Азаматтардың өзара сапарларының шарттары туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2002-01-15
approved_by:
- '102000000000'
version_date:
  kaz: 2015-01-28
  rus: 2015-01-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/11131/kaz/28.01.2015
  rus: https://zan.gov.kz/client/#!/doc/11131/rus/28.01.2015
caused_by:
  code: '86207'
  requisite: Закон Республики Казахстан от 28 января 2015 года № 281-V ЗРК
  title:
    rus: О ратификации Протокола о внесении изменений и дополнений в Соглашение между Правительством Республики Казахстан и Правительством Республики Узбекистан об условиях взаимных поездок граждан от 7 июля 2000 года
    kaz: 2000 жылғы 7 шілдедегі Қазақстан Республикасының Үкіметі мен Өзбекстан Республикасының Үкіметі арасындағы Азаматтардың өзара сапарларының шарттары туралы келісімге өзгерістер мен толықтырулар енгізу туралы хаттаманы ратификациялау туралы
  link: https://zan.gov.kz/client/#!/doc/86207/rus
