act_code: '20571'
requisite: Закон Республики Казахстан от 9 июля 2004 года N 591. Утратил силу Законом Республики Казахстан от 30 декабря 2025 года № 245-VIII (вводится в действие по истечении шестидесяти календарных дней после дня его первого официального опубликования)
title:
  rus: О профилактике правонарушений среди несовершеннолетних и предупреждении детской безнадзорности и беспризорности
  kaz: Кәмелетке толмағандар арасындағы құқық бұзушылықтардың профилактикасы мен балалардың қадағалаусыз және панасыз қалуының алдын алу туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2004-07-09
approved_by:
- '102000000000'
version_date:
  kaz: 2007-07-27
  rus: 2007-07-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/20571/kaz/27.07.2007
  rus: https://zan.gov.kz/client/#!/doc/20571/rus/27.07.2007
caused_by:
  code: '34626'
  requisite: Закон Республики Казахстан от 27 июля 2007 года № 320-III
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам образования
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне білім беру мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/34626/rus
