act_code: '29314'
requisite: Постановление Правительства Республики Казахстан от 15 августа 2006 года № 771
title:
  rus: Об утверждении Соглашения государств - участников Содружества Независимых Государств о сотрудничестве в сфере работы с молодежью
  kaz: Тәуелсiз Мемлекеттер Достастығына қатысушы мемлекеттердiң жастармен жұмыс саласындағы ынтымақтастығы туралы келiсiмдi бекiту туралы
form: СОГЛ
type_codes:
- ПОЛ
- ПОСТ
- СОГЛ
approved_on: 2006-08-15
approved_by:
- '103000000000'
version_date:
  kaz: 2006-08-15
  rus: 2006-08-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/29314/kaz/15.08.2006
  rus: https://zan.gov.kz/client/#!/doc/29314/rus/15.08.2006
