act_code: '106248'
requisite: Постановление Правительства Республики Казахстан от 10 апреля 2015 года № 212
title:
  rus: Об утверждении Соглашения по профилактике и тушению природных пожаров на приграничных территориях государств-участников Содружества Независимых Государств
  kaz: Тәуелсіз Мемлекеттер Достастығына қатысушы мемлекеттердің шекара маңындағы аумақтарында табиғи өрттердің профилактикасы және оларды сөндіру жөніндегі келісімді бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2015-04-10
approved_by:
- '103000000000'
version_date:
  kaz: 2019-05-03
  rus: 2019-05-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/106248/kaz/03.05.2019
  rus: https://zan.gov.kz/client/#!/doc/106248/rus/03.05.2019
caused_by:
  code: '131075'
  requisite: Постановление Правительства Республики Казахстан от 3 мая 2019 года № 247
  title:
    rus: О внесении дополнений в постановление Правительства Республики Казахстан от 10 апреля 2015 года № 212 «Об утверждении Соглашения по профилактике и тушению природных пожаров на приграничных территориях государств-участников Содружества Независимых Государств»
    kaz: «Тәуелсіз Мемлекеттер Достастығына қатысушы мемлекеттердің шекара маңындағы аумақтарында табиғи өрттердің профилактикасы және оларды сөндіру жөніндегі келісімді бекіту туралы» Қазақстан Республикасы Үкіметінің 2015 жылғы 10 сәуірдегі № 212 қаулысына толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/131075/rus
