act_code: '12656'
requisite: Постановление Правительства Республики Казахстан от 15 июля 2002 года N 778
title:
  rus: Об утверждении Соглашения между Правительством Республики Казахстан и Правительством Туркменистана о сотрудничестве и взаимопомощи в таможенных делах
  kaz: Қазақстан Республикасының Yкiметi мен Түрікменстан Yкiметiнiң арасындағы кеден iстерiндегi ынтымақтастық пен өзара көмек туралы келiсiмді бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2002-07-14
approved_by:
- '103000000000'
version_date:
  kaz: 2002-07-14
  rus: 2002-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/12656/kaz/14.07.2002
  rus: https://zan.gov.kz/client/#!/doc/12656/rus/14.07.2002
