act_code: '7832'
requisite: Закон Республики Казахстан от 18 декабря 2000 года № 126
title:
  rus: О страховой деятельности
  kaz: Сақтандыру қызметі туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2000-12-18
approved_by:
- '102000000000'
version_date:
  kaz: 2022-01-01
  rus: 2022-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/7832/kaz/01.01.2022
  rus: https://zan.gov.kz/client/#!/doc/7832/rus/01.01.2022
caused_by:
  code: '123091'
  requisite: Закон Республики Казахстан от 2 июля 2018 года № 166-VІ ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам страхования и страховой деятельности, рынка ценных бумаг
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне сақтандыру және сақтандыру қызметі, бағалы қағаздар нарығы мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123091/rus
