act_code: '196513'
requisite: Нормативное постановление Конституционного Суда Республики Казахстан от 4 мая 2024 года № 43-НП
title:
  rus: О рассмотрении на соответствие Конституции Республики Казахстан пункта 17) части девятой статьи 64 и пункта 5) части второй статьи 70 Уголовно-процессуального кодекса Республики Казахстан от 4 июля 2014 года
  kaz: 2014 жылғы 4 шілдедегі Қазақстан Республикасы Қылмыстық-процестік кодексінің 64-бабы тоғызыншы бөлігі 17) тармағының және 70-бабы екінші бөлігі 5) тармағының Қазақстан Республикасының Конституциясына сәйкестігін қарау туралы
form: НПОС
type_codes:
- НПОС
approved_on: 2024-05-04
approved_by:
- '106000000000'
version_date:
  kaz: 2024-05-04
  rus: 2024-05-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/196513/kaz/04.05.2024
  rus: https://zan.gov.kz/client/#!/doc/196513/rus/04.05.2024
