act_code: '104440'
requisite: Закон Республики Казахстан от 28 февраля 1997 года N 75-I ЗРК. Утратил силу Законом Республики Казахстан от 8 января 2003 года N 373
title:
  rus: О государственной поддержке прямых инвестиций
  kaz: Тiкелей инвестицияларды мемлекеттiк қолдау туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1997-02-28
approved_by:
- '102000000000'
version_date:
  rus: 1997-02-28
source:
  rus: https://zan.gov.kz/client/#!/doc/104440/rus/28.02.1997
