act_code: '107245'
requisite: Закон Республики Казахстан от 28 октября 2016 года № 18-VІ ЗРК
title:
  rus: О ратификации Соглашения о продолжении деятельности Международного научно-технического центра
  kaz: Халықаралық ғылыми-техникалық орталықтың қызметін жалғастыру туралы келісімді ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2016-10-28
approved_by:
- '102000000000'
version_date:
  kaz: 2016-10-28
  rus: 2016-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/107245/kaz/28.10.2016
  rus: https://zan.gov.kz/client/#!/doc/107245/rus/28.10.2016
