act_code: '81164'
requisite: Кодекс Республики Казахстан от 4 июля 2014 года № 231-V ЗРК
title:
  rus: Уголовно-процессуальный кодекс Республики Казахстан
  kaz: Қазақстан Республикасының Қылмыстық-процестік кодексi
form: КОД
type_codes:
- КОД
approved_on: 2014-07-04
approved_by:
- '102000000000'
version_date:
  kaz: 2023-12-31
  rus: 2023-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/81164/kaz/31.12.2023
  rus: https://zan.gov.kz/client/#!/doc/81164/rus/31.12.2023
caused_by:
  code: '190600'
  requisite: Закон Республики Казахстан от 23 декабря 2023 года № 51-VIII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам обеспечения национальной безопасности и службы в специальных государственных органах Республики Казахстан
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне ұлттық қауіпсіздікті қамтамасыз ету және Қазақстан Республикасының арнаулы мемлекеттік органдарындағы қызмет мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/190600/rus
