act_code: '81164'
requisite: Кодекс Республики Казахстан от 4 июля 2014 года № 231-V ЗРК
title:
  rus: Уголовно-процессуальный кодекс Республики Казахстан
  kaz: Қазақстан Республикасының Қылмыстық-процестік кодексi
form: КОД
type_codes:
- КОД
approved_on: 2014-07-04
approved_by:
- '102000000000'
version_date:
  kaz: 2024-11-21
  rus: 2024-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/81164/kaz/21.11.2024
  rus: https://zan.gov.kz/client/#!/doc/81164/rus/21.11.2024
caused_by:
  code: '203024'
  requisite: Закон Республики Казахстан от 21 ноября 2024 года № 136-VIII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам реформирования судебной системы и совершенствования процессуального законодательства
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне сот жүйесін реформалау және процестік заңнаманы жетілдіру мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/203024/rus
