act_code: '19180'
requisite: Указ Президента Республики Казахстан от 31 марта 2004 года N 1327. Утратил силу Указом Президента Республики Казахстан от 11 февраля 2008 года N 533 .
title:
  rus: О штатной численности и структуре Администрации Президента Республики Казахстан
  kaz: Қазақстан Республикасы Президенті Әкімшілігінің штат саны мен құрылымы туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2004-03-30
approved_by:
- '101000000000'
version_date:
  kaz: 2006-01-28
  rus: 2006-01-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/19180/kaz/28.01.2006
  rus: https://zan.gov.kz/client/#!/doc/19180/rus/28.01.2006
caused_by:
  code: U060000051_
