act_code: '94875'
requisite: Закон Республики Казахстан от 29 октября 2015 года № 372-V ЗРК
title:
  rus: О сельскохозяйственных кооперативах
  kaz: Ауыл шаруашылығы кооперативтері туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2015-10-29
approved_by:
- '102000000000'
version_date:
  kaz: 2025-06-10
  rus: 2025-06-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/94875/kaz/10.06.2025
  rus: https://zan.gov.kz/client/#!/doc/94875/rus/10.06.2025
caused_by:
  code: '209027'
  requisite: Закон Республики Казахстан от 9 апреля 2025 года № 179-VIII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам охраны и использования водного фонда
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне су қорын қорғау және пайдалану мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/209027/rus
