act_code: '106797'
requisite: Закон Республики Казахстан от 14 октября 2016 года № 17-VІ ЗРК
title:
  rus: О ратификации Конвенции между Правительством Республики Казахстан и Правительством Республики Сербия об избежании двойного налогообложения и предотвращении уклонения от налогообложения в отношении налогов на доход и на капитал и Протокола к ней
  kaz: Қазақстан Республикасының Үкіметі мен Сербия Республикасының Үкіметі арасындағы Табыс пен капиталға салынатын салықтарға қатысты қосарланған салық салуды болдырмау және салық салудан жалтаруға жол бермеу туралы конвенцияны және оған Хаттаманы ратификациялау туралы
form: КОНВ
type_codes:
- ЗАК
- КОНВ
approved_on: 2016-10-14
approved_by:
- '102000000000'
version_date:
  kaz: 2016-10-14
  rus: 2016-10-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/106797/kaz/14.10.2016
  rus: https://zan.gov.kz/client/#!/doc/106797/rus/14.10.2016
