act_code: '162833'
requisite: Закон Республики Казахстан от 30 декабря 2021 года № 97-VII ЗРК
title:
  rus: Об ответственном обращении с животными
  kaz: Жануарларға жауапкершілікпен қарау туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2021-12-30
approved_by:
- '102000000000'
version_date:
  kaz: 2023-04-19
  rus: 2023-04-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/162833/kaz/19.04.2023
  rus: https://zan.gov.kz/client/#!/doc/162833/rus/19.04.2023
caused_by:
  code: '179978'
  requisite: Закон Республики Казахстан от 19 апреля 2023 года № 223-VII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам административной реформы в Республике Казахстан
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне Қазақстан Республикасындағы әкімшілік реформа мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/179978/rus
