act_code: '54869'
requisite: Закон Республики Казахстан от 27 сентября 2010 года № 341-IV ЗРК
title:
  rus: О ратификации Нахичеванского соглашения о создании Совета сотрудничества тюркоязычных государств
  kaz: Түркітілдес мемлекеттердің ынтымақтастық кеңесін құру туралы Нахчыван келісімін ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2010-09-27
approved_by:
- '102000000000'
version_date:
  kaz: 2025-05-23
  rus: 2025-05-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/54869/kaz/23.05.2025
  rus: https://zan.gov.kz/client/#!/doc/54869/rus/23.05.2025
caused_by:
  code: '210706'
  requisite: Закон Республики Казахстан от 23 мая 2025 года № 191-VIII ЗРК
  title:
    rus: О ратификации Протокола о внесении изменений в Нахичеванское соглашение о создании Совета сотрудничества тюркоязычных государств
    kaz: Түркітілдес мемлекеттердің ынтымақтастық кеңесін құру туралы Нахчыван келісіміне өзгерістер енгізу туралы хаттаманы ратификациялау туралы
  link: https://zan.gov.kz/client/#!/doc/210706/rus
