act_code: '17447'
requisite: Закон Республики Казахстан от 6 ноября 2003 года № 494-II
title:
  rus: О ратификации Соглашения в форме обмена нотами между Правительством Республики Казахстан и Правительством Японии о привлечении займа для осуществления проекта "Водоснабжение и канализация города Астаны"
  kaz: Қазақстан Республикасының Үкіметі мен Жапония Үкіметінің арасындағы "Астана қаласын сумен жабдықтау және оның кәрізі" жобасын жүзеге асыру үшін қарыз алу туралы ноталар алмасу нысанындағы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2003-11-06
approved_by:
- '102000000000'
version_date:
  kaz: 2003-11-06
  rus: 2003-11-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/17447/kaz/06.11.2003
  rus: https://zan.gov.kz/client/#!/doc/17447/rus/06.11.2003
