act_code: '1301'
requisite: Утверждена Постановлением Правления Национального Банка Республики Казахстан от 25 июля 1997 г. N 295. Утратила силу - постановлением Правления Национального Банка Республики Казахстан от 15 ноября 1999г. N 400
title:
  rus: Инструкция "Об организации обменных операций с наличной иностранной валютой в Республике Казахстан"
  kaz: Қазақстан Республикасында қолма-қол шет ел валютасымен айырбастау операцияларын ұйымдастыру туралы Нұсқаулық
type_codes:
- ПОЛ
approved_on: 1997-07-24
approved_by:
- '117000000000'
version_date:
  rus: 1999-05-19
source:
  rus: https://zan.gov.kz/client/#!/doc/1301/rus/19.05.1999
caused_by:
  code: '3325'
  requisite: Постановление Правления Национального Банка Республики Казахстан от 20 мая 1999 года № 113 Зарегистрирован в Министерстве юстиции Республики Казахстан 18.06.1999г. за № 808. Утратило силу постановлением Правления Национального Банка РК от 1 ноября 2010 года № 88
  title:
    rus: Об утверждении изменений в Инструкцию об организации обменных операций с наличной иностранной валютой в Республике Казахстан и в постановление Правления Национального Банка Республики Казахстан от 19 февраля 1999 года № 17
    kaz: Қазақстан Республикасында қолма-қол шет ел валютасымен айырбастау операцияларын ұйымдастыру туралы нұсқаулыққа және Қазақстан Республикасы Ұлттық Банкі Басқармасының 1999 жылғы 19 ақпандағы N 17 қаулысына өзгерістерді бекіту жөнінде
  link: https://zan.gov.kz/client/#!/doc/3325/rus
