act_code: '56107'
requisite: Постановление Правительства Республики Казахстан от 13 декабря 2010 года № 1346
title:
  rus: Об утверждении Соглашения между Правительством Республики Казахстан и Правительством Российской Федерации о совместной деятельности по геологическому изучению и разведке трансграничного газоконденсатного месторождения Имашевское
  kaz: Қазақстан Республикасының Үкіметі мен Ресей Федерациясының Үкіметі арасындағы Имашев трансшекаралық газ конденсаты кен орнын геологиялық зерделеу және барлау жөніндегі бірлескен қызмет туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2010-12-13
approved_by:
- '103000000000'
version_date:
  kaz: 2010-12-13
  rus: 2010-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/56107/kaz/13.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56107/rus/13.12.2010
