act_code: '80031'
requisite: Указ Президента Республики Казахстан от 4 мая 2014 года № 814
title:
  rus: Об утверждении Положения о Службе государственной охраны Республики Казахстан
  kaz: Қазақстан Республикасы Мемлекеттік күзет қызметі туралы ережені бекіту туралы
form: УКАЗ
type_codes:
- ПОЛ
- УКАЗ
approved_on: 2014-05-04
approved_by:
- '101000000000'
version_date:
  kaz: 2024-06-18
  rus: 2024-06-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/80031/kaz/18.06.2024
  rus: https://zan.gov.kz/client/#!/doc/80031/rus/18.06.2024
caused_by:
  code: '197851'
  requisite: Указ Президента Республики Казахстан от 18 июня 2024 года № 574
  title:
    rus: О внесении изменений и дополнений в Указ Президента Республики Казахстан от 4 мая 2014 года № 814 «Об утверждении Положения о Службе государственной охраны Республики Казахстан»
    kaz: «Қазақстан Республикасы Мемлекеттік күзет қызметі туралы ережені бекіту туралы» Қазақстан Республикасы Президентінің 2014 жылғы 4 мамырдағы № 814 Жарлығына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/197851/rus
