act_code: '72743'
requisite: Закон Республики Казахстан от 23 мая 2013 года № 99-V
title:
  rus: 'О ратификации Письма-соглашения между Республикой Казахстан и Международным Банком Реконструкции и Развития относительно поправок в Соглашение о займе № 7681-KZ (Проект развития автомобильных дорог Юг-Запад: Международный транзитный коридор Западная Европа - Западный Китай (ЦАРЭС 1b и 6b) между Республикой Казахстан и Международным Банком Реконструкции и Развития'
  kaz: 'Қазақстан Республикасы мен Халықаралық Қайта Құру және Даму Банкi арасындағы № 7681-KZ Қарыз туралы келiсiмге (Оңтүстік – Батыс автомобиль жолдарын дамыту жобасы: Батыс Еуропа – Батыс Қытай халықаралық транзит дәлізі (ОАӨЭЫ 1b және 6b) түзетулерге қатысты Қазақстан Республикасы мен Халықаралық Қайта Құру және Даму Банкi арасындағы келісім-хатты ратификациялау туралы'
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2013-05-23
approved_by:
- '102000000000'
version_date:
  kaz: 2013-05-23
  rus: 2013-05-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/72743/kaz/23.05.2013
  rus: https://zan.gov.kz/client/#!/doc/72743/rus/23.05.2013
