act_code: '12697'
requisite: Закон Республики Казахстан от 10 июля 2002 года N 340-II. Утратил силу Кодексом Республики Казахстан от 18 сентября 2009 года N 193-IV
title:
  rus: О профилактике и ограничении табакокурения
  kaz: Темекi шегушілiктiң алдын алу және оны шектеу туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2002-07-09
approved_by:
- '102000000000'
version_date:
  kaz: 2002-07-09
  rus: 2002-07-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/12697/kaz/09.07.2002
  rus: https://zan.gov.kz/client/#!/doc/12697/rus/09.07.2002
