act_code: '350'
requisite: Постановление Национальной комиссии Республики Казахстан по ценным бумагам от 7 ноября 1995 года N 23. Утратило силу - постановлением НКЦБ от 8.10.97г. N 161 V970458
title:
  rus: Об утверждении "Положения о порядке присвоения Национальных идентификационных номеров государственным ценным бумагам"
  kaz: Қазақстан Республикасының Құнды қағаздар жөніндегі ұлттық комиссиясының Қаулысы
type_codes:
- ПОЛ
approved_on: 1995-11-07
approved_by:
- '111000000000'
version_date:
  rus: 1995-11-07
source:
  rus: https://zan.gov.kz/client/#!/doc/350/rus/07.11.1995
