act_code: '41901'
requisite: Закон Республики Казахстан от 20 октября 2008 года № 70-IV
title:
  rus: Об Ассамблее народа Казахстана
  kaz: Қазақстан халқы Ассамблеясы туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2008-10-20
approved_by:
- '102000000000'
version_date:
  kaz: 2010-06-14
  rus: 2010-06-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/41901/kaz/14.06.2010
  rus: https://zan.gov.kz/client/#!/doc/41901/rus/14.06.2010
caused_by:
  code: '53075'
  requisite: Закон Республики Казахстан от 14 июня 2010 года № 290-IV
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам совершенствования законодательства в сфере обеспечения деятельности Первого Президента Республики Казахстан - Лидера Нации
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне Қазақстан Республикасы Тұңғыш Президентінің - Елбасының қызметін қамтамасыз ету саласында заңнаманы жетілдіру мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/53075/rus
