act_code: '7405'
requisite: Закон Республики Казахстан от 13 ноября 2000 года № 100-II
title:
  rus: О ратификации Соглашения между Таможенным комитетом Министерства государственных доходов Республики Казахстан и Министерством государственных доходов Республики Армения о сотрудничестве и взаимном признании таможенных документов и таможенных обеспечений
  kaz: Қазақстан Республикасы Мемлекеттік кіріс министрлігінің Кеден комитеті мен Армения Республикасы Мемлекеттік кіріс министрлігінің арасындағы Ынтымақтастық және кеден құжаттары мен кедендік қамтамасыз етулерді өзара тану туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2000-11-13
approved_by:
- '102000000000'
version_date:
  kaz: 2000-11-13
  rus: 2000-11-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/7405/kaz/13.11.2000
  rus: https://zan.gov.kz/client/#!/doc/7405/rus/13.11.2000
