act_code: '1330'
requisite: Распоряжение Акима Павлодарской области от 7 июля 1997 года № 1-151-р. Зарегистрировано Управлением юстиции Павлодарской области 11 августа 1997 года за № 12. Утратило силу решением Акима Павлодарской области от 29 октября 2004 года № 25
title:
  rus: О проверке состояния машино-технического парка
  kaz: Машина-техникалық паркінің жағдайын тексеру туралы
form: РАСП
type_codes:
- РАСП
approved_on: 1997-07-06
approved_by:
- '164000000003'
version_date:
  kaz: 1997-07-06
  rus: 1997-07-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/1330/kaz/06.07.1997
  rus: https://zan.gov.kz/client/#!/doc/1330/rus/06.07.1997
