act_code: '3124'
requisite: Распоряжение акима Восточно-Казахстанской области от 17 февраля 1997 года № 1-353р. Зарегистрировано управлением юстиции Восточно-Казахстанской области 12 апреля 1998 года за № 14. Утратило силу - распоряжением акима Восточно-Казахстанской области от 18 октября 2004 года № 1-175р
title:
  rus: Об упорядочении реализации подакцизных товаров и обеспечении полноты сбора местных налогов
  kaz: Акциздік тауарларды сатуды реттеу және жергілікті салықтарды толық жинауды қамтамасыз ету туралы
form: РАСП
type_codes:
- РАСП
approved_on: 1997-02-17
approved_by:
- '157000000001'
version_date:
  kaz: 1997-02-17
  rus: 1997-02-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/3124/kaz/17.02.1997
  rus: https://zan.gov.kz/client/#!/doc/3124/rus/17.02.1997
