act_code: '5632'
requisite: Постановление Правительства Республики Казахстан от 30 марта 2000 года № 466
title:
  rus: Об утверждении Соглашения между Правительством Республики Казахстан и Правительством Республики Таджикистан о сотрудничестве в военной области
  kaz: Қазақстан Республикасының Үкіметі мен Тәжікстан Республикасының Үкіметі арасындағы әскери саладағы ынтымақтастық туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2000-03-29
approved_by:
- '103000000000'
version_date:
  kaz: 2000-03-29
  rus: 2000-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/5632/kaz/29.03.2000
  rus: https://zan.gov.kz/client/#!/doc/5632/rus/29.03.2000
