act_code: '31393'
requisite: Закон Республики Казахстан от 11 января 2007 года № 214. Утратил силу Законом Республики Казахстан от 16 мая 2014 года № 202-V
title:
  rus: О лицензировании
  kaz: Лицензиялау туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2007-01-11
approved_by:
- '102000000000'
version_date:
  rus: 2011-01-06
source:
  rus: https://zan.gov.kz/client/#!/doc/31393/rus/06.01.2011
caused_by:
  code: '56743'
  requisite: Закон Республики Казахстан от 6 января 2011 года № 378-IV
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам государственного контроля и надзора
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне мемлекеттік бақылау және қадағалау мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/56743/rus
