act_code: '31393'
requisite: Закон Республики Казахстан от 11 января 2007 года № 214. Утратил силу Законом Республики Казахстан от 16 мая 2014 года № 202-V
title:
  rus: О лицензировании
  kaz: Лицензиялау туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2007-01-11
approved_by:
- '102000000000'
version_date:
  rus: 2012-01-12
source:
  rus: https://zan.gov.kz/client/#!/doc/31393/rus/12.01.2012
caused_by:
  code: '62741'
  requisite: Закон Республики Казахстан от 12 января 2012 года № 538-IV
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам развития фондового рынка в Республике Казахстан
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне Қазақстан Республикасында қор нарығын дамыту мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/62741/rus
