act_code: '6301'
requisite: Закон Республики Казахстан от 23 июня 2000 года № 60-II
title:
  rus: О ратификации Договора о дружбе и сотрудничестве между Республикой Казахстан и Республикой Армения
  kaz: Қазақстан Республикасы мен Армения Республикасы арасындағы достық пен ынтымақтастық туралы шартты бекіту туралы
form: ДОГ
type_codes:
- ДОГ
- ЗАК
approved_on: 2000-06-22
approved_by:
- '102000000000'
version_date:
  kaz: 2000-06-22
  rus: 2000-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/6301/kaz/22.06.2000
  rus: https://zan.gov.kz/client/#!/doc/6301/rus/22.06.2000
