act_code: '7697'
requisite: Приказ Министра финансов Республики Казахстан от 17 ноября 2000 года N 488. Зарегистрирован в Министерстве юстиции Республики Казахстан 18 декабря 2000 года N 1333. Утратило силу - приказом Министра финансов Республики Казахстан от 4 апреля 2007 года N 107
title:
  rus: Об утверждении Инструкции о выплате заработной платы, стипендий и других денежных выплат работникам государственных учреждений и стипендиатам через банки второго уровня и организации, имеющие лицензию Национального Банка Республики Казахстан на соответствующие виды банковских операций и Инструкции о порядке использования государственными учреждениями чеков территориальных подразделений Казначейства
  kaz: Мемлекеттік мекемелердің қызметкерлерiне және стипендиаттарға екінші деңгейдегі банктер және банктiк операциялардың тиiстi түрлерiне арналған Қазақстан Республикасы Ұлттық Банкiнiң лицензиясы бар ұйымдар арқылы жалақы, стипендия және басқа да ақшалай төлемдер төлеу туралы нұсқаулық және Қазынашылықтың аумақтық бөлiмшелерiнiң чектерiн мемлекеттiк мекемелердiң пайдалану тәртiбi туралы нұсқаулықты бекiту туралы
type_codes:
- ИНСТ
approved_on: 2000-11-17
approved_by:
- '103002000000'
version_date:
  kaz: 2000-11-17
  rus: 2000-11-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/7697/kaz/17.11.2000
  rus: https://zan.gov.kz/client/#!/doc/7697/rus/17.11.2000
