act_code: '26134'
requisite: Закон Республики Казахстан от 14 декабря 2005 года № 100
title:
  rus: О ратификации Конвенции о борьбе с торговлей людьми и с эксплуатацией проституции третьими лицами и Заключительного протокола
  kaz: Адамдарды сатуға және үшінші тұлғалардың жезөкшелікті пайдалануына қарсы күрес туралы конвенцияны және Қорытынды хаттаманы ратификациялау туралы
form: КОНВ
type_codes:
- ДОГ
- ЗАК
- КОНВ
approved_on: 2005-12-14
approved_by:
- '102000000000'
version_date:
  kaz: 2005-12-14
  rus: 2005-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/26134/kaz/14.12.2005
  rus: https://zan.gov.kz/client/#!/doc/26134/rus/14.12.2005
