act_code: '30467'
requisite: Закон Республики Казахстан от 25 ноября 2006 года № 191
title:
  rus: О ратификации Соглашения между Правительством Республики Казахстан и Правительством Грузии о взаимных поездках граждан
  kaz: Қазақстан Республикасының Yкiметi мен Грузия Үкiметi арасындағы азаматтардың өзара сапарлары туралы келiсiмдi ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2006-11-25
approved_by:
- '102000000000'
version_date:
  kaz: 2006-11-25
  rus: 2006-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/30467/kaz/25.11.2006
  rus: https://zan.gov.kz/client/#!/doc/30467/rus/25.11.2006
