act_code: '70827'
requisite: Закон Республики Казахстан от 11 февраля 2013 года № 76-V ЗРК
title:
  rus: О ратификации Соглашения о займе (Обычные операции) (ЦАРЭС Коридор 1 [Обход города Тараз] [Международный транзитный коридор Западная Европа – Западная Китайская Народная Республика] Проект) между Республикой Казахстан и Азиатским Банком Развития
  kaz: Қазақстан Республикасы мен Азия Даму Банкі арасындағы Қарыз туралы келісімді (Жай операциялар) (ОАӨЭЫ Дәліз 1 [Тараз қаласының айналма жолы] [Батыс Еуропа - Батыс Қытай Халық Республикасы халықаралық транзит дәлізі] Жоба) ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2013-02-11
approved_by:
- '102000000000'
version_date:
  kaz: 2013-02-11
  rus: 2013-02-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/70827/kaz/11.02.2013
  rus: https://zan.gov.kz/client/#!/doc/70827/rus/11.02.2013
