act_code: '72742'
requisite: Закон Республики Казахстан от 23 мая 2013 года № 98-V ЗРК
title:
  rus: О ратификации Договора между Республикой Казахстан и Королевством Испания о выдаче
  kaz: Қазақстан Республикасы мен Испания Корольдігі арасындағы ұстап беру туралы шартты ратификациялау туралы
form: ДОГ
type_codes:
- ДОГ
- ЗАК
approved_on: 2013-05-23
approved_by:
- '102000000000'
version_date:
  kaz: 2013-05-23
  rus: 2013-05-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/72742/kaz/23.05.2013
  rus: https://zan.gov.kz/client/#!/doc/72742/rus/23.05.2013
