act_code: '185734'
requisite: Постановление Правительства Республики Казахстан от 1 сентября 2023 года № 756
title:
  rus: Об утверждении Соглашения о сотрудничестве государств – участников Содружества Независимых Государств в области музейного дела
  kaz: Тәуелсіз Мемлекеттер Достастығына қатысушы мемлекеттердің музей ісі саласындағы ынтымақтастығы туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2023-09-01
approved_by:
- '103000000000'
version_date:
  kaz: 2023-09-01
  rus: 2023-09-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/185734/kaz/01.09.2023
  rus: https://zan.gov.kz/client/#!/doc/185734/rus/01.09.2023
