act_code: '151249'
requisite: Закон Республики Казахстан от 30 декабря 2020 года № 398-VI ЗРК
title:
  rus: О ратификации Соглашения между Правительством Республики Казахстан и Правительством Объединенных Арабских Эмиратов о взаимном предоставлении в безвозмездное пользование земельных участков в городе Астане и городе Абу Даби для нужд Посольства Республики Казахстан в Объединенных Арабских Эмиратах и Посольства Объединенных Арабских Эмиратов в Республике Казахстан
  kaz: Қазақстан Республикасының Үкіметі мен Біріккен Араб Әмірліктерінің Үкіметі арасындағы Қазақстан Республикасының Біріккен Араб Әмірліктеріндегі Елшілігінің және Біріккен Араб Әмірліктерінің Қазақстан Республикасындағы Елшілігінің қажеттіліктеріне Астана қаласында және Әбу Даби қаласында жер учаскелерін өтеусіз пайдалануға өзара беру туралы келісімді ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2020-12-30
approved_by:
- '102000000000'
version_date:
  kaz: 2020-12-30
  rus: 2020-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/151249/kaz/30.12.2020
  rus: https://zan.gov.kz/client/#!/doc/151249/rus/30.12.2020
