act_code: '163005'
requisite: Указ Президента Республики Казахстан от 5 января 2022 года № 744
title:
  rus: О введении чрезвычайного положения в Павлодарской области
  kaz: Павлодар облысында төтенше жағдайды енгізу туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2022-01-05
approved_by:
- '101000000000'
version_date:
  kaz: 2022-01-12
  rus: 2022-01-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/163005/kaz/12.01.2022
  rus: https://zan.gov.kz/client/#!/doc/163005/rus/12.01.2022
caused_by:
  code: '163474'
  requisite: Указ Президента Республики Казахстан от 12 января 2022 года № 764
  title:
    rus: Об отмене чрезвычайного положения в Павлодарской области
    kaz: Павлодар облысындағы төтенше жағдайдың күшін жою туралы
  link: https://zan.gov.kz/client/#!/doc/163474/rus
