act_code: '9267'
requisite: Закон Республики Казахстан от 13 июня 2001 года № 211
title:
  rus: О туристской деятельности в Республике Казахстан
  kaz: Қазақстан Республикасындағы туристік қызмет туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2001-06-13
approved_by:
- '102000000000'
version_date:
  kaz: 2019-04-11
  rus: 2019-04-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/9267/kaz/11.04.2019
  rus: https://zan.gov.kz/client/#!/doc/9267/rus/11.04.2019
caused_by:
  code: '125030'
  requisite: Закон Республики Казахстан от 5 октября 2018 года № 184-VІ ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам обеспечения единства измерений и стандартизации
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне өлшем бірлігін қамтамасыз ету және стандарттау мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/125030/rus
