act_code: '9267'
requisite: Закон Республики Казахстан от 13 июня 2001 года № 211
title:
  rus: О туристской деятельности в Республике Казахстан
  kaz: Қазақстан Республикасындағы туристік қызмет туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2001-06-13
approved_by:
- '102000000000'
version_date:
  kaz: 2022-01-01
  rus: 2022-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/9267/kaz/01.01.2022
  rus: https://zan.gov.kz/client/#!/doc/9267/rus/01.01.2022
caused_by:
  code: '155528'
  requisite: Закон Республики Казахстан от 30 апреля 2021 года № 34-VII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам туристской деятельности
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне туристік қызмет мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/155528/rus
