act_code: '60287'
requisite: Закон Республики Казахстан от 22 июля 2011 года № 472-IV
title:
  rus: О ратификации Соглашения о создании условий на финансовых рынках для обеспечения свободного движения капитала
  kaz: Қаржы нарықтарында капиталдың еркін қозғалысын қамтамасыз ету үшін жағдай жасау туралы келісімді ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2011-07-22
approved_by:
- '102000000000'
version_date:
  kaz: 2011-07-22
  rus: 2011-07-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/60287/kaz/22.07.2011
  rus: https://zan.gov.kz/client/#!/doc/60287/rus/22.07.2011
