act_code: '1851'
requisite: Закон Республики Казахстан от 22 декабря 1998 года № 330-І
title:
  rus: О ратификации Соглашения между Правительством Республики Казахстан и Правительством Федеративной Республики Германия о финансовом сотрудничестве
  kaz: Қазақстан Республикасының Үкіметі мен Германия Федеративтік Республикасының Үкіметі арасындағы Қаржы ынтымақтастығы туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 1998-12-22
approved_by:
- '102000000000'
version_date:
  kaz: 1998-12-22
  rus: 1998-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/1851/kaz/22.12.1998
  rus: https://zan.gov.kz/client/#!/doc/1851/rus/22.12.1998
