act_code: '162987'
requisite: Указ Президента Республики Казахстан от 5 января 2022 года № 735
title:
  rus: О введении чрезвычайного положения в Жамбылской области
  kaz: Жамбыл облысында төтенше жағдайды енгізу туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2022-01-05
approved_by:
- '101000000000'
version_date:
  kaz: 2022-01-05
  rus: 2022-01-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/162987/kaz/05.01.2022
  rus: https://zan.gov.kz/client/#!/doc/162987/rus/05.01.2022
