act_code: '208242'
requisite: Указ Президента Республики Казахстан от 18 марта 2025 года № 818
title:
  rus: О мерах по дальнейшему совершенствованию системы государственного управления Республики Казахстан
  kaz: Қазақстан Республикасының мемлекеттік басқару жүйесін одан әрі жетілдіру жөніндегі шаралар туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2025-03-18
approved_by:
- '101000000000'
version_date:
  kaz: 2025-03-18
  rus: 2025-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/208242/kaz/18.03.2025
  rus: https://zan.gov.kz/client/#!/doc/208242/rus/18.03.2025
