act_code: '603'
requisite: Приказ Комитета по водным ресурсам Министерства сельского хозяйства Республики Казахстан от 22 ноября 1997 г. № 47а. Зарегистрирован в Министерстве юстиции Республики Казахстан 19.04.1998 г. за № 500. Утратил силу - совместный приказ Комитета по водным ресурсам Министерства природных ресурсов и охраны окружающей среды от 20 июня 2001 г. N 50-П и Комитета геологии и охраны недр Министерства энергетики и минеральных ресурсов РК от 20 июня 2001 г. N 155-П
title:
  rus: Об утверждении Инструкции о порядке согласования и выдачи разрешений на специальное водопользование на использование поверхностных вод
  kaz: ЖЕРYСТI СУ КӨЗДЕРIНЕН АРНАЙЫ СУ ПАЙДАЛАНУҒА КЕЛIСУ ЖӘНЕ ОҒАН РҰҚСАТТАР БЕРУ ТӘРТIБI ТУРАЛЫ НҰСҚАУ
type_codes:
- ИНСТ
approved_on: 1997-11-22
approved_by:
- '103012002000'
version_date:
  rus: 1997-11-22
source:
  rus: https://zan.gov.kz/client/#!/doc/603/rus/22.11.1997
