act_code: '7357'
requisite: Приказ Министра иностранных дел Республики Казахстан от 18 августа 2000 года N 115 Зарегистрировано в Министерстве юстиции Республики Казахстан 14 ноября 2000 года за N 1283. Утратил силу приказом Министра иностранных дел Республики Казахстан от 3 августа 2009 года № 08-1-1-1/236
title:
  rus: Об утверждении Правил аккредитации глав, сотрудников, военных атташе и административно-технического персонала дипломатических миссий, консульских учреждений, представительств международных организаций и иностранных инвесторов в Республике Казахстан
  kaz: Қазақстан Республикасындағы дипломатиялық миссиялардың, консулдық мекемелердiң, халықаралық ұйымдар өкiлдiктерi мен шетелдiк инвесторлардың басшыларын, қызметкерлерiн, әскери атташелерi мен әкiмшілік-техникалық персоналдарын тiркеудiң ережесiн бекiту туралы
type_codes:
- ПРАВ
approved_on: 2000-08-17
approved_by:
- '103004000000'
version_date:
  kaz: 2000-08-17
  rus: 2000-08-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/7357/kaz/17.08.2000
  rus: https://zan.gov.kz/client/#!/doc/7357/rus/17.08.2000
