act_code: '104243'
requisite: ЗАКОН Республики Казахстан от 17 янваpя 1992 года. Утратил силу - Законом РК от 13 июля 1999 года № 412-I
title:
  rus: Об аpбитpажном суде Республики Казахстан
  kaz: Об аpбитpажном суде Республики Казахстан
form: ЗАК
type_codes:
- ЗАК
approved_on: 1992-01-17
approved_by:
- '102000000000'
version_date:
  rus: 1993-10-18
source:
  rus: https://zan.gov.kz/client/#!/doc/104243/rus/18.10.1993
