act_code: '104140'
requisite: Закон Республики Казахстан от 7 мая 1997 года № 98-1. Утратил силу Законом Республики Казахстан от 19 марта 2010 года № 257-IV (вводится в действие по истечении десяти календарных дней после его первого официального опубликования)
title:
  rus: О ГОСУДАРСТВЕННОЙ СТАТИСТИКЕ
  kaz: Мемлекеттiк статистика туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1997-05-06
approved_by:
- '102000000000'
version_date:
  rus: 1997-05-06
source:
  rus: https://zan.gov.kz/client/#!/doc/104140/rus/06.05.1997
