act_code: '887'
requisite: Инструкция Главной налоговой инспекции Министерства финансов Республики Казахстан от 1 июля 1995 г. N 43. Зарегистрирована в Министерстве юстиции Республики Казахстан 12.07.95 г. за N 80. Утратила силу - приказом Министра государственных доходов РК от 9.04.2002 № 416
title:
  rus: Инструкция № 43 Об административных положениях по налогам и другим обязательным платежам в бюджет
  kaz: Салық және бюджетке төленетiн басқа да мiндеттi төлемдер жөнiндегi әкiмшiлiк ереже туралы Нұсқаулық
type_codes:
- ИНСТ
approved_on: 1995-06-30
approved_by:
- '103002002000'
version_date:
  rus: 1998-07-09
source:
  rus: https://zan.gov.kz/client/#!/doc/887/rus/09.07.1998
caused_by:
  code: '1042'
  requisite: Утверждено Приказом Председателя Налогового комитета Министерства финансов Республики Казахстан от 10 июля 1998 года N 62. Зарегистрировано в Министерстве юстиции Республики Казахстан 23.07.1998 г. N 544. Утратил силу - приказом Министра государственных доходов РК от 9.04.2002 № 416.
  title:
    rus: Изменения и дополнения к Инструкции N 43 "Об административных положениях по налогам и другим обязательным платежам в бюджет"
    kaz: '"Салық және бюджетке төленетін басқа да міндетті төлемдер жөніндегі әкімшілік ережелері туралы" N 43 Нұсқаулыққа жасалған өзгерістер және толықтырулар'
  link: https://zan.gov.kz/client/#!/doc/1042/rus
