act_code: '106319'
requisite: Указ Президента Республики Казахстан от 8 октября 1996 г. N 3123. Утратил силу - Указом Президента РК от 31 марта 1999 года N 104
title:
  rus: О создании Кызылординской специальной экономической зоны
  kaz: Қызылорда арнайы экономикалық аймағын құру туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 1996-10-07
approved_by:
- '101000000000'
version_date:
  rus: 1996-10-07
source:
  rus: https://zan.gov.kz/client/#!/doc/106319/rus/07.10.1996
