act_code: '622'
requisite: Закон Республики Казахстан от 8 мая 1998 года № 224
title:
  rus: О ратификации Соглашения между Правительством Республики Казахстан и Правительством Республики Узбекистан о свободной торговле
  kaz: Қазақстан Республикасының Үкiметi мен Өзбекстан Республикасының Үкiметi арасындағы Еркiн сауда туралы келiсiмдi бекiту туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 1998-05-07
approved_by:
- '102000000000'
version_date:
  kaz: 1998-05-07
  rus: 1998-05-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/622/kaz/07.05.1998
  rus: https://zan.gov.kz/client/#!/doc/622/rus/07.05.1998
