act_code: '2215'
requisite: Закон Республики Казахстан от 11 февраля 1999 года № 344
title:
  rus: О карантине растений
  kaz: Өсімдіктер карантині туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1999-02-11
approved_by:
- '102000000000'
version_date:
  kaz: 2011-07-05
  rus: 2011-07-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/2215/kaz/05.07.2011
  rus: https://zan.gov.kz/client/#!/doc/2215/rus/05.07.2011
caused_by:
  code: '59629'
  requisite: Закон Республики Казахстан от 5 июля 2011 года № 452-IV
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам пересмотра компетенции уполномоченных государственных органов и Правительства Республики Казахстан на принятие нормативных правовых актов, устанавливающих требования к проверяемым субъектам
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне уәкілетті мемлекеттік органдар мен Қазақстан Республикасы Үкіметінің тексерілетін субъектілерге қойылатын талаптарды белгілейтін нормативтік құқықтық актілерді қабылдау құзыреттерін қайта қарау мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/59629/rus
