act_code: '38280'
requisite: Указ Президента Республики Казахстан от 11 марта 2008 года № 552
title:
  rus: Об утверждении Положения об Администрации Президента Республики Казахстан
  kaz: Қазақстан Республикасы Президентінің Әкімшілігі туралы ережені бекіту туралы
form: УКАЗ
type_codes:
- ПОЛ
- УКАЗ
approved_on: 2008-03-11
approved_by:
- '101000000000'
version_date:
  kaz: 2024-01-03
  rus: 2024-01-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/38280/kaz/03.01.2024
  rus: https://zan.gov.kz/client/#!/doc/38280/rus/03.01.2024
caused_by:
  code: '191794'
  requisite: Указ Президента Республики Казахстан от 3 января 2024 года № 429
  title:
    rus: О внесении изменений и дополнений в некоторые акты Президента Республики Казахстан и признании утратившими силу некоторых актов Президента Республики Казахстан
    kaz: Қазақстан Республикасы Президентінің кейбір актілеріне өзгерістер мен толықтырулар енгізу және Қазақстан Республикасы Президентінің кейбір актілерінің күші жойылды деп тану туралы
  link: https://zan.gov.kz/client/#!/doc/191794/rus
