act_code: '38280'
requisite: Указ Президента Республики Казахстан от 11 марта 2008 года № 552
title:
  rus: Об утверждении Положения об Администрации Президента Республики Казахстан
  kaz: Қазақстан Республикасы Президентінің Әкімшілігі туралы ережені бекіту туралы
form: УКАЗ
type_codes:
- ПОЛ
- УКАЗ
approved_on: 2008-03-11
approved_by:
- '101000000000'
version_date:
  kaz: 2020-09-08
  rus: 2020-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/38280/kaz/08.09.2020
  rus: https://zan.gov.kz/client/#!/doc/38280/rus/08.09.2020
caused_by:
  code: '146181'
  requisite: Указ Президента Республики Казахстан от 8 сентября 2020 года № 407
  title:
    rus: О мерах по дальнейшему совершенствованию системы государственного управления Республики Казахстан
    kaz: Қазақстан Республикасының мемлекеттік басқару жүйесін одан әрі жетілдіру жөніндегі шаралар туралы
  link: https://zan.gov.kz/client/#!/doc/146181/rus
