act_code: '14456'
requisite: Закон Республики Казахстан от 8 февраля 2003 года № 384-II
title:
  rus: О ратификации Рамочного соглашения Организации экономического сотрудничества по транзитным перевозкам и Протокола о подписании текстов Приложений к Рамочному соглашению Организации экономического сотрудничества по транзитным перевозкам
  kaz: Транзиттік тасымалдар жөніндегі Экономикалық Ынтымақтастық Ұйымының Негізгі келісімін және Транзиттік тасымалдар жөніндегі Экономикалық Ынтымақтастық Ұйымының Негізгі келісіміне Қосымшалардың мәтіндеріне қол қою туралы Хаттаманы бекіту туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2003-02-08
approved_by:
- '102000000000'
version_date:
  kaz: 2003-02-08
  rus: 2003-02-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/14456/kaz/08.02.2003
  rus: https://zan.gov.kz/client/#!/doc/14456/rus/08.02.2003
