act_code: '59543'
requisite: Постановление Правительства Республики Казахстан от 30 июня 2011 года № 733
title:
  rus: Об утверждении Соглашения между Правительством Республики Казахстан и Правительством Словацкой Республики об экономическом и научно-техническом сотрудничестве
  kaz: Қазақстан Республикасының Үкіметі мен Словакия Республикасының Үкіметі арасындағы Экономикалық және ғылыми-техникалық ынтымақтастық туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2011-06-30
approved_by:
- '103000000000'
version_date:
  kaz: 2011-06-30
  rus: 2011-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/59543/kaz/30.06.2011
  rus: https://zan.gov.kz/client/#!/doc/59543/rus/30.06.2011
