act_code: '34477'
requisite: Закон Республики Казахстан от 21 июля 2007 года N 303-III. Утратил силу Законом Республики Казахстан от 4 декабря 2015 года № 434-V ЗРК
title:
  rus: О государственных закупках
  kaz: Мемлекеттік сатып алу туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2007-07-21
approved_by:
- '102000000000'
version_date:
  kaz: 2014-12-10
  rus: 2014-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/34477/kaz/10.12.2014
  rus: https://zan.gov.kz/client/#!/doc/34477/rus/10.12.2014
caused_by:
  code: '84946'
  requisite: Закон Республики Казахстан от 10 декабря 2014 года № 264-V ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам официальной помощи развитию
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне дамуға ресми көмек мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/84946/rus
