act_code: '100255'
requisite: Закон Республики Казахстан от 18 марта 2016 года № 474-V ЗРК
title:
  rus: О ратификации Протокола о региональной готовности, реагировании и сотрудничестве в случае инцидентов, вызывающих загрязнение нефтью, к Рамочной конвенции по защите морской среды Каспийского моря
  kaz: Каспий теңізінің теңіз ортасын қорғау жөніндегі негіздемелік конвенцияға Мұнаймен ластануға әкелетін тосын оқиғалар жағдайындағы өңірлік әзірлік, ден қою және ынтымақтастық туралы хаттаманы ратификациялау туралы
form: ПРОТ
type_codes:
- ЗАК
- ПРОТ
approved_on: 2016-03-18
approved_by:
- '102000000000'
version_date:
  kaz: 2016-03-18
  rus: 2016-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/100255/kaz/18.03.2016
  rus: https://zan.gov.kz/client/#!/doc/100255/rus/18.03.2016
