act_code: '35943'
requisite: Закон Республики Казахстан от 27 ноября 2007 года N 3-IV
title:
  rus: О ратификации Соглашения между Правительством Республики Казахстан и Евразийским экономическим сообществом об условиях пребывания Интеграционного Комитета Евразийского экономического сообщества на территории Республики Казахстан
  kaz: Қазақстан Республикасының аумағында Еуразиялық экономикалық қоғамдастығы Интеграциялық Комитетінің болу жағдайлары туралы Қазақстан Республикасының Үкіметі мен Еуразиялық экономикалық қоғамдастығы арасындағы келісімді ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2007-11-27
approved_by:
- '102000000000'
version_date:
  kaz: 2007-11-27
  rus: 2007-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/35943/kaz/27.11.2007
  rus: https://zan.gov.kz/client/#!/doc/35943/rus/27.11.2007
