act_code: '84254'
requisite: Закон Республики Казахстан от 28 июня 1995 г. № 2350. Утратил силу Законом Республики Казахстан от 24 июня 2010 года № 291-IV (вводится в действие с 05.07.2010)
title:
  rus: О нефти
  kaz: Мұнай туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1995-06-27
approved_by:
- '101000000000'
version_date:
  kaz: 2006-12-29
  rus: 2006-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/84254/kaz/29.12.2006
  rus: https://zan.gov.kz/client/#!/doc/84254/rus/29.12.2006
caused_by:
  code: '31066'
  requisite: Закон Республики Казахстан от 29 декабря 2006 года № 209
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам технического регулирования
    kaz: Қазақстан Республикасының кейбiр заңнамалық актілеріне техникалық реттеу мәселелерi бойынша өзгерiстер мен толықтырулар енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/31066/rus
