act_code: '131699'
requisite: Постановление Правительства Республики Казахстан от 22 мая 2019 года № 308
title:
  rus: Об утверждении Соглашения об использовании систем спутниковой связи военного назначения и их дальнейшем совершенствовании
  kaz: Әскери мақсаттағы спутниктік байланыс жүйелерін пайдалану және оларды одан әрі жетілдіру туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2019-05-22
approved_by:
- '103000000000'
version_date:
  kaz: 2019-05-22
  rus: 2019-05-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/131699/kaz/22.05.2019
  rus: https://zan.gov.kz/client/#!/doc/131699/rus/22.05.2019
