act_code: '35883'
requisite: Постановление Правительства Республики Казахстан от 26 ноября 2007 года N 1128
title:
  rus: Об утверждении Соглашения о подготовке кадров для органов внутренних дел (полиции) и внутренних войск государств-участников Содружества Независимых Государств
  kaz: Тәуелсіз Мемлекеттер Достастығына қатысушы мемлекеттердің ішкі істер органдары (полиция) мен ішкі әскерлері үшін кадрлар даярлау туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2007-11-26
approved_by:
- '103000000000'
version_date:
  kaz: 2007-11-26
  rus: 2007-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/35883/kaz/26.11.2007
  rus: https://zan.gov.kz/client/#!/doc/35883/rus/26.11.2007
