act_code: '3743'
requisite: Утверждены постановлением Государственного комитета Республики Казахстан по инвестициям от 13 июня 1997 г. № 20. Зарегистрированы в Министерстве юстиции Республики Казахстан 20 октября 1997 г. № 410. Утратили силу - постановлением Госкомитета РК по инвестициям от 7 августа 1998г. № 131
title:
  rus: Методические указания по порядку предоставления льгот и преференций, определению их размеров и сроков
  kaz: '"Жеңiлдiктер мен преференцияларды берудiң, олардың мөлшерлерi мен мерзiмдерiн айқындаудың тәртiбi жөнiндегi әдiстемелiк нұсқаулықтарды" бекiту туралы'
form: УКЗН
type_codes:
- УКЗН
approved_on: 1997-06-12
approved_by:
- '103004001000'
version_date:
  rus: 1997-06-12
source:
  rus: https://zan.gov.kz/client/#!/doc/3743/rus/12.06.1997
