act_code: '2873'
requisite: Указ Президента Республики Казахстан от 19 мая 1999 года № 141
title:
  rus: Об утверждении Соглашения между Республикой Казахстан и Святым Престолом о взаимоотношениях
  kaz: Қазақстан Республикасы мен Қасиетті Тақ арасындағы Өзара қатынастар туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- СОГЛ
- УКАЗ
approved_on: 1999-05-18
approved_by:
- '101000000000'
version_date:
  kaz: 1999-05-18
  rus: 1999-05-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/2873/kaz/18.05.1999
  rus: https://zan.gov.kz/client/#!/doc/2873/rus/18.05.1999
