act_code: '1561'
requisite: Закон Республики Казахстан от 20 ноября 1998 года № 304-I
title:
  rus: Об аудиторской деятельности
  kaz: Аудиторлық қызмет туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1998-11-20
approved_by:
- '102000000000'
version_date:
  kaz: 2024-09-01
  rus: 2024-09-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/1561/kaz/01.09.2024
  rus: https://zan.gov.kz/client/#!/doc/1561/rus/01.09.2024
caused_by:
  code: '198416'
  requisite: Закон Республики Казахстан от 1 июля 2024 года № 107-VIII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам закупок и исключения излишней законодательной регламентации
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне сатып алу және артық заңнамалық регламенттеуді болғызбау мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/198416/rus
