act_code: '9940'
requisite: Постановление Правительства Республики Казахстан от 11 сентября 2001 года N 1174
title:
  rus: О заключении Соглашения о Технической помощи (грант) между Правительством Республики Казахстан и Исламским Банком Развития по улучшению научной и экспериментальной базы Физико-технического института Министерства образования и науки Республики Казахстан
  kaz: Қазақстан Республикасының Үкіметі мен Ислам Даму Банкі арасында Қазақстан Республикасының Білім және ғылым министрлігі Физика-техникалық институтының ғылыми және эксперименттік базасын жақсарту жөніндегі техникалық көмек (грант) туралы келісім жасасу туралы
type_codes:
- ПРОЕ
approved_on: 2001-09-10
approved_by:
- '103000000000'
version_date:
  kaz: 2001-09-10
  rus: 2001-09-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/9940/kaz/10.09.2001
  rus: https://zan.gov.kz/client/#!/doc/9940/rus/10.09.2001
