act_code: '3736'
requisite: Утверждено Постановлением Национальной комиссии Республики Казахстан по ценным бумагам от 29 августа 1997 г. N 133. Зарегистрировано в Министерстве юстиции Республики Казахстан 9 сентября 1997 года N 362. Утратило силу - постановлением НКЦБ РК от 13 августа 1998г. N 11
title:
  rus: ПОЛОЖЕНИЕ об инвестиционной деятельности компаний по управлению пенсионными активами
  kaz: Зейнетақы активтерiн басқару жөнiндегi компанияның инвестициялық қызметi туралы Ереже
type_codes:
- ПОЛ
approved_on: 1997-08-28
approved_by:
- '111000000000'
version_date:
  rus: 1997-08-28
source:
  rus: https://zan.gov.kz/client/#!/doc/3736/rus/28.08.1997
