act_code: '5734'
requisite: Указ Президента Республики Казахстан от 13 апреля 2000 года N 371
title:
  rus: Об утверждении Перечня должностных лиц государственных органов, наделенных полномочиями по отнесению сведений к государственным секретам Республики Казахстан
  kaz: Мемлекеттік органдардың мәліметтерді Қазақстан Республикасының мемлекеттік құпияларына жатқызу жөніндегі өкілеттіктер берілген лауазымды тұлғаларының тізбесін бекіту туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2000-04-13
approved_by:
- '101000000000'
version_date:
  kaz: 2019-09-18
  rus: 2019-09-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/5734/kaz/18.09.2019
  rus: https://zan.gov.kz/client/#!/doc/5734/rus/18.09.2019
caused_by:
  code: '134851'
  requisite: Указ Президента Республики Казахстан от 18 сентября 2019 года № 163
  title:
    rus: О некоторых вопросах Комитета национальной безопасности Республики Казахстан
    kaz: Қазақстан Республикасы Ұлттық қауіпсіздік комитетінің кейбір мәселелері туралы
  link: https://zan.gov.kz/client/#!/doc/134851/rus
