act_code: '203557'
requisite: Постановление Правительства Республики Казахстан от 27 ноября 2024 года № 1006
title:
  rus: Об утверждении Соглашения между Правительством Республики Казахстан и Правительством Ливанской Республики об освобождении от визовых требований владельцев дипломатических, служебных и специальных паспортов
  kaz: Қазақстан Республикасының Үкіметі мен Ливан Республикасының Үкіметі арасындағы дипломатиялық, қызметтік және арнайы паспорттардың иелерін визалық талаптардан босату туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2024-11-27
approved_by:
- '103000000000'
version_date:
  kaz: 2024-11-27
  rus: 2024-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/203557/kaz/27.11.2024
  rus: https://zan.gov.kz/client/#!/doc/203557/rus/27.11.2024
