act_code: '3469'
requisite: Закон Республики Казахстан от 23 июня 1999 года № 397-I
title:
  rus: О ратификации Соглашения между Правительством Республики Казахстан и Правительством Федеративной Республики Германия о направлении германских преподавателей в школы Республики Казахстан
  kaz: Қазақстан Республикасының Үкіметі мен Германия Федеративтік Республикасының Үкіметі арасындағы Қазақстан Республикасының мектептеріне герман оқытушыларын жіберу туралы келісімді бекіту туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 1999-06-22
approved_by:
- '102000000000'
version_date:
  kaz: 1999-06-22
  rus: 1999-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/3469/kaz/22.06.1999
  rus: https://zan.gov.kz/client/#!/doc/3469/rus/22.06.1999
