act_code: '330'
requisite: Закон Республики Казахстан от 2 декабря 1997 г. № 193
title:
  rus: О ратификации Консульской Конвенции между Республикой Казахстан и Республикой Беларусь
  kaz: Қазақстан Республикасы мен Беларусь Республикасы арасындағы Консулдық конвенцияны бекiту туралы
form: КОНВ
type_codes:
- ЗАК
- КОНВ
approved_on: 1997-12-02
approved_by:
- '102000000000'
version_date:
  kaz: 1997-12-02
  rus: 1997-12-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/330/kaz/02.12.1997
  rus: https://zan.gov.kz/client/#!/doc/330/rus/02.12.1997
