act_code: '205239'
requisite: Нормативное постановление Конституционного Суда Республики Казахстан от 27 декабря 2024 года № 60-НП
title:
  rus: О рассмотрении на соответствие Конституции Республики Казахстан части второй статьи 109, подпункта 2) части первой статьи 134 Уголовно-исполнительного кодекса Республики Казахстан от 5 июля 2014 года и пункта 104 Правил внутреннего распорядка учреждений уголовно-исполнительной системы, утвержденных приказом Министра внутренних дел Республики Казахстан от 17 ноября 2014 года № 819
  kaz: 2014 жылғы 5 шілдедегі Қазақстан Республикасы Қылмыстық-атқару кодексінің 109-бабы екінші бөлігінің, 134-бабы бірінші бөлігі 2) тармақшасының және Қазақстан Республикасы Ішкі істер министрінің 2014 жылғы 17 қарашадағы № 819 бұйрығымен бекітілген Қылмыстық-атқару жүйесі мекемелерінің ішкі тәртіптеме қағидаларының 104-тармағының Қазақстан Республикасының Конституциясына сәйкестігін қарау туралы
form: НПОС
type_codes:
- НПОС
approved_on: 2024-12-27
approved_by:
- '106000000000'
version_date:
  kaz: 2024-12-27
  rus: 2024-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/205239/kaz/27.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205239/rus/27.12.2024
