act_code: '8745'
requisite: Закон Республики Казахстан от 25 апреля 2001 года № 178
title:
  rus: О Банке Развития Казахстана
  kaz: Қазақстанның Даму Банкі туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2001-04-25
approved_by:
- '102000000000'
version_date:
  kaz: 2005-12-23
  rus: 2005-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/8745/kaz/23.12.2005
  rus: https://zan.gov.kz/client/#!/doc/8745/rus/23.12.2005
caused_by:
  code: '26294'
  requisite: Закон Республики Казахстан от 23 декабря 2005 года № 108
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам деятельности Банка Развития Казахстана
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне Қазақстанның Даму Банкі қызметінің мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/26294/rus
