act_code: '8745'
requisite: Закон Республики Казахстан от 25 апреля 2001 года № 178
title:
  rus: О Банке Развития Казахстана
  kaz: Қазақстанның Даму Банкі туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2001-04-25
approved_by:
- '102000000000'
version_date:
  kaz: 2004-12-13
  rus: 2004-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/8745/kaz/13.12.2004
  rus: https://zan.gov.kz/client/#!/doc/8745/rus/13.12.2004
caused_by:
  code: '22238'
  requisite: Закон Республики Казахстан от 13 декабря 2004 года N 11
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам налогообложения
    kaz: Қазақстан Республикасының кейбiр заңнамалық актiлерiне салық салу мәселелерi бойынша өзгерiстер мен толықтырулар енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/22238/rus
