act_code: '8745'
requisite: Закон Республики Казахстан от 25 апреля 2001 года № 178
title:
  rus: О Банке Развития Казахстана
  kaz: Қазақстанның Даму Банкі туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2001-04-25
approved_by:
- '102000000000'
version_date:
  kaz: 2003-07-09
  rus: 2003-07-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/8745/kaz/09.07.2003
  rus: https://zan.gov.kz/client/#!/doc/8745/rus/09.07.2003
caused_by:
  code: '16307'
  requisite: Закон Республики Казахстан от 10 июля 2003 года № 483-ІІ
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам организации единой системы государственного регулирования и надзора финансового рынка и финансовых организаций
    kaz: Қазақстан Республикасының кейбiр заң актiлерiне қаржы рыногын және қаржылық ұйымдарды мемлекеттiк реттеу мен қадағалаудың бiрыңғай жүйесiн ұйымдастыру мәселелерi бойынша өзгерiстер мен толықтырулар енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/16307/rus
