act_code: '23188'
requisite: Постановление Правительства Республики Казахстан от 15 марта 2005 года N 232
title:
  rus: Об утверждении Соглашения между Правительством Республики Казахстан и Правительством Республики Польша о сотрудничестве в борьбе с организованной преступностью и иными видами преступлений
  kaz: Қазақстан Республикасының Yкiметi мен Польша Республикасының Үкiметi арасындағы Ұйымдасқан қылмысқа және қылмыстардың өзге де түрлерiне қарсы күрестегi ынтымақтастық туралы келiсiмдi бекiту туралы
form: СОГЛ
type_codes:
- ПОСТ
- СОГЛ
approved_on: 2005-03-15
approved_by:
- '103000000000'
version_date:
  kaz: 2005-03-15
  rus: 2005-03-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/23188/kaz/15.03.2005
  rus: https://zan.gov.kz/client/#!/doc/23188/rus/15.03.2005
