act_code: '1343'
requisite: Приказ Министра транспорта и коммуникаций Республики Казахстан от 18 июня 1998 года N 123. Зарегистрирован в Министерстве юстиции Республики Казахстан 27.07.1998 г. N 554. Утратил силу - приказом Министра транспорта и коммуникаций РК от 30.12.2004г. N 491-I. Отменен - постановлением Правительства РК от 9 февраля 2005 года N 124
title:
  rus: Об утверждении Положения о порядке организации и проведения конкурсов (подрядных торгов) на дорожные работы
  kaz: Жол жұмыстарына конкурс (мердігерлік сауда-саттық) ұйымдастыру мен өткізу тәртібі туралы ЕРЕЖЕ
type_codes:
- ПОЛ
approved_on: 1998-06-17
approved_by:
- '103013000000'
version_date:
  kaz: 1998-06-17
  rus: 1998-06-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/1343/kaz/17.06.1998
  rus: https://zan.gov.kz/client/#!/doc/1343/rus/17.06.1998
