act_code: '165949'
requisite: Закон Республики Казахстан от 1 апреля 2022 года № 113-VII ЗРК
title:
  rus: О ратификации Соглашения о взаимной правовой помощи по административным вопросам в сфере обмена персональными данными
  kaz: Дербес деректер алмасу саласындағы әкімшілік мәселелер бойынша өзара құқықтық көмек туралы келісімді ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2022-04-01
approved_by:
- '102000000000'
version_date:
  kaz: 2022-04-01
  rus: 2022-04-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/165949/kaz/01.04.2022
  rus: https://zan.gov.kz/client/#!/doc/165949/rus/01.04.2022
