act_code: '139615'
requisite: Закон Республики Казахстан от 13 февраля 2020 года № 301-VІ ЗРК
title:
  rus: О ратификации Протокола о запрещении применения на войне удушающих, ядовитых или других подобных газов и бактериологических средств
  kaz: Тұншықтыратын, улы немесе басқа да осыларға ұқсас газдар мен бактериологиялық құралдарды соғыста қолдануға тыйым салу туралы хаттаманы ратификациялау туралы
form: ПРОТ
type_codes:
- ЗАК
- ПРОТ
approved_on: 2020-02-13
approved_by:
- '102000000000'
version_date:
  kaz: 2020-02-13
  rus: 2020-02-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/139615/kaz/13.02.2020
  rus: https://zan.gov.kz/client/#!/doc/139615/rus/13.02.2020
