act_code: '72356'
requisite: Указ Президента Республики Казахстан от 6 мая 2013 года № 560
title:
  rus: О присвоении высших воинских и специальных званий, классных чинов
  kaz: Жоғары әскери және арнаулы атақтар, сыныптық шендер беру туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2013-05-06
approved_by:
- '101000000000'
version_date:
  kaz: 2013-05-06
  rus: 2013-05-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/72356/kaz/06.05.2013
  rus: https://zan.gov.kz/client/#!/doc/72356/rus/06.05.2013
