act_code: '18098'
requisite: Указ Президента Республики Казахстан от 31 декабря 2003 года № 1271
title:
  rus: Об утверждении Положения и структуры Национального Банка Республики Казахстан
  kaz: Қазақстан Республикасы Ұлттық Банкiнiң ережесiн және құрылымын бекiту туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2003-12-31
approved_by:
- '101000000000'
version_date:
  rus: 2011-04-18
source:
  rus: https://zan.gov.kz/client/#!/doc/18098/rus/18.04.2011
caused_by:
  code: '58390'
  requisite: Указ Президента Республики Казахстан от 18 апреля 2011 года № 61
  title:
    rus: О некоторых вопросах Национального Банка Республики Казахстан
    kaz: Қазақстан Республикасы Ұлттық Банкінің кейбір мәселелері туралы
  link: https://zan.gov.kz/client/#!/doc/58390/rus
