act_code: '18098'
requisite: Указ Президента Республики Казахстан от 31 декабря 2003 года № 1271
title:
  rus: Об утверждении Положения и структуры Национального Банка Республики Казахстан
  kaz: Қазақстан Республикасы Ұлттық Банкiнiң ережесiн және құрылымын бекiту туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2003-12-31
approved_by:
- '101000000000'
version_date:
  kaz: 2025-11-20
  rus: 2025-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/18098/kaz/20.11.2025
  rus: https://zan.gov.kz/client/#!/doc/18098/rus/20.11.2025
caused_by:
  code: '216062'
  requisite: Указ Президента Республики Казахстан от 24 октября 2025 года № 1066
  title:
    rus: О внесении изменений в Указ Президента Республики Казахстан от 31 декабря 2003 года № 1271 «Об утверждении Положения и структуры Национального Банка Республики Казахстан»
    kaz: «Қазақстан Республикасы Ұлттық Банкiнiң ережесiн және құрылымын бекiту туралы» Қазақстан Республикасы Президентінің 2003 жылғы 31 желтоқсандағы № 1271 Жарлығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/216062/rus
