act_code: '18098'
requisite: Указ Президента Республики Казахстан от 31 декабря 2003 года № 1271
title:
  rus: Об утверждении Положения и структуры Национального Банка Республики Казахстан
  kaz: Қазақстан Республикасы Ұлттық Банкiнiң ережесiн және құрылымын бекiту туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2003-12-31
approved_by:
- '101000000000'
version_date:
  rus: 2003-12-31
source:
  rus: https://zan.gov.kz/client/#!/doc/18098/rus/31.12.2003
