act_code: '3418'
requisite: Утверждены приказом Таможенного комитета Республики Казахстан от 5 июня 1996 года № 120-П Зарегистрирован в Министерстве юстиции Республики Казахстан 23.06.1996 г. за № 187. у.с. - приказом Таможенного комитета МГД РК от 9.02.2001г. № 46
title:
  rus: Пpавила учpеждения таможенных складов таможенными оpганами Республики Казахстан и использования таких складов
  kaz: Қазақстан Республикасы кеден органдарының кеден қоймаларын құруының және осындай қоймаларды пайдаланудың ережелерiн бекiту туралы
type_codes:
- ПРАВ
approved_on: 1996-06-04
approved_by:
- '103002004000'
version_date:
  rus: 1996-06-04
source:
  rus: https://zan.gov.kz/client/#!/doc/3418/rus/04.06.1996
