act_code: '61774'
requisite: Указ Президента Республики Казахстан от 24 ноября 2011 года № 181
title:
  rus: О создании специальной экономической зоны "Сарыарқа"
  kaz: '"Сарыарқа" арнайы экономикалық аймағын құру туралы'
form: УКАЗ
type_codes:
- ПОЛ
- УКАЗ
approved_on: 2011-11-24
approved_by:
- '101000000000'
version_date:
  kaz: 2015-10-02
  rus: 2015-10-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/61774/kaz/02.10.2015
  rus: https://zan.gov.kz/client/#!/doc/61774/rus/02.10.2015
caused_by:
  code: '94319'
  requisite: Указ Президента Республики Казахстан от 2 октября 2015 года № 95
  title:
    rus: О внесении изменений в Указ Президента Республики Казахстан от 24 ноября 2011 года № 181 "О создании специальной экономической зоны "Сарыарқа"
    kaz: '"Сарыарқа" арнайы экономикалық аймағын құру туралы" Қазақстан Республикасы Президентінің 2011 жылғы 24 қарашадағы № 181 Жарлығына өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/94319/rus
