act_code: '1792'
requisite: Постановление Министерства труда Республики Казахстан от 20 мая 1994 г. N 58. Зарегистрировано в Министерстве юстиции Республики Казахстан 24.11.1994 г. N 22. Утратило силу - приказом Министра труда и социальной защиты населения РК от 4.04.2005г. N 86-п
title:
  rus: Об утверждении Разъяснения к Положению "О порядке выплаты надбавок за выслугу лет к должностным окладам работников органов государственного управления Республики Казахстан"
  kaz: '"Қазақстан Республикасының мемлекеттiк басқару органдары қызметкерлерiне көп жылдық сiңiрген еңбегi үшiн лауазымдық жалақыларына үстеме ақы төлеудiң тәртiбi туралы" ережеге түсiнiктеменi бекiту туралы'
type_codes:
- РАЗ
approved_on: 1994-05-19
approved_by:
- '103016000000'
version_date:
  kaz: 1994-05-19
  rus: 1994-05-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/1792/kaz/19.05.1994
  rus: https://zan.gov.kz/client/#!/doc/1792/rus/19.05.1994
