act_code: '11286'
requisite: Указ Президента Республики Казахстан от 11 февраля 2002 года N 805. Утратил силу Указом Президента Республики Казахстан от 11 марта 2008 года N 552.
title:
  rus: Об утверждении Положения об Администрации Президента Республики Казахстан
  kaz: Қазақстан Республикасы Президентінің Әкімшілігі туралы ережені бекіту туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2002-02-11
approved_by:
- '101000000000'
version_date:
  kaz: 2005-03-23
  rus: 2005-03-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/11286/kaz/23.03.2005
  rus: https://zan.gov.kz/client/#!/doc/11286/rus/23.03.2005
caused_by:
  code: '23934'
  requisite: Указ Президента Республики Казахстан от 23 марта 2005 года № 1528. Утратил силу Указом Президента Республики Казахстан от 29 декабря 2015 года № 152
  title:
    rus: О внесении изменений и дополнений в некоторые указы Президента Республики Казахстан
    kaz: Қазақстан Республикасы Президентiнiң кейбiр жарлықтарына өзгерiстер мен толықтырулар енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/23934/rus
