act_code: '11286'
requisite: Указ Президента Республики Казахстан от 11 февраля 2002 года N 805. Утратил силу Указом Президента Республики Казахстан от 11 марта 2008 года N 552.
title:
  rus: Об утверждении Положения об Администрации Президента Республики Казахстан
  kaz: Қазақстан Республикасы Президентінің Әкімшілігі туралы ережені бекіту туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2002-02-11
approved_by:
- '101000000000'
version_date:
  kaz: 2004-04-22
  rus: 2004-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/11286/kaz/22.04.2004
  rus: https://zan.gov.kz/client/#!/doc/11286/rus/22.04.2004
caused_by:
  code: '19499'
  requisite: Указ Президента Республики Казахстан от 23 апреля 2004 года № 1351. Утратил силу Указом Президента Республики Казахстан от 11 марта 2008 года № 552
  title:
    rus: О внесении дополнений и изменений в Указ Президента Республики Казахстан от 11 февраля 2002 года № 805
    kaz: Қазақстан Республикасы Президентінің 2002 жылғы 11 ақпандағы № 805 Жарлығына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/19499/rus
