act_code: '144041'
requisite: Закон Республики Казахстан от 15 июня 2020 года № 345-VI ЗРК
title:
  rus: О ратификации Соглашения об обмене информацией о товарах и транспортных средствах международной перевозки, перемещаемых через таможенные границы Евразийского экономического союза и Китайской Народной Республики
  kaz: Еуразиялық экономикалық одақ пен Қытай Халық Республикасының кедендік шекаралары арқылы өткізілетін тауарлар мен халықаралық тасымалдың көлік құралдары жөнінде ақпарат алмасу туралы келісімді ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2020-06-15
approved_by:
- '102000000000'
version_date:
  kaz: 2020-06-15
  rus: 2020-06-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/144041/kaz/15.06.2020
  rus: https://zan.gov.kz/client/#!/doc/144041/rus/15.06.2020
