act_code: '77515'
requisite: Указ Президента Республики Казахстан от 28 августа 2013 года № 624
title:
  rus: О формировании Президентского кадрового резерва специальных государственных органов Республики Казахстан
  kaz: Қазақстан Республикасы арнаулы мемлекеттік органдарының президенттік кадр резервін қалыптастыру туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 2013-08-28
approved_by:
- '101000000000'
version_date:
  kaz: 2019-04-17
  rus: 2019-04-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/77515/kaz/17.04.2019
  rus: https://zan.gov.kz/client/#!/doc/77515/rus/17.04.2019
caused_by:
  code: '130706'
  requisite: Указ Президента Республики Казахстан от 17 апреля 2019 года № 26
  title:
    rus: О внесении изменений и дополнений в некоторые акты Президента Республики Казахстан и признании утратившими силу некоторых актов Президента Республики Казахстан
    kaz: Қазақстан Республикасы Президентінің кейбір актілеріне өзгерістер мен толықтырулар енгізу және Қазақстан Республикасы Президентінің кейбір актілерінің күші жойылды деп тану туралы
  link: https://zan.gov.kz/client/#!/doc/130706/rus
