act_code: '104201'
requisite: Закон Республики Казахстан от 16 июня 1997 года № 127-I
title:
  rus: О мобилизационной подготовке и мобилизации
  kaz: Жұмылдыру дайындығы мен жұмылдыру туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1997-06-16
approved_by:
- '102000000000'
version_date:
  kaz: 2011-10-13
  rus: 2011-10-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/104201/kaz/13.10.2011
  rus: https://zan.gov.kz/client/#!/doc/104201/rus/13.10.2011
caused_by:
  code: '59629'
  requisite: Закон Республики Казахстан от 5 июля 2011 года № 452-IV
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам пересмотра компетенции уполномоченных государственных органов и Правительства Республики Казахстан на принятие нормативных правовых актов, устанавливающих требования к проверяемым субъектам
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне уәкілетті мемлекеттік органдар мен Қазақстан Республикасы Үкіметінің тексерілетін субъектілерге қойылатын талаптарды белгілейтін нормативтік құқықтық актілерді қабылдау құзыреттерін қайта қарау мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/59629/rus
