act_code: '16159'
requisite: Закон Республики Казахстан от 2 июля 2003 года № 461
title:
  rus: О рынке ценных бумаг
  kaz: Бағалы қағаздар рыногы туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2003-07-02
approved_by:
- '102000000000'
version_date:
  kaz: 2005-07-08
  rus: 2005-07-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/16159/kaz/08.07.2005
  rus: https://zan.gov.kz/client/#!/doc/16159/rus/08.07.2005
caused_by:
  code: '24777'
  requisite: Закон Республики Казахстан от 8 июля 2005 года № 72
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам рынка ценных бумаг и акционерных обществ
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне бағалы қағаздар нарығы және акционерлік қоғамдар мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/24777/rus
