act_code: '31308'
requisite: Кодекс Республики Казахстан от 9 января 2007 года № 212. Утратил силу Кодексом Республики Казахстан от 2 января 2021 года № 400-VI (вводится в действие с 1 июля 2021 года)
title:
  rus: Экологический кодекс Республики Казахстан
  kaz: Қазақстан Республикасының Экологиялық кодексі
form: КОД
type_codes:
- КОД
approved_on: 2007-01-09
approved_by:
- '102000000000'
version_date:
  kaz: 2009-06-23
  rus: 2009-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/31308/kaz/23.06.2009
  rus: https://zan.gov.kz/client/#!/doc/31308/rus/23.06.2009
caused_by:
  code: '46632'
  requisite: Закон Республики Казахстан от 23 июня 2009 года № 164-IV
  title:
    rus: О внесении изменений и дополнений в Экологический кодекс Республики Казахстан по вопросам регулирования ввоза экологически опасных технологий, техники и оборудования
    kaz: Қазақстан Республикасының Экологиялық кодексіне экологиялық қауіпті технологияларды, техника мен жабдықты әкелуді реттеу мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/46632/rus
