act_code: '48241'
requisite: Постановление Правительства Республики Казахстан от 22 октября 2009 года № 1643
title:
  rus: Об утверждении Протокола об обеспечении единообразного применения правил определения таможенной стоимости товаров, перемещаемых через таможенную границу таможенного союза
  kaz: Кеден одағының кедендік шекарасы арқылы өткізілетін тауарлардың кедендік құнын айқындаудың ережесін біркелкі қолдануды қамтамасыз ету туралы хаттаманы бекіту туралы
form: ПРОТ
type_codes:
- ПОСТ
- ПРОТ
approved_on: 2009-10-22
approved_by:
- '103000000000'
version_date:
  kaz: 2009-10-22
  rus: 2009-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/48241/kaz/22.10.2009
  rus: https://zan.gov.kz/client/#!/doc/48241/rus/22.10.2009
