act_code: '205236'
requisite: Закон Республики Казахстан от 24 декабря 2024 года № 147-VIII ЗРК
title:
  rus: О ратификации Соглашения о свободной торговле между Евразийским экономическим союзом и его государствами-членами, с одной стороны, и Исламской Республикой Иран, с другой стороны
  kaz: Бір тараптан Еуразиялық экономикалық одақ пен оған мүше мемлекеттер және екінші тараптан Иран Ислам Республикасы арасындағы еркін сауда туралы келісімді ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2024-12-24
approved_by:
- '102000000000'
version_date:
  kaz: 2024-12-24
  rus: 2024-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/205236/kaz/24.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205236/rus/24.12.2024
