act_code: '94981'
requisite: Кодекс Республики Казахстан от 29 октября 2015 года № 375-V ЗРК
title:
  rus: Предпринимательский кодекс Республики Казахстан
  kaz: Қазақстан Республикасының Кәсіпкерлік Кодексі
form: КОД
type_codes:
- КОД
approved_on: 2015-10-29
approved_by:
- '102000000000'
version_date:
  kaz: 2019-04-09
  rus: 2019-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/94981/kaz/09.04.2019
  rus: https://zan.gov.kz/client/#!/doc/94981/rus/09.04.2019
caused_by:
  code: '127931'
  requisite: Закон Республики Казахстан от 28 декабря 2018 года № 211-VІ ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам обращения лекарственных средств и медицинских изделий
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне дәрілік заттар мен медициналық бұйымдардың айналысы мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/127931/rus
