act_code: '94981'
requisite: Кодекс Республики Казахстан от 29 октября 2015 года № 375-V ЗРК
title:
  rus: Предпринимательский кодекс Республики Казахстан
  kaz: Қазақстан Республикасының Кәсіпкерлік Кодексі
form: КОД
type_codes:
- КОД
approved_on: 2015-10-29
approved_by:
- '102000000000'
version_date:
  kaz: 2016-01-14
  rus: 2016-01-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/94981/kaz/14.01.2016
  rus: https://zan.gov.kz/client/#!/doc/94981/rus/14.01.2016
caused_by:
  code: '97539'
  requisite: Закон Республики Казахстан от 14 января 2016 года № 445-V ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам драгоценных металлов и драгоценных камней
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне бағалы металдар мен асыл тастар мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/97539/rus
