act_code: '94981'
requisite: Кодекс Республики Казахстан от 29 октября 2015 года № 375-V ЗРК
title:
  rus: Предпринимательский кодекс Республики Казахстан
  kaz: Қазақстан Республикасының Кәсіпкерлік Кодексі
form: КОД
type_codes:
- КОД
approved_on: 2015-10-29
approved_by:
- '102000000000'
version_date:
  kaz: 2021-03-12
  rus: 2021-03-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/94981/kaz/12.03.2021
  rus: https://zan.gov.kz/client/#!/doc/94981/rus/12.03.2021
caused_by:
  code: '153474'
  requisite: Закон Республики Казахстан от 12 марта 2021 года № 15-VII ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам совершенствования нормотворчества
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне нормашығармашылықты жетілдіру мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/153474/rus
