act_code: '3732'
requisite: Закон Республики Казахстан от 2 августа 1999 года N 464. Утратил силу с 1 января 2005 года - Бюджетным кодексом Республики Казахстан от 24 апреля 2004 года N 548
title:
  rus: О государственном и гарантированном государством заимствовании и долге
  kaz: Мемлекеттік және мемлекет кепілдік берген қарыз алу мен борыш туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1999-08-01
approved_by:
- '102000000000'
version_date:
  rus: 2001-11-06
source:
  rus: https://zan.gov.kz/client/#!/doc/3732/rus/06.11.2001
caused_by:
  code: '10326'
  requisite: Закон Республики Казахстан от 6 ноября 2001 года  № 252-II
  title:
    rus: О внесении изменений и дополнений в Закон Республики Казахстан "О государственном и гарантированном государством заимствовании и долге"
    kaz: '"Мемлекеттік және мемлекет кепілдік берген қарыз алу мен борыш туралы" Қазақстан Республикасының Заңына өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/10326/rus
