act_code: '2975'
requisite: Распоряжение Акима Восточно-Казахстанской области № 1-629р от 25 мая 1999 года. Зарегистрировано управлением юстиции Восточно-Казахстанской области 27 мая 1999 года за № 189. Утратило силу - решением Акима Восточно-Казахстанской области от 28 апреля 2000 года № 852
title:
  rus: О проведении в 1999-2000 гг. двухмесячников по охране нерестующей рыбы
  kaz: 1999-2000 жылдары уылдырық шашатын балықты қорғау жөнінде екіайлык өткізу туралы
form: РАСП
type_codes:
- РАСП
approved_on: 1999-05-24
approved_by:
- '157000000003'
version_date:
  kaz: 1999-05-24
  rus: 1999-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/2975/kaz/24.05.1999
  rus: https://zan.gov.kz/client/#!/doc/2975/rus/24.05.1999
