act_code: '51792'
requisite: Закон Республики Казахстан от 2 апреля 2010 года № 261-IV
title:
  rus: Об исполнительном производстве и статусе судебных исполнителей
  kaz: Атқарушылық iс жүргiзу және сот орындаушыларының мәртебесi туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 2010-04-02
approved_by:
- '102000000000'
version_date:
  kaz: 2019-01-21
  rus: 2019-01-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/51792/kaz/21.01.2019
  rus: https://zan.gov.kz/client/#!/doc/51792/rus/21.01.2019
caused_by:
  code: '128623'
  requisite: Закон Республики Казахстан от 21 января 2019 года № 217-VІ ЗРК
  title:
    rus: О внесении изменений и дополнений в некоторые законодательные акты Республики Казахстан по вопросам усиления защиты права собственности, арбитража, оптимизации судебной нагрузки и дальнейшей гуманизации уголовного законодательства
    kaz: Қазақстан Республикасының кейбір заңнамалық актілеріне меншік құқығын қорғауды күшейту, төрелік, сот жүктемесін оңтайландыру және қылмыстық заңнаманы одан әрі ізгілендіру мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/128623/rus
