act_code: '2'
requisite: Закон Республики Казахстан от 24 апpеля 1995 года N 2235. Утратил силу Законом Республики Казахстан от 12 июня 2001 года N 210
title:
  rus: О налогах и других обязательных платежах в бюджет
  kaz: Заң күшi бар Салық және бюждетке төленетiн басқа да мiндеттi төлемдер туралы
form: ЗАК
type_codes:
- ЗАК
approved_on: 1995-04-23
approved_by:
- '101000000000'
version_date:
  rus: 1997-02-28
source:
  rus: https://zan.gov.kz/client/#!/doc/2/rus/28.02.1997
caused_by:
  code: '104441'
  requisite: Закон Республики Казахстан от 28 февраля 1997 года N 76-I ЗРК
  title:
    rus: О внесении изменений и дополнений в Указ Президента Республики Казахстан, имеющий силу Закона, "О налогах и других обязательных платежах в бюджет" и признании утратившими силу некоторых законодательных актов
    kaz: '"Салық және бюджетке төленетiн басқа да мiндеттi төлемдер туралы" Қазақстан Республикасы Президентiнiң Заң күшi бар Жарлығына өзгерiстер мен толықтырулар енгiзу және кейбiр заң актiлерiнiң күшi жойылды деп тану туралы'
  link: https://zan.gov.kz/client/#!/doc/104441/rus
