act_code: '82187'
requisite: Указ Президента Республики Казахстан от 29 декабря 1995 года № 2736
title:
  rus: О штандарте и порядке официального использования знаков отличия Президента Республики Казахстан
  kaz: Қазақстан Республикасы Президентiнiң байрағы және оның айырым белгiлерiнiң ресми пайдаланылу тәртiбi туралы
form: УКАЗ
type_codes:
- УКАЗ
approved_on: 1995-12-29
approved_by:
- '101000000000'
version_date:
  kaz: 1995-12-29
  rus: 1995-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/82187/kaz/29.12.1995
  rus: https://zan.gov.kz/client/#!/doc/82187/rus/29.12.1995
