act_code: '8371'
requisite: Приказ Министра внутренних дел Республики Казахстан от 16 февраля 2001 года № 141. Зарегистрирован в Министерстве юстиции Республики Казахстан 14 марта 2001 года № 1426. Утратил силу приказом Министра внутренних дел Республики Казахстан от 27 сентября 2012 года № 523
title:
  rus: Об утверждении Инструкции "О порядке выдачи разрешения на использование объектов и помещений в сфере оборота наркотических средств, психотропных веществ и прекурсоров"
  kaz: '"Есірткі құралдары, псиохотроптық заттар және прекурсорлар айналымы саласындағы объектілер мен үйлерді пайдалану үшін рұқсат беру тәртібі туралы" нұсқаулықты бекіту туралы'
type_codes:
- ИНСТ
approved_on: 2001-02-16
approved_by:
- '103003000000'
version_date:
  kaz: 2006-07-25
  rus: 2006-07-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/8371/kaz/25.07.2006
  rus: https://zan.gov.kz/client/#!/doc/8371/rus/25.07.2006
caused_by:
  code: '29111'
  requisite: Приказ Министра внутренних дел Республики Казахстан от 25 июля 2006 года № 373. Зарегистрирован в Министерстве юстиции Республики Казахстан 1 августа 2006 года № 4324. Утратил силу приказом Министра внутренних дел Республики Казахстан от 12 ноября 2015 года № 918
  title:
    rus: О внесении изменений в приказ Министра внутренних дел Республики Казахстан от 16 февраля 2001 года № 141 "Об утверждении Инструкции "О порядке выдачи разрешения на использование объектов и помещений в сфере оборота наркотических средств, психотропных веществ и прекурсоров"
    kaz: '"Есірткі құралдары, психотроптық заттар және прекурсорлар айналымы саласындағы объектілер мен үйлерді пайдалану үшін рұқсат беру тәртібі туралы" нұсқаулықты бекіту туралы" Қазақстан Республикасы Ішкі істер министрінің 2001 жылғы 16 ақпандағы № 141 бұйрығына өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/29111/rus
