act_code: '311'
requisite: Утверждены Министром юстиции Республики Казахстан 11 января 1997 г. Зарегистрированы в Министерстве юстиции Республики Казахстан 22 января 1997 г. N 249. Утратили силу - Приказом Министра юстиции от 29 июня 1999 г. N 51.
title:
  rus: Правила изменения, дополнения и исправления записей актов гражданского состояния и восстановления утраченных записей актов гражданского состояния
  kaz: Азаматтық хал актiлерi жазуларын өзгерту, толықтыру және түзету және жоғалған азаматтық хал актiлерi жазуларын қалпына келтiру ЕРЕЖЕЛЕРI
type_codes:
- ПРАВ
approved_on: 1997-01-11
approved_by:
- '103001000000'
version_date:
  rus: 1997-01-11
source:
  rus: https://zan.gov.kz/client/#!/doc/311/rus/11.01.1997
