act_code: '70007'
requisite: Закон Республики Казахстан от 8 января 2013 года № 62-V ЗРК
title:
  rus: О ратификации Соглашения между Правительством Республики Казахстан и Правительством Азербайджанской Республики о взаимном предоставлении земельных участков для строительства зданий дипломатических представительств
  kaz: Қазақстан Республикасының Үкіметі мен Әзербайжан Республикасының Үкіметі арасындағы дипломатиялық өкілдіктердің ғимараттарын салу үшін жер учаскелерін өзара беру туралы келісімді ратификациялау туралы
form: СОГЛ
type_codes:
- ЗАК
- СОГЛ
approved_on: 2013-01-08
approved_by:
- '102000000000'
version_date:
  kaz: 2013-01-08
  rus: 2013-01-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/70007/kaz/08.01.2013
  rus: https://zan.gov.kz/client/#!/doc/70007/rus/08.01.2013
