act_code: '112'
requisite: ПРИКАЗ Министра внутренних дел Республики Казахстан от 31 декабря 1993 г. N 473. Зарегистрирован в Министерстве юстиции Республики Казахстан 23.05.1995 г. N 66. Утратил силу - приказом Министра внутренних дел РК от 28.03.2005г. N 198
title:
  rus: Об утверждении Инструкции о порядке ввоза, реализации, приобретения, хранения, учета и использования множительной (копировальной) техники цветного изображения, открытия и функционирования множительных участков, оснащенных ею
  kaz: Түрлi түстi көбейткiш (көшipме) техникасын әкелу, өткiзу, сатып алу, сақтау, есепке алу мен пайдалану, онымен жарақталған көбейткiш учаскелерiн ашу және жұмыс iстеу тәртiбi туралы Нұсқауды бекiту туралы
type_codes:
- ИНСТ
approved_on: 1993-12-31
approved_by:
- '103003000000'
version_date:
  kaz: 1993-12-31
  rus: 1993-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/112/kaz/31.12.1993
  rus: https://zan.gov.kz/client/#!/doc/112/rus/31.12.1993
